### ISSUE TITLE
[Issue]: SDP with Hires and full previews hangs

### ISSUE THREAD

**Issue by gsgoldma** [vladmandic/automatic#492] opened 2023-04-25 18:04 UTC
### Issue Description

no log information generates, just starts using my gpu if hires is enabled. but there is zero progress. Skip/interrupt does nothing, have to quit and restart if it happens

bb438efe

### Version Platform Description

windows 10

**Comment by vladmandic** [comment] 2023-04-27 16:57
i've tried to reproduce, but no luck. can you share exact settings?

**Comment by zethfox** [comment] 2023-04-27 18:43
> i've tried to reproduce, but no luck. can you share exact settings?

This could be related to the live preview bug with full mode. When that lock up would happen to me it was ALWAY during hires portion of a gen.

**Comment by vladmandic** [comment] 2023-04-27 19:38
could be, but given i cannot reproduce i'm stumbling in the dark...

**Comment by myndxero** [comment] 2023-04-28 10:51
> could be, but given i cannot reproduce i'm stumbling in the dark...

I want to offer this may be related to the batch scenario bug. This happens intermittently to me as well, unless that got fixed somewhere and I missed it. It's just happenstance that this guy was doing hires? But Eventually, after doing I dunno, 50-100 generations, it will just cease to do anything at all. If I go to another tab or load the UI on a different device, it will just say 'waiting.'

**Comment by merodiro** [comment] 2023-04-28 13:51
I have a similar issue. this happens with me with the first few images after I start the webui. it stales either at 0 steps or at the last step for minutes

**Comment by gsgoldma** [comment] 2023-04-28 16:55
I'd like to add, I was not doing batches. At the risk of this not being related, but maybe it is, if I don't use text2img for a few minutes, it doesn't work-although img2img will still work. I have to open up a new window for text2img to function again. But since they both hang up the UI maybe they're related issues.

**Comment by vladmandic** [comment] 2023-04-28 16:55
i'll try to add extra debug logging (hiden behind cmdflag so it doesn't affect everyone)...

**Comment by thompsonplyler** [comment] 2023-04-29 15:13
Just adding on the "me too." This should be a no-brainer default repo for me. It's faster to move around, thoughtfully designed, and crammed with great features beyond the original Automatic1111 repo, but the random hanging is a tough pill to swallow. I tried running a batch of img2img while I was out last night, and not only did it hang but I just sort of knew as I was walking out the door it would hang. Sure enough, I returned and after 8 generations, the problem above happened: stalled, no errors, no log event, nothing. I could Ctrl+C and start over where I left off, but as it stands I can 100% guarantee that if I use this repo for any length of time I will eventually hit a hard hang that requires a Ctrl+C restart.

**Comment by vladmandic** [comment] 2023-04-29 15:15
just to rule out one thing, can you make sure that your live preview method is set to Approx NN?

**Comment by thompsonplyler** [comment] 2023-04-29 15:15
I've set it to NN, and I'll report back.

**Comment by DrMeo** [comment] 2023-04-29 17:32
> just to rule out one thing, can you make sure that your live preview method is set to Approx NN?

I'll add one more observation - Even with live preview set to Full / Combined I've **not** had the program just stop working after switching from SDP to xformers. 

I think I've generated as many times as with SDP enabled, and should have come across whatever is happening by now, but it could be just luck. So that might be a clue to help narrow down the search for what's happening. 

Can anyone else in here chime in and report if they are using SDP ( the default ) or if they were using xformers when the bug happened?

**Comment by vladmandic** [comment] 2023-04-29 17:35
@DrMeo thats an interesting feedback. but regardless, can you test with live preview set to approx nn?

**Comment by Averytingwong** [comment] 2023-04-29 20:21
> @DrMeo thats an interesting feedback. but regardless, can you test with live preview set to approx nn?

I set mine back to approx nn and it has seem to have fixed the freezing issue for me. I do really miss the full sizedpreviews though, since I would use them to zoom in and check details while generating.

**Comment by vladmandic** [comment] 2023-04-29 20:25
if selecting approx nn fixes it, issue is pretty complicated - its a race condition in torch 2.0 where it gets stuck if two different threads try to read same tensor data. faster polling rate for live previews makes things more likely to happen, but it can happen anyhow. it doesn't happen with approx nn since that uses separate model and tensor is copied before processed for preview.

**Comment by DrMeo** [comment] 2023-05-01 18:37
> @DrMeo thats an interesting feedback. but regardless, can you test with live preview set to approx nn?


Sorry for the late reply, been a little busy with multiple projects going on, but I may not have explained clearly enough.

 The hangs I had before where with full previews enabled AND using Scaled Dot Product for acceleration.

Now I am using xformers with full previews and the program has NOT had a hang since. It has been running for several days without a restart and is working just as it should. 

This seems to indicate that SDP optimizations might be the root cause of the issue. Or at least some interaction with the outputs of SDP and the preview code / final image generation code.

**Comment by vladmandic** [comment] 2023-05-01 18:41
thanks for confirming. btw, sdp issues are torch2 issues as sdp is implemented inside torch, not as a plugin...
i'll update the title and leave issue open so it can be tracked.

**Comment by thompsonplyler** [comment] 2023-05-01 19:05
@vladmandic I took your advice and switched the image preview to NN, and that has taken a good bit of the pain of long-term generation away. I took someone's advice to add --xformers and --no-full-vae to the startup prompt to reduce the chance of my CUDA memory errors. I don't know the specifics of how this would help, so a link to an explanation or a same explanation in your own words would be helpful. I also didn't really see how to implement it in the new UI, although I clicked around every setting in the UI with "xformers" on it. Eventually I had to reset all those settings (except the NN you recommended) because I was getting very weird and difficult to predict/reproduce errors. 

The day-to-day generation process seems to have improved after switching the live preview to NN, but the batch img2img was a bust after ~100 generations.

**Comment by vladmandic** [comment] 2023-05-01 23:08
xformers can be enabled in UI Settings -> Stable Diffusion -> Cross-attention optimization method
`--no-full-vae` never existed. what existed is fp16 vs fp32 and `--no-half-vae`. all those settings are in UI Settings -> CUDA

on the root cause of hangs - it seems that torch 2.0 has thread safety issue when multiple threads access same underlying tensor data. generate runs on main thread and can be updating tensor while preview runs in a second thread and via regular polling and it tries to read whatever is available - and if torch 2.0 has thread safety issues, it can lead to mutex locks, so threads basically hang.

why does approx nn or using xformers help? since both are external libraries, generate has to copy tensor to pass it. so while they are busy working on copy, there is far less chance that something inconsistent will happen on the main copy.

yeah, its all about timing and parallel access and gets really weird really fast.
and its really hardware timing specific - some users have never seen a lockup happen even once. some see it regularly.

neither using approx nn nor using xformers nor reducing preview polling totally solve the issue as there is always a chance of thread safety issue, but having 1 or 2 all 3 workarounds greatly reduces that chance.

i hope torch service pack addressed this.

**Comment by vladmandic** [comment] 2023-05-03 13:34
@gsgoldma any updates from your side since you're the original creator of the issue? there have been quite a few updates in the past week since last update that for sure have some indirect impact on this, so i'd like to know what is your experience now?

**Comment by thompsonplyler** [comment] 2023-05-03 13:52
I have experienced no crashes since I implemented your NN change, but I
also haven't attempted a batch process with img2img and ControlNet again.
I'll make a note here if I have any issues. VERY glad to have stopped the
arbitrary hanging, though. Thanks, Vlad!

**Comment by vladmandic** [comment] 2023-05-11 15:17
closing as no update from author provided. if there are reoccurences, update here and i'll reopen.

**Closed by vladmandic** 2023-05-11 15:17 UTC
Labels: bug, help wanted
