### ISSUE TITLE
[Issue]: in the original backend, secondary CFG is not restored when pressing restore button

### ISSUE THREAD

**Issue by elsci** [vladmandic/automatic#2570] opened 2023-11-28 17:09 UTC
### Issue Description

when i press restore button after generating an image with hires fix, the secondary CFG value does not reflect the value set while generating that image.

### Version Platform Description

Version: app=sd.next updated=2023-11-27 hash=202f27e8
Win11Pro, Firefox 120

### Backend

Original

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment] 2023-11-29 12:22
i cannot reproduce, in my test setting is restored.
set env variable `SD_PASTE_DEBUG=true`, run generate and then restore and upload log - it will show both written, parsed and restored values.

**Comment by vladmandic** [comment] 2023-12-04 14:23
any updates?

**Comment by vladmandic** [comment] 2023-12-10 12:48
closing as no update, will be reopened if info is provided.

**Closed by vladmandic** 2023-12-10 12:48 UTC
Labels: question, cannot reproduce
