### ISSUE TITLE
[Issue]: Changing to other samplers frequently causes bad/incomplete images.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [vladmandic/automatic#2351] opened 2023-10-19 06:14 UTC
### Issue Description

I'm having intermittent problems with images ending with some noise still remaining (see below) after changing from default to a different sampler, even from default to DEIS. If I make other changes (eg. disable and re-enable 2nd pass), it sometimes clears it, but not always. Have to restart the server to clear it if nothing else works. I don't know if it's related, but selecting/deselecting the "karras" option makes no difference to the image, when I'd expect it to.
Using DPM++ 2M...
![00005-SDXL-protovisionXLHighFidelity3D_release0620Bakedvae](https://github.com/vladmandic/automatic/assets/52193044/8f88b561-1337-44d8-b481-5887c0b0d4e1)
I was then trying to switch back to "default" (DEIS) to show how it should look...but it's stuck in this incomplete image rendering.
It then worked with UniPC...
![00006-SDXL-protovisionXLHighFidelity3D_release0620Bakedvae](https://github.com/vladmandic/automatic/assets/52193044/bdd9716e-f0d4-47df-8528-4e558d2d5975)
So, I tried "default" again...
![00008-SDXL-protovisionXLHighFidelity3D_release0620Bakedvae](https://github.com/vladmandic/automatic/assets/52193044/3ebc96ff-688b-4f21-9d0a-3d967c776859)

### Version Platform Description

08:10:36-391354 INFO     Starting SD.Next
08:10:36-395354 INFO     Python 3.10.6 on Windows
08:10:36-537603 INFO     Version: app=sd.next updated=2023-10-18 hash=66f75b6a
                         url=https://github.com/vladmandic/automatic.git/tree/master
08:10:36-756946 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.6
08:10:36-762048 INFO     nVidia CUDA toolkit detected: nvidia-smi present
08:10:36-847435 INFO     Verifying requirements
08:10:36-860464 INFO     Verifying packages
08:10:36-862465 INFO     Verifying repositories
08:10:39-767614 INFO     Verifying submodules
08:11:06-792301 INFO     Extensions enabled: ['clip-interrogator-ext', 'Lora', 'sd-extension-chainner',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'adetailer',
                         'sd-dynamic-prompts', 'sd-ratio-lock', 'sd-webui-roop']

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by GalaxyTimeMachine** [comment] 2023-10-19 06:20
It appears the sampler selection is not working correctly. These images were created in the same order, after starting the server:
1. Initial creation using "default" sampler...
![00000-SDXL-GTM_XLPlus_v2](https://github.com/vladmandic/automatic/assets/52193044/944231aa-fb30-4930-9cb1-5313b317e6e2)
2. Changed sampler to "DPM++ 2M"...
![00001-SDXL-GTM_XLPlus_v2](https://github.com/vladmandic/automatic/assets/52193044/9941decf-73d6-4230-8ee7-915c3f2b6d1f)
3. Changed sampler back to "default"...
![00003-SDXL-GTM_XLPlus_v2](https://github.com/vladmandic/automatic/assets/52193044/172a8508-8974-44ab-b366-67f2bce348af)
![image](https://github.com/vladmandic/automatic/assets/52193044/86b3a441-2e5a-4210-8c58-197f96aa0ea2)

**Comment by Beinsezii** [comment] 2023-10-19 10:27
The DPM++ 2M noise issue looks like what happens when the karras scheduler isnt used. I seem to have the same issue despite the box being checked.

**Comment by vladmandic** [comment] 2023-10-19 12:37
thanks not how it works
- default means "whatever is default in model", it doesn't mean deis. it means do not create sampler.
- once you select *any* sampler, default stops existing. you cannot go back to default
- if any sampler is not resolving noise fast enough, it doesn't have enough steps. and how fast it resolves noise is impacted by sampler settings. so i don't see anything wrong here.

**Comment by GalaxyTimeMachine** [comment] 2023-10-19 13:26
You really should look into this before brushing it off so quickly. I get this exact same problem using UniPC and 30 steps, yet I can use 15 steps to create a complete image on other platforms. This is an issue seen by others as well, and should not have been closed.

**Comment by GalaxyTimeMachine** [comment] 2023-10-19 13:35
DMP++ 2m still has issues with 50 steps. From experience, this shouldn't need so many steps.
![00003-SDXL-GTM_XLPlus_v2](https://github.com/vladmandic/automatic/assets/52193044/4ae95abc-249f-4394-b6cb-27bd80cc19d1)

**Comment by GalaxyTimeMachine** [comment] 2023-10-19 13:38
Identical image with or without karras selected

**Comment by vladmandic** [comment] 2023-10-19 13:38
using which settings.
and ok, i'll reopen.

**Comment by GalaxyTimeMachine** [comment] 2023-10-19 13:43
> using which settings. and ok, i'll reopen. i originally closed because incorrect assumptions were at the top of the issue.
and all the talk about "default" is going to confuse anyone trying to read through this issue and its not relevant.

Thanks, I'm not a dev so can only explain how it seems to me. I wasn't aware of a "default" sampler within models, I thought it was fomr the configuration, but that's another topic.

The settings can be seen in the screenshot further up, or in the meta of this image...
![00000-SDXL-GTM_XLPlus_v2](https://github.com/vladmandic/automatic/assets/52193044/7281b649-26fa-492c-84b6-9cf7c26cd85e)

**Closed** 2023-10-19 14:20 UTC
Labels: help wanted

**Comment by GalaxyTimeMachine** [comment] 2023-10-19 14:56
Thanks for the fix. It works with DPM++ 2M, but I'm also seeing the same with UniPC (I'll try the others when I get time).
Not sure if this is related, but DEIS now gives me the error:

sde-dpmsolver++ does is not implemented for <class 'diffusers.schedulers.scheduling_deis_multistep.DEISMultistepScheduler'>

Let me know if I should open a new bug for that.

**Comment by GalaxyTimeMachine** [comment] 2023-10-19 15:05
Really strange!  While going through the list, I re-tried DPM++ 2M and it's not working this time. I've changed nothing except the sampler each try.

**Comment by vladmandic** [comment] 2023-10-19 15:50
> ...but I'm also seeing the same

which is what? that image is not denoising fast enought or that sampler settings are not applied?

> sde-dpmsolver++ does is not implemented for <class 'diffusers.schedulers.scheduling_deis_multistep.DEISMultistepScheduler'>

never seen that before. if you can find reproduction steps, best to create a new issue.

**Comment by GalaxyTimeMachine** [comment] 2023-10-20 09:15
> which is what? that image is not denoising fast enought or that sampler settings are not applied?
> 
> >

The same as the original problem reported. None of these samplers were denoising the image with 35 steps. That problem is still there, but I think it may be related to changing the sampler. Whichever sampler I use first, after the server starts, seems to work just fine, but when I change to another sampler it stops working/denoising properly.
However, it is now very intermittent, so I'm struggling to find reliable steps to reproduce it.

**Comment by vladmandic** [comment] 2023-10-20 11:08
When you find a way to reproduce, let me know.
Also, run webui with --debug, it will show sampler creation on each generate.

**Comment by GalaxyTimeMachine** [comment] 2023-10-20 12:41
There doesn't appear to be anything specific to reproduce it, I just try using it and the error occurs whatever settings I change....then it sometimes works, without making any change since it last failed.

**Comment by IowaSovereign** [comment] 2023-10-25 00:09
For me none but two samplers are usable at all due to this behaviour, Euler a and DPM SDE. You can see it in the comparison I attached, settings between each were completely untouched, no LORA's, simple prompt. All settings for samplers left at default, in the IMG2TXT settings I had karras, dynamic thresholding and low order enabled. 

Interestingly, KDPM a looks alright from afar, but when you get a good look you see the swirls all over the image. DPM++ 1S, 2M and UniPC are weirdly desaturated, and DPM++ 1S and UniPC are uncanilly similar to each other.

I've seen one or two other people mention this.

![Samplers-2](https://github.com/vladmandic/automatic/assets/63501758/c1d6f199-7fd2-4507-9061-8f8b22c50d8e)

**Comment by vladmandic** [comment] 2023-10-25 01:02
> For me none but two samplers are usable at all due to this behaviour, Euler a and DPM SDE. You can see it in the comparison I attached, settings between each were completely untouched, no LORA's, simple prompt. All settings for samplers left at default, in the IMG2TXT settings I had karras, dynamic thresholding and low order enabled.
> 
> Interestingly, KDPM a looks alright from afar, but when you get a good look you see the swirls all over the image. DPM++ 1S, 2M and UniPC are weirdly desaturated, and DPM++ 1S and UniPC are uncanilly similar to each other.
> 
> I've seen one or two other people mention this.
> 
> ![Samplers-2](https://user-images.githubusercontent.com/63501758/277836000-c1d6f199-7fd2-4507-9061-8f8b22c50d8e.png)

This does not related to filled issue as nobody reported such massive sampler issues. 
I'd suggest to open a new issue and fill the template with as many details as possible.

**Comment by GalaxyTimeMachine** [comment] 2023-10-25 06:16
This is very similar to what I was seeing, but it was intermittent. I try not to change the sampler once I find one that's working, otherwise even the working one then sometimes breaks. I've actually had to return to ComfyUI to get clean, sharp images.

**Comment by vladmandic** [comment] 2023-10-25 14:16
Grid for samplers looks pretty much exactly as expected for me:

![samplers](https://github.com/vladmandic/automatic/assets/57876960/4569618f-7834-431b-acef-75e629742bb2)
