### ISSUE TITLE
[Issue]: Failed to convert UNET (Flux)

### ISSUE THREAD

**Issue by MysticDaedra** [vladmandic/automatic#3401] opened 2024-09-02 22:49 UTC
### Issue Description

Starting up SD.Next dev with --upgrade, presumably this error is from trying to load the selected unet-only Flux checkpoint?

The full error:
```python
15:45:26-117627 INFO     Loading UNet: type=FLUX file="D:\Stable Diffusion
                         Files\Models\UNET\creartHyperFluxDevBnbNf4_hyperDevBnbNf4Unet.safetensors" offload=balanced
                         quant=nf4 dtype=torch.float16
15:45:28-057356 ERROR    Loading FLUX: Failed to convert UNET: split_with_sizes expects split_sizes to sum exactly to
                         33030144 (input tensor's size at dimension 0), but got split_sizes=[3072, 3072, 3072, 12288]
``` 

### Version Platform Description

Using VENV: D:\automatic\venv
15:43:21-788203 INFO     Starting SD.Next
15:43:21-792714 INFO     Logger: file="D:\automatic\sdnext.log" level=DEBUG size=65 mode=create
15:43:21-793715 INFO     Python version=3.11.8 platform=Windows bin="D:\automatic\venv\Scripts\Python.exe"
                         venv="D:\automatic\venv"
15:43:24-246505 INFO     Version: app=sd.next updated=2024-09-02 hash=045b24c0 branch=dev
                         url=https://github.com/vladmandic/automatic/tree/dev ui=dev
15:43:24-816954 INFO     Updating main repository
15:43:29-888223 INFO     Upgraded to version: bba17766 Mon Sep 2 18:08:32 2024 -0400
15:43:29-895732 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.11.8
15:43:29-896734 DEBUG    Setting environment tuning
15:43:29-898733 INFO     HF cache folder: C:\Users\Joshua\.cache\huggingface\hub
15:43:29-898733 DEBUG    Torch allocator:
                         "garbage_collection_threshold:0.20,max_split_size_mb:512,backend:cudaMallocAsync"
15:43:29-916070 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
15:43:29-917068 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
15:43:29-930095 INFO     nVidia CUDA toolkit detected: nvidia-smi present
15:43:30-152845 INFO     Verifying requirements
15:43:30-155844 INFO     Verifying packages
15:43:30-156845 INFO     Startup: standard
15:43:30-157846 INFO     Verifying submodules
15:43:32-916799 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
15:43:33-576603 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
15:43:34-219901 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
15:43:34-909362 DEBUG    Submodule: extensions-builtin/sdnext-modernui / dev
15:43:35-617831 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
15:43:36-315608 DEBUG    Submodule: modules/k-diffusion / master
15:43:37-033878 DEBUG    Git detached head detected: folder="wiki" reattach=master
15:43:37-034881 DEBUG    Submodule: wiki / master
15:43:37-999493 DEBUG    Register paths
15:43:38-059819 DEBUG    Installed packages: 203
15:43:38-059819 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg']
15:43:38-677345 DEBUG    Submodule: extensions-builtin\sd-extension-chainner / main
15:43:39-371360 DEBUG    Submodule: extensions-builtin\sd-extension-system-info / main
15:43:40-057819 DEBUG    Submodule: extensions-builtin\sd-webui-agent-scheduler / main
15:43:40-652624 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
15:43:41-011305 DEBUG    Submodule: extensions-builtin\stable-diffusion-webui-images-browser / main
15:43:41-699882 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\stable-diffusion-webui-images-browser\install.py
15:43:42-069387 DEBUG    Submodule: extensions-builtin\stable-diffusion-webui-rembg / master
15:43:42-679956 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
15:43:43-004336 DEBUG    Extensions all: ['adetailer', 'canvas-zoom', 'sd-webui-infinite-image-browsing',
                         'sd-webui-temporal', 'ultimate-upscale-for-automatic1111']
15:43:43-046972 DEBUG    Submodule: extensions\adetailer / main
15:43:44-454354 DEBUG    Running extension installer: D:\automatic\extensions\adetailer\install.py
15:43:44-837530 DEBUG    Submodule: extensions\canvas-zoom / main
15:43:45-472476 DEBUG    Running extension installer: D:\automatic\extensions\canvas-zoom\install.py
15:43:54-254284 DEBUG    Submodule: extensions\sd-webui-infinite-image-browsing / main
15:43:54-899765 DEBUG    Running extension installer:
                         D:\automatic\extensions\sd-webui-infinite-image-browsing\install.py
15:44:02-696313 DEBUG    Submodule: extensions\sd-webui-temporal / master
15:44:03-435476 DEBUG    Submodule: extensions\ultimate-upscale-for-automatic1111 / master
15:44:04-108460 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'adetailer', 'canvas-zoom', 'sd-webui-infinite-image-browsing',
                         'sd-webui-temporal', 'ultimate-upscale-for-automatic1111']
15:44:04-109778 INFO     Verifying requirements
15:44:04-111296 INFO     Updating Wiki
15:44:04-143396 DEBUG    Submodule: D:\automatic\wiki / master
15:44:04-763404 DEBUG    Setup complete without errors: 1725317045
15:44:04-768404 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
15:44:04-770404 DEBUG    Starting module: <module 'webui' from 'D:\\automatic\\webui.py'>
15:44:04-771404 INFO     Command line args: ['--debug', '--upgrade', '--share'] share=True upgrade=True debug=True
15:44:04-771910 DEBUG    Env flags: ['SD_MASK_DEBUG=true']
15:44:15-001322 INFO     Load packages: {'torch': '2.3.1+cu121', 'diffusers': '0.30.2', 'gradio': '3.43.2'}
15:44:16-416527 INFO     VRAM: Detected=8.0 GB Optimization=medvram
15:44:16-419528 DEBUG    Read: file="config.json" json=81 bytes=5088 time=0.000
15:44:16-421033 DEBUG    Unknown settings: ['cross_attention_options', 'ad_max_models', 'civitai_link_key',
                         'multiple_tqdm', 'ad_same_seed_for_each_tap', 'mudd_states', 'civitai_folder_lyco',
                         'diffusers_aesthetics_score', 'image_browser_active_tabs', 'ad_extra_models_dir',
                         'canvas_zoom_mask_clear', 'canvas_zoom_draw_staight_lines', 'ad_script_names']
15:44:16-423039 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
15:44:16-439382 INFO     Device: device=NVIDIA GeForce RTX 3070 n=1 arch=sm_90 cap=(8, 6) cuda=12.1 cudnn=8907 driver=
15:44:16-446897 DEBUG    Read: file="html\reference.json" json=52 bytes=29118 time=0.006
15:44:16-962337 TRACE    Trace: MASK
15:44:17-226029 DEBUG    ONNX: version=1.18.0 provider=CUDAExecutionProvider, available=['TensorrtExecutionProvider',
                         'CUDAExecutionProvider', 'CPUExecutionProvider']

### Relevant log output

```shell
https://discord.com/channels/1101998836328697867/1130536562422186044/1280298597417484288
```

### Backend

Diffusers

### UI

Standard

### Branch

Dev

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Klevente12** [comment] 2024-09-02 22:49
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by vladmandic** [comment] 2024-09-03 14:36
duplicate of #3402

**Closed by vladmandic** 2024-09-03 14:36 UTC
