### ISSUE TITLE
Typo in model prediction types.

### ISSUE THREAD

**Issue by rabidcopy** [vladmandic/automatic#2253] opened 2023-09-26 20:30 UTC
![image](https://github.com/vladmandic/automatic/assets/8052832/e33089fd-19a4-4e2f-8b10-7a9302a67f20)

https://github.com/vladmandic/automatic/blob/c33bbc83e71a012ac29b8ae2f5ee82c87c4c1c60/modules/dml/hijack/diffusers.py#L23
https://github.com/vladmandic/automatic/blob/c33bbc83e71a012ac29b8ae2f5ee82c87c4c1c60/modules/shared.py#L572

`v-prediction` should be `v_prediction` in the choices. (or optionally the other way around?)

**Comment by vladmandic** [comment] 2023-09-26 21:50
good catch!
fortunately, it impact only loading of sd 2.1 786px models with directml...
fixed in dev.

**Closed by vladmandic** 2023-09-26 21:50 UTC

**Comment by rabidcopy** [comment] 2023-10-24 17:55
https://github.com/vladmandic/automatic/blob/0d2f535527c76602c5245cf3c77549b5030c1f17/modules/shared.py#L476C1-L476C182

This seems to have regressed back to `v-prediction` at some point in dev and makes manually setting the value to `v-prediction` in options not work as it needs to be `v_prediction`. Also the setting seems to be nowhere to be found even when putting it in the quick settings. Maybe I'm not looking in the right place but the only way to make the option visible is to set `"visible": True` at the end of the line in dev.

**Comment by vladmandic** [comment] 2023-10-24 18:11
i'll fix the regression ASAP, no idea how that happened.
but under which circumstances do you need to manually set that option? its hidden by default because in 99% of cases its auto-detected, so no reason to expose yet-one-more-option to users.

**Comment by rabidcopy** [comment] 2023-10-24 18:21
> i'll fix the regression ASAP, no idea how that happened. but under which circumstances do you need to manually set that option? its hidden by default because in 99% of cases its auto-detected, so no reason to expose yet-one-more-option to users.

When loading a particular SD 1.5 models that uses v-prediction in the Diffusers backend with a safetensors file. When using it in the full Diffusers folder format, v-prediction can be set in the scheduler_config.json and works. But when placing an accompanying v-prediction configuration yaml file next to a safetensors and loading it with the Diffusers backend, it does not make it run as v-prediction where the Original backend does apply the yaml.

**Comment by vladmandic** [comment] 2023-10-24 21:33
valid use case, but are those models worth it or is this really one of those corner cases?

**Comment by rabidcopy** [comment] 2023-10-24 22:20
> valid use case, but are those models worth it or is this really one of those corner cases?

They are active projects still being trained in the intermission to SDXL becoming more viable to train. It's not a huge deal though. There's only real benefit of running them on the Diffusers backend is the Guidance Rescale setting as results can be blown out or lacking background details without it with these niche models. However there is a CFG Rescale extension already that works for the Original backend. I don't mind making a tweak to make the option visible if need be. Though I was sort of hoping that adding it to the QuickSettings list would have worked as an alternative to a quick edit as it does show up in the list of options available.

**Comment by vladmandic** [comment] 2023-10-24 22:24
ideally, model config yaml file sitting next to model should take priority and then this would not be needed. but i've never implemented that for diffusers as simply there was no need so far.

anyhow, i'll make a change in dev branch visible: true. you have a valid use case - thats all i ask. sometimes ppl ask "can i have some obsolete setting back" and they have no real use case.

**Comment by rabidcopy** [comment] 2023-10-24 22:28
> ideally, model config yaml file sitting next to model should take priority and then this would not be needed. but i've never implemented that for diffusers as simply there was no need so far.
> 
> anyhow, i'll make a change in dev branch visible: true. you have a valid use case - thats all i ask. sometimes ppl ask "can i have some obsolete setting back" and they have no real use case.

Thanks. That's completely understandable. To a new user, it can be very overwhelming to see literally hundreds of options you'll never use and you probably will never know what they do either.
