### ISSUE TITLE
[Issue]: Crashing at launch

### ISSUE THREAD

**Issue by Davikar** [vladmandic/automatic#1294] opened 2023-06-04 02:21 UTC
### Issue Description

Getting the following message after launching webui.bat: (with the --safe and --debug flag)

```
04:17:16-013709 INFO     Loading UI theme: name=black-orange style=Dark
04:17:16-016707 DEBUG    Creating UI
04:17:16-025709 DEBUG    Adding JS scripts: ['/javascript/aspectRatioOverlay.js', '/javascript/contextMenus.js', '/javascript/dragdrop.js', '/javascript/edit-attention.js',
                         '/javascript/extensions.js', '/javascript/extraNetworks.js', '/javascript/generationParams.js', '/javascript/hints.js', '/javascript/hires.js',
                         '/javascript/imageMaskFix.js', '/javascript/imageParams.js', '/javascript/imageviewer.js', '/javascript/notification.js', '/javascript/progressbar.js',
                         '/javascript/prompt-bracket-checker.js', '/javascript/set-hints.js', '/javascript/textualInversion.js', '/javascript/ui.js',
                         '/extensions-builtin/multidiffusion-upscaler-for-automatic1111/javascript/bboxHint.js', '/extensions-builtin/sd-extension-system-info/javascript/jquery.js',
                         '/extensions-builtin/sd-extension-system-info/javascript/sparkline.js', '/extensions-builtin/sd-extension-system-info/javascript/system-info.js',
                         '/extensions-builtin/sd-webui-controlnet/javascript/hints.js', '/extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js',
                         '/extensions-builtin/sd-webui-agent-scheduler/javascript/extension.mjs']
04:17:16-029707 DEBUG    Adding CSS stylesheets: ['javascript/style.css', '/extensions-builtin/sd-webui-agent-scheduler/style.css',
                         '/extensions-builtin/stable-diffusion-webui-images-browser/style.css', '/javascript/black-orange.css']
04:17:16-031716 INFO     Theme does not support custom mode
╭──────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────────╮
│ C:\AI\automatic\launch.py:149 in <module>                                                                                                                                                  │
│                                                                                                                                                                                            │
│   148                                                                                                                                                                                      │
│ ❱ 149     instance = start_server(immediate=True, server=None)                                                                                                                             │
│   150     while True:                                                                                                                                                                      │
│                                                                                                                                                                                            │
│ C:\AI\automatic\launch.py:129 in start_server                                                                                                                                              │
│                                                                                                                                                                                            │
│   128         else:                                                                                                                                                                        │
│ ❱ 129             server = server.webui()                                                                                                                                                  │
│   130     if args.profile:                                                                                                                                                                 │
│                                                                                                                                                                                            │
│ C:\AI\automatic\webui.py:276 in webui                                                                                                                                                      │
│                                                                                                                                                                                            │
│   275     start_common()                                                                                                                                                                   │
│ ❱ 276     start_ui()                                                                                                                                                                       │
│   277     load_model()                                                                                                                                                                     │
│                                                                                                                                                                                            │
│ C:\AI\automatic\webui.py:204 in start_ui                                                                                                                                                   │
│                                                                                                                                                                                            │
│   203     startup_timer.record("scripts before_ui_callback")                                                                                                                               │
│ ❱ 204     shared.demo = modules.ui.create_ui()                                                                                                                                             │
│   205     startup_timer.record("ui")                                                                                                                                                       │
│                                                                                                                                                                                            │
│ C:\AI\automatic\modules\ui.py:353 in create_ui                                                                                                                                             │
│                                                                                                                                                                                            │
│    352     modules.scripts.scripts_current = modules.scripts.scripts_txt2img                                                                                                               │
│ ❱  353     modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)                                                                                                            │
│    354     with gr.Blocks(analytics_enabled=False) as txt2img_interface:                                                                                                                   │
│                                                                                                                                                                                            │
│ C:\AI\automatic\modules\scripts.py:282 in initialize_scripts                                                                                                                               │
│                                                                                                                                                                                            │
│   281         for script_class, path, _basedir, _script_module in auto_processing_scripts + sc                                                                                             │
│ ❱ 282             script = script_class()                                                                                                                                                  │
│   283             script.filename = path                                                                                                                                                   │
│                                                                                                                                                                                            │
│ C:\AI\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:26 in __init__                                                                                       │
│                                                                                                                                                                                            │
│    25         self.checkpoint_override = checkpoint_current                                                                                                                                │
│ ❱  26         self.generate_button                                                                                                                                                         │
│    27                                                                                                                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Script' object has no attribute 'generate_button'

```

### Version Platform Description

Windows 11 22H2, GTX 1080 Ti, Python 3.10.10, xformers 0.0.20, Vivaldi (Chrome)

Version: 5190f702

**Comment by vladmandic** [comment] 2023-06-04 02:26
check for duplicates before creating new issue. closing as duplicate of #1281

**Closed by vladmandic** 2023-06-04 02:26 UTC
