### ISSUE TITLE
[Issue]:  Diffusers/SDXL Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by bullseyepsa** [vladmandic/automatic#2196] opened 2023-09-15 04:25 UTC
### Issue Description

Starting with today's (9/14/23) pull, I get the following error in the browser when I try to generate images using SDXL (I hve tried several models), but it appears to work correctly when using a 1.5 model and Original backend:

Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

Time: 0.76s |

GPU active 2 MB reserved 2 | used 1107 MB free 7085 MB total 8192 MB | retries 0 oom 0

I have tried rebbuilding venv, config.json and ui-config.json with no change (other than it worked with the default config.json before I switched to SDXL). I tried launching with the --safe flag.

### Version Platform Description

app: SD.next
updated: 2023-09-14
hash: 083ab521
url: https://github.com/vladmandic/automatic/tree/master

arch: AMD64
cpu: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.6

device: NVIDIA GeForce RTX 3070 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700
driver: 537.34

2.0.1+cu118 Autocast  half

### Relevant log output

```shell
From the console (it's not in the log yet that I can find):
│ D:\SDVlad\automatic\modules\call_queue.py:34 in f                                                                   │
│                                                                                                                     │
│   33 │   │   │   try:                                                                                               │
│ > 34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│   35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                     │
│ D:\SDVlad\automatic\modules\txt2img.py:66 in txt2img                                                                │
│                                                                                                                     │
│   65 │   if processed is None:                                                                                      │
│ > 66 │   │   processed = processing.process_images(p)                                                               │
│   67 │   p.close()                                                                                                  │
│                                                                                                                     │
│ D:\SDVlad\automatic\modules\processing.py:622 in process_images                                                     │
│                                                                                                                     │
│    621 │   │   else:                                                                                                │
│ >  622 │   │   │   res = process_images_inner(p)                                                                    │
│    623 │   finally:                                                                                                 │
│                                                                                                                     │
│ D:\SDVlad\automatic\modules\processing.py:781 in process_images_inner                                               │
│                                                                                                                     │
│    780 │   │   │   │   from modules.processing_diffusers import process_diffusers                                   │
│ >  781 │   │   │   │   x_samples_ddim = process_diffusers(p, p.seeds, p.prompts, p.negative_pro                     │
│    782                                                                                                              │
│                                                                                                                     │
│ D:\SDVlad\automatic\modules\processing_diffusers.py:331 in process_diffusers                                        │
│                                                                                                                     │
│   330 │                                                                                                             │
│ > 331 │   base_args = set_pipeline_args(                                                                            │
│   332 │   │   model=shared.sd_model,                                                                                │
│                                                                                                                     │
│                                              ... 16 frames hidden ...                                               │
│                                                                                                                     │
│ D:\SDVlad\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                            │
│                                                                                                                     │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
│ > 1501 │   │   │   return forward_call(*args, **kwargs)                                                             │
│   1502 │   │   # Do not call functions when jit is used                                                             │
│                                                                                                                     │
│ D:\SDVlad\automatic\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:229 in forward                 │
│                                                                                                                     │
│    228 │   │   if inputs_embeds is None:                                                                            │
│ >  229 │   │   │   inputs_embeds = self.token_embedding(input_ids)                                                  │
│    230                                                                                                              │
│                                                                                                                     │
│ D:\SDVlad\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                            │
│                                                                                                                     │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
│ > 1501 │   │   │   return forward_call(*args, **kwargs)                                                             │
│   1502 │   │   # Do not call functions when jit is used                                                             │
│                                                                                                                     │
│ D:\SDVlad\automatic\venv\lib\site-packages\torch\nn\modules\sparse.py:162 in forward                                │
│                                                                                                                     │
│   161 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ > 162 │   │   return F.embedding(                                                                                   │
│   163 │   │   │   input, self.weight, self.padding_idx, self.max_norm,                                              │
│                                                                                                                     │
│ D:\SDVlad\automatic\venv\lib\site-packages\torch\nn\functional.py:2210 in embedding                                 │
│                                                                                                                     │
│   2209 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)                                       │
│ > 2210 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)                           │
│   2211                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when
checking argument for argument index in method wrapper_CUDA__index_select)
```

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment] 2023-09-15 12:28
seems that new diffusers broke something in combination with model offloading, but i cannot reproduce.
pls upload a screenshot of settings -> diffusers.

**Comment by vladmandic** [comment] 2023-09-15 17:52
temporarily resolved with downgrading diffusers to 0.20.2.
root cause should be fixed in diffusers, issue is <https://github.com/huggingface/diffusers/issues/5060>

**Comment by bullseyepsa** [comment] 2023-09-15 19:00
Tested and it is working. For some reason, I was getting an error from gradio (I'll paste it below for information purposes only) but I was able to resolve that by removing the gradio packages from venv and rerunning webui.bat

Here's the error in case there's something going on that you need is for:
Traceback (most recent call last):
  File "D:\SDVlad\automatic\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\SDVlad\automatic\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\SDVlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\SDVlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1228, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "D:\SDVlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1215, in validate_inputs
    raise ValueError(
ValueError: An event handler didn't receive enough input values (needed: 1, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number]
Received inputs:
    []

**Comment by vladmandic** [comment] 2023-10-04 16:58
fixed in dev, will be merged to master soon.

**Closed by vladmandic** 2023-10-04 16:58 UTC
Labels: upstream
