### ISSUE TITLE
[Issue]: Interrogator not working

### ISSUE THREAD

**Issue by ronbere** [vladmandic/automatic#1372] opened 2023-06-09 10:45 UTC
### Issue Description

Using VENV: C:\automatic\venv
12:36:51-911948 INFO     Starting SD.Next
12:36:51-915953 INFO     Python 3.10.9 on Windows
12:36:51-976007 INFO     Version: 4a3ab4ed Thu Jun 8 16:10:39 2023 -0400
12:36:52-413404 INFO     Setting environment tuning
12:36:52-415405 INFO     nVidia CUDA toolkit detected
12:36:55-917614 INFO     Torch 2.0.1+cu118
12:36:56-002691 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
12:36:56-004693 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12287 Arch (8, 6) Cores 80
12:36:56-146821 WARNING  Modified files: ['cmd_opts.data_dir/', 'train/templates/mypreset.txt']
12:36:56-180852 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
12:36:56-189862 INFO     Enabled extensions: ['a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer',
                         'canvas-zoom', 'deforum-for-automatic1111-webui', 'sd-webui-aspect-ratio-helper',
                         'sd-webui-photopea-embed', 'sd_dreambooth_extension', 'stable-diffusion-webui-promptgen',
                         'stable-diffusion-webui-Prompt_Generator', 'stable-diffusion-webui-two-shot',
                         'ultimate-upscale-for-automatic1111']
12:36:56-202873 INFO     No changes detected: Quick launch active
12:36:56-203875 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
12:36:56-208879 INFO     Enabled extensions: ['a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer',
                         'canvas-zoom', 'deforum-for-automatic1111-webui', 'sd-webui-aspect-ratio-helper',
                         'sd-webui-photopea-embed', 'sd_dreambooth_extension', 'stable-diffusion-webui-promptgen',
                         'stable-diffusion-webui-Prompt_Generator', 'stable-diffusion-webui-two-shot',
                         'ultimate-upscale-for-automatic1111']
12:36:56-227896 INFO     Extension preload: 0.0s C:\automatic\extensions-builtin
12:36:56-230898 INFO     Extension preload: 0.0s C:\automatic\extensions
12:36:56-231900 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
12:37:09-180222 INFO     Libraries loaded
12:37:09-182224 INFO     Using data path: C:\automatic
12:37:09-296369 INFO     Available VAEs: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\VAE
                         5
12:37:14-699434 INFO     Available models: F:\Telechargements\SUPER SD 2.0
                         Dependencies\stable-diffusion-webui\models\Stable-diffusion 181
12:37:19-504665 INFO     ControlNet v1.1.220
ControlNet preprocessor location: D:\automatic\extensions-builtin\sd-webui-controlnet\models
12:37:20-745340 INFO     ControlNet v1.1.220
[-] ADetailer initialized. version: 23.6.2, num models: 8
12:37:23-100704 INFO     Libraries loaded
Loading weights: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\Stable-diffusion\delibera…
12:37:25-887690 INFO     Torch override dtype: no-half set
12:37:25-888691 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
12:37:26-252021 INFO     Model created from config: C:\automatic\configs\v1-inference.yaml
Loading weights: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema…
12:38:01-544433 INFO     Applying scaled dot product cross attention optimization
12:38:02-954956 INFO     Model loaded in 39.7s (load=2.5s config=0.1s create=0.4s apply=31.7s vae=2.5s move=1.0s
                         embeddings=1.4s)
12:38:03-196174 INFO     Model load finished: {'ram': {'used': 3.36, 'total': 31.94}, 'gpu': {'used': 5.31, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
12:38:04-057977 INFO     Loading UI theme: name=gradio/default style=Auto
*Deforum ControlNet support: enabled*
12:38:05-578358 INFO     Available models: F:\Telechargements\SUPER SD 2.0
                         Dependencies\stable-diffusion-webui\models\Stable-diffusion 181
CUDA SETUP: Loading binary C:\automatic\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860
To create a public link, set `share=True` in `launch()`.
12:38:07-332951 INFO     Local URL: http://127.0.0.1:7860/
12:38:07-334953 INFO     Initializing middleware
12:38:07-483088 INFO     [AgentScheduler] Task queue is empty
12:38:07-484089 INFO     [AgentScheduler] Registering APIs
12:38:08-633133 INFO     Startup time: 72.4s (torch=8.0s gradio=1.8s libraries=3.1s vae=0.1s models=5.4s
                         codeformer=0.2s gfpgan=0.1s scripts=48.9s upscalers=0.2s onchange=0.1s ui=3.0s launch=0.2s
                         scripts app_started_callback=0.7s checkpoint=0.6s)
12:39:06-544115 INFO     Extensions updated: sd-webui-controlnet 05e66969 2023-06-09 05:50:02
12:39:12-956751 INFO     Extensions no update available: sd-webui-photopea-embed f465a26a 2023-05-13 18:09:09
Loading CLIP Interrogator 0.5.4...
load checkpoint from C:\automatic\models\BLIP\model_base_caption_capfilt_large.pth
Loading CLIP model...
Loaded CLIP model and data in 4.42 seconds.
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0

### Version Platform Description

windows11, Chrome

**Comment by ronbere** [comment] 2023-06-09 10:50
with --debug

C:\automatic>webui --debug
Using VENV: C:\automatic\venv
12:46:38-759468 INFO     Starting SD.Next
12:46:38-761470 INFO     Python 3.10.9 on Windows
12:46:38-796502 INFO     Version: 4a3ab4ed Thu Jun 8 16:10:39 2023 -0400
12:46:39-149828 INFO     Setting environment tuning
12:46:39-150829 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False
12:46:39-151829 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True
12:46:39-152830 INFO     nVidia CUDA toolkit detected
12:46:40-311884 INFO     Torch 2.0.1+cu118
12:46:40-322894 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
12:46:40-323895 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12287 Arch (8, 6) Cores 80
12:46:40-413975 WARNING  Modified files: ['cmd_opts.data_dir/', 'train/templates/mypreset.txt']
12:46:40-447006 DEBUG    Repository update time: Thu Jun  8 22:10:39 2023
12:46:40-448007 DEBUG    Previous setup time: Fri Jun  9 00:30:51 2023
12:46:40-449008 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
12:46:40-455013 INFO     Enabled extensions: ['a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer',
                         'canvas-zoom', 'deforum-for-automatic1111-webui', 'sd-webui-aspect-ratio-helper',
                         'sd-webui-photopea-embed', 'sd_dreambooth_extension', 'stable-diffusion-webui-promptgen',
                         'stable-diffusion-webui-Prompt_Generator', 'stable-diffusion-webui-two-shot',
                         'ultimate-upscale-for-automatic1111']
12:46:40-462020 DEBUG    Latest extensions time: Fri Jun  9 12:40:46 2023
12:46:40-463021 DEBUG    Timestamps: version:1686255039 setup:1686263451 extension:1686307246
12:46:40-463021 INFO     Verifying requirements
12:46:40-472029 WARNING  Package wrong version: accelerate 0.19.0 required 0.18.0
12:46:40-473030 INFO     Installing package: accelerate==0.18.0
12:46:40-474031 DEBUG    Running pip: install --upgrade accelerate==0.18.0
12:46:43-056780 WARNING  Package wrong version: transformers 4.29.2 required 4.26.1
12:46:43-057782 INFO     Installing package: transformers==4.26.1
12:46:43-058783 DEBUG    Running pip: install --upgrade transformers==4.26.1
12:46:51-016009 INFO     Verifying packages
12:46:51-017010 INFO     Installing repositories
12:46:53-982116 INFO     Installing submodules
12:46:55-082115 DEBUG    Submodules list: 123d1da15d802823480f8020312ce449523f10e2
                         extensions-builtin/a1111-sd-webui-lycoris (heads/main)
                          9e6bbd9b8931bbe869a8e28e7005b0e13c2efff0 extensions-builtin/clip-interrogator-ext
                         (heads/main)
                          70b3c5ea3c9f684d04e7ff59167565974415735c
                         extensions-builtin/multidiffusion-upscaler-for-automatic1111 (sd-webui-v1.1.0-25-g70b3c5e)
                          f02cacfc923e8bbf73f25327d722d50c458d66bb extensions-builtin/sd-dynamic-thresholding
                         (heads/master)
                          064c856acaed8c73c3a232e39df8c37d0bb9a15c extensions-builtin/sd-extension-system-info
                         (heads/main)
                          45dfe5977ea43a14f61f46d572615efe169ca2be extensions-builtin/sd-webui-agent-scheduler
                         (heads/main)
                         +05e669696d119aa4a8e228a3743a773e363fabee extensions-builtin/sd-webui-controlnet (heads/main)
                          b2f6e4cbe507078e3bf2b9d5fce6f83e2e233aa8
                         extensions-builtin/stable-diffusion-webui-images-browser (heads/main)
                          3d9eedbbf0d585207f97d5b21e42f32c0042df70 extensions-builtin/stable-diffusion-webui-rembg
                         (heads/master)
                          6417f5d7c183eccd79422f28804f7d7c507e05b9 modules/lora (v0.6.4-104-g6417f5d)
                          57d71913bf47a48dc7dd519b89dd30e09c937b83 modules/lycoris (heads/main)
                          801130e4c45c815c4b2718a70ae88a2653fd780e wiki (heads/master)
12:46:55-655636 INFO     Updating submodules
12:47:02-927581 DEBUG    Installed packages: 228
12:47:02-928581 DEBUG    Extensions all: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
12:47:04-221795 DEBUG    Running extension installer: C:\automatic\extensions-builtin\clip-interrogator-ext\install.py
12:47:11-803169 DEBUG    Running extension installer:
                         C:\automatic\extensions-builtin\sd-extension-system-info\install.py
12:47:12-868137 DEBUG    Running extension installer:
                         C:\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
12:47:13-922132 DEBUG    Running extension installer: C:\automatic\extensions-builtin\sd-webui-controlnet\install.py
12:47:14-964078 DEBUG    Running extension installer:
                         C:\automatic\extensions-builtin\stable-diffusion-webui-images-browser\install.py
12:47:16-684300 DEBUG    Running extension installer:
                         C:\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
12:47:17-342898 DEBUG    Extensions all: ['a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer', 'canvas-zoom',
                         'deforum-for-automatic1111-webui', 'sd-webui-aspect-ratio-helper', 'sd-webui-photopea-embed',
                         'sd_dreambooth_extension', 'stable-diffusion-webui-promptgen',
                         'stable-diffusion-webui-Prompt_Generator', 'stable-diffusion-webui-two-shot',
                         'ultimate-upscale-for-automatic1111']
12:47:19-443038 DEBUG    Running extension installer: C:\automatic\extensions\adetailer\install.py
12:47:20-557107 DEBUG    Running extension installer: C:\automatic\extensions\canvas-zoom\install.py
12:47:23-464747 DEBUG    Running extension installer:
                         C:\automatic\extensions\deforum-for-automatic1111-webui\install.py
12:47:26-009120 DEBUG    Running extension installer: C:\automatic\extensions\sd_dreambooth_extension\install.py
12:47:41-599277 INFO     Extension installed packages: sd_dreambooth_extension ['transformers==4.29.2',
                         'accelerate==0.19.0']
12:47:42-918549 DEBUG    Running extension installer:
                         C:\automatic\extensions\stable-diffusion-webui-Prompt_Generator\install.py
12:47:44-909698 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer', 'canvas-zoom',
                         'deforum-for-automatic1111-webui', 'sd-webui-aspect-ratio-helper', 'sd-webui-photopea-embed',
                         'sd_dreambooth_extension', 'stable-diffusion-webui-promptgen',
                         'stable-diffusion-webui-Prompt_Generator', 'stable-diffusion-webui-two-shot',
                         'ultimate-upscale-for-automatic1111']
12:47:44-911701 INFO     Updating Wiki
12:47:45-507241 DEBUG    Setup complete without errors: 1686307666
12:47:45-512246 INFO     Extension preload: 0.0s C:\automatic\extensions-builtin
12:47:45-513247 INFO     Extension preload: 0.0s C:\automatic\extensions
12:47:45-514248 DEBUG    Args: {'config': 'C:\\automatic\\config.json', 'ui_config': 'C:\\automatic\\ui-config.json',
                         'medvram': False, 'lowvram': False, 'ckpt': None, 'vae': None, 'data_dir': 'C:\\automatic',
                         'models_dir': 'models', 'allow_code': False, 'share': False, 'insecure': False, 'use_cpu': [],
                         'listen': False, 'port': 7860, 'freeze': False, 'auth': None, 'auth_file': None, 'autolaunch':
                         False, 'docs': False, 'api_only': False, 'api_log': False, 'device_id': None, 'cors_origins':
                         None, 'cors_regex': None, 'tls_keyfile': None, 'tls_certfile': None, 'tls_selfsign': None,
                         'server_name': None, 'no_hashing': False, 'no_download': False, 'profile': False,
                         'disable_queue': False, 'subpath': None, 'backend': None, 'f': False, 'ui_settings_file':
                         'C:\\automatic\\config.json', 'ui_config_file': 'C:\\automatic\\ui-config.json',
                         'hide_ui_dir_config': False, 'theme': None, 'disable_console_progressbars': True,
                         'disable_safe_unpickle': True, 'lowram': False, 'disable_extension_access': False, 'api':
                         True, 'api_auth': None, 'debug': True, 'reset': False, 'upgrade': False, 'use_ipex': False,
                         'use_directml': False, 'use_cuda': False, 'use_rocm': False, 'skip_update': False,
                         'skip_requirements': False, 'skip_extensions': False, 'skip_git': False, 'skip_torch': False,
                         'experimental': False, 'reinstall': False, 'test': False, 'version': False, 'ignore': False,
                         'safe': False, 'base': False, 'ldsr_models_path': 'C:\\automatic\\models\\LDSR', 'lora_dir':
                         'C:\\automatic\\models\\Lora', 'scunet_models_path': 'C:\\automatic\\models\\ScuNET',
                         'swinir_models_path': 'C:\\automatic\\models\\SwinIR', 'lyco_dir':
                         'C:\\automatic\\models\\LyCORIS', 'lyco_patch_lora': False, 'lyco_debug': False,
                         'controlnet_dir': None, 'controlnet_annotator_models_path': None, 'no_half_controlnet': None,
                         'controlnet_preprocessor_cache_size': 16, 'controlnet_loglevel': 'INFO', 'ad_no_huggingface':
                         False, 'dreambooth_models_path': None, 'lora_models_path': None, 'ckptfix': False,
                         'force_cpu': False, 'profile_db': False, 'debug_db': False}
12:47:45-519253 INFO     Server arguments: ['--debug']
12:47:45-532264 DEBUG    Memory used: 0.34 total: 31.94 Collected 0
No module 'xformers'. Proceeding without it.
12:47:50-577847 INFO     Libraries loaded
12:47:50-580850 DEBUG    Entering start sequence
12:47:50-678938 DEBUG    Version: {'app': 'sd.next', 'updated': '2023-06-08', 'hash': '4a3ab4ed', 'url':
                         'https://github.com/vladmandic/automatic/tree/master'}
12:47:50-679940 INFO     Using data path: C:\automatic
12:47:50-681941 DEBUG    Entering initialize
12:47:50-685945 INFO     Available VAEs: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\VAE
                         5
12:47:50-829074 INFO     Available models: F:\Telechargements\SUPER SD 2.0
                         Dependencies\stable-diffusion-webui\models\Stable-diffusion 181
12:47:50-889129 DEBUG    Loading scripts
12:47:53-263285 INFO     ControlNet v1.1.222
ControlNet preprocessor location: D:\automatic\extensions-builtin\sd-webui-controlnet\models
12:47:53-372384 INFO     ControlNet v1.1.222
[-] ADetailer initialized. version: 23.6.2, num models: 8
12:47:54-993857 INFO     Libraries loaded
12:47:55-129980 DEBUG    Select checkpoint: deliberate_v2.safetensors [9aba26abdf]
12:47:55-130982 DEBUG    Reload model weights: existing=False target=F:\Telechargements\SUPER SD 2.0
                         Dependencies\stable-diffusion-webui\models\Stable-diffusion\deliberate_v2.safetensors
                         info=None
Loading weights: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\Stable-diffusion\delibera…
12:47:55-272110 DEBUG    Load model: name=F:\Telechargements\SUPER SD 2.0
                         Dependencies\stable-diffusion-webui\models\Stable-diffusion\deliberate_v2.safetensors
                         dict=True
12:47:55-274112 DEBUG    Verifying Torch settings
12:47:55-302137 DEBUG    Torch FP16 test passed
12:47:55-303138 INFO     Torch override dtype: no-half set
12:47:55-304138 DEBUG    Desired Torch parameters: dtype=FP16 no-half=True no-half-vae=False upscast=False
12:47:55-304138 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
12:47:55-305140 DEBUG    Torch default device: cuda
12:47:55-306140 DEBUG    Model dict loaded: {'ram': {'used': 0.99, 'total': 31.94}, 'gpu': {'used': 1.22, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
12:47:55-316150 DEBUG    Model config loaded: {'ram': {'used': 0.99, 'total': 31.94}, 'gpu': {'used': 1.22, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
12:47:55-636440 INFO     Model created from config: C:\automatic\configs\v1-inference.yaml
12:47:55-637441 DEBUG    Model weights loading: {'ram': {'used': 1.96, 'total': 31.94}, 'gpu': {'used': 1.22, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
Loading weights: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema…
12:47:56-357095 DEBUG    Model weights loaded: {'ram': {'used': 7.3, 'total': 31.94}, 'gpu': {'used': 1.22, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
12:47:57-273927 DEBUG    Model weights moved: {'ram': {'used': 3.32, 'total': 31.94}, 'gpu': {'used': 5.31, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
12:47:57-279933 INFO     Applying scaled dot product cross attention optimization
12:47:57-348996 INFO     Model loaded in 2.2s (load=0.1s create=0.3s apply=0.5s vae=0.2s move=0.9s embeddings=0.1s)
12:47:57-584209 DEBUG    gc: collected=1319 device=cuda {'ram': {'used': 3.36, 'total': 31.94}, 'gpu': {'used': 5.31,
                         'total': 12.0}, 'retries': 0, 'oom': 0}
12:47:57-585210 INFO     Model load finished: {'ram': {'used': 3.36, 'total': 31.94}, 'gpu': {'used': 5.31, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
12:47:58-178750 INFO     Loading UI theme: name=gradio/default style=Auto
12:47:58-181752 DEBUG    Creating UI
12:47:59-036528 DEBUG    Script: 0.34s ui_tabs
                         C:\automatic\extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browser.py
*Deforum ControlNet support: enabled*
12:47:59-168649 DEBUG    Script: 0.12s ui_tabs
                         C:\automatic\extensions\deforum-for-automatic1111-webui\scripts\deforum.py
12:47:59-603043 INFO     Available models: F:\Telechargements\SUPER SD 2.0
                         Dependencies\stable-diffusion-webui\models\Stable-diffusion 181
CUDA SETUP: Loading binary C:\automatic\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
12:47:59-766192 DEBUG    Script: 0.58s ui_tabs C:\automatic\extensions\sd_dreambooth_extension\scripts\main.py
12:47:59-799222 DEBUG    Extensions list loaded: C:\automatic\html\extensions.json
Running on local URL:  http://127.0.0.1:7860
To create a public link, set `share=True` in `launch()`.
12:48:01-355635 INFO     Local URL: http://127.0.0.1:7860/
12:48:01-356636 DEBUG    Gradio registered functions: 1707
12:48:01-357637 INFO     Initializing middleware
12:48:01-359638 DEBUG    Creating API
12:48:01-496763 INFO     [AgentScheduler] Task queue is empty
12:48:01-497764 INFO     [AgentScheduler] Registering APIs
12:48:02-043260 DEBUG    Script: 0.43s app_started
                         C:\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py
12:48:02-044260 DEBUG    Scripts setup: ['Tiled Diffusion:0.018s', 'Tiled VAE:0.001s', 'Dynamic Thresholding (CFG Scale
                         Fix):0.001s', 'ControlNet:0.032s', 'ADetailer:0.083s', 'Latent Couple extension:0.009s',
                         'Prompt matrix:0.001s', 'Prompts from file:0.001s', 'X/Y/Z plot:0.004s', 'controlnet
                         m2m:0.002s', 'Alternative:0.001s', 'Outpainting:0.001s', 'Ultimate SD upscale:0.001s']s
12:48:02-045261 DEBUG    Scripts components: ['Prompt matrix:0.004s', 'Prompts from file:0.001s', 'X/Y/Z plot:0.003s',
                         'Tiled Diffusion:0.001s', 'Tiled VAE:0.002s', 'Dynamic Thresholding (CFG Scale Fix):0.003s',
                         'ControlNet:0.003s', 'controlnet m2m:0.001s', 'ADetailer:0.003s', 'Aspect Ratio
                         Helper:0.004s', 'Latent Couple extension:0.002s', 'Outpainting alternative:0.001s', 'SD
                         upscale:0.002s', 'Ultimate SD upscale:0.001s']s
12:48:02-354542 DEBUG    gc: collected=5997 device=cuda {'ram': {'used': 1.46, 'total': 31.94}, 'gpu': {'used': 5.31,
                         'total': 12.0}, 'retries': 0, 'oom': 0}
12:48:02-663823 DEBUG    gc: collected=124 device=cuda {'ram': {'used': 1.46, 'total': 31.94}, 'gpu': {'used': 5.31,
                         'total': 12.0}, 'retries': 0, 'oom': 0}
12:48:02-664824 INFO     Startup time: 17.1s (torch=2.9s gradio=0.9s libraries=1.3s vae=0.1s models=0.1s scripts=7.2s
                         onchange=0.1s ui=2.9s launch=0.2s scripts app_started_callback=0.7s checkpoint=0.6s)
12:50:00-429301 DEBUG    Server alive: True Memory used: 1.46 total: 31.94

**Comment by vladmandic** [comment] 2023-06-09 12:33
it would take only few seconds to fill some info instead of posting full log dump.
no info (which interrogator???), no version and platform info, etc...
marking issue as invalid!

**Comment by ShmuelRonen** [comment] 2023-06-09 12:46
How to mark issue as Extestion type?

**Comment by vladmandic** [comment] 2023-06-09 12:59
when you click new issue, it asks you what type of an issue it is. use the right template or this repo is going to degrade into thousands of issues nobody looks at and we don't want that.

**Comment by ShmuelRonen** [comment] 2023-06-09 18:29
When I click 'nwe issue' it not ask me enithing.

I've been trying for a few minutes to find where the issue is classified as an extension and I can't find the way. It really frustrates me.


Probably something is not working right.

**Comment by vladmandic** [comment] 2023-06-09 19:38
when you click on new issue, first thing you get is this:
![image](https://github.com/vladmandic/automatic/assets/57876960/e94dd010-5eed-42fb-8729-4dc98b421b27)

**Comment by vladmandic** [comment] 2023-06-09 19:44
i can convert this to extension report, fine, but it doesn't justify your total lack of information or specific comment on how to quote when creating an issue.

**Comment by ShmuelRonen** [comment] 2023-06-09 19:53
> i can convert this to extension report, fine, but it doesn't justify your total lack of information or specific comment on how to quote when creating an issue.

This is my issue:

https://github.com/vladmandic/automatic/issues/1371#issuecomment-1584504920

**Comment by vladmandic** [comment] 2023-06-09 19:56
seriously, read what i wrote - i cannot go back and forth what is written in different threads - you know how many things i'm juggling? issue must be self-sufficient and document everything. yours documents nothing. not a single line of test. and i've highlighted that and gave you a chance to edit, but you go back and quote something else?

**Comment by ronbere** [comment] 2023-06-09 20:53
> it would take only few seconds to fill some info instead of posting full log dump.
> no info (which interrogator???), no version and platform info, etc...

The version is indicated in my post, the platform also. interrogator is built in extension, what do u need for informations??

**Comment by vladmandic** [comment] 2023-06-09 21:15
do i really need to say it again?
**i cannot go back and forth what is written in different threads? every issue must be self-sufficient and document everything. yours documents nothing. not a single line of text.**
it doesn't matter if you documented it in a different issue.
and you could have updated the issue much faster than spend time on this text thread. i've asked for it 3 times, now closing.

**Closed** 2023-06-09 21:15 UTC
Labels: invalid
