### ISSUE TITLE
[Issue]: Checkpoint select turns into infinite loading

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#1113] opened 2023-05-21 16:20 UTC
### Issue Description

Since the last updates I'm experience this strange behavior, that after a while, the checkpoint select in the quick settings turns into an infinite loading.
![Zwischenablagebild (1)](https://github.com/vladmandic/automatic/assets/122026301/912765ae-4ad2-4aaf-b93a-0b7e602e2a8e)
Everything stays working, but checkpoint changing is not possible anymore.

It appears mostly after the webpage is reloaded. There is then no way to restore the dropdown but a complete shutdown of the webpage and the WebUI.

### Version Platform Description

Win10, FF 106
Version: b6289d56 Sat May 20 13:36:27 2023 -0400

**Comment by vladmandic** [comment] 2023-05-21 23:02
lets avoid generic terms as "infinite loading" (yes, i've heard it before and its still as misleading as ever).
when this happens, does the model actually get finished loading (what does console log say)?
does the problem go away if you do a browser page reload? if not, what happens?
do you see similar problems with chrome or only firefox?

> It appears mostly after the webpage is reloaded

do you mean if page is reloaded during model load or anytime or ? be a bit more descriptive.
i'd really like to help, but i need more information for something that is not easily reproducible.

**Comment by vladmandic** [comment] 2023-05-22 13:32
ahhh, i though this might be a reoccurence of the old issue, but this sounds very specific and not reported before.
what would help is to a) open browser inspector, b) reproduce.
its important that inspector is open before the problem happens so it captures the actual issue, not only evens afterwards.
and then copy&paste browser console log here.

**Comment by sebaxakerhtc** [comment] 2023-05-22 13:34
Just tried latest known stable 26b05ef88360aa25582d8be8ba8dbf33c3d2d9ad and all works fine and from next [minor updates](https://github.com/vladmandic/automatic/commit/d647bb5c052277ec48d5c1858a52d4b6de30e8f1) it happens

**Comment by sebaxakerhtc** [comment] 2023-05-22 13:43
To reproduce you need to 
1) log in to WebUI
2) Change model (ckpt/safetensors)
3) Refresh the page

**Comment by vladmandic** [comment] 2023-05-22 13:57
i understand that, but i set "cannot reproduce" flag for a reason - i don't see that behavior, that's why i need info from you.

**Comment by sebaxakerhtc** [comment] 2023-05-22 14:23
> i understand that, but i set "cannot reproduce" flag for a reason - i don't see that behavior, that's why i need info from you.

When all works normally in console we can see one message `TypeError: parent.Symbol.for is not a function`
When this BUG happens  we see many rows of this message

**Comment by vladmandic** [comment] 2023-05-22 14:38
i need a full traceback of single instance of error in apply.js:105:70

**Comment by sebaxakerhtc** [comment] 2023-05-22 14:41
> i need a full traceback of single instance of error in apply.js:105:70

Tested with latest known working instance - same errors.
In Google Chrome no errors at all

**Comment by sebaxakerhtc** [comment] 2023-05-22 14:42
<img width="2048" alt="Снимок экрана 2023-05-22 в 17 39 44" src="https://github.com/vladmandic/automatic/assets/32651506/69e44098-1de5-4c1e-b6e5-aab002de18e3">

**Comment by sebaxakerhtc** [comment] 2023-05-22 14:51
If you want - i can create a clean installation and send you a credentials for logging in and test it by yourself

**Comment by Tillerz** [comment] 2023-05-22 16:00
I had that "endless loading" turning spinner thing and the timer going up yesterday, but for the Styles box. I had not clicked it or something, it just did it when I saw it was at 240 or something, still counting. That happened like 2 or 3 times, and then I didn't see it anymore.

I know it is adding more to confusion that helping. :D

**Comment by Woisek** [comment] 2023-05-22 17:39
> For the workaround to this "endless spinner", you could try `--disable-queue` as startup parameter, it helped me in the past A LOT. 🙂

But isn't that intended for the generation process? 🤔

**Comment by vladmandic** [comment] 2023-05-22 18:25
`--disable-queue` changes how server communicates with browser in general - it disables usage of websockets and uses pure http for everything.

**Comment by Woisek** [comment] 2023-05-22 18:36
OK, but didn't you considered that as "bad" some time ago ... ? Can remember exactly ...

**Comment by brknsoul** [comment] 2023-05-23 12:31
I'm getting this as well with the Styles dropdown;
![image](https://github.com/vladmandic/automatic/assets/1969381/29b01dca-a9f6-42d4-92ba-d476b3000c1e)

794b23cc

**Comment by sebaxakerhtc** [comment] 2023-05-24 06:54
@vladmandic 
Hi. So, after many tests i don't see any errors in browser console but many rows of [this](https://github.com/vladmandic/automatic/issues/1113#issuecomment-1557316089)
But problem is not there, because on working commit i can still see those.

Only one thing i found - wss
<img width="819" alt="wss" src="https://github.com/vladmandic/automatic/assets/32651506/66b7f8cf-6efe-4efd-8b7b-47799e26ca30">
The first one appears when UI loaded and we see the old checkpoint
The second appears when checkpoint list is grayed out
And the last one i see the new model and timer goes infinity...

Here is the request headers of the last one:
```
GET /queue/join HTTP/1.1
Host: sebaxakerhtc.tplinkdns.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: */*
Accept-Language: ru
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: http://sebaxakerhtc.tplinkdns.com
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: ssJ+y56ehT3q8LlVzjzuaA==
DNT: 1
Connection: keep-alive, Upgrade
Cookie: access-token-unsecure=CPJiZdt_q_Zafc-jdBPX0A
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

And the answer headers:
```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: QNyL+3rYrbPZiPUSOfgRC7A+2/4=
Sec-WebSocket-Extensions: permessage-deflate
date: Wed, 24 May 2023 06:36:37 GMT
server: uvicorn
```

I hope it will be helpful. Thank you!

**Comment by sebaxakerhtc** [comment] 2023-05-24 11:25
[video of this](https://cloud.burgas.pro/s/6QaxjRgsmm6jfTH) BUG

**Comment by vladmandic** [comment] 2023-05-24 14:35
two days ago i've asked to try with `--disable-queue` and in all recent updates i still see websockets being used, so there is no update provided on that specific test?

**Comment by sebaxakerhtc** [comment] 2023-05-24 14:37
> two days ago i've asked to try with `--disable-queue`

It works fine. I don't understand you want it

**Comment by vladmandic** [comment] 2023-05-24 14:40
> it works fine

you're saying that there is no issue if you use `--disable-queue`?
nobody has provided that feedback here until you just said it, so please confirm?!

**Comment by sebaxakerhtc** [comment] 2023-05-24 14:40
> you're saying that there is no issue if you use `--disable-queue`?

Yes

**Comment by vladmandic** [comment] 2023-05-24 14:43
which means that 99% of issue is with your network.
and by network, i mean connection between browser and server - even if they are on the same localhost, there can still be network issues, especially if you use 3rd party browser extensions (for example, some adblockers are horrible) or firewalls or antivirus (which also scans network traffic).

so use `--disable-queue` as a workaround (no issues using it long term), but if it were me, i'd investigate what is causing websocket disconnects on your network and stop using that product.

**Comment by sebaxakerhtc** [comment] 2023-05-24 14:49
> which means that 99% of issue is with your network.

Ok, but why it worked fine before commit https://github.com/vladmandic/automatic/commit/d647bb5c052277ec48d5c1858a52d4b6de30e8f1 ?

**Comment by vladmandic** [comment] 2023-05-24 14:56
> Ok, but why it worked fine before commit 

every new version of gradio switches more and more of legacy http connections to websockets. so its going to get worse and worse over time unless you either use workaround or fix your network.

> I don't use any 3rd party extensions on this WebUI page.

yes, you do, i can see at least a hint of chrome extension in the video you've posted. and like i said, its not only about extensions.

**Comment by sebaxakerhtc** [comment] 2023-05-24 14:59
> yes, you do, i can see at least a hint of chrome extension

I don't use chrome - it's just for the tests. Yes, it have ADBlock, but I can send you a video from Firefox without extensions - the result is the same

**Comment by vladmandic** [comment] 2023-05-24 15:10
ok, i believe you on browser extensions, but the root cause is the same - it works with HTTP and causes issues with WebSockets - because something is interfering with WebSockets.

**Comment by mart-hill** [comment] 2023-05-24 15:11
For me, WebSockets now work with beff89ba commit (upgrading just now to newest one), after switching to Approx NN preview and then fixes to Gradio concerning timeouts. I use Comodo Internet Security (free version) and AdGuard with its network driver on Windows 22H2.
It's nice to have this --disable-queue fallback method though. 🙂

**Comment by sebaxakerhtc** [comment] 2023-05-24 16:47
> the root cause is the same - it works with HTTP and causes issues with WebSockets - because something is interfering with WebSockets.

Double checked all security things, 
added exclusions in firewall to this specific IP in router, 
added exclusion in windows firewall, 
moved to httpS with help of lets encrypt,
tested websockets on my ESXi - all wss works fine,
BUT still have this issue!

**Comment by vladmandic** [comment] 2023-05-24 16:58
wait, what is you topology like between browser and actual server?
how gradio implemented websockets (not ideal by far, but nothing i can do about it) is with hard coded 5sec timeout (used to be 1sec, at least that has changed), so for long running operations like model change, it relies on network layer to socket alive even if it doesn't specity keepalive itself (yes, it should). given your topology, likely something in between is being a bit aggressive (as it should be, but not what you want in this case).

in either case, i've provided a valid workaround and i cannot solve websockets closing in my app level. so really not sure what else do you want me to say here?

**Comment by vladmandic** [comment] 2023-05-24 16:59
@Woisek since you're the original author of the issue, how are things on your side with `--disable-queue`?

**Comment by sebaxakerhtc** [comment] 2023-05-24 17:12
> how gradio implemented websockets (not ideal by far, but nothing i can do about it)

i think gradio has nothing common with this issue, because not gradio update but another commit - [minor updates](https://github.com/vladmandic/automatic/commit/d647bb5c052277ec48d5c1858a52d4b6de30e8f1) broke this.
Thats why I think you can solve it

**Comment by Woisek** [comment] 2023-05-24 18:34
> @Woisek since you're the original author of the issue, how are things on your side with `--disable-queue`?

At the moment, I had it not happening again. But I also did a bit different things lately, so ... can't be completely sure. But I work again in a few days, I will look out what's happening then and report.

**Comment by radry** [comment] 2023-05-29 20:11
I also have the impression that model loading has become extremly slow with some update in the past 3 weeks (was away and didn't use SD in that time). Loading a model now takes around 5 Minutes while before it was done in 1-2 Minutes.

**Comment by vladmandic** [comment] 2023-05-29 20:14
@radry that sounds like a completely separate issue, why not treat it as such instead of posting on unrelated thread?
btw, model loading takes couple of seconds on ssd. what is your platform and storage and how is it connected/mounted?

**Comment by vladmandic** [comment] 2023-06-04 17:27
@woisek since i haven't heard any news and last update was 2 weeks ago that its not happening at that time, i'm closing the issue. if there are any news, let me know and i'll reopen if needed.

**Closed by vladmandic** 2023-06-04 17:27 UTC
Labels: question, cannot reproduce

**Comment by Woisek** [comment] 2023-06-04 18:00
@vladmandic 
It's OK, had not this issue lately. Only the problem with the invisible dropdown is still there.

**Comment by lbeltrame** [comment] 2023-06-07 21:13
Still an issue, happens also on underpowered devices that are too slow in loading the JS (like my phone). Queue unfortunately is essential when reverse proxying, or the repeated POSTs cause all sorts of issues. Experienced on latest Firefox and Chrome, on Linux, on two separate machines.

**Comment by vladmandic** [comment] 2023-06-07 21:38
i can reopen, but there not much i can do here...and current ui although it might work on mobile devices, its not really intended for it. hopefully new ui (comming soon) will be better.

**Comment by sebaxakerhtc** [comment] 2023-06-07 21:48
> i can reopen, but there not much i can do here...and current ui although it might work on mobile devices, its not really intended for it. hopefully new ui (comming soon) will be better.

I hope it too. 
Because another fork (https://github.com/anapnoe/stable-diffusion-webui-ux) all works fine

**Comment by vladmandic** [comment] 2023-06-07 21:54
he's the guy writing the new ui, so yeah, i hope so too :)

**Comment by StableInfo** [comment] 2023-06-14 11:59
Not sure what I did, I went to the PARAM file and changed he model, and it still did not work, when I restarted a fourth or fivth time the program and this time I went and modified the VAE in settings beforehand. It finally rested and no longer indefinite loading.

**Comment by sebaxakerhtc** [comment] 2023-06-14 12:03
> Not sure what I did, I went to the PARAM file and changed he model, and it still did not work, when I restarted a fourth or fivth time the program and this time I went and modified the VAE in settings beforehand. It finally rested and no longer indefinite loading.

Can you provide step-by-step log of what you do?
Because i'm still stack at this point after many tries different solutions. For now i just use webui-ux or original a1111 when need to change models

**Comment by StableInfo** [comment] 2023-06-14 12:17
There is a very simply way to change the model, you go to XYZ tool and chose only one parameter (checkpoint) and one value (the model you want).
As for what I did:
- Restarting the tab. Did not work.
- restarted from bat file. Did not work.
- did that many times, no change.
- Went to the PARAM file (you can find it at the same level of the bat file), pasted the name of the model I wanted. I did this because I was afraid the loading model was missing somehow (I did not have errors when loading even when the indefinite loading was here but still just in case)
- Did not solve the problem yet, i generated an image, then mmodified the CLIP from 1 to 2 and went to settings and modified the VAE from 84000 to 5X..... Regenrated an image.
- Retarted again from bat file. Waited a bit, went to the tab (my browser) and relaunched http://127.0.0.1:7860/, and this time the infinite loading stopped.
I don't know why.
Anyway if its does not work out for you, you can use the XYZ with argument and you can change your model easily.

**Comment by dkarma** [comment] 2023-09-26 20:32
i've got this as well, but only when loading models above 2.1 gig.  all the models i load that are around 6 gig from civitai site crash the instance when loading:

from the terminal:
Loading weights [fa892e66c0] from /home/dkarma/civitai-stabil-diffusion WORKING/stable-diffusion-webui/models/Stable-diffusion/sdxlNijiSpecial_sdxlNijiSE.safetensors
Creating model from config: /home/dkarma/civitai-stabil-diffusion WORKING/stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml
Killed

theres red popups in teh web page itself, but no error message in the output box generated by teh framework

**Comment by vladmandic** [comment] 2023-09-26 21:48
`killed` is a simple kernel message when it decides to kill the process - and in most cases, its because it over the system ram limits. its not related to symptoms in this issue.

**Comment by hassanoza22** [comment] 2024-03-30 21:08
I don't know if this was ever resolved, but the issue seems to be stemming from a extension called sd_smartprocess, as soon as I remove that extension I no longer have this issue.
