### ISSUE TITLE
[Diffusers]: SDXL Images desaturated and blurry after 77de9cd

### ISSUE THREAD

**Issue by DenkingOfficial** [vladmandic/automatic#1869] opened 2023-07-28 17:47 UTC
### Issue Description

SDXL after 77de9cd commit is producing desaturated and blurry images.

Before 77de9cd
![image](https://github.com/vladmandic/automatic/assets/38957619/3c350ea4-7e81-46ee-bbf0-365d22b780bf)

After:
![image](https://github.com/vladmandic/automatic/assets/38957619/3cc3a8c2-e774-4335-abce-e2cfaeaa224d)

Also, for some reason, external VAE is not working too, here's an example (same images, both with fixed fp16 vae)

First: before 77de9cd, second: after
![image](https://github.com/vladmandic/automatic/assets/38957619/05be1fdc-d172-4368-94ce-5b3d5ac86697)

First one has a lot of purple and green noise (even with fixed VAE), but saturation is ok, second one doesn't have this noise (even WITHOUT fixed VAE), but it's blurry and desaturated

### Diffusers pipeline used

Stable Diffusion XL pipeline with SDXL 1.0

### Version Platform Description

Win 10, Google Chrome

### Relevant log output

```shell
22:42:19-659110 INFO     Starting SD.Next
22:42:19-663610 INFO     Python 3.10.6 on Windows
22:42:19-715610 INFO     Version: 77de9cd0 Fri Jul 28 19:18:37 2023 +0500
22:42:20-258595 INFO     nVidia CUDA toolkit detected
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by DenkingOfficial** [comment] 2023-07-28 19:33
After c8af2af it's fully broken
![20221015242240-1000-A studio portrait photo of a cat](https://github.com/vladmandic/automatic/assets/38957619/0bff92c5-2f59-424b-acf8-1b2770024176)

**Comment by Disty0** [comment] 2023-07-28 19:45
Commits after https://github.com/vladmandic/automatic/commit/77de9cd0934c386ce4798c05955826bab09544b4 made Sequential CPU Offloading work as intended. 
Only difference should be Sequential CPU Offloading. I got the exact same image with the latest and old commits.

Commits before https://github.com/vladmandic/automatic/commit/77de9cd0934c386ce4798c05955826bab09544b4
(https://github.com/vladmandic/automatic/commit/a32bf083f1b68c9c41233e7fe262c7d766dd41f3)

![image](https://github.com/vladmandic/automatic/assets/47277141/9de43fb2-790c-4e0d-b13f-1a075723d638)

Latest commit (https://github.com/vladmandic/automatic/commit/c8af2affafd0740a7330925dc1966ac9e0fb169b):

![image](https://github.com/vladmandic/automatic/assets/47277141/58b9110b-dc21-445b-b1c3-fe35ff00dda4)

**Comment by DenkingOfficial** [comment] 2023-07-28 19:51
> Only difference should be Sequential CPU Offloading.

Hmmm, that's strange
Latest commit works as intended, but it gives me absolute mess instead of an image "Enable VAE tiling" setting is off
![image](https://github.com/vladmandic/automatic/assets/38957619/a4340839-c94c-4d72-ac0d-e154ed8720bf)

**Comment by DenkingOfficial** [comment] 2023-07-28 20:01
UPD: Enable VAE tiling setting is unrelated, turned it on, but still get very noisy image
![image](https://github.com/vladmandic/automatic/assets/38957619/015011d6-32bb-4d54-9248-d49e1397b281)

**Comment by Disty0** [comment] 2023-07-28 20:25
Pushed another commit (https://github.com/vladmandic/automatic/commit/31e1bb01ffb0a905229e582ac713f61693c2e0db).
Can you try again?

**Comment by DenkingOfficial** [comment] 2023-07-28 21:12
Updated to latest version and there is no more messy images, but external VAE still doesn't do anything, there is still a lot of pink/green noise, I made a comparison:

![vaecomp](https://github.com/vladmandic/automatic/assets/38957619/0a73347b-2ac3-4bc0-b134-e3662d8db10e)

Also, StabilityAI pushed a SDXL 1.0 model with VAE from 0.9, I will test it later

**Comment by Disty0** [comment] 2023-07-28 21:13
> 

Reload the model after changing the VAE.

**Comment by DenkingOfficial** [comment] 2023-07-28 21:16
I got this...
![image](https://github.com/vladmandic/automatic/assets/38957619/32a9e582-baad-4605-9cc3-c6f1ae40763d)

**Comment by Kubuxu** [comment] 2023-07-28 21:23
Don't use standalone safetensors vae with SDXL (one in directory with model.json works correctly). It helpfully downloads SD1.5 VAE's `model.json`, which causes desaturation issues.

**Comment by DenkingOfficial** [comment] 2023-07-28 21:32
> Don't use standalone safetensors vae with SDXL (one in directory with model.json works correctly). It helpfully downloads SD1.5 VAE's `model.json`, which causes desaturation issues.

Yes, I know, i'm already using a folder with config and a safetensors file (as a symlink)
![image](https://github.com/vladmandic/automatic/assets/38957619/9f15a006-50de-4989-a656-1b7fe8012e3c)

**Comment by vladmandic** [comment] 2023-08-11 05:42
fixed in dev, will post to main branch soon.

**Closed by vladmandic** 2023-08-11 05:42 UTC
