### ISSUE TITLE
[Extension]: Agent Scheduler not working

### ISSUE THREAD

**Issue by HarrisTerry** [vladmandic/automatic#1506] opened 2023-06-25 12:16 UTC
### Issue Description

OK so as of now, I am having issues with two extensions:

Agent Scheduler - doing nothing. Enque does nothing, no idea what's happening, just does nothing.

Interrogator: Says Loading CLIP Interrogator 0.5.4... but it never does anything, just endlessly tics the time away. I read in a thread Transformers was needed for it to work, I am not sure if that is xformers but I know my SDNext startup says I do not have that, should that be autoinstalled?

Anyhow, those two are not working at all for me.

### Version Platform Description

Win11, 3070ti 8GB, 64GB RAM, 12700k 5ghz

Already up to date.
Using VENV: D:\AI\Vlad1111\automatic\venv
07:56:21-839534 INFO     Starting SD.Next
07:56:21-844855 INFO     Python 3.10.9 on Windows
07:56:21-873225 INFO     Version: 4867dafa Fri Jun 23 08:00:51 2023 -0400
07:56:22-244599 INFO     nVidia CUDA toolkit detected
07:56:25-642828 INFO     Torch 2.0.0+cu118
07:56:25-651832 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
07:56:25-653832 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 Ti VRAM 8192 Arch (8, 6) Cores 48
07:56:25-746510 WARNING  Modified files: ['webui.bat']
07:56:25-781243 INFO     Disabled extensions-builtin: ['TemporalKit', 'sd-webui-panorama-viewer']
07:56:25-781591 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
07:56:25-790663 INFO     Disabled extensions: ['TemporalKit', 'sd-webui-panorama-viewer']
07:56:25-791663 INFO     Enabled extensions: ['a1111-mini-paint', 'a1111-sd-webui-haku-img',
                         'a1111-sd-webui-tagcomplete', 'adetailer', 'deforum-for-automatic1111-webui',
                         'instruct-pix2pix', 'sd-dynamic-prompts', 'sd-webui-3d-open-pose-editor', 'sd-webui-ar',
                         'sd-webui-aspect-ratio-helper', 'sd-webui-cutoff', 'sd_webui_SAG',
                         'stable-diffusion-webui-state', 'ultimate-upscale-for-automatic1111']
07:56:25-808954 INFO     No changes detected: Quick launch active
07:56:25-818084 INFO     Extension preload: 0.0s D:\AI\Vlad1111\automatic\extensions-builtin
07:56:25-820084 INFO     Extension preload: 0.0s D:\AI\Vlad1111\automatic\extensions
07:56:25-841084 INFO     Server arguments: ['--autolaunch']
No module 'xformers'. Proceeding without it.
07:56:36-655177 INFO     Libraries loaded
07:56:36-657177 INFO     Using data path: D:\AI\Vlad1111\automatic
07:56:36-660742 INFO     Available VAEs: D:\AI\Stable Diffusion\stable-diffusion-webui\models\VAE 4
07:56:36-678762 INFO     Available models: D:\AI\Stable Diffusion\stable-diffusion-webui\models\Stable-diffusion 30
07:56:38-264914 INFO     ControlNet v1.1.225
ControlNet v1.1.225
ControlNet preprocessor location: D:\AI\Vlad1111\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
07:56:38-521337 INFO     ControlNet v1.1.225
ControlNet v1.1.225
[-] ADetailer initialized. version: 23.6.3, num models: 8
07:56:40-505185 INFO     Libraries loaded
Libraries loaded
07:56:40-884745 INFO     Loading UI theme: name=gradio/default style=Dark
add tab
*Deforum ControlNet support: enabled*
Loading general settings...
reading custom settings from deforum_settings.txt
legacy_colormatch is missing from settings file, so we are setting it to *True* for backwards compatability. You are welcome to test your file with that setting being disabled for better color coherency.

Running on local URL:  http://127.0.0.1:7860
07:56:44-262798 INFO     Local URL: http://127.0.0.1:7860/
07:56:44-265071 INFO     Initializing middleware
07:56:44-768383 INFO     Model metadata saved: D:\AI\Vlad1111\automatic\metadata.json 1
Loading weights: D:\AI\Stable Diffusion\stable-diffusion-webui\models\Stable-diffusion\absolutereality_v10.safetensors
07:56:45-619298 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: D:\AI\Stable Diffusion\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors ━  -…
07:56:50-724131 INFO     Applying scaled dot product cross attention optimization
07:56:50-798463 INFO     Embeddings: loaded=77 skipped=3
07:56:50-803464 INFO     Model loaded in 5.8s (load=0.6s config=0.1s create=0.2s apply=3.5s vae=0.8s move=0.6s
                         embeddings=0.1s)
07:56:51-003512 INFO     Model load finished: {'ram': {'used': 9.53, 'total': 63.8}, 'gpu': {'used': 3.12, 'total':
                         8.0}, 'retries': 0, 'oom': 0} cached=1
07:56:51-285517 INFO     Startup time: 25.4s (torch=7.1s gradio=1.3s libraries=2.4s codeformer=0.1s scripts=4.0s
                         onchange=0.1s ui=3.2s launch=0.2s app-started=0.5s checkpoint=6.5s)
07:56:51-287517 INFO     Launching browser

### URL link of the extension

https://github.com/pharmapsychotic/clip-interrogator-ext

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by HarrisTerry** [comment] 2023-06-25 12:59
Issue is happening with both on Auto1111 installation that is near-identical with extensions and settings as well :(

**Comment by HarrisTerry** [comment] 2023-06-25 13:00
I checked and I have CLIP models installed

**Comment by ronbere** [comment] 2023-06-25 17:13
> I checked and I have CLIP models installed

delete the folder clip-interrogator-ext on extensions-builtin, install this one : 
https://github.com/Dahvikiin/clip-interrogator-ext

it installs by default in the extensions folder, move it in extensions-builtin.
It works for me

**Comment by vladmandic** [comment] 2023-06-25 17:15
Give me a day and I'll check.
In principle, what you did is a good diag step, but should not be done without considerations, so not a blanket advice.

**Comment by fbellgr** [comment] 2023-06-25 18:57
I personally uninstalled the agent scheduler because it was throwing errors at startup and was not working anymore.

I am sure certain it is not a problem with automatic.

I did not try reinstalling and it's quite possible that a hard rest on the extension's repo might have helped, but as I do not use it, I just let it go.

One with the same problem might want to try hard resetting and cleaning the extension's repo.

**Comment by vladmandic** [comment] 2023-06-25 19:10
If you don't use it, feel free to do whatever you like.
But the rest of the statements are not really helpful here, especially since issue has not been investigated and there are no logs to go over.

**Comment by vladmandic** [comment] 2023-06-26 14:16
i've just tried interrogator (4d865c54) and agent scheduler (9180642e), latest updates for both and both are working fine on my system.

@HarrisTerry can you create separate issue for interrogator (if issue persists) and we'll use this one for agent scheduler - cannot deal with two unrelated things in a same thread.

and post actual log leading up to `Loading CLIP Interrogator 0.5.4.`
which model did you try? default is `vit-l-14/openai` and its 855mb which needs to be downloaded on first usage.

> I checked and I have CLIP models installed

can you show them?

> Agent Scheduler - doing nothing. Enque does nothing, no idea what's happening, just does nothing.

if you write prompt, click enqueue and go to agent scheduler tab, what do you see there?

@Eagle07-Sudo 

before running reinstall, its much simpler/faster to delete config first to use default values. reinstall is very rarely needed and if issue is config, it will still use that same config after reinstall.

**Comment by IkariDevGIT** [comment] 2023-06-26 16:39
@vladmandic idk if this has anything to do with it, but i get this error with the newest version:

```
18:38:42-829655 ERROR    Running script after component:
                         D:\-automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:
                         AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\-automatic\modules\scripts.py:485 in after_component                                                             │
│                                                                                                                     │
│   484 │   │   │   │   t0 = time.time()                                                                              │
│ > 485 │   │   │   │   script.after_component(component, **kwargs)                                                   │
│   486 │   │   │   │   time_component[script.title()] = time_component.get(script.title(), 0) +                      │
│                                                                                                                     │
│ D:\-automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:94 in after_component           │
│                                                                                                                     │
│    93 │   │   if (                                                                                                  │
│ >  94 │   │   │   shared.opts.queue_button_placement == placement_between_prompt_and_generate                       │
│    95 │   │   │   and component.elem_id == neg_id                                                                   │
│                                                                                                                     │
│ D:\-automatic\modules\shared.py:567 in __getattr__                                                                  │
│                                                                                                                     │
│   566 │   │   │   return self.data_labels[item].default                                                             │
│ > 567 │   │   return super(Options, self).__getattribute__(item) # pylint: disable=super-with-                      │
│   568                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Options' object has no attribute 'queue_button_placement'
18:38:42-942354 ERROR    Running script after component:
                         D:\-automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:
                         AttributeError
```

**Comment by vladmandic** [comment] 2023-06-26 16:58
Could be related, don't know since issue was created without logs.

This looks like bug (race condition) in extension where extension is trying to read it's options just before it actually initialized them for the first time.

Can you create issue upstream with your back trace and this info? Author normally pays attention to that pretty fast.

**Comment by vladmandic** [comment] 2023-06-27 12:57
startup error with latest agent-scheduler is tracked under #1518

**Comment by vladmandic** [comment] 2023-06-27 15:24
@Eagle07-Sudo are you on latest version of extension? post version here.
also check browser inspector for any js errors as table not showing up probably means something did not get initialized correctly.

**Comment by vladmandic** [comment] 2023-06-27 16:10
@Eagle07-Sudo 
well, that is the root cause - browser blocked loading of javascript code.

the question is why as i've tested with edge 114 (latest release) and 117 (latest canary) and this does not happen.
do you have some custom settings? or some browser extension/addon that may interfere?
or are you running using public ip and via some proxy?

**Comment by Eagle07-Sudo** [comment] 2023-06-27 19:58
Sorry for keep asking, although it seems like this issue has become specific to my case only. However, none of the solutions below work for me:

- I checked that there is no proxy added in my Windows settings.
- I disabled all Microsoft Edge extensions or plugins (the third issue disappeared).
- I cleared my browser cache and cookies to ensure I'm fetching the latest version of the app.
- I installed Firefox and Chrome browsers and launched the app on them (the same three remaining errors appear).
- I uninstalled the antivirus.
- I tried using another internet provider.

How can I solve a such problem?

**Comment by vladmandic** [comment] 2023-06-27 20:02
what is the full url of the js script that is not loading? screenshot crops it

**Comment by HarrisTerry** [comment] 2023-06-27 22:31
@Eagle07-Sudo its not just you, I have the exact issue. I gave up worrying about it lol, but the exact same thing happens - nothing when I click the button. I have tons of extensions installed, however, and atm I doubt I am going to uninstall one at a time to find a culprit. This and the Interrogator were broken, now the Interrogator works.... I just figured eventually Agent Scheduler would be back online!

**Comment by vladmandic** [comment] 2023-06-28 00:15
> its not just you, I have the exact issue. 

@HarrisTerry you have exactly the same problem with js script rejected in the browser inspector?

**Comment by HarrisTerry** [comment] 2023-06-28 10:04
I have the same issue in regards to the extension doing nothing and the
button doing nothing, sorry for any confusion

**Comment by SignalFlagZ** [comment] 2023-06-28 12:48
I got the same problem.  I found the solution in the sd-webui-agent-scheduler [troubleshooting](https://github.com/ArtVentureX/sd-webui-agent-scheduler#troubleshooting).
After fixing the registry and rebooting Windows, the problem is gone.

**Comment by HarrisTerry** [comment] 2023-06-28 13:27
Here is that soultion, I am wondering what Vlado thinks of it, as I am always wary of messing with my registry

"I tried removing the venv folder and letting it reinitialize but no luck. After some investigation I found the cause of my issue to be a registry error. Computer\HKEY_CLASSES_ROOT\.mjs had the Content Type set to text/plain. I reset it to application/javascript and rebooted and everything is working now.


Open the Registry Editor
Navigate to HKEY_CLASSES_ROOT\.mjs
Double-click on the Content Type value
Change the value to application/javascript
Click OK

Thoughts?

**Comment by Eagle07-Sudo** [comment] 2023-06-28 13:36
@SignalFlagZ Thank you so much for sharing this helpful solution! I followed the steps mentioned in [this guide](https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/4#issuecomment-1575986274), then I restarted my computer and cleared the browser's cache and cookies once again. And guess what? It worked perfectly! I'm really grateful for your assistance.

**Comment by vladmandic** [comment] 2023-06-29 10:45
closing as recommendations have been implemented upstream.

**Closed by vladmandic** 2023-06-29 10:45 UTC
Labels: extension
