### ISSUE TITLE
[Feature]: Generate Seeds via CPU for Platform Agnosticism

### ISSUE THREAD

**Issue by krausekai** [vladmandic/automatic#1263] opened 2023-06-02 05:58 UTC
### Feature description

Per https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9613

It would be beneficial to have an option that allows seed generation via the CPU to keep seeds consistent and backward/forward compatible across different OS, GPU vendors and architectures, PCs, and enable wider community sharing.

**Comment by DirtyHamster** [comment] 2023-06-02 08:17
I read through the comments on this to where it was closed as an expected behavior from where the settings were stated to have them provide the same image at the cost of performance. The issue comes down to the --use-cpu all issue on mac and the xformers issue on windows to have it match linux.

If it were implemented as an on off setting defaulting to off, I wouldn't have an issue with it. I wouldn't want to force it on a user though as there's a cost of performance involved in it. On top of that someone might want to research the differences between the images generated between the platforms as well.

As far as the wider community sharing portion goes I see that more of an issue of getting people sharing filling out the data sets that goes with the shared image correctly. If using png the generative settings data might be able to be placed in file itself perhaps. See: https://www.w3.org/TR/PNG-Chunks.html search for: 4.2.7. tEXt Textual data 

snipped from the article above:
The keyword indicates the type of information represented by the text string. The following keywords are predefined and should be used where appropriate:

   Title            Short (one line) title or caption for image
   Author           Name of image's creator
   Description      Description of image (possibly long)
   Copyright        Copyright notice
   Creation Time    Time of original image creation
   Software         Software used to create the image
   Disclaimer       Legal disclaimer
   Warning          Warning of nature of content
   Source           Device used to create the image
   Comment          Miscellaneous comment; conversion from GIF comment
   
If the generative settings could be listed in there in a standardize manner then the community share point could just scan the file for the known settings. Rather than relying on a person to fill out the data. The file could also then be interrogated for those above mentioned settings too.

**Comment by vladmandic** [comment] 2023-06-02 12:05
regarding seed generation on cpu - its not seed, its actual noise, seed is only used to initialize random number generator.
and i've stated before that i'm against "we need to have ability to reproduce 100% cross-platform". 

also, if original user did not use on-cpu rnd generator, it doesn't help if you want to do it as it has to be identical both during generation and during reproduction. and both original and reproduction still must have same cross-attention settings and cross-attention must run in predictive mode. and phase of the moon must be the same. 

so having on-cpu rng generator doesn't solve reproducibility - you'd need to actually *force* it on everyone AND disable good cross-attention options.

so what's the use case? i cannot see anything other than "its cool in theory"  
unless someone can point to a valid use-case, its pointless and costs significant performance.

@DirtyHamster 
regarding pnginfo chunks, i'm not sure what are you refering to? app already writes png chunks with metadata, its been doing that since forever and one of the first things i've re-implmented in here is how metadata is handled as i found original implementation to be quite broken.

**Closed by vladmandic** 2023-06-02 12:05 UTC
Labels: enhancement

**Comment by DirtyHamster** [comment] 2023-06-02 15:02
@vladmandic  Sorry if it came out vague it's been a long night. Unless the chunk types can be proposed for inclusion in that list by contacting the PNG specification maintainers a website developer might not find the custom application specific usage to use it unless looking here for it. If you look down through their site map https://png-mng.sourceforge.net/pub/png/png-sitemap.html there is a section on programs that details PNG-Supporting Applications the usage details you have implemented could potentially be listed there as a backlink to where you've documented it. Currently there is no section at all for AI Generative.

On top of that I was trying to say if those setting could be included in the metadata they could also be used by the sharing site to notify the page viewer of the repeatability issues and potential fixes to achieve the image.

**Comment by vladmandic** [comment] 2023-06-02 15:28
@krausekai 

> I was able to reproduce seeds across different PCs

yes, if they all use same option. but that means that option must be enforced for all to have any meaning and that kind of defeats the purpose.

> I did not notice a difference in performance

if you have a good CPU, you shouldn't - but I don't want to execute stuff on CPU unless absolutely necessary.

> At which points is it used? At initialization of a generation, or throughout the process?

throughout

**Comment by vladmandic** [comment] 2023-06-02 15:29
@DirtyHamster 

ahh, i understand now. yeah, would be nice to have a standard, but pushing a new standard is a non-trivial task and would require a buy-in from a lot of different players. not something i have in me to attempt right now.

**Comment by DirtyHamster** [comment] 2023-06-02 18:37
@vladmandic I don't think a singular person has to push for a standard. I think that kind of grows more organically out of people being able to self post what they have implemented so far in a manner that people with an interest in standardization can see/access it without doing a lot of extra leg work. Otherwise it falls on the back of larger industry presences that could easily ignore outside industry needs and uses.

In the manner I'm thinking anyone (not you in particular) could ask the curator of the list nicely to see if they will even give space in that list for AI apps to self assemble what each of them are individually doing with the metadata fields currently. Most of the stuff in the software lists have been frozen for a while now. Git does an excellent job at crosslinking so chances of an interested party seeing the idea is fair, so just putting out the idea there is good enough for me right now.

**Comment by vladmandic** [comment] 2023-06-02 22:19
i get it. and i may do it sometime in the future.
