### ISSUE TITLE
[Issue]: Newlines in prompt causing corrupted output

### ISSUE THREAD

**Issue by Shakahs** [vladmandic/automatic#3012] opened 2024-03-27 21:20 UTC
### Issue Description

Newlines in the prompt are causing corrupt output depending where they are placed. 
This is happening with SD1.5, all models, diffusers backend, on multiple machines with different Nvidia GPUs. 

Working prompt: 
```
a dingo,
in the savannah,
next to a lake
```

![00144-cyberrealistic_v40-a dingo in the savannah next to a](https://github.com/vladmandic/automatic/assets/390302/b1f3de76-21d0-4c34-823e-3539a2f40a30)

Broken prompt:
```
a dingo,

in the savannah,

next to a lake
```
![00147-cyberrealistic_v40-a dingo in the savannah next to a](https://github.com/vladmandic/automatic/assets/390302/84b0e111-5c33-43d7-a42e-68644c8ea190)

### Version Platform Description

Ubuntu 22, Firefox, SDNext @ master (82973c49ca491b1d50418b00e37131d308fad6b6).  
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |. 
RTX 4090
```
user@be4dbe76-56bc-44d1-b2b2-bbc741a59ea7:~/automatic$ ./webui.sh  --safe --debug
Create and activate python venv
Launching launch.py...: connect failed: Connection refused
21:13:14-036259 INFO     Starting SD.Next
21:13:14-042886 INFO     Logger: file="/home/user/automatic/sdnext.log" level=DEBUG size=64 mode=create
21:13:14-044935 INFO     Python 3.10.12 on Linux
21:13:14-059710 INFO     Version: app=sd.next updated=2024-03-21 hash=82973c49 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master
21:13:14-606236 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=5.15.0-88-generic
                         python=3.10.12
21:13:14-610362 DEBUG    Setting environment tuning
21:13:14-612905 DEBUG    HF cache folder: /home/user/.cache/huggingface/hub
21:13:14-615443 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
21:13:14-618516 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
21:13:14-621578 INFO     nVidia CUDA toolkit detected: nvidia-smi present
21:13:14-624700 DEBUG    Installing torch: torch torchvision --index-url
                         https://download.pytorch.org/whl/cu121
```

### Relevant log output

```shell
21:17:08-712517 DEBUG    Setting model: pipeline=StableDiffusionPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.float16, 'load_connected_pipeline': True, 'extract_ema': True,
                         'original_config_file': 'configs/v1-inference.yaml', 'use_safetensors': True}
21:17:08-714615 DEBUG    Setting model: enable VAE slicing
21:17:09-131095 INFO     Load embeddings: loaded=8 skipped=0 time=0.06
21:17:09-375261 DEBUG    GC: collected=223 device=cuda {'ram': {'used': 4.45, 'total': 25.43}, 'gpu':
                         {'used': 2.65, 'total': 23.65}, 'retries': 0, 'oom': 0} time=0.24
21:17:09-381868 INFO     Load model: time=0.98 load=0.98 native=512 {'ram': {'used': 4.45, 'total': 25.43},
                         'gpu': {'used': 2.65, 'total': 23.65}, 'retries': 0, 'oom': 0}
21:17:09-399494 INFO     Base: class=StableDiffusionPipeline
21:17:09-496642 DEBUG    Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE
                         set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds':
                         torch.Size([1, 77, 768]), 'guidance_scale': 6, 'generator': device(type='cuda'),
                         'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0.7, 'output_type':
                         'latent', 'width': 512, 'height': 512, 'parser': 'Full parser'}
Progress 29.45it/s █████████████████████████████████ 100% 20/20 00:00 00:00 Base
21:17:10-238206 INFO     Saving: image="outputs/text/00155-epicrealism_naturalSinRC1VAE-a dingo in the
                         savannah next to a.jpg" type=JPEG resolution=512x512 size=0
21:17:10-249046 INFO     Processed: images=1 time=0.86 its=23.14 memory={'ram': {'used': 4.45, 'total':
                         25.43}, 'gpu': {'used': 3.4, 'total': 23.65}, 'retries': 0, 'oom': 0}
21:17:59-622092 DEBUG    Server: alive=True jobs=1 requests=6 uptime=277 memory=4.45/25.43
                         backend=Backend.DIFFUSERS state=idle
```
```


### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment] 2024-03-28 13:23
i cannot reproduce this, prompt parser is correctly removing extra empty lines.
pls set env variable `SD_PROMPT_DEBUG=true`, re-run and upload entire log. it will show exact parsed output, for example:
> 09:21:58-256753 TRACE    Prompt: parser=Full parser [['a dingo,', 1.0], ['BREAK', -1], ['in the savannah,', 1.0], ['BREAK', -1], ['next to a lake', 1.0], ['BREAK', -1]]

**Comment by vladmandic** [comment] 2024-04-02 13:43
what is the status of this issue?

**Comment by vladmandic** [comment] 2024-04-09 18:32
closing for now as there are no updated, can be reopened once additional information is provided.

**Closed by vladmandic** 2024-04-09 18:32 UTC
Labels: question, cannot reproduce
