### ISSUE TITLE
[Issue]: Adding Trigger words will remove text from <lora> if the same.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#2414] opened 2023-10-27 02:30 UTC
### Feature description

When adding a lora through the Networks pane, hovering over a lora reveals its trigger words.
If you click the lora and then click the trigger, it will remove the trigger work from the <lora> if they are the same.

For example, `<lora:After_Shower1.1:0.7>` with a trigger of  `After_Shower` becomes  `<lora:1.1:0.7>`

### Version Platform Description

Logger: file=E:\SM\Data\Packages\SD.Next Web UI\sdnext.log level=10 size=0 mode=create                                        
Starting SD.Next                                                                                                              
Python 3.10.11 on Windows                                                                                                     
Version: app=sd.next updated=2023-10-22 hash=3fec4d49 url=https://github.com/vladmandic/automatic/tree/master                 
Latest published version: d91338b3c75860728d9dcecd018167f1f868d7e4 2023-10-26T16:01:55Z                                       
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 11, GenuineIntel system=Windows release=Windows-10-10.0.19045-SP0
python=3.10.11                                                                                                                

*EDIT: Accidentally labelled this a [Feature] instead of [Issue]*

**Comment by vladmandic** [comment] 2023-10-29 12:39
fixed in dev, will be merged to master next week.

**Closed by vladmandic** 2023-10-29 12:39 UTC
Labels: enhancement

**Comment by brknsoul** [comment] 2024-01-12 06:13
This is happening again, if the lora name has a space in it.
![image](https://github.com/vladmandic/automatic/assets/1969381/7c01610a-1730-4b13-892b-ab57f6117598)

**Comment by vladmandic** [comment] 2024-01-12 18:09
i tried, i cannot reproduce this is in dev branch.
can you send me a link actual lora where you see this problem?

**Comment by brknsoul** [comment] 2024-01-12 19:01
Just rename a lora so that it has a space in it, and a trigger word after the space;
`<lora:AnyLora- trigger word:1>`
becomes
`<lora:AnyLora-:1>`
when you click the trigger word from the Network panel.

This happens in master. So if it was 'accidentally' fixed in dev, yay. ;)

**Comment by vladmandic** [comment] 2024-01-12 19:14
i did that and i couldn't reproduce.

**Comment by brknsoul** [comment] 2024-01-13 00:37
Ok, i'll clone a dev and see if it got fixed.

**Comment by vladmandic** [comment] 2024-01-13 02:26
Like I said l, I tried to reproduce manually and couldn't, so really need a link to lora where this is reproducible.

**Comment by brknsoul** [comment] 2024-01-13 02:56
https://civitai.com/models/96401/karen-gillan

this one, renamed to `locon_karengillan_v1_from_v1_64_32- sks woman.safetensors`

**Comment by Woisek** [comment] 2024-01-13 10:26
The question is: Why rename the LoRA in such a strange way? Also, it is always advisable to use underscores instead of spaces, so ... 🤷‍♂️

**Comment by brknsoul** [comment] 2024-01-13 11:06
> use underscores instead of spaces

Perhaps in ancient times. Spaces have been allowed in filenames for a very long time now.

**Comment by vladmandic** [comment] 2024-01-13 13:45
reproduced and fixed

**Comment by Woisek** [comment] 2024-01-13 18:57
> > use underscores instead of spaces
> 
> Perhaps in ancient times. Spaces have been allowed in filenames for a very long time now.

That isn't a question of "is allowed", but rather of compatibility. Spaces produce very often headaches, and have to be "fixed" cumbersome. Underscores are just a safe way for filenames, no matter the OS.

**Comment by brknsoul** [comment] 2024-01-13 19:02
> compatibility

Perhaps, but it's not really expected that a coder should require their users not to use spaces in filenames in 2024.
I use spaces in my loras because it makes it easier to be able to double click the text to select the relevant trigger word.

**Comment by Woisek** [comment] 2024-01-13 19:06
You would not need to do so, if you would know, that the trigger word(s) are added automatically if you have filled out the appropriate field under the configuration of the LoRA ...

**Comment by brknsoul** [comment] 2024-01-13 19:07
> appropriate field under the configuration of the LoRA

That's the issue. Some lora trainers don't do this, so I have to rename said lora.

**Comment by Woisek** [comment] 2024-01-13 21:07
> > appropriate field under the configuration of the LoRA
> 
> That's the issue. Some lora trainers don't do this, so I have to rename said lora.

You mean, you can't add the trigger word(s) by yourself into that mentioned field and save that ... ? 🤔

**Comment by brknsoul** [comment] 2024-01-13 21:12
This is getting off topic. I'll using my naming convention, and you use yours.

**Comment by Woisek** [comment] 2024-01-13 21:24
No, no ... this is quite on topic. For people like you, struggling with trigger words, there is an important feature, and you tell me you don't use it? 🤔
![Zwischenablagebild](https://github.com/vladmandic/automatic/assets/122026301/ac277716-7662-46ac-ba7c-ba81bf3aa55e)

**Comment by brknsoul** [comment] 2024-01-13 21:28
That's a nifty feature, but it's not on master yet, soooo.. I didn't know about it, ROFL

**Comment by Woisek** [comment] 2024-01-14 00:27
It isn't there? Okay, I switch so often between A1111 and SD:Next, that I often forget, where I am. 😅 My bad.
But anyway, at least in SD:Next you have a description box where you could add the trigger words. You still have to copy it, but it's still accessible all the time.
