### ISSUE TITLE
[Feature Request]: Is it any way to use default Gradio style for UI elements?

### ISSUE THREAD

**Issue by ke1ne** [vladmandic/automatic#142] opened 2023-04-14 23:50 UTC
### Feature description

One of latest builds accidentally(?) loaded default(?) sliders, buttons, inputs, etc. Is it any way to make this optional?
And the same question for the light theme.
Thank you!

### Version Platform Description

Version: b28b7c7a Fri Apr 14 17:50:19

**Comment by ke1ne** [comment] 2023-04-14 23:54
Maybe, I was too quick, sorry. It's all in `user.css`, right?

**Comment by vladmandic** [comment] 2023-04-15 00:22
duplicate of #84

**Closed by vladmandic** 2023-04-15 00:22 UTC
Labels: enhancement
