### ISSUE TITLE
[Issue]: "AssertionError: Torch not compiled with XPU enabled" on Intel Arc A770

### ISSUE THREAD

**Issue by AndrewRainfall** [vladmandic/automatic#3547] opened 2024-11-01 17:22 UTC
### Issue Description

SD Next don't launch with "AssertionError: Torch not compiled with XPU enabled" on Intel Arc A770. 

I tried --reinstall and --upgrade SD Next, tried to upgrade torch, nothing helped. Not sure what to do.

### Version Platform Description

Using VENV: C:\automatic\venv
20:17:28-622778 INFO     Starting SD.Next
20:17:28-628779 INFO     Logger: file="C:\automatic\sdnext.log" level=DEBUG size=65 mode=create
20:17:28-631780 INFO     Python: version=3.10.11 platform=Windows bin="C:\automatic\venv\Scripts\python.exe"
                         venv="C:\automatic\venv"
20:17:29-013782 INFO     Version: app=sd.next updated=2024-11-01 hash=b48222cd branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
20:17:40-689699 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.11
20:17:40-693700 INFO     Args: ['--use-ipex', '--upgrade', '--debug', '--autolaunch']
20:17:40-695700 DEBUG    Setting environment tuning
20:17:40-698702 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
20:17:40-711704 DEBUG    Torch overrides: cuda=False rocm=False ipex=True directml=False openvino=False zluda=False
20:17:40-714704 INFO     Python: version=3.10.11 platform=Windows bin="C:\automatic\venv\Scripts\python.exe"
                         venv="C:\automatic\venv"
20:17:40-722706 INFO     IPEX: Intel OneAPI toolkit detected
20:17:40-724707 DEBUG    Diffusers upgrade: package=diffusers 0.32.0.dev0 current=
                         target=0d1d267b12e47b40b0e8f265339c76e0f45f8c49
20:18:10-947976 INFO     Verifying requirements
20:18:10-954068 WARNING  Package: protobuf installed=3.20.3 required=4.25.3 version mismatch
20:18:10-956627 INFO     Install: package="protobuf==4.25.3" mode=pip
20:18:10-958678 DEBUG    Running: pip="install --upgrade protobuf==4.25.3"
20:18:18-808737 INFO     Verifying packages
20:18:18-810737 INFO     Startup: standard
20:18:18-812400 INFO     Verifying submodules
20:18:22-375352 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
20:18:34-443487 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
20:18:35-551810 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
20:18:36-662015 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
20:18:36-664016 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
20:18:37-678953 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
20:18:38-696654 DEBUG    Git submodule: modules/k-diffusion / master
20:18:39-766091 DEBUG    Git submodule: wiki / master
20:18:40-768553 DEBUG    Register paths
20:18:40-940488 DEBUG    Installed packages: 268
20:18:40-943436 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sdnext-modernui',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']
20:18:41-952812 DEBUG    Git submodule: extensions-builtin\sd-extension-chainner / main
20:18:43-142355 DEBUG    Git submodule: extensions-builtin\sd-extension-system-info / main
20:18:48-555617 DEBUG    Git submodule: extensions-builtin\sd-webui-agent-scheduler / main
20:18:49-489950 DEBUG    Extension installer: C:\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
20:18:53-401014 DEBUG    Git detached head detected: folder="extensions-builtin\sd-webui-controlnet" reattach=main
20:18:53-405014 DEBUG    Git submodule: extensions-builtin\sd-webui-controlnet / main
20:18:54-970883 DEBUG    Extension force: name="sd-webui-controlnet" commit=ecd33eb
20:18:54-973884 DEBUG    Extension installer: C:\automatic\extensions-builtin\sd-webui-controlnet\install.py
![unnamed](https://github.com/user-attachments/assets/0ac94b0e-6a87-4180-97df-b71cbecbe39c)

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by CraterCrater** [comment] 2024-11-01 19:19
I have been getting an error I suspect is being caused by the same thing as yours:
[sdnext.log](https://github.com/user-attachments/files/17603382/sdnext.log)
![image](https://github.com/user-attachments/assets/c445dca9-287d-4807-a80a-aa29d453a645)

Mine says: Error loading .......c10_xpu.dll 

I'm using an arc a770 as well

**Comment by vladmandic** [comment] 2024-11-01 19:42
@CraterCrater why would you guess that? you log and error message doesn't look anything like the original issue. please create a separate issue and document it fully.

**Comment by AndrewRainfall** [comment] 2024-11-02 06:52
I tried to manually install fresh SD Next on another drive and got this
![1](https://github.com/user-attachments/assets/0cd6aaa5-834b-4d2e-ab73-ba25cfde3502)

**Comment by Disty0** [comment] 2024-11-02 14:10
You have CPU version of PyTorch. Not using --use-ipex at the first install will cause this. Make a new clean install.

Second issue is a duplicate of this: https://github.com/vladmandic/automatic/issues/3548

**Closed** 2024-11-02 14:42 UTC
