### ISSUE TITLE
[Issue]: listen mode error

### ISSUE THREAD

**Issue by OtokoNoIzumi** [vladmandic/automatic#825] opened 2023-05-09 10:09 UTC
### Issue Description

I opened the listening mode to share SD in my workspace network. 

![image](https://user-images.githubusercontent.com/29002083/237063469-7d2e84fa-00df-463f-abad-5eeab0bbe702.png)

It used to work fine but recently I got an error like the following:
![image](https://github.com/vladmandic/automatic/assets/29002083/934437df-47f4-4e57-ae18-f3eb0a869084)

Launch info:
![image](https://github.com/vladmandic/automatic/assets/29002083/73f82cd4-fd7c-4d53-97b6-634a4f434ad7)

### Version Platform Description

Version: b401d9ed Wed May 3 08:40:50 2023 -0400
```
2023-05-09 18:03:25,797 | INFO | E:\SD_Vlad_automatic\installer.py | Python 3.10.11 on Windows
2023-05-09 18:03:25,850 | DEBUG | E:\SD_Vlad_automatic\installer.py | Git 2.40.0.windows.1
2023-05-09 18:03:26,204 | INFO | E:\SD_Vlad_automatic\installer.py | Version: b401d9ed Wed May 3 08:40:50 2023 -0400
2023-05-09 18:03:27,457 | INFO | E:\SD_Vlad_automatic\installer.py | Latest published version: 4d9fab49848700de2814939228c842b2e0add24d 2023-05-08T15:56:59Z
2023-05-09 18:03:27,459 | INFO | E:\SD_Vlad_automatic\installer.py | Setting environment tuning
2023-05-09 18:03:27,461 | INFO | E:\SD_Vlad_automatic\installer.py | nVidia CUDA toolkit detected
2023-05-09 18:03:27,657 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: torch 2.0.0+cu118
2023-05-09 18:03:27,657 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: torchvision 0.15.1+cu118
2023-05-09 18:03:27,657 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: torchaudio 2.0.1+cu118
2023-05-09 18:03:29,005 | INFO | E:\SD_Vlad_automatic\installer.py | Torch 2.0.0+cu118
2023-05-09 18:03:29,028 | INFO | E:\SD_Vlad_automatic\installer.py | Torch backend: nVidia CUDA 11.8 cuDNN 8700
2023-05-09 18:03:29,032 | INFO | E:\SD_Vlad_automatic\installer.py | Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68
2023-05-09 18:03:29,034 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: tensorflow 2.12.0
2023-05-09 18:03:29,034 | INFO | E:\SD_Vlad_automatic\installer.py | Verifying requirements
2023-05-09 18:03:29,035 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: addict 2.4.0
2023-05-09 18:03:29,035 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: aenum 3.1.12
2023-05-09 18:03:29,036 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: aiohttp 3.8.4
2023-05-09 18:03:29,036 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: anyio 3.6.2
2023-05-09 18:03:29,036 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: appdirs 1.4.4
2023-05-09 18:03:29,036 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: astunparse 1.6.3
2023-05-09 18:03:29,036 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: basicsr 1.4.2
2023-05-09 18:03:29,037 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: bitsandbytes 0.38.1
2023-05-09 18:03:29,037 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: blendmodes 2022
2023-05-09 18:03:29,037 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: clean-fid 0.1.35
2023-05-09 18:03:29,037 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: easydev 0.12.1
2023-05-09 18:03:29,037 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: extcolors 1.0.0
2023-05-09 18:03:29,038 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: facexlib 0.3.0
2023-05-09 18:03:29,038 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: filetype 1.2.0
2023-05-09 18:03:29,038 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: font-roboto 0.0.1
2023-05-09 18:03:29,039 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: fonts 0.0.3
2023-05-09 18:03:29,039 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: future 0.18.3
2023-05-09 18:03:29,039 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: gdown 4.7.1
2023-05-09 18:03:29,039 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: gfpgan 1.3.8
2023-05-09 18:03:29,039 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: GitPython 3.1.31
2023-05-09 18:03:29,039 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: httpcore 0.17.0
2023-05-09 18:03:29,040 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: inflection 0.5.1
2023-05-09 18:03:29,040 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: jsonmerge 1.9.0
2023-05-09 18:03:29,040 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: kornia 0.6.12
2023-05-09 18:03:29,040 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: lark 1.1.5
2023-05-09 18:03:29,040 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: lmdb 1.4.1
2023-05-09 18:03:29,040 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: lpips 0.1.4
2023-05-09 18:03:29,041 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: numpy 1.23.5
2023-05-09 18:03:29,041 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: omegaconf 2.3.0
2023-05-09 18:03:29,041 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: open-clip-torch 2.18.0
2023-05-09 18:03:29,041 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: opencv-contrib-python 4.7.0.72
2023-05-09 18:03:29,041 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: piexif 1.1.3
2023-05-09 18:03:29,041 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: Pillow 9.5.0
2023-05-09 18:03:29,042 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: psutil 5.9.5
2023-05-09 18:03:29,042 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: pyyaml 6.0
2023-05-09 18:03:29,042 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: realesrgan 0.3.0
2023-05-09 18:03:29,042 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: requests 2.29.0
2023-05-09 18:03:29,042 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: resize-right 0.0.2
2023-05-09 18:03:29,042 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: rich 13.3.5
2023-05-09 18:03:29,043 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: safetensors 0.3.1
2023-05-09 18:03:29,043 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: scipy 1.10.1
2023-05-09 18:03:29,043 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: tb_nightly 2.13.0a20230429
2023-05-09 18:03:29,043 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: toml 0.10.2
2023-05-09 18:03:29,043 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: torch 2.0.0+cu118
2023-05-09 18:03:29,044 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: torchdiffeq 0.2.3
2023-05-09 18:03:29,044 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: torchsde 0.2.5
2023-05-09 18:03:29,044 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: torchvision 0.15.1+cu118
2023-05-09 18:03:29,044 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: voluptuous 0.13.1
2023-05-09 18:03:29,044 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: yapf 0.33.0
2023-05-09 18:03:29,044 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: scikit-image 0.20.0
2023-05-09 18:03:29,045 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: tqdm 4.65.0
2023-05-09 18:03:29,045 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: accelerate 0.18.0
2023-05-09 18:03:29,045 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: opencv-python 4.7.0.72
2023-05-09 18:03:29,045 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: diffusers 0.16.1
2023-05-09 18:03:29,045 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: einops 0.4.1
2023-05-09 18:03:29,045 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: gradio 3.28.1
2023-05-09 18:03:29,046 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: numexpr 2.8.4
2023-05-09 18:03:29,046 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: pandas 1.5.3
2023-05-09 18:03:29,046 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: protobuf 3.20.3
2023-05-09 18:03:29,046 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: pytorch_lightning 1.9.4
2023-05-09 18:03:29,046 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: transformers 4.26.1
2023-05-09 18:03:29,046 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: timm 0.6.13
2023-05-09 18:03:29,047 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: tomesd 0.1.2
2023-05-09 18:03:29,047 | DEBUG | E:\SD_Vlad_automatic\installer.py | Package version found: urllib3 1.26.15
2023-05-09 18:03:29,087 | DEBUG | E:\SD_Vlad_automatic\installer.py | Repository update time: Wed May  3 20:40:50 2023
2023-05-09 18:03:29,087 | DEBUG | E:\SD_Vlad_automatic\installer.py | Previous setup time: Mon May  8 19:34:08 2023
2023-05-09 18:03:29,088 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Mon May  8 19:32:56 2023 E:\SD_Vlad_automatic\extensions-builtin;a1111-sd-webui-lycoris
2023-05-09 18:03:29,088 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;clip-interrogator-ext
2023-05-09 18:03:29,088 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;LDSR
2023-05-09 18:03:29,088 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Wed May  3 21:16:05 2023 E:\SD_Vlad_automatic\extensions-builtin;Lora
2023-05-09 18:03:29,089 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Mon May  8 19:32:59 2023 E:\SD_Vlad_automatic\extensions-builtin;multidiffusion-upscaler-for-automatic1111
2023-05-09 18:03:29,089 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:10:49 2023 E:\SD_Vlad_automatic\extensions-builtin;prompt-bracket-checker
2023-05-09 18:03:29,089 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;ScuNET
2023-05-09 18:03:29,090 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;sd-dynamic-thresholding
2023-05-09 18:03:29,090 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;sd-extension-aesthetic-scorer
2023-05-09 18:03:29,090 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;sd-extension-steps-animation
2023-05-09 18:03:29,090 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sun Apr 30 20:17:56 2023 E:\SD_Vlad_automatic\extensions-builtin;sd-extension-system-info
2023-05-09 18:03:29,091 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Mon May  8 19:33:10 2023 E:\SD_Vlad_automatic\extensions-builtin;sd-webui-controlnet
2023-05-09 18:03:29,091 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;sd-webui-model-converter
2023-05-09 18:03:29,091 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;seed_travel
2023-05-09 18:03:29,092 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Mon May  8 19:33:18 2023 E:\SD_Vlad_automatic\extensions-builtin;stable-diffusion-webui-images-browser
2023-05-09 18:03:29,092 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;stable-diffusion-webui-rembg
2023-05-09 18:03:29,092 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Sat Apr 29 23:32:45 2023 E:\SD_Vlad_automatic\extensions-builtin;SwinIR
2023-05-09 18:03:29,093 | DEBUG | E:\SD_Vlad_automatic\installer.py | Extension version: Mon May  8 19:34:04 2023 E:\SD_Vlad_automatic\extensions;Auto-Photoshop-StableDiffusion-Plugin
2023-05-09 18:03:29,093 | DEBUG | E:\SD_Vlad_automatic\installer.py | Latest extensions time: Mon May  8 19:34:05 2023
2023-05-09 18:03:29,093 | DEBUG | E:\SD_Vlad_automatic\installer.py | Timestamps: version:1683117650 setup:1683545648 extension:1683545645
2023-05-09 18:03:29,094 | INFO | E:\SD_Vlad_automatic\installer.py | No changes detected: Quick launch active
2023-05-09 18:03:29,096 | INFO | E:\SD_Vlad_automatic\installer.py | Running extension preloading
2023-05-09 18:03:29,097 | INFO | E:\SD_Vlad_automatic\launch.py | Server arguments: ['--listen']
2023-05-09 18:03:29,098 | DEBUG | E:\SD_Vlad_automatic\launch.py | Starting WebUI
2023-05-09 18:03:34,058 | INFO | E:\SD_Vlad_automatic\modules\import_hook.py | Unloading xFormers
2023-05-09 18:03:34,875 | INFO | E:\SD_Vlad_automatic\webui.py | Libraries loaded
2023-05-09 18:03:34,904 | INFO | E:\SD_Vlad_automatic\modules\sd_models.py | Available models: E:\SD_Vlad_automatic\models\Stable-diffusion 12
2023-05-09 18:03:42,305 | INFO | E:\SD_Vlad_automatic\modules\shared.py | Loading theme: black-orange
2023-05-09 18:03:49,182 | INFO | E:\SD_Vlad_automatic\modules\middleware.py | Initializing middleware
2023-05-09 18:03:53,475 | INFO | E:\SD_Vlad_automatic\modules\sd_models.py | Creating model from config: E:\SD_Vlad_automatic\configs\v1-inference.yaml
2023-05-09 18:03:57,007 | INFO | E:\SD_Vlad_automatic\modules\sd_hijack.py | Applying scaled dot product cross attention optimization
2023-05-09 18:03:57,047 | INFO | E:\SD_Vlad_automatic\modules\textual_inversion\textual_inversion.py | Embeddings loaded: 0 []
2023-05-09 18:03:57,052 | INFO | E:\SD_Vlad_automatic\modules\sd_models.py | Model loaded in 7.8s (load=4.2s create=0.4s apply=0.5s vae=1.7s move=1.0s)
2023-05-09 18:03:57,283 | INFO | E:\SD_Vlad_automatic\webui.py | Startup time: 28.2s (torch=3.5s gradio=1.5s libraries=0.8s codeformer=0.1s scripts=2.4s opts onchange=4.8s ui=2.5s start=4.4s checkpoint=8.1s)
```

**Comment by vladmandic** [comment] 2023-05-09 11:42
so the only error is actually in the ui saying there is a syntax error? that almost looks like bad stuff lingering in browser cache and not related to server listening on public ip at all. which browser is that? can you clear cache and try again with new browser session?

i've tried to reproduce and it works fine here.

**Comment by froger-me** [comment] 2023-05-09 11:42
Did you try setting CORS Origins?
`set COMMANDLINE_ARGS=--cors-origins=http://127.0.0.1:7860 --listen`

Works 4 me at the moment.

**Comment by OtokoNoIzumi** [comment] 2023-05-10 07:10
> 

Can't generate pics when error accured. Relaunch without --listen will work fine.

**Comment by vladmandic** [comment] 2023-05-10 16:51
> Can't generate pics when error accured

which error?
i can run with `--listen` without issues with latest version.

**Comment by OtokoNoIzumi** [comment] 2023-05-15 05:15
> > Can't generate pics when error accured
> 
> which error? i can run with `--listen` without issues with latest version.
![image](https://github.com/vladmandic/automatic/assets/29002083/e99b04e2-80ab-4ff6-9359-42d233f9231f)
![image](https://github.com/vladmandic/automatic/assets/29002083/0cc2b171-8170-4709-b185-f3c45bf230fa)
![image](https://github.com/vladmandic/automatic/assets/29002083/c085504c-32f0-43f8-83b6-e077268333eb)


still error, maybe it's because I‘ve installed PS plusin?

**Comment by vladmandic** [comment] 2023-05-15 11:46
- i cannot reproduce - it works fine.
- those lines in console are not error messages, they are reported by extension, nothing more nothing less.
- i don't know which version you're running, but simply looking at console messages, its older. update the app and retry.

**Comment by iDeNoh** [comment] 2023-05-16 23:44
Strangely enough, I just had this issue using the Torch 2.1.0 + ROCm 5.4.2 nightly from earlier this month, I restarted the server and it started boot looping when it hit "Initializing Middleware" with no error messages and it worked fine if I removed the --listen (same issue using --share). after that I forced a reinstall that didn't fix it, so I tried wiping my torch install and installed the most recent 2.0.1 version it works fine, upgrading back to any version using 2.1.0 it breaks again.

**Comment by vladmandic** [comment] 2023-05-21 13:56
closing the issue as no updates from original author. will reopen if issue persists and new information is provided.

**Comment by OtokoNoIzumi** [comment] 2023-06-18 11:53
can you tell me how can I debug this on my own? with method should I check? I can't find the following error info in the code "Something went wrong Expecting value: line 1 column 1 (char 0)"

**Comment by vladmandic** [comment] 2023-06-18 12:41
i've closed the issue since i haven't heard from you in a month.
if the issue is still happening with the lastest version, open browser inspector and check for any messages in browser console.

**Comment by OtokoNoIzumi** [comment] 2023-06-19 08:06
thx...I can't find any debug info for me to apply any modify locally...
![image](https://github.com/vladmandic/automatic/assets/29002083/3957e52f-e61e-4ae5-8949-e44e790dc948)

**Comment by vladmandic** [comment] 2023-06-28 15:28
@OtokoNoIzumi i've made some changes how `--listen` works, can you try with latest version?
if it doesn't work, can you check browser inspector -> network tab and see if all js code is actually loading correctly?

**Comment by OtokoNoIzumi** [comment] 2023-07-09 12:12
> @OtokoNoIzumi i've made some changes how `--listen` works, can you try with latest version? if it doesn't work, can you check browser inspector -> network tab and see if all js code is actually loading correctly?

It doesn't work well. there is my first attemp for screenshot
![image](https://github.com/vladmandic/automatic/assets/29002083/d230421d-4565-4e1f-b379-b496f9bd01df)
---
version info
---
Using VENV: E:\SD_Vlad_automatic\venv
20:06:05-806020 INFO     Starting SD.Next
20:06:05-811453 INFO     Python 3.10.11 on Windows
20:06:05-950928 INFO     Version: 6b638933 Sun Jul 9 15:47:38 2023 +0900
20:06:07-006433 INFO     nVidia CUDA toolkit detected
20:06:09-099376 INFO     Torch 2.0.0+cu118
20:06:09-111377 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:06:09-113377 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68
20:06:09-228257 WARNING  Modified files: ['models/.placeholder', 'models/VAE-approx/model.pt',
                         'models/karlo/ViT-L-14_stats.th', 'repositories/.placeholder', 'models', 'outputs',
                         'repositories']
20:06:09-268257 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
20:06:09-281257 INFO     Enabled extensions: ['Auto-Photoshop-StableDiffusion-Plugin', 'sd-dynamic-prompts']
20:06:09-289262 INFO     Verifying requirements
20:06:09-297257 WARNING  Package wrong version: typing-extensions 4.6.3 required 4.7.1
20:06:09-298257 INFO     Installing package: typing-extensions==4.7.1
20:06:21-296350 WARNING  Package wrong version: pydantic 1.10.9 required 1.10.11
20:06:21-298348 INFO     Installing package: pydantic==1.10.11
20:06:40-465118 WARNING  Package wrong version: diffusers 0.17.1 required 0.18.1
20:06:40-467118 INFO     Installing package: diffusers==0.18.1
20:06:55-629076 WARNING  Package wrong version: transformers 4.26.1 required 4.30.2
20:06:55-630076 INFO     Installing package: transformers==4.30.2
20:07:08-116634 INFO     Verifying packages
20:07:08-119344 INFO     Installing package:
                         git+https://github.com/patrickvonplaten/invisible-watermark.git@remove_onnxruntime_depedency
20:07:17-796381 INFO     Verifying repositories
20:07:23-367213 INFO     Verifying submodules
20:07:47-886402 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'Auto-Photoshop-StableDiffusion-Plugin', 'sd-dynamic-prompts']
20:07:47-892402 INFO     Verifying packages
20:07:47-900410 INFO     Extension preload: 0.0s E:\SD_Vlad_automatic\extensions-builtin
20:07:47-902409 INFO     Extension preload: 0.0s E:\SD_Vlad_automatic\extensions
20:07:47-915409 INFO     Server arguments: ['--listen']
20:07:52-166251 INFO     Pipeline: Backend.ORIGINAL
No module 'xformers'. Proceeding without it.
20:07:53-486613 INFO     Libraries loaded
20:07:53-488613 INFO     Using data path: E:\SD_Vlad_automatic
20:07:53-494613 INFO     Available VAEs: E:\SD_Vlad_automatic\models\VAE 3
20:07:53-509613 INFO     Available models: E:\SD_Vlad_automatic\models\Stable-diffusion 13
20:07:55-777124 INFO     ControlNet v1.1.227
ControlNet v1.1.227
ControlNet preprocessor location: E:\SD_Vlad_automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
20:07:55-896124 INFO     ControlNet v1.1.227
ControlNet v1.1.227
python_server_full_path:  E:\SD_Vlad_automatic\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
20:08:01-617702 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://0.0.0.0:7860
20:08:09-819637 INFO     Local URL: http://localhost:7860/
20:08:09-820637 INFO     Initializing middleware
20:08:09-977945 INFO     [AgentScheduler] Task queue is empty
20:08:09-980944 INFO     [AgentScheduler] Registering APIs
Loading weights: E:\SD_Vlad_automatic\models\Stable-diffusion\(大模型)nightSkyYOZORAStyle日插_yozoraV1Origin.safetens…
20:08:11-220670 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: E:\SD_Vlad_automatic\models\VAE\(vae)YOZORA.vae.pt ------------------- -------- 283.0/404.7 MB 0:00:00
20:08:14-874473 INFO     Applying scaled dot product cross attention optimization
20:08:14-909475 INFO     Embeddings: loaded=0 skipped=0
20:08:14-915318 INFO     Model loaded in 4.3s (load=0.5s config=0.1s create=0.3s apply=2.2s vae=0.8s move=0.4s)
20:08:15-103318 INFO     Model load finished: {'ram': {'used': 6.56, 'total': 47.86}, 'gpu': {'used': 3.19, 'total':
                         10.0}, 'retries': 0, 'oom': 0} cached=0
20:08:15-506022 INFO     Startup time: 27.6s (torch=2.6s gradio=1.3s libraries=1.7s codeformer=0.1s scripts=3.2s
                         onchange=6.2s ui-txt2img=0.2s ui-img2img=0.1s ui-settings=0.2s ui-extensions=2.0s
                         ui-defaults=0.1s launch=4.3s app-started=0.4s checkpoint=5.3s)

**Comment by vladmandic** [comment] 2023-07-23 15:22
no attempt at reproduction has been successful so far. but looking at your browser inspector console log, it seems you're loading page wrapped in some other code as all load requests are coming from iframe?

lets seprate that - is there issue loading page directly? if not, then troubleshoot your wrapper separately.

**Comment by vladmandic** [comment] 2023-08-13 09:23
closing as no update for several weeks. can reopen if new information is provided.

**Closed by vladmandic** 2023-08-13 09:23 UTC
Labels: cannot reproduce
