### ISSUE TITLE
[Extension]: Weird Error with Wildcards | Dynamic Prompts

### ISSUE THREAD

**Issue by derspanier1** [vladmandic/automatic#1344] opened 2023-06-07 18:53 UTC
### Issue Description

Positive Prompt:

`[{2$$:$$(comics style:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0})|(analog style:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0})|(illustration:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0})|(lineart:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0})}:{0.3|0.4|0.5|0.6|0.7}], illustrated cowboy shot of (22 years old ([__mine/Sub_CelebF__|__mine/Sub_CelebF__])) with auburn colored hair and pale green eyes dancing, celebrating, (balloons and confetti), eyes closed, big grin, happy, wearing sundress, small breasts, cleavage, party, (heart shaped balloons) flying in the air, celebration, high energy, uhd, absurdres, dynamic lighting, dynamic pose, hand drawn style, bright colors, fun explosion background`

( the stuff at the start is me having issues to decide which keyword to use and with what strength so i let rando decide )
Edit: Disregard the useless () thats me organizing visually when editing the prompt.

Negative Prompt:

`__mine/Xtr_Neg__`

( pull 1 negative embedding from a wildcard)

Batch size 4. Renders without a hitch. But as soon as i add anything to the negative, be it a comma or a word or a BREAK, i get:

```
20:40:12-457473 ERROR    Exception: The expanded size of the tensor (77) must match the existing size (154) at
                         non-singleton dimension 0.  Target sizes: [77, 768].  Tensor sizes: [154, 768]
20:40:12-462357 ERROR    Arguments: args=('task(rh67ay8p1dxc72j)', '[{2$$:$$(comics
                         style:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0})|(analog
                         style:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0})|(illustration:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.
                         8|0.9|1.0})|(lineart:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0})}:{0.3|0.4|0.5|0.6|0.7}],
                         illustrated cowboy shot of (22 years old ([__mine/Sub_CelebF__|__mine/Sub_CelebF__])) with
                         auburn colored hair and pale green eyes dancing, celebrating, (balloons and confetti), eyes
                         closed, big grin, happy, wearing sundress, small breasts, cleavage, party, (heart shaped
                         balloons) flying in the air, celebration, high energy, uhd, absurdres, dynamic lighting,
                         dynamic pose, hand drawn style, bright colors, fun explosion background', '__mine/Xtr_Neg__,
                         BREAK', [], 20, 0, False, False, 1, 4, 6, 1, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7,
                         2, 'Latent', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4,
                         'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         1536, 96, True, True, True, False, False, 7, 100, 'Constant', 0, 'Constant', 0, 4,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001A9391CDDB0>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001A93A617220>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001A93A0C5660>,
                         False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '',
                         'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0,
                         'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4,
                         'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True,
                         'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False,
                         'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28,
                         'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model':
                         'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0,
                         'ad_controlnet_guidance_end': 1}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt':
                         '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0,
                         'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4,
                         'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True,
                         'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False,
                         'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28,
                         'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model':
                         'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0,
                         'ad_controlnet_guidance_end': 1}, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7,
                         False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '',
                         'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,
                         0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,
                         0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUT
                         S:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,
                         0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5\nTT:1,0.2,0.2,0.2,0.5,0.5,0.5,0.5,
                         1,1,1,1,0.5,0.5,0.5,0.5,0.5\nSET1:0.2,0.4,0.6,0.8,0.5,0.5,0.5,0.5,0.2,0.2,0.2,0.2,0.8,0.8,0.8,
                         0.8,0.8\nSET2:0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9\nSET3:0.1,0.
                         1,0.1,0.1,0.2,0.2,0.2,0.2,0.9,0.9,0.9,0.9,0.8,0.8,0.8,0.8,0.8\nSET4:0.1,0.1,0.1,0.1,0.2,0.2,0.
                         2,0.2,0.9,0.9,0.9,0.9,0.8,0.8,0.8,0.8,0.7', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block
                         ID', 'IN05-OUT05', 'none', '', '0.5,1',
                         'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,
                         OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False,
                         'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:
                         0\n\nXYZ:::1', False, False, 0.75, 1, False, False, 'positive', 'comma', 0, False, False, '',
                         6, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None,
                         None, False, None, None, False, 50, False, False, 'Euler a', 0.95, 0.75, '0.75:0.95:5',
                         '0.2:0.8:5', 'zero', 'pos', 'linear', 0.2, 0.0, 0.75, None, 'Lanczos', 1, 0, 0) kwargs={}
20:40:12-577594 ERROR    gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\SD_Next\modules\call_queue.py:34 in f                                                                            │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ E:\SD_Next\modules\txt2img.py:58 in txt2img                                                                         │
│                                                                                                                     │
│   57 │   if processed is None:                                                                                      │
│ > 58 │   │   processed = process_images(p)                                                                          │
│   59 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                              ... 10 frames hidden ...                                               │
│                                                                                                                     │
│ E:\SD_Next\modules\sd_samplers_kdiffusion.py:97 in forward                                                          │
│                                                                                                                     │
│    96 │   │   conds_list, tensor = prompt_parser.reconstruct_multicond_batch(cond, self.step)                       │
│ >  97 │   │   uncond = prompt_parser.reconstruct_cond_batch(uncond, self.step)                                      │
│    98                                                                                                               │
│                                                                                                                     │
│ E:\SD_Next\modules\prompt_parser.py:238 in reconstruct_cond_batch                                                   │
│                                                                                                                     │
│   237 │   │   │   │   break                                                                                         │
│ > 238 │   │   res[i] = cond_schedule[target_index].cond                                                             │
│   239 │   return res                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: The expanded size of the tensor (77) must match the existing size (154) at non-singleton dimension 0.
Target sizes: [77, 768].  Tensor sizes: [154, 768]
```

i strongly suspect its my weird way of using SD, but i wanted to make you aware.

### Version Platform Description

19:03:43-742068 INFO     Upgraded to version: 8e3a8fb4 Wed Jun 7 19:17:55 2023 +0300

**Comment by vladmandic** [comment] 2023-06-07 19:30
since dynamic prompt pretty much intercepted normal processing, i have no way of knowing what's going on here.
if you can reproduce a problem without dynamic prompts, i would take a look at it, otherwise report to that repo - and please mark the issue as extension and use extension template in the future.

**Comment by vladmandic** [comment] 2023-07-23 15:48
closing as no follow-ups. if there is an issue, provide upstream tracking.

**Closed by vladmandic** 2023-07-23 15:48 UTC
Labels: extension
