### ISSUE TITLE
[Issue]: Errors when using Tiled VAE combined with HiRes fix

### ISSUE THREAD

**Issue by rosenius** [vladmandic/automatic#625] opened 2023-04-29 19:43 UTC
### Issue Description

Everytime I use Tiled VAE and the total image-size it larger then the tile-size i get the  following error in the console.

`radio call: RuntimeError
╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮
│ D:\automatic\modules\call_queue.py:58 in f                                                                                        │
│                                                                                                                                   │
│    57 │   │   │   │   pr.enable()                                                                                                 │
│ ❱  58 │   │   │   res = list(func(*args, **kwargs))                                                                               │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                                     │
│                                                                                                                                   │
│ D:\automatic\modules\call_queue.py:38 in f                                                                                        │
│                                                                                                                                   │
│    37 │   │   │   try:                                                                                                            │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                                 │
│    39 │   │   │   finally:                                                                                                        │
│                                                                                                                                   │
│                                                     ... 13 frames hidden ...                                                      │
│                                                                                                                                   │
│ D:\automatic\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context                                            │
│                                                                                                                                   │
│   114 │   │   with ctx_factory():                                                                                                 │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                                                    │
│   116                                                                                                                             │
│                                                                                                                                   │
│ D:\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py:618 in vae_tile_forward         │
│                                                                                                                                   │
│   617 │   │   │   │   │   num_completed += 1                                                                                      │
│ ❱ 618 │   │   │   │   │   result[:, :, out_bboxes[i][2]:out_bboxes[i][3], out_bboxes[i][0]:out                                    │
│   619 │   │   │   │   │   del tile                                                                                                │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The expanded size of the tensor (3) must match the existing size (8) at non-singleton dimension 1.  Target sizes: [1,
3, 136, 100].  Tensor sizes: [8, 136, 100]

[Tiled VAE]: Executing Encoder Task Queue:  98%|███████████████████████████████████████████████▊ | 355/364 [00:13<00:00, 331.25it/s] `

### Version Platform Description

updated: 2023-04-29
hash: 69ee51f7
url: https://github.com/vladmandic/automatic/tree/master

**Comment by rosenius** [comment] 2023-04-29 19:47
I should add that it happens when using HiRes-fix. Using a big image-size "normally" seems to work

**Comment by vladmandic** [comment] 2023-04-29 19:51
So it only happens when combining tiled vae and hires? Yeah, they're not supposed to be combined.
Unless I'm misunderstanding something.

**Comment by rosenius** [comment] 2023-04-29 19:52
I've been able to do so until today so something have changed. Not saying your wrong about them not beeing supposed to be combined. Just noting that it have worked until today.

**Comment by Jooju** [comment] 2023-04-29 21:25
I'm seeing this error in img2img when tiled VAE and multidiffusion are combined with ControlNet. 

`                                                                                                                       gradio call: RuntimeErrorncoder Task Queue:   0%|                                   | 56/69888 [00:00<06:54, 168.32it/s]
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ G:\vlad1111\modules\call_queue.py:58 in f                                                                           │
│                                                                                                                     │
│    57 │   │   │   │   pr.enable()                                                                                   │
│ >  58 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ G:\vlad1111\modules\call_queue.py:38 in f                                                                           │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                              ... 16 frames hidden ...                                               │
│                                                                                                                     │
│ G:\vlad1111\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context                               │
│                                                                                                                     │
│   114 │   │   with ctx_factory():                                                                                   │
│ > 115 │   │   │   return func(*args, **kwargs)                                                                      │
│   116                                                                                                               │
│                                                                                                                     │
│ G:\vlad1111\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py:618 in             │
│ vae_tile_forward                                                                                                    │
│                                                                                                                     │
│   617 │   │   │   │   │   num_completed += 1                                                                        │
│ > 618 │   │   │   │   │   result[:, :, out_bboxes[i][2]:out_bboxes[i][3], out_bboxes[i][0]:out                      │
│   619 │   │   │   │   │   del tile                                                                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: The expanded size of the tensor (3) must match the existing size (8) at non-singleton dimension 1.
Target sizes: [1, 3, 68, 68].  Tensor sizes: [8, 68, 68]`

**Comment by vladmandic** [comment] 2023-04-29 21:38
not surprising, any two extensions that modify in-the-flight processing result are just luck if they work together.

**Comment by Jooju** [comment] 2023-04-29 21:58
It does it even with ControlNet disabled:

[Tiled VAE]: input_size: torch.Size([1, 3, 6048, 8064]), tile_size: 1536, padding: 32
[Tiled VAE]: split to 4x6 = 24 tiles. Optimal tile size 1344x1504, original tile size 1536x1536
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 1536 x 1152 image
                                                                                                                       gradio call: RuntimeErrorncoder Task Queue:   4%|█▎                                   | 79/2184 [00:02<01:03, 33.14it/s]
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ G:\vlad1111\modules\call_queue.py:58 in f                                                                           │
│                                                                                                                     │
│    57 │   │   │   │   pr.enable()                                                                                   │
│ >  58 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ G:\vlad1111\modules\call_queue.py:38 in f                                                                           │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                              ... 15 frames hidden ...                                               │
│                                                                                                                     │
│ G:\vlad1111\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context                               │
│                                                                                                                     │
│   114 │   │   with ctx_factory():                                                                                   │
│ > 115 │   │   │   return func(*args, **kwargs)                                                                      │
│   116                                                                                                               │
│                                                                                                                     │
│ G:\vlad1111\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py:618 in             │
│ vae_tile_forward                                                                                                    │
│                                                                                                                     │
│   617 │   │   │   │   │   num_completed += 1                                                                        │
│ > 618 │   │   │   │   │   result[:, :, out_bboxes[i][2]:out_bboxes[i][3], out_bboxes[i][0]:out                      │
│   619 │   │   │   │   │   del tile                                                                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: The expanded size of the tensor (3) must match the existing size (8) at non-singleton dimension 1.
Target sizes: [1, 3, 192, 172].  Tensor sizes: [8, 192, 172]

**Comment by cool-bigdogs-tshirt** [comment] 2023-04-30 02:23
looks like it's the extension itself: https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/155

**Comment by cool-bigdogs-tshirt** [comment] 2023-04-30 02:44
willing to bet it's here, but haven't been able to reproduce it myself yet: https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/7253cb449c85e2d2317ba541bf770ef372a807a4#diff-1bf94555243cd602434f1e3b668b005c00035f63fa015882daff02a6ce307c83R574

**Comment by LieDeath** [comment] 2023-04-30 07:40
caused by encoder in tiled VAE

**Comment by vladmandic** [comment] 2023-04-30 13:26
looping in @pkuliyi2015 and @LightChaser666 directly if they have any thoughts/guidance?

**Comment by pkuliyi2015** [comment] 2023-04-30 13:58
The problem is due to a latest upgrade by my partner. It should be fixed now, please check again.

**Comment by wzgrx** [comment] 2023-04-30 13:58
Update multifusion upscale for automation 1111, which has been fixed in the latest version

**Comment by vladmandic** [comment] 2023-04-30 14:56
perfect. its automatically updated when user upgrades the main repo.
so i'd suggest to run `webui --upgrade` once and confirm if this resolves the issue?

**Comment by rosenius** [comment] 2023-04-30 15:44
It works for me.

**Comment by vladmandic** [comment] 2023-04-30 16:05
great! closing the issue since you're the original author of it :)

**Closed by vladmandic** 2023-04-30 16:05 UTC
Labels: bug, upstream
