### ISSUE TITLE
[Feature]: Does not correctly detect the ROCM version during installation

### ISSUE THREAD

**Issue by tornado73** [vladmandic/automatic#2542] opened 2023-11-23 18:26 UTC
### Feature description

            # install torch nightly via torchvision to avoid wasting bandwidth when torchvision depends on torch from yesterday
            torch_command = os.environ.get('TORCH_COMMAND', f'torch torchvision --pre --index-url https://download.pytorch.org/whl/nightly/rocm{rocm_ver}')
        elif rocm_ver in {"5.5", "5.6"}:
            torch_command = os.environ.get('TORCH_COMMAND', f'torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm{rocm_ver}')
        else:
            # ROCm 5.5 is oldest for PyTorch 2.1
            **torch_command = os.environ.get('TORCH_COMMAND', 'torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm5.7')**

Installs version 5.5 and doesn't work 

replaced the link to the  nightly release  and everything was installed  and worked-)

### Version Platform Description

Ubuntu 22.04.3, with ROCM 5.7.1

**Comment by vladmandic** [comment] 2023-11-24 00:52
you replaced exactly what with what? from your comment, its really hard to tell.

**Comment by tornado73** [comment] 2023-11-24 06:11
was

   # install torch nightly via torchvision to avoid wasting bandwidth when torchvision depends on torch from yesterday
        torch_command = os.environ.get('TORCH_COMMAND', f'torch torchvision --pre --index-url https://download.pytorch.org/whl/nightly/rocm{rocm_ver}')
    elif rocm_ver in {"5.5", "5.6"}:
        torch_command = os.environ.get('TORCH_COMMAND', f'torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm{rocm_ver}')
    else:
        # ROCm 5.5 is oldest for PyTorch 2.1
      torch_command = os.environ.get('TORCH_COMMAND', 'torch torchvision --index-url https://download.pytorch.org/whl/rocm5.5')
________________________________________________________________________________________________
replacement

        # install torch nightly via torchvision to avoid wasting bandwidth when torchvision depends on torch from yesterday
        torch_command = os.environ.get('TORCH_COMMAND', f'torch torchvision --pre --index-url https://download.pytorch.org/whl/nightly/rocm{rocm_ver}')
    elif rocm_ver in {"5.5", "5.6"}:
        torch_command = os.environ.get('TORCH_COMMAND', f'torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm{rocm_ver}')
    else:
        # ROCm 5.5 is oldest for PyTorch 2.1
        torch_command = os.environ.get('TORCH_COMMAND', 'torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm5.7')

**Comment by vladmandic** [comment] 2023-11-24 13:36
if detected drivers are 5.7, it will install correct version.
if drivers are NOT detected, fallback is to 5.5 - and that is not going to change.
why are your drivers not recognized? what is the output of `hipconfig --version`?

**Comment by tornado73** [comment] 2023-11-24 15:58
ROCM version 5.7.1 is installed, 
![Screenshot from 2023-11-24 18-47-58](https://github.com/vladmandic/automatic/assets/58679489/1736ba0a-a6ba-45e4-9af0-5ab6ea85b747)

the installer installs Pytorch version 5.5

![Screenshot from 2023-11-24 18-29-31](https://github.com/vladmandic/automatic/assets/58679489/310beeb9-a8cc-4097-a323-de98410c1d03)

I got around this by explicitly specifying which version of pytorch to put by changing the line in installer.py.
For me this is not a problem, for others it may become

And thank you for your work!

**Comment by vladmandic** [comment] 2023-11-24 16:27
i asked what is the output of `hipconfig --version`? because that is what is used to detect rocm version.

**Comment by tornado73** [comment] 2023-11-24 18:21
rocm-hip-libraries is already the newest version (5.7.0.50700-63~22.04).

tor@tor:~$ hipconfig --version
hipconfig: command not found
tor@tor:~$

**Comment by vladmandic** [comment] 2023-11-24 18:47
Amd keeps changing package containing hipconfig and I cannot post full installation notes for hip itself, that is out of scope.

As it is, seems that product works as designed.

**Comment by tornado73** [comment] 2023-11-24 18:59
Yes, it works, but then you need to write the installation- sudo apt install rocm-hip-sdkb in the script, if it is possible
snx!

**Comment by vladmandic** [comment] 2023-11-24 19:32
No, sdnext is not responsible for installing required hip drivers or binaries.

**Closed** 2023-11-25 05:37 UTC
Labels: enhancement, question
