### ISSUE TITLE
[Issue]: Generations freeze at the last step, sometimes very slow

### ISSUE THREAD

**Issue by eadnams22** [vladmandic/automatic#839] opened 2023-05-09 18:34 UTC
### Issue Description

On first generation it's particularly slow, then intermittently after that, generations just seem to hang in the UI for minutes at the last after completing in the console (but preview says 99%), I thought it might be the aesthetic scorer, or face restore, but disabling those doesn't seem to change a lot, same with changing cross-attention modes.

Previews are already at approx NN, every 4 steps.

There is nothing in the console to indicate what it's doing, and I can't see any processes doing anything unusual, though python seems at higher utilization, the GPU(Cuda) is mostly idle, though VRAM stays utilized.

This happens when running locally, remotely, or from a mobile device.

args are: --listen --upgrade --disable-queue

disable-queue is so gradio/image gallery don't hang if i'm using my ipad.

### Version Platform Description

System data

Platform
arch: AMD64
cpu: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.19044-SP0
python: 3.10.7

Torch
2.0.0+cu118 Autocast  half

GPU
device: NVIDIA GeForce RTX 3090 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700

Memory optimization
none

Cross-attention
sdp

Libs
xformers: unavailable
accelerate: 0.18.0
transformers: 4.26.1

Repos:
Stable Diffusion: [cf1d67a] 2023-03-25
Taming Transformers: [9e9981c] 2022-11-07
CodeFormer: [c5b4593] 2022-09-09
BLIP: [48211a1] 2022-06-07
k_diffusion: [b43db16] 2023-02-06

Other options:

![Screenshot 2023-05-09 at 12 25 27 PM](https://github.com/vladmandic/automatic/assets/68871928/2704345e-d807-4d80-8bad-ce82938fa604)
![Screenshot 2023-05-09 at 12 25 07 PM](https://github.com/vladmandic/automatic/assets/68871928/f65d8e16-4a51-4fee-9aa0-5312a598e1ec)
![Screenshot 2023-05-09 at 12 27 03 PM](https://github.com/vladmandic/automatic/assets/68871928/447ee4ed-bfc0-4c45-a4d4-0b2847ee7ed0)

**Comment by vladmandic** [comment] 2023-05-09 20:07
RTX3090 should have no delays.
Can you run with `--debug` arg and capture the run?

**Comment by eadnams22** [comment] 2023-05-10 07:06
For sure, in the console it just stops here, and sometimes doesn’t finish at all, in the webui it says 99%, and the system info says one step is remaining still.

![IMG_0239](https://github.com/vladmandic/automatic/assets/68871928/a395d824-5d3e-4f0b-8943-49ab91427397)
![IMG_0238](https://github.com/vladmandic/automatic/assets/68871928/59a5ad17-7a36-40b5-b40a-e8060f0cb05b)

**Comment by MDMAchine** [comment] 2023-05-10 07:53
same thing happens to me. It happens eventually if I run batch size 2 or more or when I enable Tiled Diffusion in txt2img. 

When tiled diffusion halts it'll be at 99% and the the last step freezes. However the image outputs to its respective folder/
When its the batch size it'll hit 99% and just freeze (just like in @eadnams22 pic).

Sometimes it'll work but after a few runs it'll freeze and I have to restart.

```
System Data

Platform
arch: AMD64
cpu: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

Torch
2.0.0+cu118 Autocast  half

GPU
device: NVIDIA GeForce RTX 3060 Ti (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700

Memory optimization
none

Cross-attention
sdp

Libs
xformers: unavailable
accelerate: 0.18.0
transformers: 4.26.1

Repos:
Stable Diffusion: (unknown)
Taming Transformers: (unknown)
CodeFormer: (unknown)
BLIP: (unknown)
k_diffusion: (unknown)

```

**Comment by vladmandic** [comment] 2023-05-11 14:45
@eadnams22 according to your log, you have both face restore enabled and hrfix enabled. can you reproduce without those two options? and if it works, introduce one or other so we can isolate it, not both at the same time.

**Comment by eadnams22** [comment] 2023-05-11 14:54
I was able to replicate it without those as well. 

Though I seem to have fixed it by changing some settings, but I’m not sure which change did it. I renamed my old config, then restarted, and it worked fine with the same settings, so then moved chunks of the fresh config in to my old config, and seemed to have no issues outside of the initial loading of the clip model for the aesthetic ranking tool.

Still experimenting to see if it returns, but so far so good, it seems.

I’m trying to assess which setting caused it, for future prevention, as others could benefit from that.

**Comment by vladmandic** [comment] 2023-05-11 15:33
most likely its some script callback that executes upon completion, not actual saving images.
i'll keep the issue open for few more days if you can replicate the problem.

**Comment by eadnams22** [comment] 2023-05-11 19:11
Okay, I think I found the culprit:

The "Use channels last as torch memory format" switch, with my particular config at least:

<img width="501" alt="Screenshot 2023-05-11 at 1 07 58 PM" src="https://github.com/vladmandic/automatic/assets/68871928/78d88dbe-e98f-4d8f-ac32-479b75e80c1e">

<img width="501" alt="Screenshot 2023-05-11 at 1 10 36 PM" src="https://github.com/vladmandic/automatic/assets/68871928/66414322-9f45-46f1-bd8b-e1f69490882b">

Seems to make it stall on after generation, but before image saving.

**Comment by vladmandic** [comment] 2023-05-11 19:17
that is VERY interesting.
if that's the root cause, i'll close the issue.
but if you have anything to add, feel free to comment here (and i'll reopen if needed).

**Closed by vladmandic** 2023-05-11 19:17 UTC
Labels: question

**Comment by MDMAchine** [comment] 2023-05-11 19:56
I'll add my situation in the token merging section I had down sampling set to 2. Once I put that back to 1 everything seemed fine.
