### ISSUE TITLE
[Issue]: Unhnown crash when second pass is enabled with Force Hires checked

### ISSUE THREAD

**Issue by ACWeb23** [vladmandic/automatic#2749] opened 2024-01-25 06:08 UTC
### Issue Description

when attempting to run a second pass while generating an image SD.Next crashes when the Force Hires box is checked. I am using a fresh install with no added extensions.

### Version Platform Description

Starting SD.Next
Logger: file="E:\Artifical\automatic\sdnext.log" level=INFO size=16333 mode=append
Python 3.10.6 on Windows
Version: app=sd.next updated=2024-01-13 hash=5fb290f4
                      url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.6
Using CPU-only Torch
Extensions: disabled=[]
Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
Extensions: enabled=[] extensions
 Startup: quick launch
Verifying requirements
Verifying packages
Extensions: disabled=[]
 Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
Extensions: enabled=[] extensions
Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
Command line args: []
Load packages: torch=2.1.0a0+cxx11.abi diffusers=0.25.0 gradio=3.43.2
Engine: backend=Backend.ORIGINAL compute=ipex mode=no_grad device=xpu
                         cross-optimization="Sub-quadratic"
Device: device=Intel(R) Arc(TM) A580 Graphics n=1 ipex=2.1.10+xpu
Available VAEs: path="E:\Artifical\stable-diffusion-webui\models\VAE" items=14
Disabled extensions: []
Available models: path="E:\Artifical\stable-diffusion-webui\models\Stable-diffusion" items=37
                         time=0.04
Extension: script='scripts\faceid.py' [2;36m00:02:41-626974[0m[2;36m [0m[1;31mERROR   [0m
                         FaceID: No module named [32m'ip_adapter'[0m
Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
Extension: script='extensions-builtin\sd-webui-controlnet\scripts\api.py' ControlNet
                         preprocessor location:
                         E:\Artifical\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py' Warning:
                         ControlNet failed to load SGM - will use LDM instead.
Extension: script='extensions-builtin\sd-webui-controlnet\scripts\hook.py' Warning: ControlNet
                         failed to load SGM - will use LDM instead.
Extensions time: 2.20 { automatic=0.44 Lora=1.01 sd-extension-chainner=0.05
                         sd-webui-agent-scheduler=0.26 sd-webui-controlnet=0.23
                         stable-diffusion-webui-images-browser=0.19 }
Load UI theme: name="black-teal" style=Auto base=sdnext.css
Local URL: http://127.0.0.1:7860/
Initializing middleware
[AgentScheduler] Task queue is empty
[AgentScheduler] Registering APIs
Startup time: 13.15 { torch=3.93 gradio=0.87 libraries=3.18 extensions=2.20 face-restore=0.22
                         ui-extra-networks=0.70 ui-txt2img=0.05 ui-img2img=0.07 ui-settings=0.17 ui-extensions=0.97
                         ui-defaults=0.05 launch=0.27 api=0.06 app-started=0.17 }

OS: Windows 11
Browser: Edge 

### Relevant log output

```shell
23:50:50-205815 INFO     Starting SD.Next
23:50:50-209815 INFO     Logger: file="E:\Artifical\automatic\sdnext.log" level=DEBUG size=65 mode=create
23:50:50-210815 INFO     Python 3.10.6 on Windows
23:50:50-330937 INFO     Version: app=sd.next updated=2024-01-13 hash=5fb290f4
                         url=https://github.com/vladmandic/automatic/tree/master
23:50:50-607313 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.6
23:50:50-608903 DEBUG    Setting environment tuning
23:50:50-609904 DEBUG    Cache folder: C:\Users\andad\.cache\huggingface\hub
23:50:50-611178 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
23:50:50-612623 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
23:50:50-620622 INFO     Using CPU-only Torch
23:50:50-702667 DEBUG    Repository update time: Sat Jan 13 07:47:29 2024
23:50:50-703665 INFO     Startup: standard
23:50:50-704664 INFO     Verifying requirements
23:50:50-715667 INFO     Verifying packages
23:50:50-716666 INFO     Verifying submodules
23:50:53-151118 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
23:50:53-218283 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
23:50:53-282281 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
23:50:53-347282 DEBUG    Submodule: extensions-builtin/sd-webui-controlnet / main
23:50:53-442910 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-images-browser / main
23:50:53-505910 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
23:50:53-572461 DEBUG    Submodule: modules/k-diffusion / master
23:50:53-642462 DEBUG    Submodule: modules/lora / main
23:50:53-725123 DEBUG    Submodule: wiki / master
23:50:53-763123 DEBUG    Register paths
23:50:53-933123 DEBUG    Installed packages: 256
23:50:53-934122 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg']
23:50:54-277853 DEBUG    Running extension installer:
                         E:\Artifical\automatic\extensions-builtin\sd-extension-system-info\install.py
23:50:54-786246 DEBUG    Running extension installer:
                         E:\Artifical\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
23:50:55-288746 DEBUG    Running extension installer:
                         E:\Artifical\automatic\extensions-builtin\sd-webui-controlnet\install.py
23:50:55-796224 DEBUG    Running extension installer:
                         E:\Artifical\automatic\extensions-builtin\stable-diffusion-webui-images-browser\install.py
23:50:56-299478 DEBUG    Running extension installer:
                         E:\Artifical\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
23:50:56-813626 DEBUG    Extensions all: []
23:50:56-814626 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg']
23:50:56-815626 INFO     Verifying requirements
23:50:56-825626 DEBUG    Setup complete without errors: 1706161857
23:50:56-833626 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
23:50:56-834626 DEBUG    Starting module: <module 'webui' from 'E:\\Artifical\\automatic\\webui.py'>
23:50:56-836627 INFO     Command line args: ['--debug'] debug=True
23:50:56-837627 DEBUG    Env flags: []
23:50:59-686092 DEBUG    Load IPEX==2.1.10+xpu
23:51:01-711183 INFO     Load packages: torch=2.1.0a0+cxx11.abi diffusers=0.25.0 gradio=3.43.2
23:51:02-315084 DEBUG    Read: file="config.json" json=30 bytes=1433 time=0.001
23:51:02-317084 INFO     Engine: backend=Backend.ORIGINAL compute=ipex mode=no_grad device=xpu
                         cross-optimization="Sub-quadratic"
23:51:02-318084 INFO     Device: device=Intel(R) Arc(TM) A580 Graphics n=1 ipex=2.1.10+xpu
23:51:04-948493 DEBUG    Entering start sequence
23:51:04-951493 DEBUG    Initializing
23:51:04-956496 INFO     Available VAEs: path="E:\Artifical\stable-diffusion-webui\models\VAE" items=14
23:51:04-957495 INFO     Disabled extensions: []
23:51:04-960496 DEBUG    Read: file="cache.json" json=2 bytes=558 time=0.000
23:51:04-993492 DEBUG    Read: file="metadata.json" json=954 bytes=6507143 time=0.031
23:51:04-998487 INFO     Available models: path="E:\Artifical\stable-diffusion-webui\models\Stable-diffusion" items=37
                         time=0.04
23:51:05-218533 DEBUG    Load extensions
23:51:05-516146 INFO     Extension: script='scripts\faceid.py' [2;36m23:51:05-515147[0m[2;36m [0m[1;31mERROR   [0m
                         FaceID: No module named [32m'ip_adapter'[0m
23:51:07-030804 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
23:51:07-218899 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\api.py' ControlNet
                         preprocessor location:
                         E:\Artifical\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
23:51:07-349029 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py' Warning:
                         ControlNet failed to load SGM - will use LDM instead.
23:51:07-360026 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\hook.py' Warning: ControlNet
                         failed to load SGM - will use LDM instead.
23:51:07-565167 INFO     Extensions time: 2.35 { automatic=0.31 Lora=1.01 sd-extension-chainner=0.05
                         sd-webui-agent-scheduler=0.41 sd-webui-controlnet=0.34
                         stable-diffusion-webui-images-browser=0.19 }
23:51:07-604946 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2640 time=0.000
23:51:07-606944 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2693 time=0.000
23:51:07-608943 DEBUG    chaiNNer models: path="E:\Artifical\stable-diffusion-webui\models\chaiNNer" defined=24
                         discovered=0 downloaded=0
23:51:07-610945 DEBUG    Upscaler type=ESRGAN folder="E:\Artifical\stable-diffusion-webui\models\ESRGAN"
                         model="4xUltrasharp_4xUltrasharpV10"
                         path="E:\Artifical\stable-diffusion-webui\models\ESRGAN\4xUltrasharp_4xUltrasharpV10.pt"
23:51:07-611945 DEBUG    Upscaler type=ESRGAN folder="E:\Artifical\stable-diffusion-webui\models\ESRGAN"
                         model="ESRGAN_4x" path="E:\Artifical\stable-diffusion-webui\models\ESRGAN\ESRGAN_4x.pth"
23:51:07-614598 DEBUG    Upscaler type=SwinIR folder="E:\Artifical\stable-diffusion-webui\models\SwinIR"
                         model="SwinIR_4x" path="E:\Artifical\stable-diffusion-webui\models\SwinIR\SwinIR_4x.pth"
23:51:07-615596 DEBUG    Load upscalers: total=53 downloaded=5 user=3 time=0.05 ['None', 'Lanczos', 'Nearest',
                         'ChaiNNer', 'ESRGAN', 'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
23:51:07-630595 DEBUG    Load styles: folder="models\styles" items=288 time=0.01
23:51:07-634596 DEBUG    Creating UI
23:51:07-635598 INFO     Load UI theme: name="black-teal" style=Auto base=sdnext.css
23:51:07-666595 DEBUG    Read: file="html\reference.json" json=31 bytes=16330 time=0.000
23:51:08-243730 DEBUG    Extra networks: page='model' items=43 subfolders=3 tab=txt2img
                         folders=['E:\\Artifical\\stable-diffusion-webui\\models\\Stable-diffusion',
                         'models\\Reference', 'E:\\Artifical\\stable-diffusion-webui\\models\\Stable-diffusion']
                         list=0.02 desc=0.00 info=0.01 workers=2
23:51:08-259976 DEBUG    Extra networks: page='style' items=288 subfolders=2 tab=txt2img folders=['models\\styles',
                         'html'] list=0.02 desc=0.00 info=0.00 workers=2
23:51:08-264977 DEBUG    Extra networks: page='embedding' items=77 subfolders=1 tab=txt2img
                         folders=['E:\\Artifical\\stable-diffusion-webui\\models\\embeddings'] list=0.06 desc=0.01
                         info=0.02 workers=2
23:51:08-270978 DEBUG    Extra networks: page='hypernetwork' items=0 subfolders=1 tab=txt2img
                         folders=['E:\\Artifical\\stable-diffusion-webui\\models\\hypernetworks'] list=0.00 desc=0.00
                         info=0.00 workers=2
23:51:08-274978 DEBUG    Extra networks: page='vae' items=14 subfolders=1 tab=txt2img
                         folders=['E:\\Artifical\\stable-diffusion-webui\\models\\VAE'] list=0.01 desc=0.00 info=0.00
                         workers=2
23:51:08-330981 DEBUG    Extra networks: page='lora' items=920 subfolders=7 tab=txt2img
                         folders=['E:\\Artifical\\stable-diffusion-webui\\models\\Lora',
                         'E:\\Artifical\\stable-diffusion-webui\\models\\LyCORIS'] list=0.49 desc=0.17 info=0.34
                         workers=2
23:51:08-546029 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.000
23:51:08-654342 DEBUG    Themes: builtin=9 default=5 external=55
23:51:09-010342 DEBUG    Script: 0.29 ui_tabs
                         E:\Artifical\automatic\extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_b
                         rowser.py
23:51:09-015346 DEBUG    Read: file="E:\Artifical\automatic\html\extensions.json" json=347 bytes=204450 time=0.002
23:51:09-516422 DEBUG    Extension list: processed=331 installed=7 enabled=7 disabled=0 visible=331 hidden=0
23:51:10-010501 INFO     Local URL: http://127.0.0.1:7860/
23:51:10-011503 DEBUG    Gradio functions: registered=1810
23:51:10-011503 INFO     Initializing middleware
23:51:10-015505 DEBUG    Creating API
23:51:10-083508 DEBUG    SD-System-Info: benchmark data loaded:
                         E:\Artifical\automatic\extensions-builtin\sd-extension-system-info\scripts\benchmark-data-local
                         .json
23:51:10-141508 INFO     [AgentScheduler] Task queue is empty
23:51:10-143651 INFO     [AgentScheduler] Registering APIs
23:51:10-248649 DEBUG    Scripts setup: ['X/Y/Z Grid:0.005', 'ControlNet:0.051']
23:51:10-251650 DEBUG    Model metadata: file="metadata.json" no changes
23:51:10-252650 DEBUG    Model auto load disabled
23:51:10-253649 DEBUG    Save: file="config.json" json=30 bytes=1389 time=0.000
23:51:10-255650 INFO     Startup time: 13.41 { torch=3.94 gradio=0.89 libraries=3.24 extensions=2.35 face-restore=0.22
                         upscalers=0.05 ui-extra-networks=0.70 ui-txt2img=0.06 ui-img2img=0.07 ui-settings=0.17
                         ui-extensions=0.84 ui-defaults=0.21 launch=0.26 api=0.07 app-started=0.17 }
23:51:44-526372 DEBUG    Model requested: fn=txt2img
23:51:44-528370 INFO     Select: model="realcartoonAnime_v10_bf16 [a1e8008df0]"
23:51:44-529371 DEBUG    Load model weights: existing=False
                         target=E:\Artifical\stable-diffusion-webui\models\Stable-diffusion\realcartoonAnime_v10_bf16.sa
                         fetensors info=None
Loading model: E:\Artifical\stable-diffusion-webui\models\Stable-diffusion\realcartoonAnime_v10_bf16.safetensors ━ 0… -…
                                                                                                                   GB
23:51:44-561370 DEBUG    Load model:
                         name=E:\Artifical\stable-diffusion-webui\models\Stable-diffusion\realcartoonAnime_v10_bf16.safe
                         tensors dict=True
23:51:44-644061 DEBUG    Desired Torch parameters: dtype=BF16 no-half=False no-half-vae=False upscast=False
23:51:44-645059 INFO     Setting Torch parameters: device=xpu dtype=torch.bfloat16 vae=torch.bfloat16
                         unet=torch.bfloat16 context=no_grad fp16=False bf16=True
23:51:44-646941 DEBUG    Model dict loaded: {'ram': {'used': 1.01, 'total': 15.78}, 'gpu': {'used': 0.0, 'total': 7.75},
                         'retries': 0, 'oom': 0}
23:51:44-656939 DEBUG    Model config loaded: {'ram': {'used': 1.01, 'total': 15.78}, 'gpu': {'used': 0.0, 'total':
                         7.75}, 'retries': 0, 'oom': 0}
23:51:49-309964 INFO     LDM: LatentDiffusion: mode=eps
23:51:49-311963 INFO     LDM: DiffusionWrapper params=859.52M
23:51:49-312964 DEBUG    Model created from config: E:\Artifical\automatic\configs\v1-inference.yaml
23:51:49-313963 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline
                         file="E:\Artifical\stable-diffusion-webui\models\Stable-diffusion\realcartoonAnime_v10_bf16.saf
                         etensors" size=2289MB
23:51:49-315964 DEBUG    Model weights loading: {'ram': {'used': 5.01, 'total': 15.78}, 'gpu': {'used': 0.0, 'total':
                         7.75}, 'retries': 0, 'oom': 0}
23:51:52-063148 DEBUG    Model weights loaded: {'ram': {'used': 6.2, 'total': 15.78}, 'gpu': {'used': 0.0, 'total':
                         7.75}, 'retries': 0, 'oom': 0}
23:51:52-646661 DEBUG    Model weights moved: {'ram': {'used': 5.35, 'total': 15.78}, 'gpu': {'used': 2.03, 'total':
                         7.75}, 'retries': 0, 'oom': 0}
23:51:53-203659 INFO     Applied IPEX Optimize.
23:51:53-205659 INFO     Cross-attention: optimization=Sub-quadratic options=[]
23:51:53-557751 INFO     Load embeddings: loaded=82 skipped=3 time=0.35
23:51:53-561753 INFO     Model loaded in 9.03 { config=0.10 create=4.66 apply=0.59 vae=2.16 move=0.58 hijack=0.56
                         embeddings=0.35 }
23:51:53-791800 DEBUG    gc: collected=10444 device=xpu {'ram': {'used': 3.18, 'total': 15.78}, 'gpu': {'used': 2.04,
                         'total': 7.75}, 'retries': 0, 'oom': 0}
23:51:53-793378 INFO     Model load finished: {'ram': {'used': 3.18, 'total': 15.78}, 'gpu': {'used': 2.04, 'total':
                         7.75}, 'retries': 0, 'oom': 0} cached=0
23:51:54-483811 DEBUG    Sampler: sampler="DPM++ 2M" config={'scheduler': 'karras', 'brownian_noise': False}
 14%|███████████▌                                                                       | 7/50 [00:03<00:10,  4.13it/s]23:51:58-064310 DEBUG    Load VAE decode approximate:
                         model="E:\Artifical\stable-diffusion-webui\models\VAE-approx\model.pt"
 36%|█████████████████████████████▌                                                    | 18/50 [00:05<00:04,  6.61it/s]23:51:59-852885 DEBUG    Server: alive=True jobs=1 requests=24 uptime=58 memory=1.74/15.78 backend=Backend.ORIGINAL
                         state=job="txt2img" 0/-1
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:09<00:00,  5.08it/s]
23:52:04-924197 DEBUG    Init hires: upscaler="Latent (nearest-exact)" sampler="UniPC" resize=0x0 upscale=1080x1080
23:52:05-196387 DEBUG    Sampler: sampler="UniPC" config={}
Press any key to continue . . .
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment] 2024-01-25 08:32
Try Euler a or use the Diffusers backend.

**Comment by vladmandic** [comment] 2024-01-25 12:48
that log indicates a hard crash and you'll need to check even logs for actual root cause, nothing i can do based on this.

**Comment by vladmandic** [comment] 2024-03-01 20:27
closing as issue is open for more than a month without updates.

**Closed by vladmandic** 2024-03-01 20:27 UTC
Labels: platform
