### ISSUE TITLE
[Issue]: Clip Skip setting ignored

### ISSUE THREAD

**Issue by utak3r** [vladmandic/automatic#567] opened 2023-04-27 17:28 UTC
### Issue Description

The **Clip Skip** option always starts from value == 1, regardless of settings (which is == 2).
Reloading UI resets it back to 1, if manually set to another value.

### Version Platform Description

**UI:** def7a02d Wed Apr 26 16:08:56 2023 -0400
**Python** 3.10.10 on Windows
**Server arguments**: ['--medvram', '--disable-safe-unpickle']
**Quick launch:** ON.
**Browser**: Chrome 112.0.5615.138

**Comment by vladmandic** [comment] 2023-04-27 17:30
clip skip setting is now a local setting for each txt2img operation, its no longer a global option.
and as any local setting, it is reset on reload.
if you want to change defaults, you can edit `ui-config.json`

**Comment by utak3r** [comment] 2023-04-27 17:44
If so, it should be removed from the settings then.

**Comment by vladmandic** [comment] 2023-04-27 17:45
It is as of 15min ago.

**Comment by novaexe** [comment] 2023-04-29 17:28
rip clipskip in quick settings :(

**Comment by novaexe** [comment] 2023-04-29 18:31
> clip skip setting is now a local setting for each txt2img operation, its no longer a global option. and as any local setting, it is reset on reload. if you want to change defaults, you can edit `ui-config.json`

@vladmandic changing the uiconfig.json to anything becides one doesn't do anything until you move the slider manually within the gui, this also disable quicklaunch

**Comment by vladmandic** [comment] 2023-04-29 19:27
Yes, that is true and that is new behavior.
I don't want to have clip skip as global item.

**Comment by novaexe** [comment] 2023-04-29 19:58
but surely the ui-config,json is not intended behavior? also disabling quicklaunch cause of ui clipskip change?

**Comment by utak3r** [comment] 2023-04-29 19:59
I have it changed in json and it works for me.

**Comment by vladmandic** [comment] 2023-04-29 20:04
and i've just made it persistent as well. but quicklaunch is gone - whats the point if its on the screen in main params anyhow?

**Comment by novaexe** [comment] 2023-04-29 20:10
ah can confirm it now works as intended my b, might have been a glitch related to the critical error that happened a little bit ago, xD

the main point is it was a quick setting at the top where there is now an empty void 
![image](https://user-images.githubusercontent.com/69226867/235322349-13976f80-1983-44da-910f-13310b00d174.png)

**Comment by novaexe** [comment] 2023-04-29 20:14
but thank you for you're time vlad, loving the fork :) keep up the excellent work

**Comment by MonsterAzi** [comment] 2023-05-08 22:56
I'm pretty sure that this change actually made the issue worse. After this change, I can only use CLIP skip values above 1.

**Comment by vladmandic** [comment] 2023-05-09 12:25
same prompt/seed/etc with clip skip 1/2/3/4
![00000-1444716555-beautiful anime girl](https://github.com/vladmandic/automatic/assets/57876960/a14505d3-8cc1-4b1e-be7a-fa455f0c6649)
![00001-1444716555-beautiful anime girl](https://github.com/vladmandic/automatic/assets/57876960/3b31fd58-6bb8-43bc-b44e-8f88f37268a2)
![00002-1444716555-beautiful anime girl](https://github.com/vladmandic/automatic/assets/57876960/280a0ce4-39a4-403f-a5e8-c3080487a7aa)
![00003-1444716555-beautiful anime girl](https://github.com/vladmandic/automatic/assets/57876960/d6276547-72ee-482d-aabe-177ca4d896e3)

**Comment by YKefasu** [comment] 2023-05-18 17:06
@vladmandic the issue still there, even i edited ui-config.json "txt2img/CLIP Skip/value": 2,
Every Restart clip skip 2 always ignored, need to adjust the slider to 1 and back to 2 again to get it correct value

![image](https://github.com/vladmandic/automatic/assets/129555908/e180d0d9-8a3e-46fc-8f9c-c8a6d854412c)

**Comment by vladmandic** [comment] 2023-05-18 17:55
you had clip skip set to 2 in global settings (`config.json`), so it overrides what's displayed, but its not actually in effect.
as a test, remove both `ui-config.json` and `config.json` (if you don't want to delete them, move them somewhere else and you can move them back later) and default should be 1 and as soon as you change it it will be in effect.

**Closed by vladmandic** 2023-05-18 17:55 UTC
