### ISSUE TITLE
[Issue]: Control: Face Hires causes wrong pipeline switch after first image with batch count > 1

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3100] opened 2024-04-30 15:05 UTC
### Issue Description

In this case, setting a preprocessor and an image, then doing a batch with more than one image will trigger an exception, and the pipeline class switch will fail. This does *not* occur if batch count is 1. 

## Steps to reproduce

1. Input text in prompt
2. Create one ControlNet unit, Preprocessor "Depth Zoe", model "Depth Zoe XL"
3. Load as override image the provided image
4. Set parameters
5. Set batch size of 2 or higher
6. Hit generate

## Observed result

After the first successful generation, an error occurs when preparing the second image (see log below)

## Image

![raised](https://github.com/vladmandic/automatic/assets/25192/c8fbd4cb-9d44-4d46-bcea-9ab303fb5e6a)

### Version Platform Description

14:31:05-199622 INFO     Starting SD.Next                                       
14:31:05-242770 INFO     Logger: file="/notebooks/automatic/sdnext.log"         
                         level=INFO size=12336903 mode=append                   
14:31:05-244363 INFO     Python 3.10.10 on Linux                                
14:31:05-332054 INFO     Version: app=sd.next updated=2024-04-30 hash=96389a97  
                         branch=dev                                             
                         url=https://github.com/vladmandic/automatic/tree/dev   
14:31:05-490971 INFO     Updating main repository                               
14:31:07-501063 INFO     Upgraded to version: 96389a97 Tue Apr 30 17:02:01 2024 
                         +0300                                                  
14:31:07-507151 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=5.19.0-45-generic python=3.10.10 

### Relevant log output

```shell
Loading model: /notebooks/automatic/models/Lora/great_lighting.safetensors ━  -…0m
Loading model: /notebooks/automatic/models/Lora/xl_more_art-full_v1.safetensors ors 
Loading model: /notebooks/automatic/models/Lora/Difference_AnimeFace.safetenso… so… 
Loading model: /notebooks/automatic/models/Lora/hinaMaybeBetterPoseXL_v1.safet… et… 
14:59:27-630148 INFO     LoRA apply: ['great_lighting', 'xl_more_art-full_v1',  
                         'Difference_AnimeFace', 'hinaMaybeBetterPoseXL_v1',    
                         'Perfect Hands v2'] patch=0.00 load=6.55               
14:59:27-665339 INFO     Base: class=StableDiffusionXLControlNetInpaintPipeline 
Progress  1.83it/s █████████████████████████████████ 100% 20/20 00:10 00:00 Base
14:59:42-623171 INFO     High memory utilization: GPU=87% RAM=42% {'ram':       
                         {'used': 18.67, 'total': 44.08}, 'gpu': {'used': 13.61,
                         'total': 15.73}, 'retries': 0, 'oom': 0}               
14:59:43-221733 INFO     Processed: images=1 time=22.39 its=0.89 memory={'ram': 
                         {'used': 18.66, 'total': 44.08}, 'gpu': {'used': 10.25,
                         'total': 15.73}, 'retries': 0, 'oom': 0}               
14:59:43-310386 INFO     Saving:                                                
                         image="/tmp/images/control/00005-2867894035-7th_anime_X
                         L-A-fp16-1girl original solo standing clenched hand    
                         raised fist.webp" type=WEBP resolution=1664x2432 size=0
Loading model: /notebooks/automatic/models/Lora/great_lighting.safetensors ━  -…0m
Loading model: /notebooks/automatic/models/Lora/xl_more_art-full_v1.safetensors ors 
Loading model: /notebooks/automatic/models/Lora/Difference_AnimeFace.safetenso… so… 
Loading model: /notebooks/automatic/models/Lora/Perfect Hands v2.safetensors   …36m…
14:59:53-033024 INFO     LoRA apply: ['great_lighting', 'xl_more_art-full_v1',  
                         'Difference_AnimeFace', 'hinaMaybeBetterPoseXL_v1',    
                         'Perfect Hands v2'] patch=0.00 load=4.81               
14:59:53-071196 WARNING  Processing: mode=inpaint mask=None                     
14:59:53-073000 WARNING  Pipeline class change failed:                          
                         type=DiffusersTaskType.IMAGE_2_IMAGE                   
                         pipeline=StableDiffusionXLControlNetInpaintPipeline    
                         Pipeline <class                                        
                         'diffusers.pipelines.controlnet.pipeline_controlnet_sd_
                         xl_img2img.StableDiffusionXLControlNetImg2ImgPipeline'>
                          expected {'text_encoder_2', 'tokenizer_2',            
                         'tokenizer', 'vae', 'image_encoder', 'text_encoder',   
                         'controlnet', 'feature_extractor', 'unet',             
                         'scheduler'}, but only {'text_encoder_2',              
                         'tokenizer_2', 'tokenizer', 'vae', 'text_encoder',     
                         'controlnet', 'unet', 'scheduler'} were passed         
14:59:53-074831 INFO     Base: class=StableDiffusionXLControlNetInpaintPipeline 
14:59:54-111616 ERROR    Control pipeline failed: type=controlnet units=1       
                         error='NoneType' object is not iterable                
14:59:54-113043 ERROR    Control: TypeError                                     
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /notebooks/automatic/modules/control/run.py:569 in control_run               │
│                                                                              │
│   568 │   │   │   │   │   │   if processed is None:                          │
│ ❱ 569 │   │   │   │   │   │   │   processed: processing.Processed = processi │
│   570 │   │   │   │   │   │   else:                                          │
│                                                                              │
│ /notebooks/automatic/modules/processing.py:189 in process_images             │
│                                                                              │
│   188 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):  │
│ ❱ 189 │   │   │   │   processed = process_images_inner(p)                    │
│   190                                                                        │
│                                                                              │
│ /notebooks/automatic/modules/processing.py:307 in process_images_inner       │
│                                                                              │
│   306 │   │   │   │   │   from modules.processing_diffusers import process_d │
│ ❱ 307 │   │   │   │   │   x_samples_ddim = process_diffusers(p)              │
│   308 │   │   │   │   else:                                                  │
│                                                                              │
│ /notebooks/automatic/modules/processing_diffusers.py:472 in process_diffuser │
│                                                                              │
│   471 │   │   apply_hidiffusion()                                            │
│ ❱ 472 │   │   output = shared.sd_model(**base_args) # pylint: disable=not-ca │
│   473 │   │   if isinstance(output, dict):                                   │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py:115 in de │
│                                                                              │
│   114 │   │   with ctx_factory():                                            │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                               │
│   116                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/diffusers/pipelines/controlnet/pipel │
│                                                                              │
│   1528 │   │   # 5.3 Prepare mask                                            │
│ ❱ 1529 │   │   mask = self.mask_processor.preprocess(                        │
│   1530 │   │   │   mask_image, height=height, width=width, resize_mode=resiz │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/diffusers/image_processor.py:499 in  │
│                                                                              │
│   498 │   │   │   raise ValueError(                                          │
│ ❱ 499 │   │   │   │   f"Input is in incorrect format: {[type(i) for i in ima │
│   500 │   │   │   )                                                          │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not iterable
```

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by lbeltrame** [comment] 2024-04-30 15:14
But now that I look at it, isn't it trying to switch to the wrong pipeline?

**Comment by vladmandic** [comment] 2024-05-06 13:01
i can see the error: pipe change: INPAINT -> IMG2IMG
> Pipeline <class 'diffusers.pipelines.controlnet.pipeline_controlnet_sd_xl_img2img.StableDiffusionXLControlNetImg2ImgPipeline'>
> expected {'text_encoder_2', 'tokenizer_2', 'tokenizer', 'vae', 'image_encoder', 'text_encoder', 'controlnet', 'feature_extractor', 'unet', 'scheduler'},
> but only {'text_encoder_2', 'tokenizer_2', 'tokenizer', 'vae', 'text_encoder', 'controlnet', 'unet', 'scheduler'} were passed  

but i cannot reproduce it.
also not sure why would this result in error anyhow since image_encoder and feature_extractor are optional pipeline components, not mandatory.

can you double-check reproduction steps?

**Comment by lbeltrame** [comment] 2024-05-06 15:43
Will try to reproduce again and see what happens.

**Comment by lbeltrame** [comment] 2024-05-29 15:29
I can reproduce this with Openpose and any other model. It's a bit different than what I originally expected. The *first* image uses `ControlNetXLPipeline` but the *second* element in the batch onward will use `Img2ImgPipeline` on the *previous* image. 
I used a model with 100% conditioning. Logs follow:

```
Loading model: /notebooks/automatic/models/Lora/great_lighting.safetensors ━  -…0m
Loading model: /notebooks/automatic/models/Lora/xl_more_art-full_v1.safetensors ors 
Loading model: /notebooks/automatic/models/Lora/Difference_AnimeFace.safetenso… so… 
Loading model: /notebooks/automatic/models/Lora/better_scenery.safetensors ━  -…6m-…
Loading model: /notebooks/automatic/models/Lora/hinaMaybeBetterPoseXL_v2_rank3… k3… 
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
                                                                       MB       
15:23:21-325782 INFO     LoRA apply: ['great_lighting', 'xl_more_art-full_v1',  
                         'Difference_AnimeFace', 'better_scenery',              
                         'hinaMaybeBetterPoseXL_v2_rank32', 'hand5'] patch=0.00 
                         load=27.96                                             
15:23:21-388628 INFO     Base: class=StableDiffusionXLControlNetPipeline        
Progress  1.31it/s █████████████████████████████████ 100% 24/24 00:18 00:00 Base
15:23:41-375299 INFO     Upscale: upscaler="ESRGAN 4x Ultrasharp" resize=0x0    
                         upscale=1664x2432                                      
15:23:50-068007 INFO     Upscaler loaded: type=ESRGAN                           
                         model=models/ESRGAN/ESRGAN-UltraSharp-4x.pth           
Upscaling ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:06m 0:00:06
15:23:56-923702 INFO     HiRes: class=StableDiffusionXLImg2ImgPipeline          
                         sampler="DPM++ 2M"                                     
Progress  1.80s/it ████████████████████████████████ 100% 15/15 00:26 00:00 Hires
15:24:41-704386 INFO     Loading: type=FaceHires                                
                         model=/notebooks/automatic/models/yolo/yolov8n-face.pt 
Loading model: /notebooks/automatic/models/Lora/great_lighting.safetensors ━  -…0m
Loading model: /notebooks/automatic/models/Lora/xl_more_art-full_v1.safetensors ors 
Loading model: /notebooks/automatic/models/Lora/Difference_AnimeFace.safetenso… so… 
Loading model: /notebooks/automatic/models/Lora/better_scenery.safetensors ━  -…6m-…
Loading model: /notebooks/automatic/models/Lora/hinaMaybeBetterPoseXL_v2_rank3… k3… 
15:24:48-579513 INFO     LoRA apply: ['great_lighting', 'xl_more_art-full_v1',  
                         'Difference_AnimeFace', 'better_scenery',              
                         'hinaMaybeBetterPoseXL_v2_rank32', 'hand5'] patch=0.00 
                         load=4.72                                              
15:24:48-606840 INFO     Base: class=StableDiffusionXLInpaintPipeline           
Progress  2.32it/s █████████████████████████████████ 100% 15/15 00:06 00:00 Base
15:24:58-112472 INFO     High memory utilization: GPU=91% RAM=36% {'ram':       
                         {'used': 15.74, 'total': 44.08}, 'gpu': {'used': 14.36,
                         'total': 15.73}, 'retries': 0, 'oom': 0}               
15:24:58-758096 INFO     Processed: images=1 time=15.10 its=0.99 memory={'ram': 
                         {'used': 15.74, 'total': 44.08}, 'gpu': {'used': 9.64, 
                         'total': 15.73}, 'retries': 0, 'oom': 0}               
15:25:34-781696 INFO     Save:                                                  
                         image="/tmp/images/control/00000-3397520873-7th_anime_X
                         L-A-fp16-1girl original solo standing pointing medium  
                         breasts intricate.webp" type=WEBP resolution=1664x2432 
                         size=3179118                                           
Loading model: /notebooks/automatic/models/Lora/great_lighting.safetensors ━  -…0m
Loading model: /notebooks/automatic/models/Lora/xl_more_art-full_v1.safetensors ors 
Loading model: /notebooks/automatic/models/Lora/Difference_AnimeFace.safetenso… so… 
Loading model: /notebooks/automatic/models/Lora/better_scenery.safetensors ━  -…6m-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
Loading model: /notebooks/automatic/models/Lora/hand5.safetensors ━━━━ 0.0… -:-…
                                                                       MB       
15:25:40-475286 INFO     LoRA apply: ['great_lighting', 'xl_more_art-full_v1',  
                         'Difference_AnimeFace', 'better_scenery',              
                         'hinaMaybeBetterPoseXL_v2_rank32', 'hand5'] patch=0.00 
                         load=5.67                                              
15:25:40-516502 WARNING  Processing: mode=inpaint mask=None                     
15:25:40-519222 INFO     Base: class=StableDiffusionXLImg2ImgPipeline           
Progress  1.74s/it ███████████████████▏                56% 9/16 00:15 00:12 Base
15:25:57-771699 INFO     Interrupted...                                      
```

Notice how it goes in mode "inpaint".

**Comment by lbeltrame** [comment] 2024-05-29 15:32
Ok, I think I'm starting to narrowing things down. This happens *when face hires is active*. If it's not, the pipeline correctly goes to `ControlNetXLPipeline".

**Comment by lbeltrame** [comment] 2024-06-09 08:48
Update: this happens with **all** Control pipelines, including Reference.

**Comment by vladmandic** [comment] 2024-06-09 12:32
should be fixed now.

**Closed by vladmandic** 2024-06-09 12:32 UTC
Labels: bug
