### ISSUE TITLE
[Issue]: latent upscaler is enabled, even though it shoudln't

### ISSUE THREAD

**Issue by Xerdunits** [vladmandic/automatic#1762] opened 2023-07-19 20:44 UTC
### Issue Description

I just noticed that the latent upscaler seems to be enabled even though it shouldn't? At least I don't have it enabled, yet it does show up in the generation information. I don't think it is really enabled, but it appears so in the generation info.

I love the new loading animation btw! :)

### Version Platform Description

Starting SD.Next                                                                                                                                                                                
Python 3.10.6 on Linux                                                                                                                                                                          
Version: e002652a Wed Jul 19 15:09:01 2023 -0400                                                                                                                                                
nVidia CUDA toolkit detected 

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by TeutonJon78** [comment] 2023-07-19 22:25
https://github.com/vladmandic/automatic/issues/1745

**Comment by vladmandic** [comment] 2023-07-20 00:04
indeed its the same root cause, but this variable went through cracks, fixed in dev.

**Closed by vladmandic** 2023-07-20 00:04 UTC
