### ISSUE TITLE
[Issue]: Log File Not User Friendly since update

### ISSUE THREAD

**Issue by plscripts** [vladmandic/automatic#1261] opened 2023-06-02 05:13 UTC
### Issue Description

Previous output was a csv file with columns A through I with the following headings:
prompt, seed, width, height, sampler, cfgs, steps, filename, negative prompt

New output to csv is formatted as follows:
][
   {
        "filename:":"<filepath>"
        "time": "2023-06-02T10:35:01.554777"
        "info": "<beginning of prompts>
        
then each individual prompt word gets it's own column across the csv for as many words there are in the prompt! So if your prompt has 150 words, it spans 150 columns, a word per column.

### Version Platform Description

Version: 562947c9 Fri Jun 2 01:14:12 2023 +0300

**Comment by vladmandic** [comment] 2023-06-02 12:54
previous log format was CSV and it may look ok to you visually, but it was impossible to properly use progamatically.
new format is standard JSON with 3 properties: generate filename, time stamp and info string which is in standard format that can be applied to recreate image.

closing as this is by design.

**Closed by vladmandic** 2023-06-02 12:54 UTC
