### ISSUE TITLE
[Issue]: 33% lower performance than an older build

### ISSUE THREAD

**Issue by VictorZakharov** [vladmandic/automatic#941] opened 2023-05-14 12:12 UTC
### Issue Description

Vlad SD is at least 33% slower than it was roughly 2 weeks ago, down to 16 it/sec from 24 it/sec (anywhere between 14 and 16). Here is performance benchmark on 4070 Ti:
```
2023-05-13 15:31:48.111424
11.46 / 13.6 / 16.63
updated:2023-05-13 hash:c46f0dbd url:https://github.com/vladmandic/automatic/tree/master
arch:AMD64 cpu:AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system:Windows release:Windows-10-10.0.19045-SP0 python:3.10.6
torch:2.0.1+cu118 Autocast half xformers:unavailable accelerate:0.18.0 transformers:4.26.1
device:NVIDIA GeForce RTX 4070 Ti (1) (compute_37) (8, 9) cuda:11.8 cudnn:8700 12GB
sdp none
experience_80.safetensors [28bb9b6d12]
Victor
606e53
```

Unfortunately, I am not able to run the old build anymore, it gives me this error:
```
TypeError: Logger._log() got an unexpected keyword argument 'file'
```

I did not keep the old version, just checked out a commit on May 2, which is where I had 24 it/sec on high batch.

But I compared to the latest version of A1111:
Vlad SD: 400 steps, 100 steps @ batch 4, 512 = 27 seconds. Effective 14.8 it/sec. Second run - 28 seconds (slower). Change to batch size 2 (200 steps total) = 15.38 it/sec.
A1111 (pulled latest 89f9faa63388756314e8a1d96cf86bf5e0663045, deleted venv and recreated): 400 steps, 100 steps @ batch 4, 512 = 19 seconds. Effective 21 it/sec
So this SD is actually 45% slower than the most recent version of A1111? These are my numbers anyway.

Here is how I run A1111:
```
set COMMANDLINE_ARGS=--api --cors-allow-origins=https://www.painthua.com --opt-sdp-no-mem-attention
```

### Version Platform Description

- Google Chrome, Version 113.0.5672.93 (Official Build) (64-bit)
- Windows 10, all updates.
- Version: https://github.com/vladmandic/automatic/commit/c46f0dbdeb27dac2f17f19b119a43a094076d1b7 Sat May 13 12:55:50 2023 -0400

**Comment by vladmandic** [comment] 2023-05-14 12:31
duplicate #918

**Comment by vladmandic** [comment] 2023-05-14 12:32
- run actual benchmark (in system info).
- what are your cuda settings?
- try resetting configuration by deleting `config.json`

**Comment by ronbere** [comment] 2023-05-14 13:02
i'm not an expert, maybe because A1111 turns on torch 2.0.1 now

**Comment by vladmandic** [comment] 2023-05-14 13:04
nope, i support torch 2.0.1 as well. and there are no differences in performance. torch 2.0.1 fixes some specific bugs, but nothing related to this.

**Comment by VictorZakharov** [comment] 2023-05-14 13:04
This is the actual benchmark, it's in the issue description:
```
2023-05-13 15:31:48.111424
11.46 / 13.6 / 16.63
updated:2023-05-13 hash:c46f0dbd url:https://github.com/vladmandic/automatic/tree/master
arch:AMD64 cpu:AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system:Windows release:Windows-10-10.0.19045-SP0 python:3.10.6
torch:2.0.1+cu118 Autocast half xformers:unavailable accelerate:0.18.0 transformers:4.26.1
device:NVIDIA GeForce RTX 4070 Ti (1) (compute_37) (8, 9) cuda:11.8 cudnn:8700 12GB
sdp none
experience_80.safetensors [28bb9b6d12]
Victor
606e53
```

Not sure about CUDA settings, where can I check that?

Deleting config.json helped. I'm back to 22 it/sec, which is very close to what I had. The difference could be measurement error.
Thanks!

Benchmark after deleting config.json is provided below:
```
2023-05-14 09:00:49.697253
11.88 / 13.92 / 18.39
updated:2023-05-14 hash:12569f7f url:https://github.com/vladmandic/automatic/tree/master
arch:AMD64 cpu:AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system:Windows release:Windows-10-10.0.19045-SP0 python:3.10.6
torch:2.0.1+cu118 Autocast half xformers:unavailable accelerate:0.18.0 transformers:4.26.1
device:NVIDIA GeForce RTX 4070 Ti (1) (compute_37) (8, 9) cuda:11.8 cudnn:8700 12GB
sdp none
analogMadness_analogMadnessV11.safetensors [c353698edc]
Victor
606e53
```

I don't see it reporting anywhere close to 22 it/sec, so not sure if it helps in any way, vs a regular test.

BTW, running 100 step, batch 4, 512 gives me 23.5 it/sec (17 seconds for 400 steps total).

**Comment by vladmandic** [comment] 2023-05-14 13:58
cuda settings are in -> ui -> settings -> compute settings

most likely cuda settings got modified (cant say how) to run in fp32 mode instead of fp16 which nearly halfed your performance. could be due to interim bug in some of recent builds that unintentionally detected that fp16 is not supported or could be just the wrong click. deleting `config.json` reset the settings (there is also now button on top of settings tab to reset settings)

anyhow, seems like its resolved.

**Comment by VictorZakharov** [comment] 2023-05-14 22:50
@vladmandic After several generations, between 20-30, performance drops to 13 it/sec. It is only restored after PC restart or starting A1111 (weird?), and lasts 20-30 gens more. Restarting SD doesn't help, same performance. I cannot always reproduce it. Happened 2 times out of 3, currently does not happen.

A1111 does not have this problem. I ran 50 gens a in row, consistently around 20 it/sec. I also ran A1111 after Vlad SD became slow, no issues, A1111 is fast.

Here is how it looks in the logs:

![image](https://github.com/vladmandic/automatic/assets/8978766/2908007b-ec6b-4cf2-ae42-e9c60142d122)

Notice a sharp drop from 19.89 to 11.55, it never recovers until PC restart or until A1111 is started. No other applications are open, just SD.

**Comment by vladmandic** [comment] 2023-05-15 00:15
i can see it. and you have quite a typical environment - nothing strange and all components well tested, its not like its one of the less-tested combos.
i just ran generate with batch count 200 and performance was same throughout - i just cannot reproduce this.
if you find a way to shine more light on this, i'd be happy to take a look, but at the moment, i don't know what to look for at all.

**Comment by VictorZakharov** [comment] 2023-05-15 23:12
An interesting observation - when it happens, performance drops to 13-14 it/sec, I can put it back to 24 it/sec by using batch size 3. It's the minimum required to get 24 it/sec.

Not 2, not 4, exactly 3. It's pretty consistent also. But size 2 or 4 is also higher than 13-14. Batch 2 = 20 it/sec, batch 4 = 22 it/sec. Batch 3 = 24 it/sec. For completeness, batch 5 is 23 it/sec, batch 6 = 24 it/sec. It then starts dropping again, batch 7 = 23.3 it/sec, batch 8 = 22.8 it/sec, will probably drop with higher batch sizes. This is on 4070 Ti with 12GB of memory, image size 512x512.

**Comment by vladmandic** [comment] 2023-05-15 23:22
Can you monitor your GPU clock speeds (MSI afterburner or even just `nvidia-smi`) while drop in performance happens?

**Comment by SAC020** [comment] 2023-05-21 11:03
Also seeing degraded performance. GPU usage is at 66%, CPU at 30% during image generation. RTX 3080.

![image](https://github.com/vladmandic/automatic/assets/50420272/071697b8-321e-4b2f-85e2-14389b183540)

[setup.log](https://github.com/vladmandic/automatic/files/11524320/setup.log)

![image](https://github.com/vladmandic/automatic/assets/50420272/a78a9b69-8259-4e0d-a45e-bbc26d4b7e85)

Version is current as of 4 hours ago (b6289d56)

I am using a number (4..5) of controlnets with "low vram" checked, otherwise I get "out of memory"

**Comment by vladmandic** [comment] 2023-05-21 12:04
@SAC020 if you're using low vram, you're spending all that extra time swaping module in and out of vram and its normal you're seeing the slowdown, that's not what @VictorZakharov reported.

@VictorZakharov any updates from your side?

**Comment by VictorZakharov** [comment] 2023-05-21 12:06
@vladmandic Didn't have time to work more with it yet, sorry. This is just a hobby for me.

**Comment by vladmandic** [comment] 2023-05-21 12:08
> @vladmandic Didn't have time to work more with it yet, sorry. This is just a hobby for me.

understood? when you get a chance, capture output of `nvidia-smi -x -q` to a log file while its running fast (when you start generating) and once more when it slows down - that will give me all internal states from the gpu.

**Comment by VictorZakharov** [comment] 2023-05-21 13:14
@vladmandic Tried to reproduce on the latest version and could not. Here is how nvidia-smi looks when it runs normally (while generating). I will update here if I see the issue again.
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.68                 Driver Version: 531.68       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070 Ti    WDDM | 00000000:0C:00.0  On |                  N/A |
|  0%   54C    P2              243W / 285W|   3607MiB / 12282MiB |     93%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by vladmandic** [comment] 2023-05-21 13:38
i guess thats good :)
i'll close the issue for now, but if issue reoccurs post an update here and i'll reopen it.

**Closed by vladmandic** 2023-05-21 13:38 UTC
Labels: question, cannot reproduce

**Comment by VictorZakharov** [comment] 2023-05-27 23:21
@vladmandic I was able to reproduce on the latest build.
> Version: 8022de74 Fri May 26 23:43:37 2023 +0300

Getting anywhere from 8 to 14 it/sec on 512.

nvidia-smi shows this table, so only using half the power or less.
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.61                 Driver Version: 531.61       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070 Ti    WDDM | 00000000:0C:00.0  On |                  N/A |
| 31%   53C    P2              124W / 285W|   4047MiB / 12282MiB |     94%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by vladmandic** [comment] 2023-05-28 11:58
first, try with higher batch sizes, for example 4. batch size of 1 is often too small to fully saturate gpu as there are too many round trips cpu<->gpu.

second, provide `nvidia-smi -x -q` log as i've noted below. output like you've provided is nice-to-see, but doesn't help identifyinging the problem.

**Comment by VictorZakharov** [comment] 2023-05-28 12:58
@vladmandic I'll try nvidia-smi with args next time, just forgot to include them.
Regarding batch size 1, after restart, I can get 20-21 it/sec at 512, which is enough to tell no issue.
When this number drops to around 10 or below, then again, it's enough to tell smth's wrong.

Here is power saturation on batch size 1, 512, 100 steps.

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.61                 Driver Version: 531.61       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070 Ti    WDDM | 00000000:0C:00.0  On |                  N/A |
|  0%   57C    P2              250W / 285W|   3208MiB / 12282MiB |     94%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by Ke031** [comment] 2023-06-03 14:54
@vladmandic i cannot understand since the update of june mayeb 1st, it's like i run slower than the other versions of vlad...
i mean it's not during the generation of an images but when i use hi res fix, i saw too that you change 150 steps to 99 ? 
why ? agent scheduler not working properly too, or i don't know how to use it, but anyway the most important problem still the lnger generations that it take, it's like forever now to do something now.... there was no problem on May .... too many changes sometimes go against quality, can you help me on this ? i have a i9 9900K, RTX 2080TI, 32go ram.... and it was like fast to do something in may but now.....

**Comment by vladmandic** [comment] 2023-06-03 15:02
@Ke031 this feels like you needed to vent a bit? i cannot address unrelated issues in a single sentence and without any details.

re: number of steps higher than 99 does not exist in theory how samplers work. this has been covered in details - search for "timesteps"

re: agent scheduler - create an issue if its not working for you

re: performance - i don't know what your issue is, but its quite possible that its related to nvidia drivers due to their recent change in memory management - just as much as its possible it is fault of this app. i am not aware of the general issue and i'm running regular performance benchmarks. and hires fix code has not changed recently.

**Comment by Ke031** [comment] 2023-06-03 15:10
@vladmandic i'm sorry didnt' know that but i'm new on github it's my first comment ever ...
does i do something wrong ? 

17:09:16-699709 INFO     Running extension preloading
17:09:16-712397 INFO     Starting SD.Next
17:09:16-718253 INFO     Python 3.10.9 on Windows
17:09:16-789266 INFO     Version: 299f1229 Fri Jun 2 20:54:09 2023 -0400
17:09:17-182142 INFO     Latest published version: 549c02a874eac1b3ac78ec61b7f1beec81dd76aa 2023-06-03T14:36:53Z
17:09:17-184094 INFO     Setting environment tuning
17:09:17-187023 INFO     nVidia CUDA toolkit detected
17:09:19-308802 INFO     Torch 2.0.1+cu118
17:09:19-327775 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:09:19-329695 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 SUPER VRAM 8192 Arch (7, 5) Cores 48
17:09:19-331647 INFO     Verifying requirements
17:09:19-349231 INFO     Installing packages
17:09:19-398137 INFO     No changes detected: Quick launch active
17:09:19-399109 INFO     Running extension preloading
17:09:19-400099 INFO     Server arguments: []

**Comment by vladmandic** [comment] 2023-06-03 15:20
@Ke031 that part of the log looks clean, but i don't see how is that relevant to any of the concerns you've raised.

**Comment by Ke031** [comment] 2023-06-03 15:27
@vladmandic cause i said to myself it was may a wrong version of something i had installed or something...
but it don't seems to be that if i read your words ... i'm trying to roll back to a earlier version of nvidia drivers, maybe as you says it's because of that, i will make an update if that solved my problem :) sorry for mistakes i'm new on github and i don't really know the rules of comments etc...
