### ISSUE TITLE
[Issue]: failed finding central directory

### ISSUE THREAD

**Issue by chrisbward** [vladmandic/automatic#1168] opened 2023-05-26 00:52 UTC
### Issue Description

When using a fresh setup, and trying to upscale for the first time, I see this error in the console;

```
Downloading: "https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth " to /home/user/Projects/04_MachineLearning/01_StableDiffusion/vlad-automatic-python310/models/SwinIR/SwinIR_4x.pth

 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 133M/136M [00:13<00:00, 10.2MB/s]
Loading weights: /home/user/Projects/04_MachineLearning/01_StableDiffusion/vlad-automatic-python310/models/SwinIR/SwinIR_4x.pth ━━━━━━━━━╸ 139.9/140… 0:00:00
                                                                                                                                           MB                
01:36:10-075524 ERROR    Exception: PytorchStreamReader failed reading zip archive: failed finding central directory   
```

### Version Platform Description

Linux, Ubuntu 20.04, venv is 3.10.10

 Version: 9a3a56db Thu May 25 13:40:48 2023 -0400

**Comment by chrisbward** [comment] 2023-05-26 01:14
```
Downloading: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth" to /home/user/Projects/04_MachineLearning/01_StableDiffusion/vlad-automatic-python310/models/RealESRGAN/RealESRGAN_x4plus.pth

 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████        | 59.5M/63.9M [00:05<00:00, 11.0MB/s]
02:11:20-613625 ERROR    Exception: PytorchStreamReader failed reading zip archive: failed finding central directory     
```

**Comment by chrisbward** [comment] 2023-05-26 01:14
I'll try to use `wget` directly in the directory and check to see if the hashsums match, if it's completed the download

**Comment by chrisbward** [comment] 2023-05-26 01:16
okay, so they do not match - so for some reason the download is bailing early?
``` 
99ec365d4afad750833258a1a24f44ca  ./RealESRGAN_x4plus.pth 
4c06e30837a43bebf66babff5bb83b27  ./RealESRGAN_x4plus.pth.bak (failed)
```

**Comment by vladmandic** [comment] 2023-05-26 10:00
so you found the cause - download is incomplete. why is that happening, i cant say. actual download process inside `basicsr` library and its completely opaque, i cannot get any more details from it unless i start meddling with their source code and then it would not longer be installable. i'm affraid there is really not much i can do here.

**Comment by vladmandic** [comment] 2023-06-01 22:10
any updates?
is this issue persistent - meaning that any download of realesrgan models will result in incomplete download or?

**Comment by vladmandic** [comment] 2023-06-05 11:41
i'm closing the issue as there are no updates - but if issue persists or reoccurs, update here and i'll reopen.

**Closed by vladmandic** 2023-06-05 11:41 UTC
Labels: question
