### ISSUE TITLE
[Extension]: stable-diffusion-webui-depthmap-script

### ISSUE THREAD

**Issue by semjon00** [vladmandic/automatic#1335] opened 2023-06-06 20:31 UTC
### Issue Description

Sometimes can not import from files in the directory of the plugin. Please see this issue:
https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/243

### Version Platform Description

Tested on 8f4bc4df08c48e70ea66e16c76151f1052f034c1, see issue mentioned above.

### URL link of the extension

https://github.com/thygate/stable-diffusion-webui-depthmap-script

**Comment by vladmandic** [comment] 2023-06-06 20:51
extension has an incorrect understanding how extensions are loaded by webui - only files loaded by webui should be in `scripts` folder. and files imported by extension itself should be relative to extension root, not to `scripts`  

what extension is doing right now is causing webui to load each of its files directly instead of single entry point as its intended.

btw, this is pretty bad.

**Comment by Lalimec** [comment] 2023-06-06 21:34
There are bunch of issues opened about this in the extension's repo but dev doesn't seem to take a look at any of them.

**Comment by semjon00** [comment] 2023-06-10 06:18
I have tried to move the deps outside of the scripts folder, but it turned out harder than it seems.

@thygate could you please do this?

**Comment by Lalimec** [comment] 2023-06-16 10:26
I ve changed these lines from depthmap.py

```
sys.path.append('extensions/stable-diffusion-webui-depthmap-script/scripts')
```
to these

```
import os

script_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(script_dir)
```

seems ok for now.

**Comment by Lalimec** [comment] 2023-06-16 11:41
nvm got this now

```
11:34:20-345910 ERROR    Exception: local variable 'inpaint_imgs' referenced
                         before assignment
11:34:20-347301 ERROR    Arguments: args=(0, <PIL.Image.Image image mode=RGB
                         size=1160x1680 at 0x7F7DDCE3A560>, None, '', '', 0, 0,
                         512, 512, False, True, False, False, 0, 1, False, 1,
                         True, True, False, False, ['left-right',
                         'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True,
                         False, False, False, False, 'u2net', False, 0, 2,
                         False, None, True, True, True, False) kwargs={}
11:34:20-349350 ERROR    gradio call: UnboundLocalError
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/ubuntu/vlad-webui/modules/call_queue.py:34 in f                        │
│                                                                              │
│    33 │   │   │   try:                                                       │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                            │
│    35 │   │   │   │   progress.record_results(id_task, res)                  │
│                                                                              │
│ /home/ubuntu/stable-diffusion-webui/extensions/stable-diffusion-webui-depthm │
│ ap-script/scripts/depthmap.py:1185 in run_generate                           │
│                                                                              │
│   1184 │                                                                     │
│ ❱ 1185 │   outputs, mesh_fi, meshsimple_fi = run_depthmap(                   │
│   1186 │   │   None, outpath, imageArr, imageNameArr,                        │
│                                                                              │
│ /home/ubuntu/stable-diffusion-webui/extensions/stable-diffusion-webui-depthm │
│ ap-script/scripts/depthmap.py:780 in run_depthmap                            │
│                                                                              │
│    779 │   │   │                                                             │
│ ❱  780 │   │   │   mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depth │
│    781                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
UnboundLocalError: local variable 'inpaint_imgs' referenced before assignment
Traceback (most recent call last):
  File "/home/ubuntu/vlad-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ubuntu/vlad-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/ubuntu/vlad-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/home/ubuntu/vlad-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 4).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "", "<div class='error'>local variable &#x27;inpaint_imgs&#x27; referenced before assignment</div><div class='performance'><p class='time'>Time taken: 6m 3.03s</p> | <p class='vram'>GPU active 3787 MB reserved 4354 MB | System peak 4709 MB total 22581 MB</p></div>"]
```

**Comment by vladmandic** [comment] 2023-07-23 15:51
closing as no follow-ups. if the issue is still ocurring, provide upstream tracking info.

**Closed by vladmandic** 2023-07-23 15:51 UTC
Labels: upstream, extension
