### ISSUE TITLE
[Issue]: Checkpoint loading twice at startup

### ISSUE THREAD

**Issue by EfourC** [vladmandic/automatic#710] opened 2023-05-02 20:13 UTC
### Issue Description

Just ran the latest version and I noticed the checkpoint is loading twice at startup (same behavior after killing and re-starting).

![WindowsTerminal_t905B44Xg2](https://user-images.githubusercontent.com/121468033/235774788-704d28cb-c8d8-4de1-80cc-4bcdad963c8a.png)

### Version Platform Description

Windows 10
Version: eb03fce3 Tue May 2 15:57:28 2023 -0400

**Comment by vladmandic** [comment] 2023-05-02 20:32
ah, my bad - i know the root cause, tried to fix when model was not loading correctly if they are from similar-but-not-same version (e.g. two models which are different subvariants of sd2.0), but caused this regression.

unfortunately, i need to head out now, i'll try to fix it when i'm back.

**Comment by mark-wd** [comment] 2023-05-03 01:03
Same issue as #713.

**Comment by vladmandic** [comment] 2023-05-03 01:31
should be fixed.
also fixed is applying correct model config when switching between similar-but-not-identical models as well as generally faster model load on startup (by at least few sec).

**Closed by vladmandic** 2023-05-03 01:31 UTC
Labels: bug
