### ISSUE TITLE
[Issue]: Unable to launch

### ISSUE THREAD

**Issue by Lumpsack** [vladmandic/automatic#920] opened 2023-05-13 16:14 UTC
### Issue Description

Used the upgrade this morning and it ran with errors - complaining of modules not being able to be upgraded by GitHub, but loaded - I closed and re-opened the command line, no reported faults.
Later ran the upgrade again as I'd noted some changes in DirectML (I use AMD under Windows)

Now will not launch - see the image below

![image](https://github.com/vladmandic/automatic/assets/127429289/e5c62ad6-00e4-40a1-8c75-137e9358333f)

### Version Platform Description

Windows 11, Edge (current), Version: a2923064 Sat May 13 11:52:31 2023 -0400

**Comment by vladmandic** [comment] 2023-05-13 16:26
i just pushed a fix.
but to use torch-directml, you need to start `webui --use-directml`.

**Closed by vladmandic** 2023-05-13 16:26 UTC

**Comment by Lumpsack** [comment] 2023-05-13 16:37
Cheers Vlad, that upgraded and launched again, but as you say I need to use --use-directml now, that wasn't the case before the script was picking up my card correctly and automatically setting it, was that the fix, to remove that part?

**Comment by Lumpsack** [comment] 2023-05-13 16:40
ah, new issue - it launched fine, but when I go to make an image I get this error.
![image](https://github.com/vladmandic/automatic/assets/127429289/65f565eb-2692-4af6-9ddb-9e45c2f79a3c)

**Comment by vladmandic** [comment] 2023-05-13 16:57
ok, i've posted another fix :)

re: `--use-directml` - the problem is that without that, there is no way to know if user wants to use directml or he wants to run on cpu?
so i changed behavior to explicitly require user to present that choice.

**Comment by Lumpsack** [comment] 2023-05-13 17:00
lol, that was quick and working perfectly again - many thanks :D
