### ISSUE TITLE
[Feature]: Better style button icons on "From Text" page

### ISSUE THREAD

**Issue by afbagwell** [vladmandic/automatic#1377] opened 2023-06-09 15:57 UTC
### Feature description

I know these have gone through a few iterations, but so far this is the worst of them. The current icons are completely indecipherable. Even after using them heavily, I'm only remembering what they do based on position -- and sometimes I even screw that up. 

Right now from left to right, here's my initial impression: 

- book (?) 
- man doing something
- Internet
- luggage (? - honestly no idea)
- lock safe (?)

Can they be replaced by something from the Bootstrap library or another UI icon library with a cleaner look and more obvious meanings? They also need a hover text on them to describe their function.

### Version Platform Description

4a3ab4ed

**Comment by vladmandic** [comment] 2023-06-09 16:12
icons are not even icons, right now they are limited to whats available as unicode characters.
new ui will have actual icons when its released. in the meantime, i don't plan to spend time tweaking unicode characters.

**Comment by afbagwell** [comment] 2023-06-09 16:46
Good to know! Thanks!

**Comment by brknsoul** [comment] 2023-06-09 20:36
>  i don't plan to spend time tweaking unicode characters

I'm just wondering why they were changed in the first place. ;-)

**Comment by mariodian** [comment] 2023-06-11 07:51
At least title="<description>" for each button  would be nice (I can make a PR) so that you get an info on mouse over.

**Comment by vladmandic** [comment] 2023-06-11 12:44
@mariodian hints were disabled due to error in parsing for couple of days, they are back on as of yesterday.

**Comment by mariodian** [comment] 2023-06-13 08:43
Got it! Although, I don't see those because I'm using the kitchen-theme :(

**Comment by vladmandic** [comment] 2023-06-13 11:39
@mariodian you should see new hints that i've published yesterday regardless of the theme. if you don't, that's pretty bad.

**Comment by vladmandic** [comment] 2023-06-13 12:38
375 hints were correctly set and type 2 means that it should show as box in the top right corner on the screen which appears on mouse over.

**Comment by mariodian** [comment] 2023-06-13 13:00
It can't be visible because `.tooltip-show` doesn't rewrite `display: none` defined in `.tooltip`:

````css
.tooltip {
    display: none;
}
.tooltip-show {
    opacity: 1;
}
````

Since it's hidden with `display: none`, it needs to be displayed with `display: block` (or you can hide it with `opacity: 0` instead)

**Comment by mariodian** [comment] 2023-06-13 13:19
After a bit of investigating, canvas-zoom plugin for whatever reason sets `display: none` for `.tooltip` which messes with your code.

**Comment by vladmandic** [comment] 2023-06-13 13:40
amazing...why? :(

**Comment by mariodian** [comment] 2023-06-13 13:51
They do have their own tooltip but its class is `.tooltip--extension` anyway so perhaps it's an old code that they don't use anymore?

<img width="524" alt="Screenshot 2023-06-13 at 9 46 24 PM" src="https://github.com/vladmandic/automatic/assets/3636406/e4f7e0e7-a764-4164-9366-9c720de2846f">

Do you want me to open an issue with them or would you do it?

**Comment by vladmandic** [comment] 2023-06-13 14:08
you can do it - why not?

**Comment by mariodian** [comment] 2023-06-14 01:15
The issue is fixed now!

**Comment by afbagwell** [comment] 2023-06-14 18:29
I'm running into an issue with the tooltip box being invisible and blocking clicking whatever button it's hovering over. Attached some pictures to show. This has been aggravating because I often am not completely scrolled to the top of my browser, and I click the generate button and when my attention comes back I realize nothing happened.

![tooltip01](https://github.com/vladmandic/automatic/assets/1495201/c05d2059-1acb-4c9e-a3a9-6436cfd2f473)
![tooltip02](https://github.com/vladmandic/automatic/assets/1495201/ab72725e-1ef8-406f-86dc-6e4078977d59)
![tooltip03](https://github.com/vladmandic/automatic/assets/1495201/3f6b53d5-ebd6-4efe-a10a-2ccb03f8745f)

**Comment by vladmandic** [comment] 2023-06-14 18:32
You can change tooltip display mode in settings.

**Comment by vladmandic** [comment] 2023-08-21 08:59
further work is tracked under ui redesign, individual improvements in this area are not expected otherwise.

**Closed by vladmandic** 2023-08-21 08:59 UTC
Labels: enhancement, ui
