### ISSUE TITLE
[Issue]: Interrogate CLIP button doesn't work

### ISSUE THREAD

**Issue by acorderob** [vladmandic/automatic#406] opened 2023-04-23 10:37 UTC
### Issue Description

The interrogate CLIP button in the img2img tab results in an error. The deepbooru button does work.

Console shows this:

```
load checkpoint from models\BLIP\model_base_caption_capfilt_large.pth
interrogate: AttributeError
┌────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────┐
│ D:\Other Applications\stable-diffusion-webui-vladmandic\modules\interrogate.py:193 in interrogate                                              │
│                                                                                                                                                │
│   192 │   │   │                                                                                                                                │
│ > 193 │   │   │   self.load()                                                                                                                  │
│   194                                                                                                                                          │
│                                                                                                                                                │
│ D:\Other Applications\stable-diffusion-webui-vladmandic\modules\interrogate.py:127 in load                                                     │
│                                                                                                                                                │
│   126 │   │   if self.clip_model is None:                                                                                                      │
│ > 127 │   │   │   self.clip_model, self.clip_preprocess = self.load_clip_model()                                                               │
│   128 │   │   │   if not shared.cmd_opts.no_half and not self.running_on_cpu:                                                                  │
│                                                                                                                                                │
│ D:\Other Applications\stable-diffusion-webui-vladmandic\modules\interrogate.py:111 in load_clip_model                                          │
│                                                                                                                                                │
│   110 │   │   else:                                                                                                                            │
│ > 111 │   │   │   model, preprocess = clip.load(clip_model_name, download_root=shared.opts.cli                                                 │
│   112                                                                                                                                          │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: module 'clip' has no attribute 'load'
```

### Version Platform Description

commit: 4cb46d5400b04491ae9e70d992ca0019d48942a9
Windows 10
Chrome

**Comment by vladmandic** [comment] 2023-04-23 11:52
duplicate of #150, answer already provided, please search for issues before creating new one.

**Closed** 2023-04-23 11:53 UTC
