### ISSUE TITLE
[Extension]: AttributeError in p.init_images.clear() when using Tiled Diffusion

### ISSUE THREAD

**Issue by abetteridea** [vladmandic/automatic#1988] opened 2023-08-11 19:00 UTC
### Issue Description

This is an issue with a built-in extension, so I hope I am not wrong reporting it as a core app one.

This happens every time when Tiled Diffusion is used, although it doesn't seem to affect the upscaling process itself (just the canvas view). Any Tiled Diffusion settings result in the log output below at the end of the upscaling process.

### Version Platform Description

14:54:54-929631 INFO     Starting SD.Next
14:54:54-929631 INFO     Python 3.10.6 on Windows
14:54:54-960883 INFO     Version: 9fc70cb3 Fri Aug 11 08:14:14 2023 +0200
14:54:55-227676 INFO     nVidia CUDA toolkit detected
14:54:55-337444 WARNING  Modified files: ['modules/lora', 'modules/lycoris']
14:54:55-375201 INFO     Disabled extensions: ['stable-diffusion-webui-images-browser', 'sd-webui-agent-scheduler',
                         'sd-dynamic-thresholding', 'a1111-sd-webui-lycoris', 'stable-diffusion-webui-rembg']
14:54:55-375201 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-extension-system-info',
                         'sd-webui-controlnet', 'SwinIR']
14:54:55-375201 INFO     Enabled extensions: ['sd-webui-lora-block-weight', 'sd-webui-neutral-prompt',
                         'stable-diffusion-webui-model-toolkit', 'ultimate-upscale-for-automatic1111']

### Relevant log output

```shell
14:52:38-977552 ERROR    Running script postprocess:
                         C:\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\
                         tilediffusion.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\automatic\modules\scripts.py:463 in postprocess                                                      │
│                                                                                                                      │
│   462 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 463 │   │   │   │   script.postprocess(p, processed, *args)                                                        │
│   464 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      │
│                                                                                                                      │
│ C:\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:394  │
│ in postprocess                                                                                                       │
│                                                                                                                      │
│   393 │   │   if hasattr(p, 'init_images') and hasattr(p, 'init_images_original_md'):                                │
│ ❱ 394 │   │   │   p.init_images.clear()       # NOTE: do NOT change the list object, compatibl                       │
│   395 │   │   │   p.init_images.extend(p.init_images_original_md)                                                    │
│                                                                                                                      │
│ C:\automatic\venv\lib\site-packages\PIL\Image.py:528 in __getattr__                                     │
│                                                                                                                      │
│    527 │   │   │   return self._category                                                                             │
│ ❱  528 │   │   raise AttributeError(name)                                                                            │
│    529                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: clear
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment] 2023-08-11 19:03
Issue is valid. Still please convert to extension report (don't have to refile), regardless if it's a built in extension or not.

**Comment by abetteridea** [comment] 2023-08-11 19:09
> Issue is valid. Still please convert to extension report (don't have to refile), regardless if it's a built in extension or not.

Sure! What's the best way to do it without refiling? I am fairly new to GitHub! Can I add the 'extension' label to the title somehow?

**Comment by vladmandic** [comment] 2023-08-12 07:35
i cannot reproduce this issue on the latest version.
please upgrade (yesterday there was a massive update) and provide detailed reproduction steps

**Comment by lellotrek** [comment] 2023-08-12 15:01
Hi, just to let you know i had the same issue before and still have, even with the new upgrade, thanks.

**Comment by abetteridea** [comment] 2023-08-12 17:19
Same here, the issue is still present. Using the latest version

`Version: 69eaf4c6 Sat Aug 12 08:32:19 2023 +0000`

**Comment by vladmandic** [comment] 2023-08-12 18:07
Like I said - I cannot reproduce, so please provide detailed and exact steps. Otherwise posting "me too" really doesn't lead to a solution.

**Comment by lellotrek** [comment] 2023-08-12 18:36
Sure, in my case happen when i try the tiling upscale in the "from image" section. 

Drop the image, open Controlnet and setting Enable-control type Tile - Controlnet is more important and the other setting default.

Tiled diffusion: Enable - Method MultiDiffusion - Upscaler and scale factor 2. The other setting to default.

Tiled vae: Enable and all the settings to default.

At the end of the process i have this error in the log file.

**Comment by abetteridea** [comment] 2023-08-12 18:38
Thank you for looking into this @vladmandic!

@lellotrek could you post your version platform info? Maybe disabling 'stable-diffusion-webui-images-browser' has something to do with it, for instance?

I have an even simpler step-by-step for the issue:
1) Start Server
2) Go to _From Image_ tab
3) Drag an image into the _Image_ tab
4) Check "Enable Tiled Diffusion"

The issue is there in the terminal window even with every other setting intact:

![image](https://github.com/vladmandic/automatic/assets/67851516/a6d3f030-a4b8-4cae-af31-932f99af82a7)

**Comment by vladmandic** [comment] 2023-08-13 08:22
should be fixed now.

**Closed by vladmandic** 2023-08-13 08:22 UTC
Labels: question, extension
