### ISSUE TITLE
[Issue]: img2img prompt bleeding over to text2img

### ISSUE THREAD

**Issue by josh5671** [vladmandic/automatic#1931] opened 2023-08-04 09:20 UTC
### Issue Description

`txt2img has a prompt, img2img a different prompt (with lora's i might add)

after using both and going back to text2img, parts (prompts) of the img2img prompt are showing in the results of text2img
like its bleeding over somehow
`

*
referring to the original discussion: https://github.com/vladmandic/automatic/discussions/1856
as author of that discussion didnt post anything on 'issues'. i try to forward it here. so SDNext contributor albe to keep track.

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment] 2023-08-04 13:21
can you check if there is "bleed" effect if loras are not used? those are two quite different things as it would imply that lora un-apply is at fault, not prompt itself.

**Comment by josh5671** [comment] 2023-08-04 14:18
> can you check if there is "bleed" effect if loras are not used? those are two quite different things as it would imply that lora un-apply is at fault, not prompt itself.

update to latest version and test again. the issue magically gone even with lora applied.
the problem should be still there last week (while you reply in discussion)
i keep the issue open for a day or two and run some T2I-I2I upscale back and forth to test it more.


mind to take a look another issue? this is mutliduffusion problem or ...?
https://github.com/vladmandic/automatic/issues/1855

**Comment by vladmandic** [comment] 2023-08-04 15:12
original lora does have issues unwinding weights, especially if you change number of loras, not just one on/off.
i personally prefer to enable lyco handler for all lora types and disable original lora as its works much more reliably that way.

**Comment by josh5671** [comment] 2023-08-04 18:01
> original lora does have issues unwinding weights, especially if you change number of loras, not just one on/off. i personally prefer to enable lyco handler for all lora types and disable original lora as its works much more reliably that way.

yet trying that.
but for that enable lyco handler. it cant detect lora anymore, am i doing anything wrong?

**Comment by vladmandic** [comment] 2023-08-04 18:14
Enable lyco and disable lora - both checkboxes should be used together. Then restart server and lyco should look for models in lora folder (not lyco folder as it does normally).

**Comment by josh5671** [comment] 2023-08-05 02:29
> Enable lyco and disable lora - both checkboxes should be used together. Then restart server and lyco should look for models in lora folder (not lyco folder as it does normally).
double check both setting ticked (if correct)

![image](https://github.com/vladmandic/automatic/assets/9864414/3c810b90-f733-4601-ac0e-910679a8fa95)


`10:23:06-084759 WARNING  Triggered lyco-patch-lora, will take lora_dir and <lora> format.`
and only lyco showup. not a single lora inside.
![image](https://github.com/vladmandic/automatic/assets/9864414/3b1ef1b9-81c1-40eb-b99f-2bbbd99289fb)


*i definately make mistake somewhere.

**Comment by vladmandic** [comment] 2023-08-05 05:09
There is an open issue for Loras disappearing from EN, but I could never reproduce, so didn't move forward much.

**Comment by josh5671** [comment] 2023-08-05 06:34
> There is an open issue for Loras disappearing from EN, but I could never reproduce, so didn't move forward much.
for me, lora disappear problem didnt exist when using normal lora handle.. it only appear after switch to lycoris handle.

**Comment by vladmandic** [comment] 2023-08-05 06:43
i understand that, i still cant reproduce, so if you can shed some light on that, i'd love to fix that.

**Comment by josh5671** [comment] 2023-08-05 06:52
> i understand that, i still cant reproduce, so if you can shed some light on that, i'd love to fix that.

i will try to dig. see how it goes. 
as in debug mode CMD didnt show up any error/warning...i don think able to do much unless there others people with similiar issue has error in CMD

**Comment by vladmandic** [comment] 2023-08-11 05:39
extra-network issue is tracked separately, is there any update here on promt bleeding issue based on the suggestion from last week?

**Comment by vladmandic** [comment] 2023-08-13 09:33
closing as no update regarding bleed issue since suggestions were provided last week - if there is new information provided, will reopen.

**Closed by vladmandic** 2023-08-13 09:33 UTC
