### ISSUE TITLE
[Issue]: RuntimeError: The size of tensor a (9) must match the size of tensor b (4) at non-singleton dimension 1

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#948] opened 2023-05-14 17:27 UTC
### Issue Description

I try to use ControlNet v1.1.166 -> Reference_only and got this error.
I work on WLS 2.0 on windows 10 pro

**This is the seetings:**
Launching launch.py...
06:01:59-475977 INFO     Starting SD.Next
06:01:59-479163 INFO     Python 3.10.10 on Linux
06:01:59-496359 INFO     Version: c46f0dbd Sat May 13 12:55:50 2023 -0400
06:02:00-105227 INFO     Latest published version: 926b8666cdfca5f7ee3bbb3fb216b5eee5326d22 2023-05-13T20:42:01Z
06:02:00-106175 INFO     Setting environment tuning
06:02:00-108411 INFO     nVidia CUDA toolkit detected
06:02:01-446329 INFO     Torch 1.13.1+cu117
06:02:01-657281 INFO     Torch backend: nVidia CUDA 11.7 cuDNN 8500
06:02:01-702330 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82
06:02:24-186216 INFO     Installing package: astunparse
06:02:26-024866 INFO     Installing package: bitsandbytes
06:02:29-340888 INFO     Installing package: easydev
06:02:32-136175 INFO     Installing package: extcolors
06:02:34-309180 INFO     Installing package: filetype
06:02:36-296761 INFO     Installing package: voluptuous
06:02:38-183515 WARNING  Package wrong version: requests 2.25.1 required 2.30.0
06:02:38-184354 INFO     Installing package: requests==2.30.0
06:02:40-103900 WARNING  Package wrong version: accelerate 0.12.0 required 0.18.0
06:02:40-104685 INFO     Installing package: accelerate==0.18.0
06:02:42-072759 INFO     Installing package: diffusers==0.16.1
06:02:44-358677 WARNING  Package wrong version: gradio 3.23.0 required 3.29.0
06:02:44-359465 INFO     Installing package: gradio==3.29.0
06:02:47-162604 WARNING  Package wrong version: pandas 2.0.1 required 1.5.3
06:02:47-163440 INFO     Installing package: pandas==1.5.3
06:02:51-525638 WARNING  Package wrong version: protobuf 3.20.0 required 3.20.3
06:02:51-526494 INFO     Installing package: protobuf==3.20.3
06:02:53-632885 WARNING  Package wrong version: transformers 4.25.1 required 4.26.1
06:02:53-633682 INFO     Installing package: transformers==4.26.1
06:02:58-126765 WARNING  Package wrong version: timm 0.6.7 required 0.6.13
06:02:58-127570 INFO     Installing package: timm==0.6.13
06:03:00-376707 INFO     Installing package: tomesd==0.1.2
06:03:02-249161 INFO     Installing package: onnxruntime==1.14.0
06:03:04-403736 INFO     Running setup
06:03:04-404494 INFO     Installing packages
06:03:04-405043 INFO     Installing package:
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
06:03:10-052268 INFO     Installing repositories
06:03:10-077166 INFO     Installing submodules
06:03:10-279460 INFO     Updating submodules
06:03:40-148778 ERROR    Error running extension installer: /home/shmuel/vlad/extensions/animator_extension/install.py
06:03:40-150066 INFO     Extensions enabled: ['sd-webui-model-converter', 'stable-diffusion-webui-rembg', 'LDSR',
                         'Lora', 'stable-diffusion-webui-images-browser', 'sd-webui-controlnet',
                         'a1111-sd-webui-lycoris', 'SwinIR', 'clip-interrogator-ext', 'sd-extension-system-info',
                         'seed_travel', 'sd-extension-steps-animation', 'sd-extension-aesthetic-scorer',
                         'prompt-bracket-checker', 'ScuNET', 'multidiffusion-upscaler-for-automatic1111',
                         'sd-dynamic-thresholding', 'SD-CN-Animation', 'infinite-zoom-automatic1111-webui',
                         'animator_extension']
06:03:40-151611 INFO     Updating Wiki
06:03:40-786422 WARNING  Setup complete with errors (1)
06:03:40-787241 WARNING  See log file for more details: setup.log
06:03:40-789977 INFO     Running extension preloading
06:03:40-790720 INFO     Server arguments: []
06:03:44-556133 INFO     Unloading xFormers
06:03:45-356016 INFO     Libraries loaded
Creating folder: /home/shmuel/vlad/automatic/models/VAE
Creating folder: /home/shmuel/vlad/automatic/models/embeddings
06:03:45-386952 INFO     Available models: /home/shmuel/stable-diffusion-webui/models/Stable-diffusion 11
ControlNet v1.1.166
ControlNet v1.1.166
Image Browser: ImageReward is not installed, cannot be used.
06:03:58-963108 INFO     Libraries loaded
06:03:59-452866 INFO     Loading UI theme: gradio/default
Running on local URL:  http://127.0.0.1:7860

**This is the erroe:**

                                             ... 23 frames hidden ...                                               │
│                                                                                                                      │
│ /home/shmuel/vlad/extensions-builtin/sd-webui-controlnet/scripts/hook.py:402 in forward_webui                        │
│                                                                                                                      │
│   401 │   │   │   │                                                                                                  │
│ ❱ 402 │   │   │   │   return forward(*args, **kwargs)                                                                │
│   403 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│ /home/shmuel/vlad/extensions-builtin/sd-webui-controlnet/scripts/hook.py:356 in forward                              │
│                                                                                                                      │
│   355 │   │   │   │   │   # We should use sin/cos to make sure that the std of weighted matrix                       │
│ ❱ 356 │   │   │   │   │   ref_uncond_xt = x * torch.sin(time_weight) + ref_cond_xt.clone() * t                       │
│   357 │   │   │   │   │   # print('Balanced - Using time-balanced cfg for reference.')                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (9) must match the size of tensor b (4) at non-singleton dimension 1

### Version Platform Description

Device name	DESKTOP-89OI1TC
Processor	AMD Ryzen 7 6800H with Radeon Graphics            3.20 GHz
Installed RAM	32.0 GB (31.2 GB usable)
Device ID	57F773B6-2052-4400-9EEE-5DA99ADC9758
Product ID	00331-20350-00000-AA537
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro
Version	22H2
Installed on	‎27/‎06/‎2020
OS build	19045.2913
Experience	Windows Feature Experience Pack 1000.19041.1000.0

I use Chrome browser

**Comment by vladmandic** [comment] 2023-05-14 17:34
i just tried and cannot reproduce - worked fine.
let go through step by step what do you do to get into this error state?

**Comment by ShmuelRonen** [comment] 2023-05-14 18:21
I restart everyting and now it works.
But... I try to make inage in 1:1 840x840 and get an error:
I have Nvidia RTX 3090

CUDA out of memory. Tried to allocate 14.49 GiB (GPU 0; 24.00 GiB total capacity; 9.69 GiB already allocated; 12.19 GiB free; 9.78 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Time taken: 17.81s | GPU active 17341 MB reserved 23360 MB | System peak 24576 MB total 24576 MB

_______
It going right only under 720x720 ??????


________

 /home/shmuel/vlad/modules/txt2img.py:53 in txt2img                                                                   │
│                                                                                                                      │
│   52 │   if processed is None:                                                                                       │
│ ❱ 53 │   │   processed = process_images(p)                                                                           │
│   54 │   p.close()                                                                                                   │
│                                                                                                                      │
│                                               ... 34 frames hidden ...                                               │
│                                                                                                                      │
│ /home/shmuel/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1194 in _call_impl                       │
│                                                                                                                      │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                                             │
│   1195 │   │   # Do not call functions when jit is used                                                              │
│                                                                                                                      │
│ /home/shmuel/vlad/modules/hypernetworks/hypernetwork.py:414 in attention_CrossAttention_forward                      │
│                                                                                                                      │
│   413 │   # attention, what we cannot get enough of                                                                  │
│ ❱ 414 │   attn = sim.softmax(dim=-1)                                                                                 │
│   415                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 14.49 GiB (GPU 0; 24.00 GiB total capacity; 9.69 GiB already
allocated; 12.19 GiB free; 9.78 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by vladmandic** [comment] 2023-05-14 18:33
Is that OOM with ControlNet or just regular generate?

**Comment by ShmuelRonen** [comment] 2023-05-14 18:35
In 760x760 it try to make it but the computer stuck
![Screenshot 2023-05-14 213102](https://github.com/vladmandic/automatic/assets/80190186/7adc9d9a-c55b-4503-8b99-27029c57b0c7)

**Comment by vladmandic** [comment] 2023-05-14 18:49
I cannot control how much memory controlnet uses :(

**Comment by ShmuelRonen** [comment] 2023-05-14 18:51
In your computer it's work fine in 840x840?
Mabe I need --xformers?

**Comment by vladmandic** [comment] 2023-05-14 18:55
I didn't try, I'll try later.

**Comment by vladmandic** [comment] 2023-05-15 00:33
i just tried txtg2img + controlnet (reference only) with 1024x1024 using sdp as cross-attention and no issues. my vram peak usage was ~4.5gb allocated.

but...you're running 
> 06:02:01-446329 INFO Torch 1.13.1+cu117
> 06:02:01-657281 INFO Torch backend: nVidia CUDA 11.7 cuDNN 8500
> 06:02:01-702330 INFO Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82

why? how? sure, you can run torch 1.13 with this repo, but all about it is optimized for torch 2.0 and it installs torch 2.0 by default unless you installed torch 1.13 manually before (either as global package or did you copy old venv from a1111?)
if you're using global packages, i suggest to uninstall them and rely on venv instead.
if you have torch 1.13 in venv, i suggest to delete that venv completly.

anyhow, we can continue chatting here, but closing the issue as original problem is resolved.

**Closed by vladmandic** 2023-05-15 00:33 UTC
Labels: cannot reproduce
