### ISSUE TITLE
[Issue]: NotImplementedError: 

### ISSUE THREAD

**Issue by iDeNoh** [vladmandic/automatic#216] opened 2023-04-18 19:49 UTC
### Issue Description

As of yesterday afternoon (I'm unsure which commit caused it, I haven't had a chance to test until just now) whenever I attempt to generate an image I receive this error almost immediately:

```
Initializing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:02
gradio call: NotImplementedError
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/oem/Desktop/automatic/modules/call_queue.py:61 in f                    │
│                                                                              │
│    60 │   │   │   │   pr.enable()                                            │
│ ❱  61 │   │   │   res = list(func(*args, **kwargs))                          │
│    62 │   │   │   if shared.cmd_opts.profile:                                │
│                                                                              │
│ /home/oem/Desktop/automatic/modules/call_queue.py:39 in f                    │
│                                                                              │
│    38 │   │   │   try:                                                       │
│ ❱  39 │   │   │   │   res = func(*args, **kwargs)                            │
│    40 │   │   │   finally:                                                   │
│                                                                              │
│                           ... 31 frames hidden ...                           │
│                                                                              │
│ /home/oem/Desktop/automatic/venv/lib/python3.10/site-packages/xformers/ops/f │
│ mha/dispatch.py:98 in _dispatch_fw                                           │
│                                                                              │
│    97 │   │   priority_list_ops.insert(0, triton.FwOp)                       │
│ ❱  98 │   return _run_priority_list(                                         │
│    99 │   │   "memory_efficient_attention_forward", priority_list_ops, inp   │
│                                                                              │
│ /home/oem/Desktop/automatic/venv/lib/python3.10/site-packages/xformers/ops/f │
│ mha/dispatch.py:73 in _run_priority_list                                     │
│                                                                              │
│    72 │   │   msg += "\n" + _format_not_supported_reasons(op, not_supported) │
│ ❱  73 │   raise NotImplementedError(msg)                                     │
│    74                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
NotImplementedError: No operator found for `memory_efficient_attention_forward` 
with inputs:
     query       : shape=(1, 4096, 1, 512) (torch.float16)
     key         : shape=(1, 4096, 1, 512) (torch.float16)
     value       : shape=(1, 4096, 1, 512) (torch.float16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 128
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 128
    requires A100 GPU
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float16 (supported: {torch.float32})
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 512

``` 

So far I've tried removing my venv and having it re-generate, I've forced an update to the latest version of PyTorch for ROCM, I'm at a bit of a loss as to where to go from here. In addition to the errors above I'm also receiving an error during startup after the server arguments are passed.

```
2023-04-18 14:40:07,389 | WARNING | /home/oem/Desktop/automatic/venv/lib/python3.10/site-packages/fairscale/utils/version.py | Pytorch pre-release version 2.1.0.dev20230418+rocm5.4.2 - assuming intent to test it
2023-04-18 14:40:08,747 | WARNING | /home/oem/Desktop/automatic/venv/lib/python3.10/site-packages/xformers/_cpp_lib.py | WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.0+cu118 with CUDA 1108 (you have 2.1.0.dev20230418+rocm5.4.2)
    Python  3.10.10 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

```
[setup.log](https://github.com/vladmandic/automatic/files/11265805/setup.log)

### Version Platform Description

Version: 2b1b75dd Tue Apr 18 14:56:19 2023 -0400 
Python: 3.10.6
Linux Mint 21.1 Cinnamon 5.6.8
Kernel: 5.15.0-67-Generic
Browser: Firefox 111.0.1

CPU: AMD Ryzen 7 1700

Environment Tuning                             
Torch 2.1.0.dev20230418+rocm5.4.2                      
Torch backend: AMD ROCm HIP 5.4.22803-474e8620         
GPU: AMD Radeon RX 6700 XT VRAM 12272

**Comment by vladmandic** [comment] 2023-04-18 19:54
duplicate of #194
there's a workaround there, but still looking for a full fix. i don't have amd system, so its slow.

**Closed by vladmandic** 2023-04-18 19:54 UTC
