### ISSUE TITLE
[Extension]: stable-diffusion-webui-composable-lora is not compatible

### ISSUE THREAD

**Issue by NiskoDT** [vladmandic/automatic#2022] opened 2023-08-17 12:21 UTC
### Issue Description

So this error has been going for like some weeks now as far as I know, is that I am getting an error with the [a1111-sd-webui-lycoris](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git) extension everytime it is enabled. Before it gives an error just like #1726 , but now it gives `TypeError: 'NoneType' object is not callable`

Here is the prompt I am trying to generate
`2023-08-17 18:59:44,504 | sd | ERROR | call_queue | Arguments: args=('task(u1zcj4tu0xe9zi0)', '<lora:ChromaticAberration:0.43> <lora:add_detail:0.27> ((best quality)), ((masterpiece)), (detailed), absurdres, HDR, mountains, trees in the background, 1girl, shirt, two-tone jacket, coat, brown bodysuit, cloth, suit, plaid skirt, puffy sleeves, blue coat, grey jacket, military jacket, red cloak, layered clothes, sleeveless turtleneck, hooded jacket, letterman jacket, brown coat, black leotard, torn coat, white jacket', 'bad-artist, bad-hands-5, bad-image-v2-39000, bad_pictures, bad_prompt_version2, bad_quality, easynegative, negative_hand-neg, ng_deepnegative_v1_75t, verybadimagenegative_v1.3', ['Default_Negative (sfw)', 'Skin Enhancer (clean)']`

Here is the full traceback
```
╭─────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮
│ D:\AI_generation_stuff\vladmandic\modules\call_queue.py:34 in f                                                 │
│                                                                                                                 │
│    33 │   │   │   try:                                                                                          │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                               │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                     │
│                                                                                                                 │
│ D:\AI_generation_stuff\vladmandic\modules\txt2img.py:65 in txt2img                                              │
│                                                                                                                 │
│   64 │   if processed is None:                                                                                  │
│ ❱ 65 │   │   processed = processing.process_images(p)                                                           │
│   66 │   p.close()                                                                                              │
│                                                                                                                 │
│ D:\AI_generation_stuff\vladmandic\modules\processing.py:564 in process_images                                   │
│                                                                                                                 │
│    563 │   │   else:                                                                                            │
│ ❱  564 │   │   │   res = process_images_inner(p)                                                                │
│    565 │   finally:                                                                                             │
│                                                                                                                 │
│ D:\AI_generation_stuff\vladmandic\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py:42 in          │
│ processing_process_images_hijack                                                                                │
│                                                                                                                 │
│    41 │   │   │   # we are not in batch mode, fallback to original function                                     │
│ ❱  42 │   │   │   return getattr(processing, '__controlnet_original_process_images_inner')(p,                   │
│    43                                                                                                           │
│                                                                                                                 │
│ D:\AI_generation_stuff\vladmandic\modules\processing.py:680 in process_images_inner                             │
│                                                                                                                 │
│    679 │   │   │   if shared.backend == shared.Backend.ORIGINAL:                                                │
│ ❱  680 │   │   │   │   uc = get_conds_with_caching(prompt_parser.get_learned_conditioning, p.ne                 │
│    681 │   │   │   │   c = get_conds_with_caching(prompt_parser.get_multicond_learned_condition                 │
│                                                                                                                 │
│                                            ... 15 frames hidden ...                                             │
│                                                                                                                 │
│ C:\Users\Public\miniconda3\envs\vlad\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl            │
│                                                                                                                 │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                  │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                         │
│   1502 │   │   # Do not call functions when jit is used                                                         │
│                                                                                                                 │
│ C:\Users\Public\miniconda3\envs\vlad\lib\site-packages\transformers\models\clip\modeling_clip.py:274 in forward │
│                                                                                                                 │
│    273 │   │   # get query proj                                                                                 │
│ ❱  274 │   │   query_states = self.q_proj(hidden_states) * self.scale                                           │
│    275 │   │   key_states = self._shape(self.k_proj(hidden_states), -1, bsz)                                    │
│                                                                                                                 │
│ C:\Users\Public\miniconda3\envs\vlad\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl            │
│                                                                                                                 │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                  │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                         │
│   1502 │   │   # Do not call functions when jit is used                                                         │
│                                                                                                                 │
│ D:\AI_generation_stuff\vladmandic\extensions\stable-diffusion-webui-composable-lora\composable_lora.py:451 in   │
│ lora_Linear_forward                                                                                             │
│                                                                                                                 │
│   450 │   │   │   │   │   return result                                                                         │
│ ❱ 451 │   │   │   return lycoris.lyco_Linear_forward(self, input)                                               │
│   452 │   if lora_ext.is_sd_1_5:                                                                                │
│                                                                                                                 │
│ D:\AI_generation_stuff\vladmandic\extensions-builtin\a1111-sd-webui-lycoris\lycoris.py:741 in                   │
│ lyco_Linear_forward                                                                                             │
│                                                                                                                 │
│   740 │                                                                                                         │
│ ❱ 741 │   return torch.nn.Linear_forward_before_lyco(self, input)                                               │
│   742                                                                                                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not callable
```

And yes, I already tried to disable the [stable-diffusion-webui-composable-lora](https://github.com/a2569875/stable-diffusion-webui-composable-lora.git) extension, and still, it gives this error. Now I would just not use LyCORIS at all but then I have a LyCORIS model that I might someday use, and I don't really want to enable then disable one or more extension(s), which is very tidious because of the server restart sequence.

### Version Platform Description

Browser: Microsoft Edge

- From the System Info Tab:

Platform:
arch: AMD64
cpu: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.12
2.0.1+cu118 Autocast  half
device: NVIDIA GeForce GTX 1050 Ti (1) (compute_37) (6, 1)
cuda: 11.8
cudnn: 8700
driver: 536.99

- Flags: 
```
2023-08-11 18:45:11,254 | sd | INFO | launch | Server arguments: ['--use-cuda', '--upgrade', '--allow-code', '--listen', '--port', '7760', '--tls-selfsign', '--no-hashing', '--insecure', '--debug', '--ignore', '--no-download']
```

SDNext.log snippet
```
2023-08-11 18:40:34,032 | sd | INFO | launch | Starting SD.Next
2023-08-11 18:40:34,077 | sd | INFO | installer | Python 3.10.12 on Windows
2023-08-11 18:40:34,156 | sd | INFO | installer | Version: 9fc70cb3 Fri Aug 11 08:14:14 2023 +0200
2023-08-11 18:40:46,273 | sd | DEBUG | installer | Setting environment tuning
2023-08-11 18:40:46,276 | sd | DEBUG | installer | Torch overrides: cuda=True rocm=False ipex=False diml=False
2023-08-11 18:40:46,278 | sd | DEBUG | installer | Torch allowed: cuda=True rocm=False ipex=False diml=False
2023-08-11 18:40:46,285 | sd | INFO | installer | nVidia CUDA toolkit detected

```

### URL link of the extension

https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment] 2023-08-17 18:08
you said you tried to disable composable lora, but in the traceback you've posted its clearly enabled and its the cause of the problem.

> │ D:\AI_generation_stuff\vladmandic\extensions\stable-diffusion-webui-composable-lora\composable_lora.py:451 in   │

**Comment by NiskoDT** [comment] 2023-08-17 23:27
Oh right that part where I posted is indeed enabled. But when the CompLora extension is enabled alongside the lycoris one, it will summon errors most of the time. 

Last time it worked was yesterday, then doing a server restart or relaunching the webui will always makes it stop working again. 

However, when I disable one of them, the other one works fine. For example, if I disable CompLora, Lycoris works fine, and vice versa.

But on Automatic1111, I don’t have this problem. Both extensions work well together there. So I think there is something wrong with SDNext

**Comment by brknsoul** [comment] 2023-08-18 03:19
SD.Next tends to use the LyCORIS module to handle loras. You can disable/adjust this behaviour in Settings > Extra Networks.

**Comment by vladmandic** [comment] 2023-08-18 05:27
composable lora has several known issues (documented in earlier issues). 
it has been abandoned by the author and now replaced by a fork - i need to take a look at that fork to see if compatibility is possible.

**Comment by NiskoDT** [comment] 2023-08-18 07:42
> SD.Next tends to use the LyCORIS module to handle loras. You can disable/adjust this behaviour in Settings > Extra Networks.

Hmm theres 3 options, yes? Is there an explanantion for the differences between them?

**Comment by NiskoDT** [comment] 2023-08-20 23:57
This extension caught my attention. The [LoRa Control - Dynamic Weights Controller](https://github.com/cheald/sd-webui-loractl). 

The repo mentioned and linked that the [Composable LoRA](https://github.com/a2569875/stable-diffusion-webui-composable-lora) isn't supported on "newer versions"

Quote:
"The idea was inspired by the step control in composable lora, which unfortunately doesn't work with newer versions of the webui."

[Then below that it also says:](https://github.com/cheald/sd-webui-loractl#installation)
"⚠️ This extension only works with the Automatic1111 1.5RC or later. It is directly tied to the new network handling architecture. It does not currently work with SD.Next, and will not unless SD.Next adopts the 1.5 extra network architecture."

So I was thinking maybe that because SD.Next haven't use that "1.5 extra network architecture", the Composable LoRA isn't working at the first place. That's just my conclusion, of course it's possible that the extension is just not compatible in the first place.

**Comment by vladmandic** [comment] 2023-08-21 06:09
porting of that code is on my list regardless of composable lora - i guess we'll see if thats resolves it or further work is needed.

**Comment by vladmandic** [comment] 2023-10-11 23:55
addressed in dev branch, will be merged to master soon.

**Closed by vladmandic** 2023-10-11 23:55 UTC
Labels: extension
