### ISSUE TITLE
[Issue]: Can no longer reproduce my images after I updated today

### ISSUE THREAD

**Issue by oshimoto** [vladmandic/automatic#1056] opened 2023-05-18 15:23 UTC
### Issue Description

Hi!

After I ran the upgrade.bat today (18.05.2323) I can no longer reproduce any images that I made yesterday.
The last time I ran upgrade.bat was either 16.05.2023 in the morning or yesterday (17.05.2023) in the morning.

The image quality also seems to be worse now on the images I attempted to reproduce.
It was my guess it had something to do with the prompting parsers since I assume they were introduced yesterday, but I tried all 4 of them and none of them managed to reproduce my image.

I haven't touched any of the settings neither yesterday nor today before I tried switching the promting parsers ( I didn't even know they were there :) )

Is there any way I can fix this?
Thanks in advance!

### Version Platform Description

Version: df1fae72 Thu May 18 10:17:39 2023 -0400
Windows 10
Firefox Browser

**Comment by vladmandic** [comment] 2023-05-18 15:25
i don't know what's your prompt or expected output?

**Comment by oshimoto** [comment] 2023-05-18 15:58
Here are some images and prompts. I decided to upload as .zip because github renames the image files. 
[Stable Diffusion.zip](https://github.com/vladmandic/automatic/files/11509360/Stable.Diffusion.zip)
The first one is the original(expected). the other 4 are the 4 prompting parsers I tested today.

The settings I use:
cmd parameters --medvram

other settings:
cross attention(scaled-dot-product + disable memory attention)
vae-ft-mse-840000-ema-pruned.safetensors
I am using Cuda (3070ti) autocast fp16, with use full precision for vae

By the way is there a way I can install and old version(commit?) so that I can test if I will get the same output?

**Comment by oshimoto** [comment] 2023-05-18 16:19
Thanks! I might try installing an older version to test.

**Comment by vladmandic** [comment] 2023-05-18 19:43
i didn't have time to run full test using your prompts, but just pushed an update with one near-trivial change, but that should return original prompts to what they were (it was removing empty token which is correct thing to do, but i guess i have to be compatible with old bugs)

**Comment by oshimoto** [comment] 2023-05-18 21:10
😆 
I updated to the newest commit fef4927. 
I Tested and there was indeed a very small change in image details but still nothing close to my original (expected) output from yesterday. So I guess this is not what caused the issue.

**Comment by vladmandic** [comment] 2023-05-19 00:16
i've tried fully restoring old prompt parser code and that's not it - my a1111 compatibility works properly.
there has to be some other change that impacts this, but between last-known-good and time you reported the issue, there was a massive merge from a1111 upstream. i tried to take a look at diff, but cannot spot anything quickly, this is a nightmare to track down: <https://github.com/vladmandic/automatic/compare/f4bb3b4..df1fae7>

**Comment by TheOnlyHolyMoly** [comment] 2023-05-20 11:58
I am partially struggling with the same issue, I think some kind of emphasis-guidance has changed somehow... I have tested all 4 parsers with and without attention flag, and they all deliver very nice images but majorly different from original. Subjectively I'd say the quality of my newer images comes out a lot higher and with many more fine details in the main object and less details in sourrounding parts. So I am not at all worried, I just need to keep a copy of the old-world repo to be able to reproduce some images in the old-style, going forward I am super happy about the additional degree of freedom to explore how the different parsers guide the image creation.

**Comment by vladmandic** [comment] 2023-05-20 17:18
i just pushed another update to prompt parser, you can see notes in <https://github.com/vladmandic/automatic/discussions/1005#discussioncomment-5956442>

**Comment by TheOnlyHolyMoly** [comment] 2023-05-20 18:25
appearance is now A LOT closer to the original image, still some minor deviations, the old image in comparison is a bit more sound and the tendency that the center has more "posh" and the outer areas "less" is still there... probably some border case of my prompt 

I have been following the conversation. I really do understand your philosophy not to keep all these old dependencies as they become hurdles going forward.... I am super fine with the new parser for new images and I am still trying to establish commit 22a9e701 as backup if I want to recreate some of my old-style images...

**Comment by vladmandic** [comment] 2023-05-21 13:40
@oshimoto how does it look to you?

**Comment by oshimoto** [comment] 2023-05-21 19:24
I installed the latest commit 26b05ef and retested with all 4 parsers. The differences since the first time I tested with the new parsers are very small, still nothing close to my original image. That's ok, I can just finish processing them on the old build and then upgrade to the latest version.
Just a small other concern is that in the new images with the 4 prompt parsers in all of them the colors seem off to me compared to my original image. I upload them again here so you can decide for yourself.  The first one is my original.
The second has "pale" colors compared to my original while the last two are over saturated.
I am just concerned there might be an issue and we might be loosing some quality.
Other than that it's all good. We may close this issue when you decide.

BTW before we were able to choose the prompt parser, which was the default one? Was it the full parser?

Thanks for all your help!
![~Expected Output - 2023-05-17 - 00040-253975417](https://github.com/vladmandic/automatic/assets/23189379/a6eb707a-8536-44fe-961d-91d2287fed30)

![00074-253975417-Anime Draw,to scale,1Girl,full body,taking a walk around town,pink tank top,short hair,(((blue hair))),((red eyes)),((shorts)),j](https://github.com/vladmandic/automatic/assets/23189379/1d8d169a-cd66-4207-8dc9-4e074434c877)
![00075-253975417-Anime Draw,to scale,1Girl,full body,taking a walk around town,pink tank top,short hair,(((blue hair))),((red eyes)),((shorts)),j](https://github.com/vladmandic/automatic/assets/23189379/cc159cf1-ca04-49ea-ae4f-e95a964fd884)
![00076-253975417-Anime Draw,to scale,1Girl,full body,taking a walk around town,pink tank top,short hair,(((blue hair))),((red eyes)),((shorts)),j](https://github.com/vladmandic/automatic/assets/23189379/25868358-b22b-4e18-8804-83593c4394bf)
![00077-253975417-Anime Draw,to scale,1Girl,full body,taking a walk around town,pink tank top,short hair,(((blue hair))),((red eyes)),((shorts)),j](https://github.com/vladmandic/automatic/assets/23189379/33833ba8-ce95-4c79-a7f8-9298feffd8ec)

**Comment by vladmandic** [comment] 2023-05-21 20:17
Before only one was A1111 and fixed when forced separately. 
Full is my new one. And comfy as complete alternative.

**Comment by vladmandic** [comment] 2023-05-21 21:28
regarding colors - i don't think that has anything to do with prompt parser, thats more factor of a) precision casting, b) vae, c) transformers itself.

**Comment by oshimoto** [comment] 2023-05-21 22:28
That's exactly what I mean because I am using all of the exact same settings and I can reproduce my picture perfectly on the old commit I installed, so maybe the big update has broken something related to the colors and completely unrelated to prompt parsers. I have no idea.

**Comment by vladmandic** [comment] 2023-05-21 22:35
@oshimoto yes, thats my theory as well. but will be a nightmare to track down.

**Comment by vladmandic** [comment] 2023-05-27 13:39
i'm closing this issue as i don't we can do much more here - prompt parser work is done (both new and compatibility) and the rest is up to upstream packages. if anyone has comments/thoughts/ideas, comment here and i'll reopen as needed.

**Comment by l-rutong** [comment] 2023-05-31 10:27
no need to reopen, just as a FYI.
This seems to be related to how weight is being parsed. When using prompts with no weight specified (e.g. no brackets/parentheses), it can reproduce images "same" as previous versions (such as https://github.com/vladmandic/automatic/commit/22a9e70150eed051be2b085add9f516fa0a359d3).
† "same": well, not exactly the same, but the differences were coming from sdp or xformer.

**Comment by l-rutong** [comment] 2023-05-31 14:39
@vladmandic 
Hello again, I looked into this a bit more, and it seems to me that there is actually something wrong with the prompt parser.
As we know,  () increase attention to the keyword by a factor of 1.1, (()) by a factor of 1.1*1.1=1.21, (word:1.0) should have the same effect of not having the parentheses.

In older version, this can be confirmed easily by the following grid.
![previous](https://github.com/vladmandic/automatic/assets/15318875/0ea49afb-9cd7-410b-a03c-71d2306183da)


However in recent version(d9f72b06), the result is out of control. (word:1.0) is apparently not equal to not having the parentheses.

![d9f72b06](https://github.com/vladmandic/automatic/assets/15318875/052f8d1f-061e-419c-a8cf-f2aa0139a8b8)

And there's color changes, similar to what [oshimoto](https://github.com/oshimoto) has mentioned earlier.

**Comment by vladmandic** [comment] 2023-05-31 15:16
can you share exact prompt and also which prompt parser did you use - full or a1111?
btw, in your example, all images are identical, like strength has no meaning at all?

**Comment by l-rutong** [comment] 2023-05-31 15:27
The problematic one was the full parser.

Prompt: red, sports car
Steps: 20 | Sampler: Euler a | CFG scale: 7 | Seed: 3733915219 | Size: 512x512 | Model hash: 6ce0161689 | Model: v1-5-pruned-emaonly | VAE: orangemix.vae | Clip skip: 1 | Version: d9f72b0 | Parser: Full parser

The upper one looks all identical, but if you take a closer look at the fog light, they are different. (the upper one was a1111)

**Comment by vladmandic** [comment] 2023-05-31 15:47
i'll reopen issue so i don't forget about it.

**Comment by vladmandic** [comment] 2023-06-02 16:24
i just did a full test and i don't see an issue with parser.

> prompt: red sports car
> xyz grid with prompt sr: red, [red], (red:1.0), (red), (red:1.1), ((red)), (red:1.21)

    [['red sports car', 1.0]]
    [['red', 0.9090909090909091], ['sports car', 1.0]]
    [['red sports car', 1.0]]
    [['red', 1.1], ['sports car', 1.0]]
    [['red', 1.1], ['sports car', 1.0]]
    [['red', 1.2100000000000002], ['sports car', 1.0]]
    [['red', 1.21], ['sports car', 1.0]]

**Closed by vladmandic** 2023-06-02 16:24 UTC
Labels: bug, backlog

**Comment by l-rutong** [comment] 2023-06-02 17:42
@vladmandic 
I noticed one single difference between our tests.
My prompt was "red, sports car", while yours were "red sports car", w/o the comma. Here are the differences in the result.

prompt: red, sports car
xyz grid with prompt sr: red, (red:1.0)
![image](https://github.com/vladmandic/automatic/assets/15318875/08cd8dee-0424-47d4-bc4e-298342e839b5)

prompt: red sports car
xyz grid with prompt sr: red, (red:1.0)
![image](https://github.com/vladmandic/automatic/assets/15318875/68320381-c3e9-4707-864e-d74aafb28f2b)

It appears that the comma is omitted when there are parentheses.

I hope this can be a hint, I will try to look at the code during the weekend.

**Comment by TheOnlyHolyMoly** [comment] 2023-06-02 19:58
https://github.com/vladmandic/automatic/discussions/1005 @l-rutong here is some more backstory to this

**Comment by vladmandic** [comment] 2023-06-02 23:35
yes, i reproduced this and after some thinking, i'm going to leave it as-is.

lets look at `(red:1.0), sports car`

- any tag in `()` is automatically processed as separate tag  
  [['red':1.0], [', sports car: 1.0]]
- all tags get cleaned  
  [['red':1.0], ['sports car': 1.0]]
- tags are then recombined to minimize number of tags  
  ['red sports car': 1.0]

so we loose `,` in a very specific scenario where tags before and after comma are explicit separate, but result in same strength.  

note that `red, sports car` is not a problem. and `(red:1.1), sports car` is not a problem.  
but `(red:1.1), (sports car:1.1) would also be a problem. but correct way to write that it is `(red, sports car:1.1)`!  

i'm sure there are other border-line cases as well as regex parsing is a voodoo art. 
that's why i've left compatibility mode in for anyone that really needs it. but this is not a special case i want to cater to since  there is no use-case for this, its more of finding borderline cases.
