### ISSUE TITLE
[Feature]: Diffusers do not support all LoRA types

### ISSUE THREAD

**Issue by hameerabbasi** [vladmandic/automatic#2054] opened 2023-08-22 19:19 UTC
### Issue Description

Results on SD1.5 do not match between originals and diffusers back-end. I'm using an external VAE with a model, and a LoRA. Here are two images with embedded generation information:

Original backend:
![01738-lora tennis outfit 0 7 a woman wearing](https://github.com/vladmandic/automatic/assets/2190658/7ee91527-04c8-4836-8e9b-21406a056b30)

Diffusers backend:
![01739-lora tennis outfit 0 7 a woman wearing](https://github.com/vladmandic/automatic/assets/2190658/2813e59e-a679-43e0-b057-b0975e685816)

Complete log-file (debug mode):
[sdnext.log](https://github.com/vladmandic/automatic/files/12412250/sdnext.log)

### Version Platform Description

2023-08-22 18:57:35,713 | sd | INFO | launch | Starting SD.Next
2023-08-22 18:57:35,720 | sd | INFO | installer | Python 3.10.12 on Linux
2023-08-22 18:57:35,755 | sd | INFO | installer | Version: 6a4d4ea5 Tue Aug 22 18:28:09 2023 +0000
2023-08-22 18:57:36,212 | sd | DEBUG | installer | Setting environment tuning
2023-08-22 18:57:36,217 | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
2023-08-22 18:57:36,220 | sd | DEBUG | installer | Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
2023-08-22 18:57:36,224 | sd | INFO | installer | nVidia CUDA toolkit detected

### Backend

Diffusers

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment] 2023-08-22 21:16
Can you provide a link to actual lora file so I can try to reproduce?

**Comment by hameerabbasi** [comment] 2023-08-23 04:14
Model: https://civitai.com/models/83991?modelVersionId=89262
VAE (external, placed next to model): https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.ckpt
LoRA: https://civitai.com/models/61194/tennis-outfit

**Comment by hameerabbasi** [comment] 2023-08-23 04:16
Please note that the model doesn't load in autodetect back end mode: It needs manual selection of Stable Diffusion back end to work.

**Comment by vladmandic** [comment] 2023-08-23 07:47
- model does not load in autodetect simply because default version of the model if fp32 unpruned which is massive 5.5gb which is not considered by autodetect as likely sd 1.5 model. download fp16 pruned version of the model and it works just fine.
- vae you've listed is in ckpt format and diffusers don't really like ckpt. diffusers support is limited to a) huggingface folder-style format, b) safetensors. given all the bad press about ckpt, i really don't want to expand support to include it
- lora you've listed does not appear as standard lora. yes, it may work in original backend, but lora support in diffusers is a relatively new thing and its going to take time until absultely every variation of lora is supported.  
  always check log if lora is loaded correctly, for example here its:

> Diffusers LoRA loading failed: tennis_outfit lora_te_text_model_encoder_layers_0_mlp_fc1 is not found in created LoRA modules.

**Comment by hameerabbasi** [comment] 2023-08-23 08:15
> vae you've listed is in ckpt format and diffusers don't really like ckpt. diffusers support is limited to a) huggingface folder-style format, b) safetensors. given all the bad press about ckpt, i really don't want to expand support to include it

All the points are valid except this one -- I'm using a Safetensors version of the VAE.

Perhaps the auto detection could be done based on the keys in the file rather than the filesize? So open the file, look at the keys inside and match against supported models?

Is there a tracking issue for supporting LoRAs like this one I could follow?

**Comment by vladmandic** [comment] 2023-08-23 08:21
looking at keys is only possible if i actually load a file - which means load huge file just to determine which type it is, then close it and then open it using correct model type - that would be an extreme overhead. it would be simple if authors set model information in model header as they should, but as it is, only 10% of models have metadata set, the rest is just empty.

regarding lora, not really - its spread over multiple internal and external issues.

**Comment by hameerabbasi** [comment] 2023-08-23 08:26
Thanks for the answers and the perspective! Would it be possible to pass the already opened file to diffusers?

**Comment by vladmandic** [comment] 2023-08-23 08:48
i wish it would, but no.

**Comment by vladmandic** [comment] 2023-10-08 22:01
new unified lora handler in dev handles this, will be merged to master shortly

**Closed by vladmandic** 2023-10-08 22:01 UTC
Labels: enhancement
