### ISSUE TITLE
[Issue]: Program self terminates on startup process due to unable to connecting to the internet?

### ISSUE THREAD

**Issue by yoshi244** [vladmandic/automatic#1807] opened 2023-07-23 15:58 UTC
### Issue Description

I updated to latest version as of today(da88af63 Sun Jul 23 11:01:26 2023 -0400) and suddenly it self closes/terminates itself. It was working fine with no issues yesterday and didn't self terminate on startup. I've tried changing ports, running on --safe to disable extensions on launch/start, neither seem to work. I did manage to get a screenshot of the console before it closed itself off. Even deleted the venv folder and redownloaded and reinstalled the files onto there.
![connectionissues](https://github.com/vladmandic/automatic/assets/56110192/587b306a-ac77-479b-9253-7259c82b0c88)

### Version Platform Description

Running on Windows 10 and main browser of use is Chrome but in this situation doesn't seem to matter. Even after a reboot hoping to clear up the ports, it still doesn't work.

08:46:51-046084 INFO     Starting SD.Next
08:46:51-052572 INFO     Python 3.10.11 on Windows
08:46:51-114954 INFO     Version: da88af63 Sun Jul 23 11:01:26 2023 -0400
08:46:52-130242 INFO     Latest published version: b1a8611b54dd54e8b2e0c28045901498adae8446 2023-07-23T15:02:40Z
08:46:52-137727 INFO     nVidia CUDA toolkit detected
08:46:52-321876 INFO     Disabled extensions: []
08:46:52-323873 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
08:46:52-334851 INFO     Enabled extensions: ['stable-diffusion-webui-dataset-tag-editor',
                         'stable-diffusion-webui-state']
08:46:52-338345 INFO     No changes detected: Quick launch active
08:46:52-340341 INFO     Verifying requirements
08:46:52-359305 INFO     Disabled extensions: []
08:46:52-361301 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
08:46:52-371781 INFO     Enabled extensions: ['stable-diffusion-webui-dataset-tag-editor',
                         'stable-diffusion-webui-state']
08:46:52-380764 INFO     Extension preload: 0.0s J:\automatic\extensions-builtin
08:46:52-382761 INFO     Extension preload: 0.0s J:\automatic\extensions
08:46:52-407715 INFO     Server arguments: ['--medvram', '--listen']

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment] 2023-07-23 16:05
duplicate of #1798

**Closed by vladmandic** 2023-07-23 16:05 UTC
