### ISSUE TITLE
[Issue]: Extra networks UI tweaks

### ISSUE THREAD

**Issue by Ratinod** [vladmandic/automatic#1559] opened 2023-07-02 23:34 UTC
### Issue Description

New extra networks UI have some bugs:
UI collapse (0:10 - 0:13); long names take up a lot of space; with a large number of folders it takes a very long time to scroll to preview.
~<sub><sup>you can't hide folders with only one main file (#1124)</sup></sub>~

https://github.com/vladmandic/automatic/assets/12137233/9b1f646b-acd8-4b1d-8fc3-1da3db4b8287

https://github.com/vladmandic/automatic/assets/12137233/48b97129-090a-4738-8055-6dceef727cea

Test files (put in a folder \models\hypernetworks): 
[UI_extra_networks_test_hypernetworks.zip](https://github.com/vladmandic/automatic/files/11931723/UI_extra_networks_test_hypernetworks.zip)

### Version Platform Description

commit 875d0db
Windows
Firefox

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment] 2023-07-03 00:00
do you have suggestions how to handle those? i can add max-width to foldernames, but not sure if that will make everyone happy.

**Comment by Ratinod** [comment] 2023-07-03 02:27
I agree, this is a feature request about the problem with long names. But the functional bug is still on the video.
"ui_bug.mp4" (0:10 - 0:13) 
"loooongName.mp4" (0:04 - 0:07)
UI collapse occurs when scrolling.

> do you have suggestions how to handle those? i can add max-width to foldernames, but not sure if that will make everyone happy.

I can’t think of anything better than adding a checkbox “limit the width of folder names” to the settings with a field for the value. Turned off - everything works as it is now, checkbox enabled - the size is limited to the specified value. Default condition: disabled.

**Comment by TKS4** [comment] 2023-07-03 23:36
Tbh I had to revert to a commit before this Extra Networks rehaul. There's just so much jank I can't make sense of any of it. One of the problems I faced was there seemed to be instances of scrolling acceleration and deceleration, like when you reach the end of of scrolling it will do this weird slow-down to the very end of the scroll. (I have smooth scrolling disabled on my browser, my pages only scroll smooth if I engage the middle mouse button, it's stepped scrolling otherwise). But yeah, I'm facing those problems also in the video,

I also have no idea what the new options do in the Settings, like the Inline, or Cover. They honestly both produced that annoying side bar transition when you move down to the front page webUI settings.

I actually really liked how the outgoing Extra Networks worked. The only possible UX issued I had with the old system is I simply couldn't drag down the Extra Networks window more then two cards length worth in viewport size. Other than that, I really like how it worked, especially after the recent upgrade for caching previews.

I'm not sure if there will be a revert to the older static-like functionality (as is expected when a big change gets made to any application since throwing most of the work out is unpalatable for a developer) - but it's so bad I think I'd honestly have to pause updates entirely just due to this one update.

**Comment by vladmandic** [comment] 2023-07-04 02:34
> One of the problems I faced was there seemed to be instances of scrolling acceleration and deceleration

that's an auto-snap and can be disabled with a single line in css. you may not prefer it (which is ok), but why call it a problem?!

> I also have no idea what the new options do in the Settings, like the Inline, or Cover

they refer how is preview sized to fit into the card itself.

> They honestly both produced that annoying side bar transition when you move down to the rest of the front page webUI settings.

of course they do - because they have nothing to do with that.

> I'm not sure if there will be a revert to the older static-like functionality (as is expected when a big change gets made to any application since throwing most of the work out is unpalatable for a developer) - but it's so bad I think I'd honestly have to pause updates entirely just due to this one update.

and this is not being helpful at all. all you've pointed so far are pretty tiny ui items, none of them actual issues and all questions of preferences. and you call it "its soo bad".

well, it has nothing to do with me throwing most of the work, but new extra networks work goes far beyond simple ui reskin. and no, that is not getting dropped. the rest? you're pretty much the only one complaining so big.

i've heard divided opinions on transition animations and i'm open to disable them by default. but what else is soooooo bad you felt you had to write this? you've haven't given me much to work with, this feels more like venting.

**Comment by TKS4** [comment] 2023-07-04 02:55
> that's an auto-snap and can be disabled with a single line in css. you may not prefer it (which is ok), but why call it a problem?!

It's a personal problem, and also a general problem around the web you see sometimes when pages do odd things with mouse control for example, or page scrolling. It's generally not something I think is typical of best practices (like other things in web design like changing the size of a scroll bar or things of that nature). But it's not a big deal, it's only problematic mostly for me, and mostly due to the compounded buggy behavior in the videos the OP posted.

> they refer how is preview sized to fit into the card itself.

Tried changing it personally, didn't notice it, but I guess it was because I was frustrated with the buggy collapsing of cards and all that to notice. But thanks for clarification.

> and this is not being helpful at all. all you've pointed so far are pretty tiny ui items, none of them actual issues and all questions of preferences. and you call it "its soo bad".

The biggest issue was demonstrated in the clips by OP, those are actual issues. The one other problem I had that I feel is an actual issue which I didn't mention was, in the older Extra Networks design, you can quickly see which LORA's or HyperNetworks, or Checkpoints had descriptions you made. With the new one I'd have to click the "Read Description" icon to see if there was any entry.

But look, if they're tiny UI issues by your definition, that's great - that means (I presume) they would be easy changes if you ever wanted to change them in the future.

> well, it has nothing to do with me throwing most of the work, but new extra networks work goes far beyond simple ui reskin. and no, that is not getting dropped. the rest? you're pretty much the only one complaining so big.

I try not to read into emotions when I'm reading things online, but I would say I was simply posting my experience. There isn't really all that much of a problem (besides the obvious glitchy nature in the clips that I'm sure will get fixed as they're actual problems). It's just a personal preference and ease of operation with how the prior one functioned.

> i've heard divided opinions on transition animations and i'm open to disable them by default. but what else is soooooo bad you felt you had to write this? you've haven't given me much to work with, this feels more like venting.

Yeah, animations I would at least provide a toggle if they must be included in future releases. But the worst offense is the behavior in the clips, and the UI simply not recovering. There's also instances of certain preview images not even loading (all my original images for the Extra Network cards are png files straight from MS paint, and all 512x512). Those are basically the biggest actual issues. Snap-on scrolling, and the cards moving to the side when you scroll down simply are too bugged to know what the original vision for this is supposed to look like. That's the issue basically in a nutshell.

But there's no venting - I was just mentioning things I didn't find good. Maybe I should keep comments like that in the discussion forum section?

**Comment by vladmandic** [comment] 2023-07-04 03:07
> But there's no venting - I was just mentioning things I didn't find good. Maybe I should keep comments like that in the discussion forum section?

yup. or discord (its quite active). i do encourage conversations, but prefer to keep issues clearer to be able to work on actual issues and not just leave them open until they pile up and nobody cares anymore.

**Comment by TKS4** [comment] 2023-07-04 03:15
> > But there's no venting - I was just mentioning things I didn't find good. Maybe I should keep comments like that in the discussion forum section?
> 
> yup. or discord (its quite active). i do encourage conversations, but prefer to keep issues clearer to be able to work on actual issues and not just leave them open until they pile up and nobody cares anymore.

Yeah I understand and agree that's best. I'll be thorough next time and explicit with the issues and perhaps post my own clips demonstrating the precise behavioral issues if I have any in the future. Out of curiosity though, are you also experiencing the same issues we are (at least the issues in the clips with the odd behavior with the cards themselves bugging out, nevermind the little UX qualms I had, those are personal)?

**Comment by vladmandic** [comment] 2023-07-04 03:26
long-folder names, already fixed in dev, will be posted to master later this week.
hide-on-scroll, yes, that will be fixed tomorrow.
slide-in-transition? should be enabled by default only if style is set to sidebar, disabled for the rest. also hoping to fix later this week.

there is some delay on loading when scrolling and that is by design as previews are now lazy-loaded (meaning they are loaded only when they are deemed visible by browser, they are not all loaded on startup - may be "annoying" but saves a LOT of traffic and speeds up initial page load). but showing "no preview" when there is actual preview available? no, i have not experienced that.

**Comment by vladmandic** [comment] 2023-07-04 13:31
hide-on-scroll and slide-in-transition are fixed in dev.
also changed that auto-snap on scroll is disabled by default.

this should address all issues raised above.
you can either checkout dev to test or wait for couple of days until dev is merged into master.

if there are any other extra network problems, lets create a new issue not to overload this one.

**Closed by vladmandic** 2023-07-04 13:31 UTC
Labels: question
