### ISSUE TITLE
[Issue]: Problem with SDXL while using lowvram

### ISSUE THREAD

**Issue by ledrose** [vladmandic/automatic#2741] opened 2024-01-23 08:43 UTC
### Issue Description

SDXL and it's derivatives stop working when turning on "Enable sequential CPU offload (--lowvram)". It seems that the error is in accelerate package and it can be fixed by downgrading it to 0.21.0 version

### Version Platform Description

```                                                                                              
Python 3.10.13 on Linux                                                                                                                                                                                            
Version: app=sd.next updated=2024-01-13 hash=5fb290f4 url=https://github.com/vladmandic/automatic.git/tree/master                                                                                                  
Platform: arch=x86_64 cpu= system=Linux release=6.6.13-1-lts python=3.10.13                                                                                                                                        
AMD ROCm toolkit detected                                                                                                                                   
Load packages: torch=2.1.2+rocm5.6 diffusers=0.25.0 gradio=3.43.2                                                                                                                                                  
Engine: backend=Backend.DIFFUSERS compute=rocm mode=no_grad device=cuda cross-optimization="Scaled-Dot-Product"                                                                                                    
Device: device=AMD Radeon RX 6600M n=2 hip=5.6.31061-8c743ae5d    869 INFO     Device: device=AMD Radeon RX 6600M n=2 hip=5.6.31061-8c743ae5d    
```

### Relevant log output

```shell
15:44:11-439134 INFO     Select: model="Diffusers/stabilityai/stable-diffusion-xl-base-1.0 [models/Dif]"                                                                                                                                    
15:44:11-440130 DEBUG    Load model weights: existing=False target=models/Diffusers/models--stabilityai--stable-diffusion-xl-base-1.0/snapshots/462165984030d82259a11f4367a4eed129e94a7b info=None                                          
15:44:11-631762 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False                                                                                                                                 
15:44:11-632893 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16 context=no_grad fp16=True bf16=False                                                                                
15:44:11-633917 INFO     Loading VAE: model=models/VAE/sdxl_vae.safetensors source=settings                                                                                                                                                 
15:44:11-634689 DEBUG    Diffusers VAE load config: {'low_cpu_mem_usage': False, 'torch_dtype': torch.float16, 'use_safetensors': True, 'variant': 'fp16'}                                                                                  
15:44:11-720436 DEBUG    Diffusers loading: path="models/Diffusers/models--stabilityai--stable-diffusion-xl-base-1.0/snapshots/462165984030d82259a11f4367a4eed129e94a7b"                                                                    
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  8.30it/s]
15:44:12-573958 DEBUG    Setting model VAE: name=sdxl_vae.safetensors upcast=True                                                                                                                                                           
15:44:12-575060 DEBUG    Setting model: enable sequential CPU offload                                                                                                                                                                       
15:44:12-671260 DEBUG    Setting model: enable VAE slicing                                                                                                                                                                                  
15:44:12-672215 DEBUG    Setting model: enable VAE tiling                                                                                                                                                                                   
15:44:12-707041 INFO     Load embeddings: loaded=1 skipped=10 time=0.01                                                                                                                                                                     
15:44:12-923038 DEBUG    gc: collected=170 device=cuda {'ram': {'used': 1.32, 'total': 15.01}, 'gpu': {'used': 0.18, 'total': 7.98}, 'retries': 0, 'oom': 0}                                                                                
15:44:12-932235 INFO     Load model: time=1.27 { load=1.27 } native=512 {'ram': {'used': 1.32, 'total': 15.01}, 'gpu': {'used': 0.18, 'total': 7.98}, 'retries': 0, 'oom': 0}                                                               
15:44:12-959455 ERROR    Prompt parser encode: Trying to set a tensor of shape torch.Size([49408, 768]) in "weight" (which has shape torch.Size([49424, 768])), this look incorrect.                                                        
15:44:12-960763 DEBUG    Diffuser pipeline: StableDiffusionXLPipeline task=DiffusersTaskType.TEXT_2_IMAGE set={'prompt': 1, 'negative_prompt': 1, 'guidance_scale': 4, 'generator': device(type='cuda'), 'output_type': 'latent',           
                         'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0.7, 'denoising_end': None, 'width': 512, 'height': 512, 'parser': 'Fixed attention'}                                                                   
15:44:12-962979 ERROR    Processing: args={'prompt': ['1'], 'negative_prompt': [''], 'guidance_scale': 4, 'generator': [<torch._C.Generator object at 0x7c09b7760670>], 'output_type': 'latent', 'callback_on_step_end': <function          
                         process_diffusers.<locals>.diffusers_callback at 0x7c09b7780700>, 'callback_on_step_end_tensor_inputs': ['latents', 'prompt_embeds', 'negative_prompt_embeds'], 'num_inference_steps': 20, 'eta': 1.0,             
                         'guidance_rescale': 0.7, 'denoising_end': None, 'width': 512, 'height': 512} Trying to set a tensor of shape torch.Size([49408, 768]) in "weight" (which has shape torch.Size([49424, 768])), this look incorrect. 
15:44:12-964713 ERROR    Processing: ValueError                                                                                                                                                                                             
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ /home/regedit/StabilityMatrix/Packages/automatic/modules/processing_diffusers.py:450 in process_diffusers                                                                                            │
│                                                                                                                                                                                                      │
│   449 │   │   t0 = time.time()                                                                                                                                                                       │
│ ❱ 450 │   │   output = shared.sd_model(**base_args) # pylint: disable=not-callable                                                                                                                   │
│   451 │   │   downcast_openvino(op="base")                                                                                                                                                           │
│                                                                                                                                                                                                      │
│ /home/regedit/StabilityMatrix/Packages/automatic/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py:115 in decorate_context                                                                │
│                                                                                                                                                                                                      │
│   114 │   │   with ctx_factory():                                                                                                                                                                    │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                                                                                                                       │
│   116                                                                                                                                                                                                │
│                                                                                                                                                                                                      │
│ /home/regedit/StabilityMatrix/Packages/automatic/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py:1096 in __call__                          │
│                                                                                                                                                                                                      │
│   1095 │   │   │   negative_pooled_prompt_embeds,                                                                                                                                                    │
│ ❱ 1096 │   │   ) = self.encode_prompt(                                                                                                                                                               │
│   1097 │   │   │   prompt=prompt,                                                                                                                                                                    │
│                                                                                                                                                                                                      │
│ /home/regedit/StabilityMatrix/Packages/automatic/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py:415 in encode_prompt                      │
│                                                                                                                                                                                                      │
│    414 │   │   │   │                                                                                                                                                                                 │
│ ❱  415 │   │   │   │   prompt_embeds = text_encoder(text_input_ids.to(device), output_hidden_st                                                                                                      │
│    416                                                                                                                                                                                               │
│                                                                                                                                                                                                      │
│ /home/regedit/StabilityMatrix/Packages/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/module.py:1518 in _wrapped_call_impl                                                             │
│                                                                                                                                                                                                      │
│   1517 │   │   else:                                                                                                                                                                                 │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                                                                                                                           │
│   1519                                                                                                                                                                                               │
│                                                                                                                                                                                                      │
│                                                                                       ... 10 frames hidden ...                                                                                       │
│                                                                                                                                                                                                      │
│ /home/regedit/StabilityMatrix/Packages/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/module.py:1518 in _wrapped_call_impl                                                             │
│                                                                                                                                                                                                      │
│   1517 │   │   else:                                                                                                                                                                                 │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                                                                                                                           │
│   1519                                                                                                                                                                                               │
│                                                                                                                                                                                                      │
│ /home/regedit/StabilityMatrix/Packages/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/module.py:1527 in _call_impl                                                                     │
│                                                                                                                                                                                                      │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                                                                                                       │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                                                                                                                              │
│   1528                                                                                                                                                                                               │
│                                                                                                                                                                                                      │
│ /home/regedit/StabilityMatrix/Packages/automatic/venv/lib/python3.10/site-packages/accelerate/hooks.py:160 in new_forward                                                                            │
│                                                                                                                                                                                                      │
│   159 │   def new_forward(module, *args, **kwargs):                                                                                                                                                  │
│ ❱ 160 │   │   args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)                                                                                                                    │
│   161 │   │   if module._hf_hook.no_grad:                                                                                                                                                            │
│                                                                                                                                                                                                      │
│ /home/regedit/StabilityMatrix/Packages/automatic/venv/lib/python3.10/site-packages/accelerate/hooks.py:293 in pre_forward                                                                            │
│                                                                                                                                                                                                      │
│   292 │   │   │   │   │   │   fp16_statistics = self.weights_map[name.replace("weight", "SCB")                                                                                                       │
│ ❱ 293 │   │   │   │   set_module_tensor_to_device(                                                                                                                                                   │
│   294 │   │   │   │   │   module, name, self.execution_device, value=self.weights_map[name], f                                                                                                       │
│                                                                                                                                                                                                      │
│ /home/regedit/StabilityMatrix/Packages/automatic/venv/lib/python3.10/site-packages/accelerate/utils/modeling.py:285 in set_module_tensor_to_device                                                   │
│                                                                                                                                                                                                      │
│    284 │   │   if old_value.shape != value.shape:                                                                                                                                                    │
│ ❱  285 │   │   │   raise ValueError(                                                                                                                                                                 │
│    286 │   │   │   │   f'Trying to set a tensor of shape {value.shape} in "{tensor_name}" (whic                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Trying to set a tensor of shape torch.Size([49408, 768]) in "weight" (which has shape torch.Size([49424, 768])), this look incorrect.
15:44:13-197616 INFO     Processed: images=0 time=0.26 its=0.00 memory={'ram': {'used': 1.32, 'total': 15.01}, 'gpu': {'used': 0.18, 'total': 7.98}, 'retries': 0, 'oom': 0}                                                                
15:44:13-219871 DEBUG    Access state.end: f                         
```

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment] 2024-01-23 14:41
> It seems that the error is in accelerate package and it can be fixed by downgrading it to 0.21.0 version

do you have a reference to that?

**Comment by ledrose** [comment] 2024-01-23 14:50
I am not sure what you mean by "do you have a reference to that". But if you mean whether I tested it, then yes. It starts working after downgrading version in requirements.txt

**Comment by vladmandic** [comment] 2024-01-23 14:55
did you report it to accelerate team?

**Comment by ledrose** [comment] 2024-01-23 14:55
No

**Comment by vladmandic** [comment] 2024-01-23 14:55
please do. i'm not sure how else its supposed to get fixed?

**Comment by ledrose** [comment] 2024-01-23 15:01
Understandable. Will report to accelerate team.

**Comment by vladmandic** [comment] 2024-01-23 15:02
lets leave it open here for tracking and just add issue link once its created.

**Comment by vladmandic** [comment] 2024-01-26 14:13
has this been reported upstream? what is the tracking # ?

**Comment by ledrose** [comment] 2024-01-27 04:17
Still has not reported upstream. I was trying to create basic example in order to illustrate issue, but it was so far unsuccessful. While doing so I figured out that crash happens during conversion of parsed prompt to prompt_embeds and that the problem disappears when you have no SDXL compatible embeddings installed. From my attempts at recreating this problem standalone SDXL diffusers pipeline with pipeline.enable_sequential_cpu_offload() works fine. If you add compel and embeddings it also works. So I am kinda no longer sure where the problem located.

**Comment by vladmandic** [comment] 2024-01-27 04:32
thanks for update - i'll keep it open for a bit longer if you can find a reproducible scenario.

**Comment by vladmandic** [comment] 2024-02-10 16:03
closing due to no follow-ups. if upstream info is added, i'll reopen for tracking purposes.

**Closed by vladmandic** 2024-02-10 16:03 UTC
Labels: upstream
