### ISSUE TITLE
[Issue]: Inpainting is breaking and not genning anything over the mask

### ISSUE THREAD

**Issue by Faith-ssbu** [vladmandic/automatic#1994] opened 2023-08-12 20:17 UTC
### Issue Description

When I try to inpaint with Vlad, instead of getting any results with my prompt, I get nothing but a blank color where the mask is. Turning off adblock didn't help, and I even tried switching to Google Chrome and Opera GX. Still nothing better than a partial-gen but still mainly blank mask. Then, it showed in my UI as the other issue with a fully blank look. When genning this inpaint, the console at the footer gives an error of "init image not set".
![00056-solo woman adult shirt apron baking cake plate](https://github.com/vladmandic/automatic/assets/110409801/38898f4c-8666-4146-8f9e-c76e24acb443) 
![Screenshot 2023-08-12 164128](https://github.com/vladmandic/automatic/assets/110409801/16dd2a9e-4f4c-427b-a367-078da00f4a55)

### Version Platform Description

Firefox Version 116.0.2 (64-bit)
Google Chrome Version 115.0.5790.171 (Official Build) (64-bit)
Opera GX LVL 5 (core: 100.0.4815.82)
Vlad Commit Version: 9fc70cb3
Windows 11 Pro Version 22H2

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment] 2023-08-13 08:06
i've tested and cannot reproduce. 
- is this happening all the time or?
- did you try with a different model (just as a test)
- can you provide step-by-step reproducible scenario?

**Comment by Faith-ssbu** [comment] 2023-08-16 03:20
> i've tested and cannot reproduce.
> 
>     * is this happening all the time or?
> 
>     * did you try with a different model (just as a test)
> 
>     * can you provide step-by-step reproducible scenario?

Sorry for the late response, I only just now saw this. 

- Yes, it is always happening. Every time I try to inpaint, it either gives a partial-genned inpaint or a completely blank mask
- Yes, the results with a different model are the same as seen here
![image](https://github.com/vladmandic/automatic/assets/110409801/40be16e0-380e-4dab-bbf9-479a88755940)
- Honestly, I am not unfortunately not sure how to reproduce it. I have already tried redownloading and with a new model, as well as being much more clear with my inpaint prompt. However, it just keeps giving this same issue. I am running with DirectML since I have an AMD GPU, if that helps at all.

**Comment by transposemc** [comment] 2023-08-19 18:18
i can get rid of that happening to me in the directml fork of automatic by using the args --no-half-vae --precision full --no-half --medvram --opt-sub-quad-attention --opt-split-attention --opt-split-attention-v1 --disable-nan-check --always-batch-cond-uncond --sub-quad-q-chunk-size 256 --sub-quad-kv-chunk-size 256 --sub-quad-chunk-threshold 75 

unsure how to implement them on this fork but its pretty much just no fp16

**Comment by transposemc** [comment] 2023-08-19 18:23
> i've tested and cannot reproduce.
> 
> * is this happening all the time or?
> * did you try with a different model (just as a test)
> * can you provide step-by-step reproducible scenario?

it happens on amd gpu with directml enabled with fp16.  in the sd_webui_dml_neuro_v2 fork the no fp16 bats are included, unsure if you can use this to fix the issue.

i also created a poweshell script to install this version easily on windows by just running and repsonding to a few questions.
[SDNEXTN8INSTALLERWINDOWS.ps1.TXT](https://github.com/vladmandic/automatic/files/12386497/SDNEXTN8INSTALLERWINDOWS.ps1.TXT)

**Comment by alarmgoose** [comment] 2023-10-20 01:29
This happen to me basically inpaint only mask changed the entire picture. I ended up going back to A111 :(

**Comment by RandJuno** [comment] 2023-11-10 11:29
had the same error. Solved as described below.

https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/84 for reference, great post.

They mention "Also inpainting often doesn't work at all without --no-half on. There is a less memory-hungry alternative for the --no-half called --upcast-sampling, you can experiment with it. For me, though, it breaks inpainting."

under system/settings I made the following changes: 
![image](https://github.com/vladmandic/automatic/assets/77006339/44c16bdf-db58-4e2e-a37b-54fc6f0feb6b)

be sure to hit apply settings! that did it for me!


I also replaced the VAEs that were preinstalled in 
models/vae and 
models/VAE-approx

not sure if the VAES did anything though

**Comment by DeXtmL** [comment] 2023-12-19 13:55
Same issue for me, i suspect that maybe the Pillow module is broken, feeding bad data to the pipeline.

My quick solution: 
use InvokeAI for the inpainting.  Limited functionality but much better UI for inpainting and outpainting.  Most importantly, it doesn't have this bug.

I hope A111 can fix this soon.

**Comment by vladmandic** [comment] 2024-01-05 01:45
this one is a long overdue, but finally fixed in dev and will be merged to master in the next release.

**Closed by vladmandic** 2024-01-05 01:45 UTC
Labels: question, cannot reproduce
