### ISSUE TITLE
[Issue]: Fix Info tab

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#273] opened 2023-04-20 09:09 UTC
### Feature description

Yes, I have seen the statement that it was integrated into "Process Image". This is incorrect.
A variant of it that works differently is indeed there, but it does not replicate the functionality of the old PNG Info tab.

I have noticed 2 major issues with it:
1- Process Image displays the prompt entirely on a single line, not respecting the prompt's newlines, meaning every prompt copy pasted from here is a mess that has to be corrected every time.
2- It is not capable of handling PNGs that have been converted to JPG (done preserving the metadata, obviously) instead showing a bunch of chinese characters. These same images work perfectly on the 1111 WebUI's info tab.

Easiest solution would be to simply re-enable the old info tab. Potentially with a setting to control it if you wish.
Another would be to fix the Process Image section, but it seems like it would be more work than the above.
Another alternative would be to make the PNG Info page a sub-tab of the Process Image section, if you really want the main tab list to be smaller.

### Version Platform Description

Version: e6701f5c Wed Apr 19 14:12:19 2023

**Comment by vladmandic** [comment] 2023-04-20 11:48
"bring back" is not a solution. i'm willing to do whatever it takes to provide fixes.
and as it is, this is a duplicate of #278 which provides more information, so closing as duplicate.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment] 2023-04-20 11:54
No, it isn't.
That post was made after mine and doesn't list the issues I do.
This is a major issue for a lot of users, the PNG Info tab is where 90% of my generations start.

**Comment by vladmandic** [comment] 2023-04-20 11:56
either way, i'm committed of fixing it, so what's the problem?

>  It is not capable of handling PNGs that have been converted to JPG (done preserving the metadata, obviously) instead showing a bunch of chinese characters. These same images work perfectly on the 1111 WebUI's info tab.

can you provide an example image so i can reproduce?

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment] 2023-04-20 12:22
Here's the original .png of a very simple example image I just made.
https://files.catbox.moe/hzy72l.png

Here's what I see in 1111's WebUI, note the newlines. Not very important in a small prompt like this but vital on long ones, doubly so when they use BREAKs, regional prompts, etc.
I can easily copy paste this if I want to create more images with this prompt when I don't want to send the whole image to txt2img. Maybe I just want the negative prompt. Or I just want the section describing the background for example. It's very useful.
https://files.catbox.moe/hkdlwx.png

Here's what I see in Automatic, all in one line, newlines not reproduced
https://files.catbox.moe/jlhhpv.png

Now I convert this to .jpg
https://files.catbox.moe/4lats2.jpg

Here's what I see in 1111's WebUI, same as before, newlines are respected and shown.
https://files.catbox.moe/obhisz.png

Here's what I see in Automatic, a mess of chinese characters.
https://files.catbox.moe/u2g8yd.png

**Comment by vladmandic** [comment] 2023-04-20 12:26
thanks, expect the fix later today.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment] 2023-04-20 12:29
Thank you, 
sorry if I sounded abrasive I'm used to people closing issues and linking to things that may be related but are actually not the same thing at all and I thought that was what you were doing.

**Comment by Threnos** [comment] 2023-04-20 12:41
+1, I use this tab all the time

**Comment by vladmandic** [comment] 2023-04-20 15:46
i just posted major update and created a writeup on it under #278.
closing this issue as resolved, follow instructions there if there are any remaining issues.

**Closed by vladmandic** 2023-04-20 15:46 UTC
Labels: bug
