### ISSUE TITLE
[Issue]: Webui-Civitai-Helper is loading only partially

### ISSUE THREAD

**Issue by razvan-nicolae** [vladmandic/automatic#115] opened 2023-04-13 21:53 UTC
### Issue Description

The tab of this extension is not visible in main interface, but some of its icons are loaded inside lora/textual inversion tabs. 
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper
No errors in logs.

Let me know if this should be raised with the owner of the addon and not with yourself.
Thanks in advance!

### Platform Description

Windows 11 latest, 4090

**Comment by vladmandic** [comment] 2023-04-13 22:15
i'll take a look first.

**Comment by razvan-nicolae** [comment] 2023-04-13 23:34
Error loading script: civitai_helper.py
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:255 in load_scripts                                                              │
│                                                                                                                     │
│   253 │   │   │   current_basedir = scriptfile.basedir                                                              │
│   254 │   │   │                                                                                                     │
│ > 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                       │
│   256 │   │   │   register_scripts_from_module(script_module)                                                       │
│   257                                                                                                               │
│                                                                                                                     │
│ I:\SD\automatic\modules\script_loading.py:11 in load_module                                                         │
│                                                                                                                     │
│    9 │   module_spec = importlib.util.spec_from_file_location(os.path.basename(path), path)                         │
│   10 │   module = importlib.util.module_from_spec(module_spec)                                                      │
│ > 11 │   module_spec.loader.exec_module(module)                                                                     │
│   12 │                                                                                                              │
│   13 │   return module                                                                                              │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ I:\SD\automatic\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py:36 in <module>           │
│                                                                                                                     │
│    34 extension_path = scripts.basedir()                                                                            │
│    35                                                                                                               │
│ >  36 model.get_custom_model_folder()                                                                               │
│    37 setting.load()                                                                                                │
│    38                                                                                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model.py:33 in                      │
│ get_custom_model_folder                                                                                             │
│                                                                                                                     │
│    31 │   global folders                                                                                            │
│    32 │                                                                                                             │
│ >  33 │   if shared.cmd_opts.embeddings_dir and os.path.isdir(shared.cmd_opts.embeddings_dir):                      │
│    34 │   │   folders["ti"] = shared.cmd_opts.embeddings_dir                                                        │
│    35                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'embeddings_dir'


Found this error in the logs just now

**Comment by vladmandic** [comment] 2023-04-13 23:40
then its a duplicate of #106, i'll try to handle it tomorrow.

**Closed by vladmandic** 2023-04-13 23:40 UTC

**Comment by razvan-nicolae** [comment] 2023-04-15 23:13
This is not yet fixed sadly - should we try to get in touch with @butaixianran? I don't see any more errors on vladmandic/automatic side but the behavior is the same - scan works, but no overlay or buttons
![image](https://user-images.githubusercontent.com/19169014/232257398-77365145-7bc9-442d-a2d4-636a9d895e1c.png)

It should look something like this on top of each one:
![image](https://user-images.githubusercontent.com/19169014/232257564-555b2ab8-632d-422b-96e4-77845bf57c35.png)

**Comment by vladmandic** [comment] 2023-04-16 00:09
i was not even aware there were buttons - i don't use the extension. i was focused on fixing core issue and thats gone.
what remains is most likely a css thing, so falls under #84
