### ISSUE TITLE
[Issue]: ADetailer massive slow down in Update for 2024-02-07

### ISSUE THREAD

**Issue by Memeheader** [vladmandic/automatic#2858] opened 2024-02-14 02:46 UTC
### Issue Description

Using a fresh install of Update for 2024-02-07
Adetailer is getting ~1 t/s
When going back to previous release Update for 2023-12-29 
Adetailer is getting ~12 t/s

Using the same settings for each.

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment] 2024-02-14 03:09
> Using the same settings for each.

this is not actionable.
need actual LOGS from before and after if this is to progress anywhere.
also, enable `--debug` command flag to capture them in details.

**Comment by ChiaYen-Kan** [comment] 2024-02-14 13:25
i also has same problem, but is in "Second pass"
after update SD.Next, Adetailer is slow down and take more memory, every time is out of memory

log and error image

9bf08c5493925b6ddb3451f6a6e00460ca92aedd is working version
[ad-ok.txt](https://github.com/vladmandic/automatic/files/14279851/ad-ok.txt)

3c952675fefd2c94b817940ffbd4cd94fd5876c9 is not working version
[ad-ng.txt](https://github.com/vladmandic/automatic/files/14279853/ad-ng.txt)
![ad-ng](https://github.com/vladmandic/automatic/assets/40080620/200ebd9c-e92f-4114-810f-caafd89fc7b7)

**Comment by Memeheader** [comment] 2024-02-14 15:38
[2024_02_07_3c95267.txt](https://github.com/vladmandic/automatic/files/14281742/2024_02_07_3c95267.txt)
[2023-12-29_c77505f.txt](https://github.com/vladmandic/automatic/files/14281743/2023-12-29_c77505f.txt)
Log with Debug parameter
Both using ADetailer 24.1.2
Image settings are 512x768, DPM 3M++ SDE Karras, second pass enabled upscale 2x, with adetailer enabled
You can see the old ui is having 23.5it/s and the new ui has 3.5it/s

**Comment by vladmandic** [comment] 2024-02-14 15:40
its exactly like i said. compare your system -> settings sections from before and after: execution, compute, inference, diffusers

**Comment by CharlesCato** [comment] 2024-02-14 18:45
I have the same problem anyway. With all the same settings in execution etc (I had a save of my config).
It's as slow as trying to manually inpaint anything with Resize mode set to none. Awefuly slow.
(I'm on Original backend cause I can't run any Hires while on diffuser, it's always crashing. Whatever setting I use. Being on ATI I run directml. But that's another issue.)

**Comment by ChiaYen-Kan** [comment] 2024-02-15 01:32
> I have the same problem anyway. With all the same settings in execution etc (I had a save of my config). It's as slow as trying to manually inpaint anything with Resize mode set to none. Awefuly slow. (I'm on Original backend cause I can't run any Hires while on diffuser, it's always crashing due to memory errors. Whatever setting I use. Being on ATI I run directml. But that's another issue.) The only solution I've found is to manually inpaint..... old fashion way ! :D

Hi @CharlesCato 
i also use directml 
you can downgrade to 9bf08c5493925b6ddb3451f6a6e00460ca92aedd, is last working release version with directml in my system

**Comment by brknsoul** [comment] 2024-02-15 01:43
That's what I had to do too.
Straight `--upgrade` to latest master, with no change in settings. Before update, adetailer was working fine. After update, adetailer is either extremely slow (~12 s/it) or OOMs.

Adetailer hasn't been updated for 3 weeks, so Adetailer is not the culprit.

**Comment by vladmandic** [comment] 2024-02-15 14:41
should be fixed in latest dev branch.
the issue was that adetailer was performing operation on full-size image instead of reduced masked section.

**Closed by vladmandic** 2024-02-15 14:41 UTC
Labels: question

**Comment by CharlesCato** [comment] 2024-02-15 15:25
@vladmandic Checked. I wish I could say it's working but, no. Not for me.

`URL: https://github.com/vladmandic/automatic.git/tree/dev
Current branch: dev
Current version: 2024-02-15 hash d0ceff70
Latest version: 2024-02-15 hash `d0ceff70``

I guess it's still working with an inappropriate size cause when adetailer work on a 512x768 image, it's still faster than the same image after a hires x2. Since adetailer is supposed to work with an image smaller than 512x768, working after an upscale shouldn't affect the speed anyway. Right ?

**Comment by vladmandic** [comment] 2024-02-15 16:17
ah, found one more issue, fixed in dev now - it was ignoring processing width/height desired by adetailer. so it was basically processing at the final resolution after hires instead.

**Comment by CharlesCato** [comment] 2024-02-15 16:24
Yep. Working now ! Thanks. 👍

**Comment by brknsoul** [comment] 2024-02-15 19:04
Woking perfectly now. Thank you!

**Comment by brknsoul** [comment] 2024-02-18 02:11
Regression in dev 3c952675fefd2c94b817940ffbd4cd94fd5876c9

Adetailer and Inpaint is masking entire image.

**Comment by vladmandic** [comment] 2024-02-18 04:19
Take 1min to document workflow or its NOT going to be looked at. Can't just dump logs and call it a day.

**Comment by vladmandic** [comment] 2024-02-18 11:56
@brknsoul sorry i don't see a problem - adetailer is inpainting masked area only. and its using specific resolution and steps for that inpainting IF you set those inside adetailer itself ("use separate ...." checkboxes)

if there is a problem, document exact workflow as "generating" can be anything - i don't even know if you're doing txt2img/img2img/control and upload full log, not just last few lines.
