### ISSUE TITLE
[Issue]: Hires Fix Bug ?

### ISSUE THREAD

**Issue by derspanier1** [vladmandic/automatic#1276] opened 2023-06-03 00:13 UTC
### Issue Description

UniPC, 15 steps, No Hires fix:
![grid-7503-2441051264-(masterpiece_1 2), (detailed_1 1), 8K, 1 girl, freckles, ginger hair, solo, upper body, looking up, red clothes, detailed backgr](https://github.com/vladmandic/automatic/assets/117949621/73305093-e864-4c57-8bb0-4be4ba87c438)

```
Loading weights: E:\Lora\Style\kVoidEnergy-000001.safetensors ------------------------------------ 0.0/151.2 MB -:--:--
LoRA Block weight (lora): kVoidEnergy-000001: 1.0 x [1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
['kVoidEnergy-000001'] [[1.0, 1, 0.0, 0.0, 1, 0.0, 1.0, 1, 1.0, 1.0, 1, 1, 1, 1.0, 1, 1, 1, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]] ['']
Progress 10.35it/s ---------------------------------------- 100% 0:00:00 0:00:02
```

with fix:
![grid-7504-2441051264-(masterpiece_1 2), (detailed_1 1), 8K, 1 girl,  freckles, ginger hair, solo, upper body, looking up, red clothes, detailed backg](https://github.com/vladmandic/automatic/assets/117949621/e888e393-d926-4d2a-9387-fccde35f6e88)

```
02:08:34-499531 ERROR    Running script process: D:\SD_Next\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py:
                         AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\SD_Next\modules\scripts.py:376 in process                                                                        │
│                                                                                                                     │
│   375 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 376 │   │   │   │   script.process(p, *args, **kwargs)                                                            │
│   377 │   │   │   │   # log.debug(f'Script process end  : {script.title()}')                                        │
│                                                                                                                     │
│ D:\SD_Next\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py:420 in process                     │
│                                                                                                                     │
│   419 │   │   original_prompt, original_negative_prompt = get_prompts(p)                                            │
│ > 420 │   │   hr_prompt_overwrite, hr_negative_overwrite = check_hr_overwrite(p)                                    │
│   421 │   │   original_seed = p.seed                                                                                │
│                                                                                                                     │
│ D:\SD_Next\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py:88 in check_hr_overwrite           │
│                                                                                                                     │
│    87 │   prompt, negative_prompt = get_prompts(p)                                                                  │
│ >  88 │   hr_prompt, hr_negative = get_hr_prompts(p)                                                                │
│    89                                                                                                               │
│                                                                                                                     │
│ D:\SD_Next\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py:71 in get_hr_prompts               │
│                                                                                                                     │
│    70 def get_hr_prompts(p) -> tuple[str, str]:                                                                     │
│ >  71 │   hr_prompt = p.all_hr_prompts[0] if len(p.all_hr_prompts) > 0 else p.hr_prompt                             │
│    72 │   hr_negative = (                                                                                           │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'all_hr_prompts'
02:08:34-584160 ERROR    activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams
                         object at 0x0000026BC49EDC30>]: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\SD_Next\modules\extra_networks.py:75 in activate                                                                 │
│                                                                                                                     │
│    74 │   │   try:                                                                                                  │
│ >  75 │   │   │   extra_network.activate(p, extra_network_args)                                                     │
│    76 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ D:\SD_Next\extensions-builtin\Lora\extra_networks_lora.py:22 in activate                                            │
│                                                                                                                     │
│   21 │   │   │   names.append(params.items[0])                                                                      │
│ > 22 │   │   │   multipliers.append(float(params.items[1]) if len(params.items) > 1 else 1.0)                       │
│   23                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: could not convert string to float: '{0.9'
02:08:34-615408 ERROR    Running script process batch:
                         D:\SD_Next\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\SD_Next\modules\scripts.py:395 in process_batch                                                                  │
│                                                                                                                     │
│   394 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 395 │   │   │   │   script.process_batch(p, *args, **kwargs)                                                      │
│   396 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ D:\SD_Next\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py:294 in process_batch                  │
│                                                                                                                     │
│   293 │   │   │   │   │   o_prompts = prompts.copy()                                                                │
│ > 294 │   │   │   loradealer(o_prompts ,self.lratios,self.elementals)                                               │
│   295                                                                                                               │
│                                                                                                                     │
│ D:\SD_Next\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py:491 in loradealer                     │
│                                                                                                                     │
│   490 │   │   │   │   called = lycodealer(called)                                                                   │
│ > 491 │   │   │   multiple = float(called.items[1])                                                                 │
│   492 │   │   │   multipliers.append(multiple)                                                                      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: could not convert string to float: '{0.9'
Progress 10.62it/s ---------------------------------------- 100% 0:00:00 0:00:02
        Tile 1/15
        Tile 2/15
        Tile 3/15
        Tile 4/15
        Tile 5/15
        Tile 6/15
        Tile 7/15
        Tile 8/15
        Tile 9/15
        Tile 10/15
        Tile 11/15
        Tile 12/15
        Tile 13/15
        Tile 14/15
        Tile 15/15
        Tile 1/15
        Tile 2/15
        Tile 3/15
        Tile 4/15
        Tile 5/15
        Tile 6/15
        Tile 7/15
        Tile 8/15
        Tile 9/15
        Tile 10/15
        Tile 11/15
        Tile 12/15
        Tile 13/15
        Tile 14/15
        Tile 15/15
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.68it/s]
```

### Version Platform Description

1f988d1d Fri Jun 2 19:39:44 2023 -0400

**Comment by vladmandic** [comment] 2023-06-03 00:26
there was a short-lived issue in `sd_dynamic_prompts` built-in extension, its been fixed by author. just update.

**Comment by derspanier1** [comment] 2023-06-03 00:51
thank you. ill wait for tomorrow as the fix is not live yet.

**Comment by vladmandic** [comment] 2023-06-03 01:01
my bad, its not resolved yet, its still waiting to be merged upstream.
but closing as duplicate of #1273

**Closed** 2023-06-03 01:03 UTC

**Comment by chuckkay** [comment] 2023-07-19 21:44
> there was a short-lived issue in `sd_dynamic_prompts` built-in extension, its been fixed by author. just update.

it appears to be back

**Comment by ViolentVotan** [comment] 2023-08-22 21:34
can confirm, is back. So conclusion is, this is a bug by the extension author, not SD.Next? The extensions works fine on A1111
