### ISSUE TITLE
[Issue]: Button to assign image to LORA not working

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#599] opened 2023-04-28 19:12 UTC
### Issue Description

On gradio/default, on the Lora tab, in thumbnail mode, when hovering over a thumbnail. On its upper left side, a button consisting of a photo icon with a refresh sign appears.

Expected behavior: upon click, it binds the currently focused image to that LORA.

Current behavior: Nothing happens.

Version 2023-04-28 eeea06b9; Firefox latest

**Comment by vladmandic** [comment] 2023-04-29 01:55
can you confirm using default theme? i don't even see a "button" to replace thumbnail on hover. what i see is 3 textual links:
- replace preview
- replace description
- read description

**Comment by mark-wd** [comment] 2023-04-29 06:42
In 1111, this button has always replaced the thumbnail of the LORA: [imgur](https://imgur.com/a/cED210E)

**Comment by vladmandic** [comment] 2023-04-29 14:25
duplicate of #615, just fixed.

**Closed by vladmandic** 2023-04-29 14:25 UTC
Labels: cannot reproduce
