### ISSUE TITLE
[Extension]: a1111-sd-webui-lycoris

### ISSUE THREAD

**Issue by latinokodi** [vladmandic/automatic#1283] opened 2023-06-03 11:44 UTC
### Issue Description

After the latest update, the Lycoris tab in Aditional networks has disappeared even thou the extension is installed and showing in main tabs:
![Screenshot_1](https://github.com/vladmandic/automatic/assets/44171499/68989da2-22f9-472a-be0a-3d155a20ed36)

### Version Platform Description

Environment:

Version: 299f122 Fri Jun 2 20:54:09 2023 -0400
Nvidia Geforce RTX 3060
Operating System: Win10
Browser: Microsoft Edge (latest)

### URL link of the extension

https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

**Comment by rosenius** [comment] 2023-06-03 13:01
When added manually to the prompt the log says:

Skipping unknown extra network: lyco

**Comment by vladmandic** [comment] 2023-06-03 13:15
i cannot reproduce, but it seems that extension never loaded correctly
can you try starting the server with `webui --debug` and post the console log?

**Comment by rosenius** [comment] 2023-06-03 13:21
> i cannot reproduce, but it seems that extension never loaded correctly can you try starting the server with `webui --debug` and post the console log?

I did a git pull before restarting and that seemed to fix it.

**Comment by Gerkinfeltser** [comment] 2023-06-03 13:33
Yep, I noticed this as well. When I went to restart the server with the --debug command it seems to have fixed it.

**Comment by vladmandic** [comment] 2023-06-03 13:42
i guess there was a interim issue with lyco extension that was solved. i'm going to close the issue as there is not much i can do here anymore, but if issue reoccurs, let me know.

**Comment by brunogcar** [comment] 2023-06-03 13:42
Version: c7051cc1 fixed  it as it updated  extensions-builtin/a1111-sd-webui-lycoris

**Closed** 2023-06-03 13:42 UTC
Labels: question, extension

**Comment by Gerkinfeltser** [comment] 2023-06-03 14:15
Hmm, its actually happened again to me. I'm not super versed in git yet. How can I make sure I am at the version you mention @brunogcar?

The relevant section of my log reads as follows:
`.....
09:09:38-058236 ERROR    executing callback: C:\ai\automatic\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py before_ui: 
                         AttributeError
╭─Traceback (most recent call last) ─╮
│ C:\ai\automatic\modules\script_callbacks.py:257 in before_ui_callback                                                                    
││                                                                                                                                         
││   256 │   │   try:                                                                                                                       
││ ❱ 257 │   │   │   c.callback()                                                                                                           
││   258 │   │   except Exception as e:                                                                                                     
││                                                                                                                                          
││ C:\ai\automatic\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py:20 in before_ui                                      
││                                                                                                                                          
││   19 def before_ui():                                                                                                                    
││ ❱ 20 │   if shared.cmd_opts.lyco_patch_lora:                                                                                             
││   21 │   │   print(                                                                                                                      
╰─╯
AttributeError: 'Namespace' object has no attribute 'lyco_patch_lora'
09:09:38-246769 INFO     Theme does not support custom mode
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
.... snip`
