### ISSUE TITLE
[Issue]: Sampler invalid when using ControlNet

### ISSUE THREAD

**Issue by MysticDaedra** [vladmandic/automatic#3219] opened 2024-06-12 20:17 UTC
### Issue Description

Any time I try to use controlnet, it gives a warning saying "Sampler is invalid", and then proceeds to throw errors and generation fails. 

Specific usage:
1. Load an image from txt2img into the control tab via send-to-control.
2. Select "Init image same as control".
3. Adjust sampler to correct one. Tested samplers include DPM++ 3M SDE Karras, DPM++ SDE Karras, and Heun. Heun test not included in provided log though.
4. Select controlnet options: regular controlnet, SDXL tile model. With or without a preprocessor, doesn't matter. I've tried both ways, they both have the same issue.

Note that I have never tried without using adetailer. However, I don't believe this should be an issue, as the warnings and failure happens long before it gets to adetailer detection and pipeline loading. Obviously I could be wrong.

5. Set adetailer settings as desired.
6. Use USDU script for tiled upscaling.

Finally hit generate. It'll do something for a bit, then it'll show "Warning: Sampler invalid" in the console, upscaling will fail, generation will fail. Using adetailer and USDU adds on skipped generations for each tile, but the issue happened at the very beginning.

Log too long to paste, here it is attached: 
[message(1).txt](https://github.com/user-attachments/files/15810516/message.1.txt)

### Version Platform Description

Python version: 3.11.8
SD.Next version: dev 94276cc5
Platform: AMD64 family 25 model 33 stepping 2
OS: Windows 11 professional
GPU: RTX 3070 8GB
CUDA: 12.1
Torch: 2.3.1+cu121
Diffusers: 0.28.1
Gradio: 3.43.2
ONNX: 1.18.0 (note: afaik I am not using ONNX, I've never turned it on.)
Enabled extensions-builtin: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg']
Enabled Extensions: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'adetailer', 'canvas-zoom', 'sd-webui-infinite-image-browsing',
                         'sd-webui-temporal', 'ultimate-upscale-for-automatic1111']

### Relevant log output

```shell
See above attachment.
```

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment] 2024-06-13 13:18
i cannot reproduce.
could be due to usdu (more likely) or adetailer (less likely) - try to reproduce without extensions and let me know.

**Comment by vladmandic** [comment] 2024-06-25 16:36
this should be fixed in latest release, if it reoccurs update here and i'll reopen.

**Closed by vladmandic** 2024-06-25 16:36 UTC
Labels: question, cannot reproduce
