### ISSUE TITLE
[Issue] Cannot generate images with lowvram/medvram

### ISSUE THREAD

**Issue by AbramovS1** [vladmandic/automatic#345] opened 2023-04-21 14:12 UTC
### Issue Description

Is there any solution to avoid generating black images? Or is there no support for 16xx here? And if there is, what should I do to fix it?

### Version Platform Description

Win11
Edge

**Comment by vladmandic** [comment] 2023-04-21 14:25
fill the issue template fully AND provide relevant information, i cannot help if i have no information.
and do not remove [Issue] from title, doesn't help.

which gpu?
which version you're using?
which model? vae?

also, search in issues/discussions for NaN, that is a common keyword and multiple answers have been provided.

**Comment by AbramovS1** [comment] 2023-04-21 14:28
Nvidia 1650 4gb
last
There is nothing in the VAE folder, but your model is in the VAE-approx folder!
I couldn't find anything (I use GitHub very rarely)

**Comment by gitmylo** [comment] 2023-04-21 14:44
have you tried turning on `Use full precision for VAE (--no-half-vae)` under `CUDA settings`, in the settings?
this could produce black images.

**Comment by AbramovS1** [comment] 2023-04-21 14:48
> Вы пробовали включить в разделе , в настройках? Это может привести к получению черных изображений.`Use full precision for VAE (--no-half-vae)``CUDA settings`

I've tried everything, and it gives errors with each parameter

**Comment by vladmandic** [comment] 2023-04-21 14:49
they are not command line params anymore, that's all in UI -> Settings -> CUDA Params

**Comment by AbramovS1** [comment] 2023-04-21 14:51
> они больше не являются параметрами командной строки, это все в пользовательском интерфейсе -> Настройки -> Параметры CUDA

I know, and I did everything I could and still got an error (failed to allocate VRAM)

**Comment by gitmylo** [comment] 2023-04-21 14:53
which gpu do you use?

**Comment by cjps-br** [comment] 2023-04-21 14:54
I also started having problems with black images and I managed to solve it by doing the configuration below in the settings relative to CUDA.

My GPU is:
GPU:
device: NVIDIA GeForce GTX 1660 SUPER (1) (compute_37) (7, 5)
cuda: 11.8
cudnn: 8700

![image](https://user-images.githubusercontent.com/75840971/233667633-465004da-e043-42f8-9f28-e3a8fe10d23f.png)

**Comment by CKwasd** [comment] 2023-04-21 14:58
try fp16

**Comment by gitmylo** [comment] 2023-04-21 15:00
> try fp16

cjps-br said they fixed it, this is a different person from AbramovS1

i asked which gpu they use because it could be an issue with having too little vram, possibly causing the model to fail loading. causing it to produce black images (?)

**Comment by AbramovS1** [comment] 2023-04-21 15:02
> > try fp16
> 
> cjps-br said they fixed it, this is a different person from AbramovS1
> 
> i asked which gpu they use because it could be an issue with having too little vram, possibly causing the model to fail loading. causing it to produce black images (?)
Maybe I realized what the problem is Torch takes more video memory than it has

**Comment by AbramovS1** [comment] 2023-04-21 15:02
> which gpu do you use?

1650 4gb

**Comment by CKwasd** [comment] 2023-04-21 15:02
> > try fp16
> 
> cjps-br said they fixed it, this is a different person from AbramovS1
> 
> i asked which gpu they use because it could be an issue with having too little vram, possibly causing the model to fail loading. causing it to produce black images (?)

yup that might be an issue casuing that , since he didn't post the log

**Comment by JayVoigt** [comment] 2023-04-21 15:03
> I also started having problems with black images and I managed to solve it by doing the configuration below in the settings relative to CUDA.
> 
> My GPU is: GPU: device: NVIDIA GeForce GTX 1660 SUPER (1) (compute_37) (7, 5) cuda: 11.8 cudnn: 8700
> 
> ![image](https://user-images.githubusercontent.com/75840971/233667633-465004da-e043-42f8-9f28-e3a8fe10d23f.png)

I'm also getting the black images issue with the same settings, but I'm on a 3090 so VRAM shouldn't be an issue.

**Comment by CKwasd** [comment] 2023-04-21 15:04
> > I also started having problems with black images and I managed to solve it by doing the configuration below in the settings relative to CUDA.
> > My GPU is: GPU: device: NVIDIA GeForce GTX 1660 SUPER (1) (compute_37) (7, 5) cuda: 11.8 cudnn: 8700
> > ![image](https://user-images.githubusercontent.com/75840971/233667633-465004da-e043-42f8-9f28-e3a8fe10d23f.png)
> 
> I'm also getting the black images issue with the same settings, but I'm on a 3090 so VRAM shouldn't be an issue.

Every time with black images? Have you tried restarting it , please post the error log if you have

**Comment by CKwasd** [comment] 2023-04-21 15:06
> please post the error log if you have

open your task manager and monitor the GPU vram usage,if it is full,tired restart it and launch with --lowvram

**Comment by AbramovS1** [comment] 2023-04-21 15:10
> > please post the error log if you have
> 
> open your task manager and monitor the GPU vram usage,if it is full,tired restart it and launch with --lowvram,also post the error log

And where can I get it ?

**Comment by JayVoigt** [comment] 2023-04-21 15:12
> > > I also started having problems with black images and I managed to solve it by doing the configuration below in the settings relative to CUDA.
> > > My GPU is: GPU: device: NVIDIA GeForce GTX 1660 SUPER (1) (compute_37) (7, 5) cuda: 11.8 cudnn: 8700
> > > ![image](https://user-images.githubusercontent.com/75840971/233667633-465004da-e043-42f8-9f28-e3a8fe10d23f.png)
> > 
> > 
> > I'm also getting the black images issue with the same settings, but I'm on a 3090 so VRAM shouldn't be an issue.
> 
> Every time with black images? Have you tried restarting it , please post the error log if you have

The issue is really intermittent, I haven't been able to reproduce it for the last couple of generations - not sure what the cause is. I'll post again here if I get more info.

**Comment by AbramovS1** [comment] 2023-04-21 15:20
> > > > please post the error log if you have
> > > 
> > > 
> > > open your task manager and monitor the GPU vram usage,if it is full,tired restart it and launch with --lowvram,also post the error log
> > 
> > 
> > And where can I get it ?
> 
> from console ![image](https://user-images.githubusercontent.com/18748818/233672525-9e121e25-0a43-4468-9b45-35e3ad50553a.png)

Traceback (most recent call last):
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\vlad111\automatic\modules\call_queue.py", line 17, in f
    res = func(*args, **kwargs)
  File "E:\vlad111\automatic\modules\ui.py", line 238, in update_token_counter
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "E:\vlad111\automatic\modules\ui.py", line 238, in <listcomp>
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "E:\vlad111\automatic\modules\sd_hijack.py", line 231, in get_prompt_lengths
    _, token_count = self.clip.process_texts([text])
AttributeError: 'NoneType' object has no attribute 'process_texts'
Traceback (most recent call last):
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\vlad111\automatic\modules\call_queue.py", line 17, in f
    res = func(*args, **kwargs)
  File "E:\vlad111\automatic\modules\ui.py", line 238, in update_token_counter
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "E:\vlad111\automatic\modules\ui.py", line 238, in <listcomp>
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "E:\vlad111\automatic\modules\sd_hijack.py", line 231, in get_prompt_lengths
    _, token_count = self.clip.process_texts([text])
AttributeError: 'NoneType' object has no attribute 'process_texts'
gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ E:\vlad111\automatic\modules\call_queue.py:61 in f                                                                   │
│                                                                                                                      │
│    60 │   │   │   │   pr.enable()                                                                                    │
│ ❱  61 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    62 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\call_queue.py:39 in f                                                                   │
│                                                                                                                      │
│    38 │   │   │   try:                                                                                               │
│ ❱  39 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    40 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│                                               ... 3 frames hidden ...                                                │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\textual_inversion\textual_inversion.py:225 in load_textual_inversion_embeddings         │
│                                                                                                                      │
│   224 │   │   self.skipped_embeddings.clear()                                                                        │
│ ❱ 225 │   │   self.expected_shape = self.get_expected_shape()                                                        │
│   226                                                                                                                │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\textual_inversion\textual_inversion.py:133 in get_expected_shape                        │
│                                                                                                                      │
│   132 │   def get_expected_shape(self):                                                                              │
│ ❱ 133 │   │   vec = shared.sd_model.cond_stage_model.encode_embedding_init_text(",", 1)                              │
│   134 │   │   return vec.shape[1]                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'cond_stage_model'
gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ E:\vlad111\automatic\modules\call_queue.py:61 in f                                                                   │
│                                                                                                                      │
│    60 │   │   │   │   pr.enable()                                                                                    │
│ ❱  61 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    62 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\call_queue.py:39 in f                                                                   │
│                                                                                                                      │
│    38 │   │   │   try:                                                                                               │
│ ❱  39 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    40 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│                                               ... 3 frames hidden ...                                                │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\textual_inversion\textual_inversion.py:225 in load_textual_inversion_embeddings         │
│                                                                                                                      │
│   224 │   │   self.skipped_embeddings.clear()                                                                        │
│ ❱ 225 │   │   self.expected_shape = self.get_expected_shape()                                                        │
│   226                                                                                                                │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\textual_inversion\textual_inversion.py:133 in get_expected_shape                        │
│                                                                                                                      │
│   132 │   def get_expected_shape(self):                                                                              │
│ ❱ 133 │   │   vec = shared.sd_model.cond_stage_model.encode_embedding_init_text(",", 1)                              │
│   134 │   │   return vec.shape[1]                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'cond_stage_model'

**Comment by AbramovS1** [comment] 2023-04-21 15:21
![image](https://user-images.githubusercontent.com/56324569/233674263-e4532fc5-486c-4e05-85d2-774e5f73d5b2.png)

**Comment by AbramovS1** [comment] 2023-04-21 15:27
RuntimeError: mat1 and mat2 must have the same dtype Now there is a new error

**Comment by AbramovS1** [comment] 2023-04-21 15:28
But everything works fine in A1111 pictures + controlnet 1024x1024, which I can generate

**Comment by vladmandic** [comment] 2023-04-21 15:29
@AbramovS1 
so there is issue loading embedding??? you did not specify that earlier and that changes everything. thats why i'd like issues to be as descriptive as possible....
can you upload that embedding somewhere so i can test it?

**Comment by ricklove** [comment] 2023-04-21 15:44
@vladmandic I just installed latest with defaults and generating only **black images** (so posting here in case it is related and the additional info will be helpful)

System info in logs below

- When generating, the gpu ram usage goes from about 4.5gb to 5.2gb (so not full)
- I tried different CUDA settings mentioned above in this thread and no change

![image](https://user-images.githubusercontent.com/703880/233678457-71aae5f6-ff44-4e1d-beec-bb6819aba81d.png)


I do get a few errors when loading:

```py
venv "D:\Projects\ai\automatic\venv\Scripts\Python.exe"
10:35:31-666523 INFO     Python 3.11.3 on Windows
10:35:31-732037 INFO     Running setup
10:35:31-770037 INFO     Version: cf80857b Fri Apr 21 09:59:50 2023 -0400
10:35:32-113049 INFO     Latest published version: 57204b3d702b7586c789dbad1e1e3bd85746d81e 2023-04-21T15:32:19Z
10:35:32-115051 INFO     Updating Wiki
10:35:33-277921 INFO     nVidia toolkit detected
10:35:35-979147 INFO     Torch 2.0.0+cu118
10:35:36-001593 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
10:35:36-003741 INFO     Torch detected GPU: NVIDIA GeForce GTX 1660 SUPER VRAM 6144 Arch (7, 5) Cores 22
10:35:36-005256 INFO     Installing package: xformers==0.0.17
10:35:37-553263 INFO     Installing requirements
10:35:37-559260 INFO     Installing package: facexlib
10:35:41-540655 ERROR    Error running pip with args: install --upgrade facexlib
10:35:41-543655 INFO     Installing package: gfpgan
10:35:45-487951 ERROR    Error running pip with args: install --upgrade gfpgan
10:35:45-492952 INFO     Installing package: realesrgan
10:35:49-620407 ERROR    Error running pip with args: install --upgrade realesrgan
10:35:49-629407 INFO     Installing packages
10:35:49-631409 INFO     Installing repositories
10:35:49-818410 INFO     Installing submodules
←[2;36m10:35:52-116309←[0m←[2;36m ←[0m←[34mINFO    ←[0m Updating submodules

←[2;36m10:36:02-332416←[0m←[2;36m ←[0m←[34mINFO    ←[0m Extensions enabled: ←[1m[←[0m←[32m'a1111-sd-webui-lycoris'←[0m, ←[32m'clip-interrogator-ext'←[0m, ←[32m'LDSR'←[0m, ←[32m'Lora'←[0m,
←[2;36m                ←[0m         ←[32m'multidiffusion-upscaler-for-automatic1111'←[0m, ←[32m'prompt-bracket-checker'←[0m, ←[32m'ScuNET'←[0m, ←[32m'sd-dynamic-thresholding'←[0m,
←[2;36m                ←[0m         ←[32m'sd-extension-aesthetic-scorer'←[0m, ←[32m'sd-extension-steps-animation'←[0m, ←[32m'sd-extension-system-info'←[0m,
←[2;36m                ←[0m         ←[32m'sd-webui-controlnet'←[0m, ←[32m'sd-webui-model-converter'←[0m, ←[32m'seed_travel'←[0m, ←[32m'stable-diffusion-webui-images-browser'←[0m,
←[2;36m                ←[0m         ←[32m'stable-diffusion-webui-rembg'←[0m, ←[32m'SwinIR'←[0m←[1m]←[0m

←[2;36m10:36:25-570005←[0m←[2;36m ←[0m←[1;31mERROR   ←[0m Error running extension installer:

←[2;36m                ←[0m         D:\Projects\ai\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py

←[2;36m10:36:26-231458←[0m←[2;36m ←[0m←[34mINFO    ←[0m Extensions enabled: ←[1m[←[0m←[1m]←[0m

←[2;36m10:36:26-232459←[0m←[2;36m ←[0m←[31mWARNING ←[0m Setup complete with errors ←[1m(←[0m←[1;36m4←[0m←[1m)←[0m

←[2;36m10:36:26-233457←[0m←[2;36m ←[0m←[34mINFO    ←[0m Setting environment tuning

←[2;36m10:36:26-234458←[0m←[2;36m ←[0m←[34mINFO    ←[0m Server arguments: ←[1m[←[0m←[1m]←[0m

No module 'xformers'. Proceeding without it.
Available models: models\Stable-diffusion 1
gfpgan: ModuleNotFoundError
╭──────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────╮
│ D:\Projects\ai\automatic\modules\gfpgan_model.py:77 in setup_model                                                                 │
│                                                                                                                                    │
│    76 │   try:                                                                                                                     │
│ ❱  77 │   │   import gfpgan                                                                                                        │
│    78 │   │   import facexlib                                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'gfpgan'
real-esrgan: ModuleNotFoundError
╭──────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────╮
│ D:\Projects\ai\automatic\modules\realesrgan_model.py:20 in __init__                                                                │
│                                                                                                                                    │
│    19 │   │   │   from basicsr.archs.rrdbnet_arch import RRDBNet                                                                   │
│ ❱  20 │   │   │   from realesrgan import RealESRGANer                                                                              │
│    21 │   │   │   from realesrgan.archs.srvgg_arch import SRVGGNetCompact                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'realesrgan'
Module load: D:\Projects\ai\automatic\extensions-builtin\stable-diffusion-webui-rembg\scripts\postprocessing_rembg.py:
ModuleNotFoundError
╭──────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────╮
│ D:\Projects\ai\automatic\modules\script_loading.py:10 in load_module                                                               │
│                                                                                                                                    │
│    9 │   try:                                                                                                                      │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                                │
│   11 │   except Exception as e:                                                                                                    │
│ in exec_module:940                                                                                                                 │
│ in _call_with_frames_removed:241                                                                                                   │
│                                                                                                                                    │
│ D:\Projects\ai\automatic\extensions-builtin\stable-diffusion-webui-rembg\scripts\postprocessing_rembg.py:5 in <module>             │
│                                                                                                                                    │
│    4 from modules.ui_components import FormRow                                                                                     │
│ ❱  5 import rembg                                                                                                                  │
│    6                                                                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'rembg'
real-esrgan: ModuleNotFoundError
╭──────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────╮
│ D:\Projects\ai\automatic\modules\realesrgan_model.py:20 in __init__                                                                │
│                                                                                                                                    │
│    19 │   │   │   from basicsr.archs.rrdbnet_arch import RRDBNet                                                                   │
│ ❱  20 │   │   │   from realesrgan import RealESRGANer                                                                              │
│    21 │   │   │   from realesrgan.archs.srvgg_arch import SRVGGNetCompact                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'realesrgan'
Loading theme: black-orange
Error creating Real-ESRGAN models list
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Checkpoint model.ckpt not found; loading fallback v1-5-pruned-emaonly.safetensors [6ce0161689]
Loading weights: models\Stable-diffusion\v1-5-pruned-emaonly.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.3 GB -:--:--
Creating model from config: D:\Projects\ai\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying scaled dot product cross attention optimization
Embeddings loaded:  (0)
Model loaded in 12.9s (load=0.5s create=0.5s apply=7.2s vae=1.9s move=0.8s embeddings=2.1s)
Startup time: 25.6s (torch=4.5s gradio=2.1s libraries=1.0s codeformer=0.2s scripts=2.2s ui=2.3s start=0.1s scripts
app_started_callback=0.1s checkpoint=13.1s)

```

**Comment by AbramovS1** [comment] 2023-04-21 15:45
> @AbramovS1 
> so there is issue loading embedding??? you did not specify that earlier and that changes everything. thats why i'd like issues to be as descriptive as possible....
> can you upload that embedding somewhere so i can test it?
> 

The cleanest possible version of your solution, I didn't put anything, but only changed (--lovvram,--medvram) and swapped the value in the Cuda tab and didn't touch anything else.

**Comment by vladmandic** [comment] 2023-04-21 15:59
@ricklove python 3.11 is not supported (experimental only). there is a detailed writeup in discussions on why is that.

**Comment by ricklove** [comment] 2023-04-21 15:59
One other thing I noticed reading through manual install: I updated CUDA to CUDA Version: `12.1`, but it is using `Torch backend: nVidia CUDA 11.8 cuDNN 8700`

**Comment by vladmandic** [comment] 2023-04-21 16:00
@AbramovS1 I believe you, but its still creating runtime errors while loading embeddings - do you have anything in `/embeddings` or `/models/embeddings`?

**Comment by vladmandic** [comment] 2023-04-21 16:01
> One other thing I noticed reading through manual install: I updated CUDA to CUDA Version: `12.1`, but it is using `Torch backend: nVidia CUDA 11.8 cuDNN 8700`

That is fine, also explanation on why the reporting mismatch explained in discussions.

**Comment by AbramovS1** [comment] 2023-04-21 16:13
> @AbramovS1 I believe you, but its still creating runtime errors while loading embeddings - do you have anything in `/embeddings` or `/models/embeddings`?

/models/embeddings folder is empty

/embeddings  there is no folder

**Comment by AbramovS1** [comment] 2023-04-21 16:16
I tried to create again and got an error

gradio call: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ E:\vlad111\automatic\modules\call_queue.py:61 in f                                                                   │
│                                                                                                                      │
│    60 │   │   │   │   pr.enable()                                                                                    │
│ ❱  61 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    62 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\call_queue.py:39 in f                                                                   │
│                                                                                                                      │
│    38 │   │   │   try:                                                                                               │
│ ❱  39 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    40 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│                                               ... 25 frames hidden ...                                               │
│                                                                                                                      │
│ E:\vlad111\automatic\extensions-builtin\a1111-sd-webui-lycoris\lycoris.py:731 in lyco_Linear_forward                 │
│                                                                                                                      │
│   730 │                                                                                                              │
│ ❱ 731 │   return torch.nn.Linear_forward_before_lyco(self, input)                                                    │
│   732                                                                                                                │
│                                                                                                                      │
│ E:\vlad111\automatic\venv\lib\site-packages\torch\nn\modules\linear.py:114 in forward                                │
│                                                                                                                      │
│   113 │   def forward(self, input: Tensor) -> Tensor:                                                                │
│ ❱ 114 │   │   return F.linear(input, self.weight, self.bias)                                                         │
│   115                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: mat1 and mat2 must have the same dtype

**Comment by vladmandic** [comment] 2023-04-21 16:22
are you using `--lovvram` or `--medvram`? it seems almost like model weights get unloaded as soon as they are loaded. so other ops fail as they model does not appear as loaded.
if yes, i can start troubleshooting. but again, I wish that was noted when creating issue. There is soo much noise here that could have been avoided if proper information was provided.
if not, how come? 16xx GPUs don't have that much VRAM to start with.

**Comment by AbramovS1** [comment] 2023-04-21 16:26
> are you using `--lovvram` or `--medvram`? it seems almost like model weights get unloaded as soon as they are loaded. so other ops fail as they model does not appear as loaded. if yes, i can start troubleshooting. but again, I wish that was noted when creating issue. There is soo much noise here that could have been avoided if proper information was provided. if not, how come? 16xx GPUs don't have that much VRAM to start with.

Also with the --lovvram parameter I get an error

Traceback (most recent call last):
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\vlad111\automatic\modules\call_queue.py", line 17, in f
    res = func(*args, **kwargs)
  File "E:\vlad111\automatic\modules\ui.py", line 238, in update_token_counter
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "E:\vlad111\automatic\modules\ui.py", line 238, in <listcomp>
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "E:\vlad111\automatic\modules\sd_hijack.py", line 231, in get_prompt_lengths
    _, token_count = self.clip.process_texts([text])
AttributeError: 'NoneType' object has no attribute 'process_texts'
gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ E:\vlad111\automatic\modules\call_queue.py:61 in f                                                                   │
│                                                                                                                      │
│    60 │   │   │   │   pr.enable()                                                                                    │
│ ❱  61 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    62 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\call_queue.py:39 in f                                                                   │
│                                                                                                                      │
│    38 │   │   │   try:                                                                                               │
│ ❱  39 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    40 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│                                               ... 3 frames hidden ...                                                │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\textual_inversion\textual_inversion.py:225 in load_textual_inversion_embeddings         │
│                                                                                                                      │
│   224 │   │   self.skipped_embeddings.clear()                                                                        │
│ ❱ 225 │   │   self.expected_shape = self.get_expected_shape()                                                        │
│   226                                                                                                                │
│                                                                                                                      │
│ E:\vlad111\automatic\modules\textual_inversion\textual_inversion.py:133 in get_expected_shape                        │
│                                                                                                                      │
│   132 │   def get_expected_shape(self):                                                                              │
│ ❱ 133 │   │   vec = shared.sd_model.cond_stage_model.encode_embedding_init_text(",", 1)                              │
│   134 │   │   return vec.shape[1]                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'cond_stage_model'
WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\vlad111\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\vlad111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError

**Comment by AbramovS1** [comment] 2023-04-21 16:29
> are you using `--lovvram` or `--medvram`? it seems almost like model weights get unloaded as soon as they are loaded. so other ops fail as they model does not appear as loaded. if yes, i can start troubleshooting. but again, I wish that was noted when creating issue. There is soo much noise here that could have been avoided if proper information was provided. if not, how come? 16xx GPUs don't have that much VRAM to start with.

after I changed from FP32 to FP16, the generation process began, but still the same black screen

**Comment by vladmandic** [comment] 2023-04-21 16:29
ok, so now i have something that i can actually troubleshoot.
next time please please put all relevant information when creating issue. soo much noise here until now.

**Comment by ricklove** [comment] 2023-04-21 17:04
Cool, I got it to work without --lowvram or --medvram with these CUDA settings:

![image](https://user-images.githubusercontent.com/703880/233694143-0310bb9c-97a0-4464-91b1-d07d6e63b31a.png)

**Comment by mart-hill** [comment] 2023-04-21 18:53
> Cool, I got it to work without --lowvram or --medvram with these CUDA settings:
> 
> ![image](https://user-images.githubusercontent.com/703880/233694143-0310bb9c-97a0-4464-91b1-d07d6e63b31a.png)

These settings also helped me with Tiled VAE on my RTX 3090, previously I was getting `RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same` while using the extension. Thank you! 🙂

**Comment by vladmandic** [comment] 2023-04-22 12:51
there is a lot of different issues and noise about this problem, i've created a single issue to unify it and posted instructions there.
for anything about NaN/black images, lets continue in https://github.com/vladmandic/automatic/issues/374.
i'm keeping this issue open to track any lowvram issues only.

**Comment by vladmandic** [comment] 2023-04-22 17:15
i cannot reproduce any issues specific to `--lowvram` or `--medvram` anymore, so closing this issue.
if you do experience problems again, update here and i'll reopen. but note this is specific to issues such as `AttributeError: 'NoneType' object has no attribute 'cond_stage_model'` which indicate that model is not loaded/ready when operations are requested.

**Closed by vladmandic** 2023-04-22 17:15 UTC
Labels: bug

**Comment by gohan2091** [comment] 2023-08-15 05:16
Apologies if this is not relevant but I think it is. When using Tiled VAE (with ControlNet tiles and Tiled Diffusion), when I have the Tiled VAE settings set to default values for the encoder (3072) and I attempt to upscale an image by 2x or more, A1111 tends to go really slow, the upscaling hangs and eventually tells me it will take hours to perform. I also get the "[Tiled VAE]: the input size is tiny and unnecessary to tile.". When I lower the Tiled VAE encoder from 3072 to 2048, the "[Tiled VAE]: the input size is tiny and unnecessary to tile." message doesn't appear and the upscaling works fine taking only minutes and doesn't hang. Why is this? I have a 4090 GPU so I would imagine there is some kind of issue here....
