### ISSUE TITLE
[Issue]: not working after update (DirectML)

### ISSUE THREAD

**Issue by motorist828** [vladmandic/automatic#1418] opened 2023-06-13 22:52 UTC
### Issue Description

After update I get this
At first I thought it was the lora, but even without them I got the same thing
Then I decided to reset all settings with a new button, it did not change anything, then I deleted ui-config.json, which also did not lead to the result
A full restart didn't change either.

Using VENV: D:\neiro\last\automatic1\venv
01:35:12-797239 INFO     Starting SD.Next
01:35:12-803237 INFO     Python 3.10.6 on Windows
01:35:12-847074 INFO     Version: cb71d05d Tue Jun 13 20:08:42 2023 +0300
01:35:13-341123 INFO     Using DirectML Backend
01:35:14-946305 INFO     Torch 2.0.0+cpu
01:35:14-961082 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
01:35:15-083691 INFO     Torch detected GPU: Radeon RX Vega
01:35:15-222003 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
01:35:15-287791 INFO     Enabled extensions: ['ultimate-upscale-for-automatic1111']
01:35:15-290038 INFO     Verifying requirements
01:35:15-307825 INFO     Verifying packages
01:35:15-310074 INFO     Installing repositories
01:35:18-831670 INFO     Installing submodules
01:35:20-632553 INFO     Updating submodules
01:35:52-498965 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'ultimate-upscale-for-automatic1111']
01:35:52-504215 INFO     Updating Wiki
01:35:53-997555 INFO     Extension preload: 0.0s D:\neiro\last\automatic1\extensions-builtin
01:35:53-999799 INFO     Extension preload: 0.0s D:\neiro\last\automatic1\extensions
01:35:54-015050 INFO     Server arguments: ['--use-directml', '--medvram', '--autolaunch']
No module 'xformers'. Proceeding without it.
01:36:00-224211 INFO     Libraries loaded
01:36:00-229474 INFO     Using data path: D:\neiro\last\automatic1
01:36:00-234724 INFO     Available VAEs: D:\neiro\last\automatic1\models\VAE 0
01:36:00-249716 INFO     Available models: D:\neiro\last\automatic1\models\Stable-diffusion 1
01:36:03-514177 INFO     ControlNet v1.1.224
ControlNet preprocessor location: D:\neiro\last\automatic1\extensions-builtin\sd-webui-controlnet\annotator\downloads
01:36:03-760424 INFO     ControlNet v1.1.224
01:36:05-193403 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
01:36:08-632599 INFO     Local URL: http://127.0.0.1:7860/
01:36:08-634848 INFO     Initializing middleware
01:36:08-896338 INFO     [AgentScheduler] Task queue is empty
01:36:08-898088 INFO     [AgentScheduler] Registering APIs
01:36:09-434103 WARNING  Selected checkpoint not found: model.ckpt
01:36:09-684077 WARNING  Loading fallback checkpoint: v1-5-pruned-emaonly.safetensors [6ce0161689]
Loading weights: D:\neiro\last\automatic1\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors ------ 0.0/4… -:--:--
                                                                                                         GB
01:36:12-523346 INFO     Torch override dtype: no-half set
01:36:12-525597 INFO     Torch override VAE dtype: no-half set
01:36:12-527233 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
01:37:24-423200 INFO     Applying sub-quadratic cross attention optimization
01:37:24-433702 INFO     Embeddings: loaded=0 skipped=0
01:37:24-447201 INFO     Model loaded in 74.8s (load=2.8s create=0.5s apply=71.4s)
01:37:24-715611 INFO     Model load finished: {'ram': {'used': 8.77, 'total': 31.94}}
01:37:24-973783 INFO     Startup time: 91.0s (torch=3.7s gradio=0.9s libraries=1.6s scripts=4.8s onchange=0.1s ui=3.2s
                         launch=0.2s app-started=0.5s checkpoint=75.8s)
01:37:24-981399 INFO     Launching browser
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:40<00:00,  1.69s/it]

![Screenshot_182](https://github.com/vladmandic/automatic/assets/40582999/b17a2ca5-d5d1-419d-9736-f54a3995872f)
![01173-91818801-highres, masterpiece, 1girl, solo, (looking_at_viewer_0 778),(1girl_1 000),__](https://github.com/vladmandic/automatic/assets/40582999/dcf87e8c-6279-4ccb-945b-4d0c54e2c931)
![01174-3021589185-highres, masterpiece, 1girl, solo, (looking_at_viewer_0 778),(1girl_1 000),__](https://github.com/vladmandic/automatic/assets/40582999/add07e47-1d4b-4515-b0cb-248143808f91)

### Version Platform Description

I am using amd vega 56 8gb, ryzen 5 2600, 32gb ram, windows 10 22h2 build 19045

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment] 2023-06-13 23:02
since you've already deleted `ui-config.json` (which doesn't matter that much), can you try removing `config.json` as well?
and start server with `--safe` flag so user extensions are not loaded. just ruling things out.

**Comment by motorist828** [comment] 2023-06-13 23:19
without changes
--safe should be reflected in the console?

Using VENV: D:\neiro\last\automatic1\venv
02:13:05-055075 INFO     Starting SD.Next
02:13:05-060892 INFO     Python 3.10.6 on Windows
02:13:05-111274 INFO     Version: cb71d05d Tue Jun 13 20:08:42 2023 +0300
02:13:05-589070 INFO     Using DirectML Backend
02:13:07-189496 INFO     Torch 2.0.0+cpu
02:13:07-204105 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
02:13:07-330540 INFO     Torch detected GPU: Radeon RX Vega
02:13:07-514076 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
02:13:07-526076 INFO     Enabled extensions: ['ultimate-upscale-for-automatic1111']
02:13:07-528325 INFO     No changes detected: Quick launch active
02:13:07-533588 INFO     Extension preload: 0.0s D:\neiro\last\automatic1\extensions-builtin
02:13:07-535827 INFO     Extension preload: 0.0s D:\neiro\last\automatic1\extensions
02:13:07-550677 INFO     Server arguments: ['--use-directml', '--medvram', '--autolaunch']
No module 'xformers'. Proceeding without it.
02:13:13-861424 INFO     Libraries loaded
02:13:13-867412 INFO     Using data path: D:\neiro\last\automatic1
02:13:13-871924 INFO     Available VAEs: D:\neiro\last\automatic1\models\VAE 0
02:13:13-885437 INFO     Available models: D:\neiro\last\automatic1\models\Stable-diffusion 1
02:13:17-137504 INFO     ControlNet v1.1.224
ControlNet preprocessor location: D:\neiro\last\automatic1\extensions-builtin\sd-webui-controlnet\annotator\downloads
02:13:17-387008 INFO     ControlNet v1.1.224
02:13:18-768831 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
02:13:22-222144 INFO     Local URL: http://127.0.0.1:7860/
02:13:22-224393 INFO     Initializing middleware
02:13:22-494205 INFO     [AgentScheduler] Task queue is empty
02:13:22-496608 INFO     [AgentScheduler] Registering APIs
02:13:23-024579 WARNING  Selected checkpoint not found: model.ckpt
02:13:23-267383 WARNING  Loading fallback checkpoint: v1-5-pruned-emaonly.safetensors [6ce0161689]
Loading weights: D:\neiro\last\automatic1\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors ------ 0.0/4… -:--:--
                                                                                                         GB
02:13:23-537409 INFO     Torch override dtype: no-half set
02:13:23-539659 INFO     Torch override VAE dtype: no-half set
02:13:23-541160 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
02:13:24-946638 INFO     Applying sub-quadratic cross attention optimization
02:13:24-955402 INFO     Embeddings: loaded=0 skipped=0
02:13:24-967919 INFO     Model loaded in 1.7s (load=0.3s create=0.5s apply=0.9s)
02:13:25-235962 INFO     Model load finished: {'ram': {'used': 8.77, 'total': 31.94}}
02:13:25-476810 INFO     Startup time: 17.9s (torch=3.7s gradio=1.0s libraries=1.6s scripts=4.7s onchange=0.1s ui=3.0s
                         launch=0.5s app-started=0.5s checkpoint=2.7s)
02:13:25-485054 INFO     Launching browser
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:39<00:00,  1.63s/it]

**Comment by vladmandic** [comment] 2023-06-13 23:27
i don't have any bright ideas right now, did you try different schedulers? this looks like very early step which is weird.
and it worked before upgrade? recent changes are pretty big, but nothing that should impact this.

**Comment by OldPixelReaper** [comment] 2023-06-14 00:05
same problem with build cb71d05d under win amd

**Comment by vladmandic** [comment] 2023-06-14 00:10
hmmmm...ok, that does sound like an issue.
can you pinpoint which commit causes it (since i cannot reproduce)?

**Comment by motorist828** [comment] 2023-06-14 00:13
It's not hard for me to check the latest commits
But I don't know the correct command for this.

**Comment by OldPixelReaper** [comment] 2023-06-14 00:35
without testing it i am almost sure that commit f510abe still worked

**Comment by motorist828** [comment] 2023-06-14 00:38
I used the command git reset --hard 0d101b9
the problem occurs in https://github.com/vladmandic/automatic/commit/cb307399dd1f28014ada77d861524a075b3c626f

**Comment by OldPixelReaper** [comment] 2023-06-14 00:46
jumbo merge issue^^

**Comment by TeutonJon78** [comment] 2023-06-14 07:28
I can say that on my RX580 that cb71d05d (after the jumbo merge) is working just fine for me with DirectML (although I'm using Python 3.10.10).

Have you tried deleting your venv folding and letting it recreate that? If you haven't updated that in a while, sometimes the files get weird or some version gets conflicted.

**Comment by OldPixelReaper** [comment] 2023-06-14 11:36
Unfortunately no. I test everything again with a complete reinstallation in case of problems.

**Comment by vladmandic** [comment] 2023-06-14 15:11
it seems there is something wrong with sub-quadratic optimization in conjuction with directml.
until i figure that out, can you switch your cross-attention method (in ui settings) to something else, for example doggetx, restart server and see if that workaround resolves your issue.

**Comment by motorist828** [comment] 2023-06-14 15:45
Yes, I chose doggetx, it works with him

**Comment by vladmandic** [comment] 2023-06-14 17:01
issue is resolved in the latest update, sub-quad is back to working state.
you can either switch back to it or use any other - there is no "this one is perfect" answer.

**Closed by vladmandic** 2023-06-14 17:01 UTC
Labels: help wanted
