### ISSUE TITLE
[Extension]: Tiled Diffusion is broken, too

### ISSUE THREAD

**Issue by AndreyRGW** [vladmandic/automatic#1302] opened 2023-06-04 12:10 UTC
### Issue Description

```
15:08:50-349067 ERROR    Exception: module 'modules.sd_samplers' has no attribute 'create_sampler_original_md'
15:08:50-350067 ERROR    Arguments: args=('task(mxj66roehsu56v6)', 'anime woman, sitting,', 'EasyNegative,
                         Unspeakable-Horrors-Composition-4v, ((kid)),', [], 16, 3, False, False, 1, 1, 6.5, 2,
                         151149830.0, -1.0, 0, 0, 0, False, 512, 864, True, 0.38, 1.65, '4x-UltraSharp', 0, 0, 0, [], 0,
                         True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64,
                         False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 2048, 128, True, True, True, False,
                         False, 7, 100, 'Constant', 0, 'Constant', 0, 4,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000000017D816050>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000000014D964C10>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000000014D966C80>,
                         False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '',
                         'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0,
                         'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4,
                         'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding':
                         32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512,
                         'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7,
                         'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1,
                         'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, {'ad_model': 'None',
                         'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0,
                         'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4,
                         'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4,
                         'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32,
                         'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512,
                         'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7,
                         'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1,
                         'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, False, '', 0.5, True,
                         False, '', 'Lerp', False, False, 0.75, 1, False, False, 'positive', 'comma', 0, False, False,
                         '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False,
                         None, None, False, None, None, False, 50, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not
                         set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not
                         set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None') kwargs={}
15:08:50-357568 ERROR    gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ F:\WBC\automatic\modules\call_queue.py:34 in f                                                                       │
│                                                                                                                      │
│    33 │   │   │   try:                                                                                               │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│ F:\WBC\automatic\modules\txt2img.py:58 in txt2img                                                                    │
│                                                                                                                      │
│   57 │   if processed is None:                                                                                       │
│ ❱ 58 │   │   processed = process_images(p)                                                                           │
│   59 │   p.close()                                                                                                   │
│                                                                                                                      │
│                                               ... 4 frames hidden ...                                                │
│                                                                                                                      │
│ F:\WBC\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:373 in        │
│ <lambda>                                                                                                             │
│                                                                                                                      │
│   372 │   │   sd_samplers.create_sampler_original_md = sd_samplers.create_sampler                                    │
│ ❱ 373 │   │   sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(                           │
│   374 │   │   │   name, model, p, Method(method),                                                                    │
│                                                                                                                      │
│ F:\WBC\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:445 in        │
│ create_sampler_hijack                                                                                                │
│                                                                                                                      │
│   444 │   │   # create a sampler with the original function                                                          │
│ ❱ 445 │   │   sampler = sd_samplers.create_sampler_original_md(name, model)                                          │
│   446 │   │   if method == Method.MULTI_DIFF: delegate_cls = MultiDiffusion                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'modules.sd_samplers' has no attribute 'create_sampler_original_md'
```

### Version Platform Description

Version: b127ca48 Sun Jun 4 07:05:29 2023 -0400
Python 3.10.8 on Windows
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 2060 VRAM 12288 Arch (7, 5) Cores 34

**Comment by AndreyRGW** [comment] 2023-06-04 12:10
Although, it works if I use the Euler A sampler. I saw the supposed [solution](https://github.com/vladmandic/automatic/issues/1259#issuecomment-1573968848), but it didn't work for me. Also, it was written that the Neutral Prompt extension can cause this error, but I don't use it.

**Comment by vladmandic** [comment] 2023-06-04 12:38
can you run with `webui --debug --safe` and see what happens?

**Comment by AndreyRGW** [comment] 2023-06-04 12:41
> can you run with `webui --debug --safe` and see what happens?

```
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:08<00:00,  1.83it/s]
15:39:41-805165 DEBUG    upscale: <PIL.Image.Image image mode=RGB size=864x512 at
                         0x7F9CC130>|1.6493055555555556|F:\WBC\automatic\models\ESRGAN\4x-UltraSharp.pth
15:39:47-930391 DEBUG    Token merging model optimizations removed
15:39:47-931893 ERROR    Exception: module 'modules.sd_samplers' has no attribute 'create_sampler_original_md'
15:39:47-932893 ERROR    Arguments: args=('task(l994df456v0ynbu)', 'anime woman, sitting,', 'EasyNegative,
                         Unspeakable-Horrors-Composition-4v, ((kid)),', [], 16, 3, False, False, 1, 1, 6.5, 2,
                         151149830.0, -1.0, 0, 0, 0, False, 512, 864, True, 0.38, 1.65, '4x-UltraSharp', 0, 0, 0, [], 0,
                         True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64,
                         False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 2048, 128, True, True, True, False,
                         False, 7, 100, 'Constant', 0, 'Constant', 0, 4,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000000D90FBE80>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000000D90FAE90>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000000D90FAF20>,
                         False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True,
                         False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50)
                         kwargs={}
15:39:47-937893 ERROR    gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ F:\WBC\automatic\modules\call_queue.py:34 in f                                                                       │
│                                                                                                                      │
│    33 │   │   │   try:                                                                                               │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│ F:\WBC\automatic\modules\txt2img.py:58 in txt2img                                                                    │
│                                                                                                                      │
│   57 │   if processed is None:                                                                                       │
│ ❱ 58 │   │   processed = process_images(p)                                                                           │
│   59 │   p.close()                                                                                                   │
│                                                                                                                      │
│                                               ... 4 frames hidden ...                                                │
│                                                                                                                      │
│ F:\WBC\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:373 in        │
│ <lambda>                                                                                                             │
│                                                                                                                      │
│   372 │   │   sd_samplers.create_sampler_original_md = sd_samplers.create_sampler                                    │
│ ❱ 373 │   │   sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(                           │
│   374 │   │   │   name, model, p, Method(method),                                                                    │
│                                                                                                                      │
│ F:\WBC\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:445 in        │
│ create_sampler_hijack                                                                                                │
│                                                                                                                      │
│   444 │   │   # create a sampler with the original function                                                          │
│ ❱ 445 │   │   sampler = sd_samplers.create_sampler_original_md(name, model)                                          │
│   446 │   │   if method == Method.MULTI_DIFF: delegate_cls = MultiDiffusion                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'modules.sd_samplers' has no attribute 'create_sampler_original_md'
15:39:48-278048 DEBUG    gc: collected=260 device=cuda {'ram': {'used': 3.43, 'total': 31.93}, 'gpu': {'used': 3.31,
                         'total': 12.0}, 'retries': 0, 'oom': 0}
```

**Comment by AndreyRGW** [comment] 2023-06-04 12:58
> can you run with `webui --debug --safe` and see what happens?

Before the upgrade I was using this version - 8f4bc4df

**Comment by AndreyRGW** [comment] 2023-06-04 13:28
> > can you run with `webui --debug --safe` and see what happens?
> 
> Before the upgrade I was using this version - [8f4bc4d](https://github.com/vladmandic/automatic/commit/8f4bc4df08c48e70ea66e16c76151f1052f034c1)

I went back to this version and it doesn't have this error

**Comment by vladmandic** [comment] 2023-06-04 16:16
i cannot reproduce this - can you describe your exact workflow and settings?
also include info on ui settings -> samplers secondary and fallback samplers selected.

**Comment by AndreyRGW** [comment] 2023-06-04 16:28
> i cannot reproduce this - can you describe your exact workflow and settings? also include info on ui settings -> samplers secondary and fallback samplers selected.

Well now I have no errors, I'm on version 8f4bc4d. But at the time this issue was created I did a fresh install and I had your standard webui without any settings changes. I used model anything v5 and vae-ft-mse-840000, as well as negative embedding. Fallback sampler was Euler A.

**Comment by vladmandic** [comment] 2023-06-04 16:38
could be same root cause as #1303 as i've just fixed that.

**Comment by vladmandic** [comment] 2023-06-04 16:38
anyhow, since issue seems to be resolved, i'll close it - but if it reoccurs let me know and i'll reopen.

**Closed by vladmandic** 2023-06-04 16:38 UTC
Labels: question, extension

**Comment by SAC020** [comment] 2023-07-23 06:04
Possibly a similar problem

Using controlnet + tiled diffussion (doesn't matter if multidiffusion or mixture of diffusers, happens to both) + regional prompt control + highres fix

- if I don't activate the region prompt control, it doesn't manifest
- if primary sampler = secondary sampler, it doesn't manifest
- if primary sampler is different than secondary sampler, then it happens




`08:57:01-773216 ERROR    gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ C:\ai\automatic\modules\call_queue.py:34 in f                                                                        ││                                                                                                                      ││    33 │   │   │   try:                                                                                               ││ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    ││    35 │   │   │   │   progress.record_results(id_task, res)                                                          ││                                                                                                                      ││ C:\ai\automatic\modules\txt2img.py:65 in txt2img                                                                     ││                                                                                                                      ││   64 │   if processed is None:                                                                                       ││ ❱ 65 │   │   processed = processing.process_images(p)                                                                ││   66 │   p.close()                                                                                                   ││                                                                                                                      ││                                               ... 5 frames hidden ...                                                ││                                                                                                                      ││ C:\ai\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:362 in         ││ <lambda>                                                                                                             ││                                                                                                                      ││   361 │   │   sd_samplers.create_sampler_original_md = sd_samplers.create_sampler                                    ││ ❱ 362 │   │   sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(                           ││   363 │   │   │   name, model, p, Method(method),                                                                    ││                                                                                                                      ││ C:\ai\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:434 in         ││ create_sampler_hijack                                                                                                ││                                                                                                                      ││   433 │   │   # create a sampler with the original function                                                          ││ ❱ 434 │   │   sampler = sd_samplers.create_sampler_original_md(name, model)                                          ││   435 │   │   if method == Method.MULTI_DIFF: delegate_cls = MultiDiffusion                                          │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯AttributeError: module 'modules.sd_samplers' has no attribute 'create_sampler_original_md'
08:57:01-865967 WARNING  GPU high memory utilization: 100% {'ram': {'used': 5.76, 'total': 31.92}, 'gpu': {'used':
                         15.99, 'total': 15.99}, 'retries': 0, 'oom': 0}`
