### ISSUE TITLE
[Issue]: Can't see my thumbnails for Extra Networks

### ISSUE THREAD

**Issue by DEC1MU5** [vladmandic/automatic#1595] opened 2023-07-07 07:35 UTC
### Issue Description

My thumbnails for extra networks, most created with the civitai helper are not appearing. 
I have thousands of very nicely chosen thumbnails to make my A1111 more user friendly, and i'm loving the Vladmandic verison, but for some reason Its not working, even after refreshing. 

### Version Platform Description

Latest Vladmandic via git pull tonight, Google Chrome, Windows 11

Using VENV: C:\AI\VladMatic\venv
23:29:30-797449 INFO     Starting SD.Next
23:29:30-801450 INFO     Python 3.10.6 on Windows
23:29:30-834800 INFO     Version: 3bcca6f9 Thu Jul 6 02:51:27 2023 +0300
23:29:31-151872 INFO     nVidia CUDA toolkit detected
23:29:32-328645 INFO     Torch 2.0.1+cu118
23:29:32-352650 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:29:32-354651 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8192 Arch (8, 6) Cores 38
23:29:32-357651 INFO     Installing package: tensorflow==2.12.0
23:29:50-144201 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:29:50-155204 INFO     Enabled extensions: []
23:29:50-157204 INFO     No changes detected: Quick launch active
23:29:50-161205 INFO     Extension preload: 0.0s C:\AI\VladMatic\extensions-builtin
23:29:50-163205 INFO     Extension preload: 0.0s C:\AI\VladMatic\extensions
23:29:50-178209 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
23:29:55-986522 INFO     Libraries loaded
23:29:55-992523 INFO     Using data path: C:\AI\VladMatic
23:29:55-998525 INFO     Available VAEs: C:\AI\VladMatic\models\VAE 0
23:29:56-001525 INFO     Available models: C:\AI\VladMatic\models\Stable-diffusion 0

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by DEC1MU5** [comment] 2023-07-07 07:51
Nevermind, a fresh tab, and full restart seems to have fixed my issue. Please close the issue, but perhaps leave it for similar confused users.

**Comment by vladmandic** [comment] 2023-07-07 14:03
there are multiple reports that resetting config (or deleting config.json) solves the problem. and i cannot reproduce it locally, so unless someone finds exact root cause of the apparently corrupt config, this will be closed as-is.

**Comment by vladmandic** [comment] 2023-07-09 12:27
major update to extra networks has been published.
one outstanding issue is still #1612, otherwise if there are any other issues, please open a new one.

**Closed by vladmandic** 2023-07-09 12:27 UTC
Labels: cannot reproduce
