### ISSUE TITLE
[Issue]: Images saving with invalid file name

### ISSUE THREAD

**Issue by cybergod96** [vladmandic/automatic#1064] opened 2023-05-18 19:27 UTC
### Issue Description

Whenever I try to generate image it ends with following error:
```
Traceback (most recent call last):
  File "D:\AI\vlad-automatic\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\vlad-automatic\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\AI\vlad-automatic\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\AI\vlad-automatic\venv\lib\site-packages\gradio\components.py", line 4412, in postprocess
    file_path = str(utils.abspath(file.name))
  File "D:\AI\vlad-automatic\venv\lib\site-packages\gradio\utils.py", line 839, in abspath
    if is_symlink or path == path.resolve():  # in case path couldn't be resolved
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'outputs\\text\\00385-1929657107-landscape.jpg?1684437304.0774896'
```

The problem is question mark in the name of file. Before updating it was working without problems (version from about 4 days ago).

### Version Platform Description

Version: 314a9bf6 Thu May 18 14:55:43 2023 -0400
Setting environment tuning
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce GTX 1660 Ti VRAM 6144 Arch (7, 5) Cores 24
CUDA FP16 test passed but desired mode is set to FP32
Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
Server arguments: ['--upgrade', '--medvram']
Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'sd-webui-aspect-ratio-helper', 'sd-webui-photopea-embed', 'sd-webui-text2video',
                         'ultimate-upscale-for-automatic1111']

Windows 10, Chrome

**Comment by vladmandic** [comment] 2023-05-18 19:41
i cannot reproduce, but just pushed a blind change that might help - please update and retry.
if problem persists, run `webui --debug` to capture more details before this error.

**Comment by cybergod96** [comment] 2023-05-18 19:56
It didn't help. There were some errors during update ([setup_error.log](https://github.com/vladmandic/automatic/files/11511168/setup_error.log)) but app launched anyway (don't know if it matters).

Here are logs with debug enabled:
[generation_log.txt](https://github.com/vladmandic/automatic/files/11511169/generation_log.txt)
[setup_debug.log](https://github.com/vladmandic/automatic/files/11511170/setup_debug.log)

**Comment by vladmandic** [comment] 2023-05-19 00:28
ok, should be fixed now.

**Closed by vladmandic** 2023-05-19 00:28 UTC
Labels: question
