### ISSUE TITLE
[Issue]: From Image bottom dropdown menus make UI extremely sluggish

### ISSUE THREAD

**Issue by Gushousekai195** [vladmandic/automatic#2157] opened 2023-09-08 22:12 UTC
### Issue Description

The latest update has broken the From Image tab. When I click on the drop down menus such as Tiled VAE, ControlNet, etc. the UI becomes very sluggish and intermittently locks up. ControlNet models do not load. Am not able to click to other tabs in the UI.

SD.Next has been rendered unusable for me now.

### Version Platform Description

app: automatic.git
updated: 2023-09-08
hash: 5b41115b
url: https://github.com/vladmandic/automatic.git/tree/master

device: NVIDIA GeForce RTX 3090 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700
driver: 531.61

Edition	Windows 10 Home
Version	20H2
Installed on	‎4/‎30/‎2021
OS build	19042.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

Google Chrome Version 116.0.5845.180 (Official Build) (64-bit)

### Relevant log output

```shell
Nothing appears in the log when the sluggishness happens.
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment] 2023-09-09 04:30
> SD.Next has been rendered unusable for me now.

i'll check, but keep in mind this is free and open-source - your tone is not appreciated

**Comment by vladmandic** [comment] 2023-09-09 13:28
i've tried and i cannot reproduce. is there anything in browser console log?

**Comment by chmatse** [comment] 2023-09-10 08:36
I can confirm, that this happens. It just happend to me 30min agon with Firefox. I can just not reproduce it :-( Currently i have the issue, that the UI (with most themes) looks horrible (compared to before my holiodays). So i tried to create my own temporary css. While doing this, i was constantly testing and reloading either the UI-Website or SD.Next. From time to time i could reproduce this behaviour, but i was thinking that i messed something up while doing changes in my css.

What i also encountered then, was some heavy load usage on Firefox on Windows. So i closed all relevant Tabs and stopped SD.Next. Then restarted SD.Next, opened a new tab and everything worked normal. In the last 36h i encountered this situation 3 times. But as said before, did not pay to much attention to it.

Since i am still fiddeling around with my css, changes are that this happens again. Do you have any suggestion or measures i should do, when this happens again?

**Comment by vladmandic** [comment] 2023-09-10 12:09
> that the UI (with most themes) looks horrible (compared to before my holidays)

are you referring to gradio upgrade that occured on 08/25 or something more recent?
what exactly looks bad?

> Do you have any suggestion or measures i should do, when this happens again (in terms of, gaining information that could help you to find out what the cause could be)?

first thing check browser console log - is there anything that goes bad during loading when this problem occurs?

**Comment by chmatse** [comment] 2023-09-10 17:10
> > that the UI (with most themes) looks horrible (compared to before my holidays)
> 
> are you referring to gradio upgrade that occured on 08/25 or something more recent? what exactly looks bad?

I guess, yes. I did not use SD.Next in August for holiday and other reasons and just started again a few days ago. Since you did so many changes since my last use, i decided to create a fresh install with a fresh conda environment. The first thing i noticed, that my favorite theme [bethecloud/storj_theme] has disappeared. To shorten this story, i could fix it by duplicating the theme on huggingface and fixing the issues, which made [STiGMaTaCH/stig_storj] as a newly selectable theme available.

But the joy lasted only a short time. Everything was now so squeezed together, Spaces were missing, dropdowns had no beginning and end because they were no longer graphically separated from the options of the previous dropdown etc. Testing other themes i found, that allmost all have these kind of problems. It is difficult to write about the errors so [i have made a comparsion screenshot](https://www.matse.ch/errors/gradio_base-mess.png) with the [gradio/base] theme. On the right you see the content of [sdnext\html\gradio-base.jpg] and on the left how it currently looks to me.

* For example, every element is now completely attached to the left border whereas the [gradio-base.jpg] has some space on the left.
* The upper border (between the [From Image], [From Text] Tabs and the input prompt) can not even be seen because there is also no space in between and border and input field have the same color.
* Or for example the Dropdowns look like a grey wall. You can not distinguish where the [Tiled Diffusion] Dropdown ends and the [Tiled VAE] begins.
* Even the Seed details look like a grey wall. You can not distinguish between the Label [Seed] and the Input Field [-1]
* Also some round corners are lost. Check the surrounding of the Dice from the Seed Block.

So i thought, maybe i only need to add som padding/spacing here, soome -radius values there. But Gradio and the Theme stuff is more difficult, than i thought ;-) And this is the reason, why i needed to do so many reloads and hence how i also spotted the problems Gushousekai195 described **_but with one difference_**. For me it did not happen in the [From Image] tab but in the default [From Text] Tab. The dropdowns did no open/close anymore or with a few seconds of delay. And the second time i also noticed the heavy load which re-appeared the third time.


> > Do you have any suggestion or measures i should do, when this happens again (in terms of, gaining information that could help you to find out what the cause could be)?
> 
> first thing check browser console log - is there anything that goes bad during loading when this problem occurs?

I will do that if i encounter it again.

**Comment by vladmandic** [comment] 2023-09-10 18:53
ah, your visual issues are with custom themes. i only test with built-in themes, haven't checked how ui looks with gradio 3rd party themes in a while. but yes, new gradio made quite a few changes i don't agree with and it was a total mess - but i don't have the luxury on staying on old version forever (i've delayed upgrading gradio for a looong time).
nothing that cannot be fixed by modifying styles.css - i just don't prioritize adjusting styles for 3rd party themes.
and quite possible fixes are in built-in themes already (see black-teal which is the new default) - in which case, it just has to be moved from specific theme into main styles.css. if you find which settings, i have not problem doing that.

anyhow, that's pretty much unrelated to the issue reported by @Gushousekai195

**Comment by vladmandic** [comment] 2023-09-11 14:07
dropdown menus have been restyled a bit, that should improve worst-case behavior.
if issue reoccurs, update here with relevant information and i'll reopen.

**Closed by vladmandic** 2023-09-11 14:07 UTC
Labels: cannot reproduce
