### ISSUE TITLE
[Issue]: error on start webui.bat with win10

### ISSUE THREAD

**Issue by tcflying** [vladmandic/automatic#123] opened 2023-04-14 04:29 UTC
### Issue Description

venv "F:\stable-diffusion-webui\venv\Scripts\Python.exe"
Installing requirements for Web UI
Running extension installer: F:\stable-diffusion-webui\extensions\clip-interrogator-ext\install.py
A Installing requirements for CLIP Interrogator

Running extension installer: F:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\ebsynth_utility\install.py
A current transparent-background 1.2.3

Running extension installer: F:\stable-diffusion-webui\extensions\PBRemTools\install.py
A Installing None
Installing onnxruntime-gpu...
Installing None
Installing opencv-python...
Installing None
Installing Pillow...
Installing None
Installing segmentation-refinement...
Installing None
Installing scikit-learn...

Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-3d-open-pose-editor\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-controlnet\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-nulienhance\install.py
A Installed.

Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-segment-anything\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py
A Stop Motion CN - Running Preload
Set Gradio Queue: True
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 google-auth-oauthlib-0.4.6 tensorboard-2.12.0 transformers-4.26.1
[+] xformers version 0.0.17.dev464 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Running extension installer: F:\stable-diffusion-webui\extensions\stable-diffusion-webui-blip2-captioner\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\stable-diffusion-webui-rembg\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\unprompted\install.py
A Installing requirements for Unprompted - img2pez
Installing requirements for Unprompted - pix2pix_zero

Running extension installer: F:\stable-diffusion-webui\extensions\video2video\install.py
A Installing video2video requirement: sk-video

Launching Web UI with arguments:
F:\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: otobuf is an invalid version and will not be supported in a future release
  warnings.warn(
Stop Motion CN - Running Preload
Set Gradio Queue: True
Error running preload() for F:\stable-diffusion-webui\extensions-builtin\sd-webui-controlnet\preload.py
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\stable-diffusion-webui\modules\script_loading.py:28 in preload_extensions                                        │
│                                                                                                                     │
│   27             if hasattr(module, 'preload'):                                                                     │
│ > 28                 module.preload(parser)                                                                         │
│   29                                                                                                                │
│                                                                                                                     │
│ F:\stable-diffusion-webui\extensions-builtin\sd-webui-controlnet\preload.py:2 in preload                            │
│                                                                                                                     │
│   1 def preload(parser):                                                                                            │
│ > 2     parser.add_argument("--controlnet-dir", type=str, help="Path to directory with Contr                        │
│   3     parser.add_argument("--no-half-controlnet", action='store_true', help="do not switch                        │
│                                                                                                                     │
│                                               ... 4 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\argparse.py:1592 in _check_conflict              │
│                                                                                                                     │
│   1591             conflict_handler = self._get_handler()                                                           │
│ > 1592             conflict_handler(action, confl_optionals)                                                        │
│   1593                                                                                                              │
│                                                                                                                     │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\argparse.py:1601 in _handle_conflict_error       │
│                                                                                                                     │
│   1600                                      in conflicting_actions])                                                │
│ > 1601         raise ArgumentError(action, message % conflict_string)                                               │
│   1602                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ArgumentError: argument --controlnet-dir: conflicting option string: --controlnet-dir

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\stable-diffusion-webui\launch.py:311 in <module>                                                                 │
│                                                                                                                     │
│   310     prepare_environment()                                                                                     │
│ > 311     start()                                                                                                   │
│   312                                                                                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\launch.py:302 in start                                                                    │
│                                                                                                                     │
│   301     print(f"Launching {'API server' if '--nowebui' in sys.argv else 'Web UI'} with argum                      │
│ > 302     import webui                                                                                              │
│   303     if '--nowebui' in sys.argv:                                                                               │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\modules\shared.py:34 in <module>                                                          │
│                                                                                                                     │
│    33 script_loading.preload_extensions(extensions_dir, parser)                                                     │
│ >  34 script_loading.preload_extensions(extensions_builtin_dir, parser)                                             │
│    35                                                                                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\modules\script_loading.py:32 in preload_extensions                                        │
│                                                                                                                     │
│   31             print(f"Error running preload() for {preload_script}", file=sys.stderr)                            │
│ > 32             shared.exception()                                                                                 │
│   33                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: partially initialized module 'modules.shared' has no attribute 'exception' (most likely due to a
circular import)
请按任意键继续. . .

### Platform Description

Please fill this form with as much information as possible

**Comment by vladmandic** [comment] 2023-04-14 12:28
closing as duplicate of #102

**Closed by vladmandic** 2023-04-14 12:28 UTC
