### ISSUE TITLE
[Issue]: DirectML causes error in txt2img when trying to generate image

### ISSUE THREAD

**Issue by Centurion-Rome** [vladmandic/automatic#1230] opened 2023-05-31 09:03 UTC
### Issue Description

I want to try DirectML and image generation causes error. Maybe it is only on my system?

Steps to reproduce:

1. Use  Server arguments: ['--autolaunch', '--medvram', '--upgrade', '--use-directml', '--safe']
2. Start UI, see info saying everything its ok:

```
10:48:29-163902 INFO     Using DirectML Backend
10:48:31-084947 INFO     Torch 2.0.0+cu118
10:48:31-119041 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
10:48:31-852912 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 SUPER
```

3. try to generate image in txt2img, press generate.

```
DDIM Sampler:   0%|                                                                                                               | 0/16 [00:02<?, ?it/s]
10:56:21-834971 ERROR    Exception: Wrong parameter.
10:56:21-836131 ERROR    Arguments: args=('task(sc2k1cmqe3ohb5o)', 'star', 'foggy, blurry,
                         duplicate,', [], 15, 5, False, False,
                         1, 1, 6, 1, -1.0, -1.0, 0, 0, 0, False, 768, 1024, False, 0.63, 1.6, 'Latent (antialiased)', 0, 0, 0, [], 0, False, '',
                         'keyword1, keyword2', 'None', 'textual inversion first', 'None', '0.7', 'None', False, 'MultiDiffusion', False, True, 1024, 1024,
                         96, 96, 48, 1, 'remacri', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 768, 96, True, True, True, False,
                         False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, 'x264', 'blend', 10, 0, 0, False, True, True, True, 'intermediate',
                         'animation', <controlnet.py.UiControlNetUnit object at 0x000001EB9B535690>, <controlnet.py.UiControlNetUnit object at
                         0x000001ECA7FCE4D0>, True, 0.25, 1, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [],
                         True, False, False, False, 0, False, None, None, False, None, None, False, 50, False, 4.0, '', 10.0, 'Linear', 3, False, 30.0,
                         True, False, False, 0, 0.0, 'Lanczos', 1, True, 0, 0, 0.001, 75, 0.0, False, True, 0, 0, 512, 512, False, True, False, False, 0,
                         1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, False, False, False,
                         False, False, False, 'u2net', False, True, False) kwargs={}
10:56:21-845650 ERROR    gradio call: RuntimeError
╭────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────╮
│ F:\!AI\StableDiffusion\automatic\modules\call_queue.py:34 in f                                                                                         │
│                                                                                                                                                        │
│    33 │   │   │   try:                                                                                                                                 │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                                                      │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                                                            │
│                                                                                                                                                        │
│ F:\!AI\StableDiffusion\automatic\modules\txt2img.py:57 in txt2img                                                                                      │
│                                                                                                                                                        │
│   56 │   if processed is None:                                                                                                                         │
│ ❱ 57 │   │   processed = process_images(p)                                                                                                             │
│   58 │   p.close()                                                                                                                                     │
│                                                                                                                                                        │
│                                                                ... 32 frames hidden ...                                                                │
│                                                                                                                                                        │
│ F:\!AI\StableDiffusion\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                                                  │
│                                                                                                                                                        │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                                                         │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                                                                │
│   1502 │   │   # Do not call functions when jit is used                                                                                                │
│                                                                                                                                                        │
│ F:\!AI\StableDiffusion\automatic\modules\sd_hijack_optimizations.py:398 in scaled_dot_product_attention_forward                                        │
│                                                                                                                                                        │
│   397 │   # the output of sdp = (batch, num_heads, seq_len, head_dim)                                                                                  │
│ ❱ 398 │   hidden_states = torch.nn.functional.scaled_dot_product_attention(                                                                            │
│   399 │   │   q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False                                                                                  │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Wrong parameter.
```

### Version Platform Description

Windows 11, Edge, RTX 2080 Super 8GB VRAM
 Version: d1ab205d Tue May 30 17:15:52 2023 -0400

**Comment by myndxero** [comment] 2023-05-31 11:09
I was messing around with directml and getting a cross-attention error or something. I am completely a pleb to this, prob have a setting wrong, but thought maybe asking you, you might know. I switched to directml, did a --reinstall so it would grab the right packages (i assume) torch+cpu it looked like it swapped me to, so I disabled SDP, both xformers cross attention and SDP disable cross attention are unchecked.

Image processes to final step but then errors. If it's an easy answer/fix cool. It was just an idle curiosity. Lots of different things I know nothing about have been popping up lately. I remember tensorRT popping out of nowhere not too long ago, but then I phased out for awhile.

**Comment by vladmandic** [comment] 2023-05-31 11:41
for directml, you shouldn't be using sdp, best one is probably sub-quadratic.
but it still shouldn't error out like that.
looping in @lshqqytiger

**Comment by myndxero** [comment] 2023-05-31 12:00
> , but it is not burning problem for me, we can use "normal" way ;)

Agreed. It seems much slower for me too but was just an idle-curiousity. Switched to sub-quadratic and it still crashes tho my error is almost the same as OP's error now with slightly different numbers. I was getting 4.63 it/s on a test prompt I was just getting 10.23 it/s before changing the settings and relaunching.

```
2023-05-31 06:58:24,626 - sd_dynamic_prompts.dynamic_prompting - INFO - Prompt matrix will create 1 images in a total of 1 batches.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:06<00:00,  4.63it/s]
06:58:30-767964 ERROR    Exception: No operator found for `memory_efficient_attention_forward` with inputs:
                              query       : shape=(1, 4096, 1, 512) (torch.float32)
                              key         : shape=(1, 4096, 1, 512) (torch.float32)
                              value       : shape=(1, 4096, 1, 512) (torch.float32)
                              attn_bias   : <class 'NoneType'>
                              p           : 0.0
                         `cutlassF` is not supported because:
                             device=privateuseone (supported: {'cuda'})
                         `flshattF` is not supported because:
                             device=privateuseone (supported: {'cuda'})
                             dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
                             max(query.shape[-1] != value.shape[-1]) > 128
                         `tritonflashattF` is not supported because:
                             device=privateuseone (supported: {'cuda'})
                             dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
                             max(query.shape[-1] != value.shape[-1]) > 128
                             triton is not available
                         `smallkF` is not supported because:
                             device=privateuseone (supported: {'cpu', 'cuda'})
                             max(query.shape[-1] != value.shape[-1]) > 32
                             unsupported embed per head: 512
06:58:30-770965 ERROR    Arguments: args=('task(dhgm3j06yzowag7)', 'masterpiece, realistic, (((perfect))), photorealistic, ultrarealism,
                         (official art), 1girl, bobcut, blue eyes, brunette, serious look on face, (sleeveless red dress), (white
                         thighhighs), (hightops), hands on handlebars, ((riding on motorcyle)), speeding, looking at viewer, highway,
                         scenery, dusk, raining, puddles, bokeh, intricate, highly detailed, motion lines', 'nsfw, lowres, ((mangled)),
                         inaccurate, mutated, mutant, tumor, growth, cancer, guro, injury, violence, (deformed), (bad anatomy),
                         (disembodied limbs), bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality,
                         low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry', [], 28, 1, False, False, 1,
                         1, 11, 2, 1747816934.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.6, 2, 'Latent', 10, 0, 0, [], 0, 0, 4, 512, 512,
                         True, 'None', 'None', 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, 10,
                         1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4,
                         0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0,
                         False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2,
                         -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True,
                         True, True, False, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <controlnet.py.UiControlNetUnit object at
                         0x0000021DEA8718A0>, <controlnet.py.UiControlNetUnit object at 0x0000021DEA8735E0>,
                         <controlnet.py.UiControlNetUnit object at 0x0000021DEA873280>, <controlnet.py.UiControlNetUnit object at
                         0x0000021DEA8A30D0>, <controlnet.py.UiControlNetUnit object at 0x0000021DEA88C910>, True, False, 1, False, False,
                         False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '',
                         False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False,
                         False, None, True, False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False,
                         'Attention', False, '0', '0', '0.4', None, False, 0.75, 1, 0, False, '', '', '', '', '', '', '', '', '', '', '',
                         '', '', False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, True,
                         -1.0, True, False, False, 'positive', 'comma', 25, False, False, '', 0, '', [], 0, '', [], 0, '', [], True,
                         False, False, False, 25, False, None, None, False, None, None, False, None, None, False, None, None, False, None,
                         None, False, 50) kwargs={}
06:58:30-775964 ERROR    gradio call: NotImplementedError
╭────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────╮
│ C:\automatic\modules\call_queue.py:34 in f                                                                                             │
│                                                                                                                                        │
│    33 │   │   │   try:                                                                                                                 │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                                      │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                                            │
│                                                                                                                                        │
│ C:\automatic\modules\txt2img.py:57 in txt2img                                                                                          │
│                                                                                                                                        │
│   56 │   if processed is None:                                                                                                         │
│ ❱ 57 │   │   processed = process_images(p)                                                                                             │
│   58 │   p.close()                                                                                                                     │
│                                                                                                                                        │
│                                                        ... 17 frames hidden ...                                                        │
│                                                                                                                                        │
│ C:\automatic\venv\lib\site-packages\xformers\ops\fmha\dispatch.py:98 in _dispatch_fw                                                   │
│                                                                                                                                        │
│    97 │   │   priority_list_ops.insert(0, triton.FwOp)                                                                                 │
│ ❱  98 │   return _run_priority_list(                                                                                                   │
│    99 │   │   "memory_efficient_attention_forward", priority_list_ops, inp                                                             │
│                                                                                                                                        │
│ C:\automatic\venv\lib\site-packages\xformers\ops\fmha\dispatch.py:73 in _run_priority_list                                             │
│                                                                                                                                        │
│    72 │   │   msg += "\n" + _format_not_supported_reasons(op, not_supported)                                                           │
│ ❱  73 │   raise NotImplementedError(msg)                                                                                               │
│    74                                                                                                                                  │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 4096, 1, 512) (torch.float32)
     key         : shape=(1, 4096, 1, 512) (torch.float32)
     value       : shape=(1, 4096, 1, 512) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    device=privateuseone (supported: {'cuda'})
`flshattF` is not supported because:
    device=privateuseone (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    max(query.shape[-1] != value.shape[-1]) > 128
`tritonflashattF` is not supported because:
    device=privateuseone (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    max(query.shape[-1] != value.shape[-1]) > 128
    triton is not available
`smallkF` is not supported because:
    device=privateuseone (supported: {'cpu', 'cuda'})
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 512

```

**Comment by vladmandic** [comment] 2023-05-31 12:01
`xformers` definitely doesn't work without cuda. why are they even installed? they should only be installed if you set cross attention to xformers at some point in the past. can you uninstall them?

**Comment by lshqqytiger** [comment] 2023-05-31 13:22
I can't reproduce this issue because I met OOM with my RX 5700 XT and Scaled Dot Product.

**Comment by vladmandic** [comment] 2023-05-31 14:28
> Vlad mentioned we shouldn't be using SDP with it. Suggests trying sub-quadratic.

He's just trying to help you by trying to reproduce - he's the subject-matter-expert for DirectML :)

**Comment by lshqqytiger** [comment] 2023-05-31 14:37
Sub-quadratic is recommended, but SDP should work too. (it is reported to provide better performance for large vram gpus than sub-quadratic)
What I think now is that there is something went wrong on your internal implementation of `torch-directml`.

**Comment by Baskhara** [comment] 2023-06-01 15:06
> > did a --reinstall
> 
> Thank you for the suggestion. I have tried it also and switched to "sub-quadratic" as suggested by vladmandic. Still getting error after generation like you:
> 
> ```
> 13:50:58-852834 ERROR    gradio call: NotImplementedError
> ╭────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────╮
> │ F:\!AI\StableDiffusion\automatic\modules\call_queue.py:34 in f                                                                                         │
> │                                                                                                                                                        │
> │    33 │   │   │   try:                                                                                                                                 │
> │ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                                                      │
> │    35 │   │   │   │   progress.record_results(id_task, res)                                                                                            │
> │                                                                                                                                                        │
> │ F:\!AI\StableDiffusion\automatic\modules\txt2img.py:57 in txt2img                                                                                      │
> │                                                                                                                                                        │
> │   56 │   if processed is None:                                                                                                                         │
> │ ❱ 57 │   │   processed = process_images(p)                                                                                                             │
> │   58 │   p.close()                                                                                                                                     │
> │                                                                                                                                                        │
> │                                                                ... 18 frames hidden ...                                                                │
> │                                                                                                                                                        │
> │ F:\!AI\StableDiffusion\automatic\venv\lib\site-packages\xformers\ops\fmha\dispatch.py:98 in _dispatch_fw                                               │
> │                                                                                                                                                        │
> │    97 │   │   priority_list_ops.insert(0, triton.FwOp)                                                                                                 │
> │ ❱  98 │   return _run_priority_list(                                                                                                                   │
> │    99 │   │   "memory_efficient_attention_forward", priority_list_ops, inp                                                                             │
> │                                                                                                                                                        │
> │ F:\!AI\StableDiffusion\automatic\venv\lib\site-packages\xformers\ops\fmha\dispatch.py:73 in _run_priority_list                                         │
> │                                                                                                                                                        │
> │    72 │   │   msg += "\n" + _format_not_supported_reasons(op, not_supported)                                                                           │
> │ ❱  73 │   raise NotImplementedError(msg)                                                                                                               │
> │    74                                                                                                                                                  │
> ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
>      query       : shape=(1, 12288, 1, 512) (torch.float32)
>      key         : shape=(1, 12288, 1, 512) (torch.float32)
>      value       : shape=(1, 12288, 1, 512) (torch.float32)
>      attn_bias   : <class 'NoneType'>
>      p           : 0.0
> `cutlassF` is not supported because:
>     device=privateuseone (supported: {'cuda'})
> `flshattF` is not supported because:
>     device=privateuseone (supported: {'cuda'})
>     dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
>     max(query.shape[-1] != value.shape[-1]) > 128
> `tritonflashattF` is not supported because:
>     device=privateuseone (supported: {'cuda'})
>     dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
>     max(query.shape[-1] != value.shape[-1]) > 128
>     triton is not available
> `smallkF` is not supported because:
>     device=privateuseone (supported: {'cpu', 'cuda'})
>     max(query.shape[-1] != value.shape[-1]) > 32
>     unsupported embed per head: 512
> ```
> 
> , but it is not burning problem for me, we can use "normal" way ;)

Got this error on Nvidia as well if xformers is installed when trying --use-directml. Uninstalling xformers solved those error, for me at least.

**Comment by lshqqytiger** [comment] 2023-06-01 16:44
How to reveal hidden errors or is there somewhere full error traceback logged? I think it will be helpful if I can get full error traceback.

**Comment by vladmandic** [comment] 2023-06-01 17:29
but `import_hook.py` gets triggered as one of the first things in `webui.py`, much earlier than `ldm`?
unless `ldm` import gets triggered in extensions preload (which happens before `webui` itself)?

**Comment by TheOnlyHolyMoly** [comment] 2023-06-01 17:43
@vladmandic @lshqqytiger: I am coming one step further in the process so far. I can at least generate images before the system throws saving errors.

**Comment by lshqqytiger** [comment] 2023-06-02 03:04
> but `import_hook.py` gets triggered as one of the first things in `webui.py`, much earlier than `ldm`?
> unless `ldm` import gets triggered in extensions preload (which happens before `webui` itself)?

`import_hook.py` imports `shared.py`.
All of the hijacks for DirectML start there, so we have to move it.
But it isn't enough. There is another import of `ldm` before `import_hook.py` without hijacks for DirectML.
These days, I don't have much time to spend here. I'll be free after the middle of June.

**Comment by vladmandic** [comment] 2023-06-02 03:14
> import_hook.py imports shared.py.

ahhhh...silly...i'll get rid of import_hook.py and move the functionality directly into installer.py before webui.py ever gets triggered.

> These days, I don't have much time to spend here. I'll be free after the middle of June.

take care and thanks for all the help so far!

**Comment by Yodrik** [comment] 2023-06-02 08:34
Centurion-Rome, you still have --medvram set, right? And could you share what the image size/batch count/size you are trying for?
A lot of us AMD users cannot generate large images directly under DirectML. We end up needing to TiledDiffuse, upscale, scale up process after initial generation. I think my best sizes were up to 1024px, but usually 800-900px were doable in batches of 7-9 at the most (with 8 GB VRAM).

**Comment by brknsoul** [comment] 2023-06-02 11:13
> but usually 800-900px 

For me (6600 XT 8Gb), the max I can get is a H+W combination of 1408 (eg: 704x704, or 640x768)

I've yet to actually play around with Tiled Diffusion for mega upscaling.

**Comment by TheOnlyHolyMoly** [comment] 2023-06-02 12:26
@Centurion-Rome this is really interesting that this works on your machine, on my 4090 and DirectML I am running OOM already at 768x768 with batch=1, hiresfix and 2x upscaling. Limited to 16 GB of RAM though.

**Comment by Yodrik** [comment] 2023-06-04 07:17
@Centurion-Rome Nowadays I (AMD RX6600 8GB w/ DirectML) use ROCm in a dual boot Ubuntu, so I have my Windows-DirectML setup on commit e0486799 and assumed 10 steps for the below.

In DirectML (Sub-quadratic) :
A): Image size 864x576 Batch size: 1 = **Works (same)**
B) mage size 864x576 Batch size: 2 => **OOM (same)**
C): Image size 1024x576 Batch size: 1 = **Works (same)**
D) Image size 864x576 Batch size: 1 + using additional Hires.Fix Latent x 1.6 (864x576 to 1382x921 => **OOM (same)**

a) 768x768 Batch=1 (no Hires): **Works**
b) 512x512 Batch=1:  **Works (See note)**
c) 512x512 Batch=1+ HiresFix x2 (1024x1024): **OOM (same)**
d) 448x448 Batch=1+ HiresFix x2 ( to 896x896) = **Works**

Hires sort of works off and on (512x448 to 1024x896 works), but usually doing Hires or a bigger size I have to close up anything touching the GPU (no YouTube while waiting, etc). I don't use Tiled/Multi Diffusion normally so I can't comment if it should be working better in this case.

Note: I have observed in my case in both Auto1111 and SD.Next that 512x512 tends to be hit and miss. Sometimes nothing but OOM, and sometimes perfectly fine. Change the resolution a bit and poof it works perfectly. Go back to 512x512 nothing but OOM. It is weird, but I've learned to accept it. 

On this topic though, both Nvidia and AMD have released drivers with notes about MS Olive(?) DirectML optimization. I haven't seen anything in regards to if the optimizations help memory management with those Olive models, but [there are speed improvements in some cases](https://www.reddit.com/r/StableDiffusion/comments/13qy8cx/a1111_vs_olive_vs_aitemplate/).

**Comment by vladmandic** [comment] 2023-06-05 11:45
Olive DirectML optimizations refer to ONNX backend, not Torch.  
Unfortunately, DirectML for Torch is quite inferior at the moment and it does use more memory than normal Torch, so really not sure if if there is anything I can do here.

**Comment by TeutonJon78** [comment] 2023-06-06 15:46
@Yodrik Multitiled diffusion doesn't with DirectML per the extension's author. It will always generate black squares in the lower left corner. It's some bug with DirectML and large tensors and not setting the initial conditions correctly.

For my RX580, it always hard locks my computer with black screen and all fans whirring at max at about 90%.

**Comment by lshqqytiger** [comment] 2023-06-28 16:11
Its tensor implementation extends `OpaqueTensorImpl` which does not have the storage.

**Comment by vladmandic** [comment] 2023-07-23 15:44
closing due to lack of updates.

**Closed by vladmandic** 2023-07-23 15:44 UTC
Labels: platform
