### ISSUE TITLE
[Issue]: Images not showing in preview

### ISSUE THREAD

**Issue by west1778** [vladmandic/automatic#305] opened 2023-04-20 17:56 UTC
### Issue Description

I'm a bit of a newb when it comes to why something isn't happening but when I generate an image it will show the preview in the preview window for a second but then goes to blank if I click on the show button it shows the image in the folder that opens but nothing on the image preview window.

### Version Platform Description

 Version: 752b91d3 Thu Apr 20 12:29:54 2023 -0400

Windows 11 Insider Preview 10.0.22624.1391 (ni_release)

Tried two different browsers, Opera GX - LVL 4 (core: 97.0.4719.84) & Chromium Version 114.0.5704.0 (Developer Build) (64-bit)

**Comment by vladmandic** [comment] 2023-04-20 17:59
what are your settings in UI -> Settings -> Live Preview
try setting show new live preview... to 1

**Comment by west1778** [comment] 2023-04-20 18:07
After generating the image shows that it was made in the folder but the UI doesn't see it at all I think. 
![image](https://user-images.githubusercontent.com/73608023/233451204-f85306b1-1a08-43af-a6bd-dfa53788a0b6.png)
This is if I try to send the image to Img2Img with the ---> button if it helps at all to trace the issue.

**Comment by myndxero** [comment] 2023-04-20 22:02
![Screenshot_20230420-170129](https://user-images.githubusercontent.com/113237671/233496871-e6b3bcf2-8eb5-492e-89b6-48df1c125501.png)
 He means here I believe.

**Comment by Averytingwong** [comment] 2023-04-21 07:55
Having this issue as well on automatic1111, think it has to do with gradio 3.23.0. I have another instance of automatic1111 running with gradio 3.16.2 and it is not having this issue.

**Comment by west1778** [comment] 2023-04-21 15:46
> ![Screenshot_20230420-170129](https://user-images.githubusercontent.com/113237671/233496871-e6b3bcf2-8eb5-492e-89b6-48df1c125501.png) He means here I believe.
> 
> Those errors you have in console I think mean you're doing img 2 img, without a base IMG chosen.

Oh yes I knew what he was referring to. It does the same thing though. I reinstalled everything started working so I don't know lol

**Comment by erebous** [comment] 2023-04-21 16:12
same here while training textual inversion, error:
`│ D:\ai\automatic\modules\textual_inversion\textual_inversion.py:601 in train_embedding                               │
│                                                                                                                     │
│   600 │   │   │   │   │   │   captioned_image = caption_image_overlay(image, title, footer_lef                      │
│ > 601 │   │   │   │   │   │   captioned_image = insert_image_data_embed(captioned_image, data)                      │
│   602                                                                                                               │
│                                                                                                                     │
│ D:\ai\automatic\modules\textual_inversion\image_embedding.py:74 in insert_image_data_embed                          │
│                                                                                                                     │
│    73 │                                                                                                             │
│ >  74 │   h = image.size[1]                                                                                         │
│    75 │   next_size = data_np_low.shape[0] + (h-(data_np_low.shape[0] % h))                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: 'int' object is not subscriptable`

**Comment by vladmandic** [comment] 2023-04-21 16:13
how is `Images not showing in preview` **SAME** as "error during TI training"?

**Comment by erebous** [comment] 2023-04-21 16:22
I noticed the preview image disappears from the UI, that console error and though it's a preview error

**Comment by pixelsurium** [comment] 2023-04-21 19:50
I have the same issue since the last update (24h before it worked). After pressing "generate" the image appears NOT in the UI. Pressing "send to img2img" or inpain etc. brings an error

![image](https://user-images.githubusercontent.com/128645410/233722837-ca354484-3114-4e0c-9bef-b0c94a60d02c.png)

**Comment by SOELexicon** [comment] 2023-04-24 21:16
get the same. running
22:07:17-722456 INFO     Python 3.10.11 on Windows
22:07:18-048752 INFO     Version: 82d7b45c Mon Apr 24 16:54:12 2023 -0400
22:07:18-265864 INFO     nVidia toolkit detected
22:07:19-899349 INFO     Torch 2.0.0+cu118

it seems to be a gradio issue, when the image has finished generating i can see the following in the console log in chrome web tools
```
caught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at Blocks.svelte:229:30
    at Array.forEach (<anonymous>)
    at ct (Blocks.svelte:214:8)
    at Blocks.svelte:293:7
```


the below error is what i got when pressing the paste prompt button under general might be related, when this happens the entire UI  locks up and wont let me press anything till i refresh. tryed applying settings thinking there was a component missing or hidden but same happens
```
Traceback (most recent call last): 
File "C:\Stable Diffusion-Updated\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict output = await app.get_blocks().process_api( 
File "C:\Stable Diffusion-Updated\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api data = self.postprocess_data(fn_index, result["prediction"], state) 
File "C:\Stable Diffusion-Updated\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data block = self.blocks[output_id] KeyError: 333
```

gonna try deleting my env folder to see if that fixs anything

**Comment by west1778** [comment] 2023-04-24 21:28
I reinstalled and it seemed to work. Now I'm having what you're referring to where the whole UI locks up and I have to completely restart everything for it to work. :-/

**Comment by vladmandic** [comment] 2023-04-24 21:41
There's a solution for that, see the thread.

**Comment by west1778** [comment] 2023-04-24 21:47
Oh thanks I'll look that up. :)

**Comment by SOELexicon** [comment] 2023-04-24 21:47
if tis live preview mines already set to 1

**Comment by west1778** [comment] 2023-04-24 21:48
Which thread is it sir?

**Comment by vladmandic** [comment] 2023-04-24 21:53
Not at my desk, but one of the open issues, there are not that many.

**Comment by west1778** [comment] 2023-04-24 21:53
kk I'll see if I can find it I might try a fresh reinstall too

**Comment by SOELexicon** [comment] 2023-04-24 21:56
> kk I'll see if I can find it I might try a fresh reinstall too

let me know if you find it, i did a quick look at the 24 issues but it doesnt stand out from the issue title will keep looking

**Comment by west1778** [comment] 2023-04-24 21:56
https://github.com/vladmandic/automatic/issues/374 Pretty sure it's this one as I'm getting NaN errors in console.

**Comment by SOELexicon** [comment] 2023-04-24 22:58
After deleting the virtual environment and reinstalling i encountered several errors installing packages torch. Eventually, I was able to install the packages and get the program running again, but I noticed a warning:

23:38:48-925417 WARNING Package wrong version: timm 0.4.12 required 0.6.13

I then proceeded to generate an image from a prompt and the image generated and outputted to the folder but
I suspect my issue might be related to this previously closed issue: [394](https://github.com/vladmandic/automatic/issues/394). Any guidance on how to resolve this would be greatly appreciated. Thanks! meanwhile going to try a fresh install in another folder

**Comment by Gustavitj** [comment] 2023-04-29 18:58
+1 

Having the same issue.

**Comment by vladmandic** [comment] 2023-04-29 19:28
Which GPU, model & settings?
Does the same happen regardless of model?

**Comment by claychinasky** [comment] 2023-04-29 19:45
having same issue, I deleted venv several times, resetted built-in extensions where it stuck, ubuntu 22.10, rtx 2080. 
Image preview is working, image is being generated correctly, but when the generation ends, there is no image shown.
no errors in terminal or setup.log.
every part of the application is up to date.
```
pip freeze
absl-py==1.4.0
accelerate==0.18.0
addict==2.4.0
aenum==3.1.12
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==4.2.2
antlr4-python3-runtime==4.9.3
anyio==3.6.2
appdirs==1.4.4
astunparse==1.6.3
async-timeout==4.0.2
attrs==23.1.0
basicsr==1.4.2
beautifulsoup4==4.12.2
bitsandbytes==0.38.1
blendmodes==2022
blip-ci==0.0.3
boltons==23.0.0
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
clean-fid==0.1.35
click==8.1.3
clip @ git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
clip-interrogator==0.5.4
cmake==3.25.0
colorama==0.4.6
coloredlogs==15.0.1
colorlog==6.7.0
contourpy==1.0.7
convcolors==2.2.0
cssselect2==0.7.0
cycler==0.11.0
deprecation==2.1.0
diffusers==0.15.0
easydev==0.12.1
einops==0.4.1
entrypoints==0.4
extcolors==1.0.0
facexlib==0.3.0
fairscale==0.4.4
fastapi==0.95.1
ffmpy==0.3.0
filelock==3.9.0
filetype==1.2.0
filterpy==1.4.5
flatbuffers==23.3.3
font-roboto==0.0.1
fonts==0.0.3
fonttools==4.39.3
frozenlist==1.3.3
fsspec==2023.4.0
ftfy==6.1.1
future==0.18.3
fvcore==0.1.5.post20221221
gast==0.4.0
gdown==4.7.1
gfpgan==1.3.8
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.17.3
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
gradio==3.23.0
grpcio==1.54.0
h11==0.14.0
h5py==3.8.0
httpcore==0.17.0
httpx==0.24.0
huggingface-hub==0.14.1
humanfriendly==10.0
idna==3.4
imageio==2.28.0
imageio-ffmpeg==0.4.8
importlib-metadata==6.6.0
inflection==0.5.1
iopath==0.1.9
jax==0.4.8
Jinja2==3.1.2
jsonmerge==1.9.0
jsonschema==4.17.3
keras==2.12.0
kiwisolver==1.4.4
kornia==0.6.12
lark==1.1.5
lazy_loader==0.2
libclang==16.0.0
lightning-utilities==0.8.0
linkify-it-py==2.0.0
lit==15.0.7
llvmlite==0.39.1
lmdb==1.4.1
lpips==0.1.4
lxml==4.9.2
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
mdit-py-plugins==0.3.3
mdurl==0.1.2
mediapipe==0.9.3.0
ml-dtypes==0.1.0
mpmath==1.2.1
multidict==6.0.4
networkx==3.0
numba==0.56.4
numexpr==2.8.4
numpy==1.23.5
oauthlib==3.2.2
omegaconf==2.3.0
onnxruntime==1.14.1
open-clip-torch==2.18.0
opencv-contrib-python==4.7.0.72
opencv-python==4.7.0.72
opt-einsum==3.3.0
orjson==3.8.11
packaging==23.1
pandas==1.5.3
pexpect==4.8.0
piexif==1.1.3
Pillow==9.5.0
platformdirs==3.5.0
pooch==1.7.0
portalocker==2.7.0
protobuf==3.20.3
psutil==5.9.5
ptyprocess==0.7.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==1.10.7
pydub==0.25.1
Pygments==2.15.1
PyMatting==1.1.8
pyparsing==3.0.9
pyrsistent==0.19.3
PySocks==1.7.1
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==1.9.4
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0
realesrgan==0.3.0
regex==2023.3.23
rembg==2.0.30
reportlab==3.6.13
requests==2.29.0
requests-oauthlib==1.3.1
resize-right==0.0.2
rich==13.3.5
rsa==4.9
safetensors==0.3.1
scikit-image==0.20.0
scipy==1.10.1
semantic-version==2.10.0
Send2Trash==1.8.2
sentencepiece==0.1.98
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
sounddevice==0.4.6
soupsieve==2.4.1
starlette==0.26.1
svglib==1.5.1
sympy==1.11.1
tabulate==0.9.0
tb-nightly==2.13.0a20230429
tensorboard==2.12.2
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorflow==2.12.0
tensorflow-estimator==2.12.0
tensorflow-io-gcs-filesystem==0.32.0
termcolor==2.3.0
tifffile==2023.4.12
timm==0.6.13
tinycss2==1.2.1
tokenizers==0.13.3
tomesd==0.1.2
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
torch==2.0.0+cu118
torchaudio==2.0.1+cu118
torchdiffeq==0.2.3
torchmetrics==0.11.4
torchsde==0.2.5
torchvision==0.15.1+cu118
tqdm==4.65.0
trampoline==0.1.2
transformers==4.26.1
triton==2.0.0
typing_extensions==4.4.0
tzdata==2023.3
uc-micro-py==1.0.1
urllib3==1.26.13
uvicorn==0.22.0
voluptuous==0.13.1
wcwidth==0.2.6
webencodings==0.5.1
websockets==11.0.2
Werkzeug==2.3.2
wrapt==1.14.1
yacs==0.1.8
yapf==0.33.0
yarl==1.9.2
zipp==3.15.0
```
and a question, why xformers isn't getting installed? is been decided that leave it as a manual install?

**Comment by claychinasky** [comment] 2023-04-29 20:07
I tried to downgrade gradio few versions, problem persists.
Is it possible this issue related to `requests==2.29.0` where it connects to local web ui?
Because I had a few issues with that package and had to reinstall that, don't know my system corrupted something or conflicting those packages or some core libraries.

**Comment by vladmandic** [comment] 2023-04-29 20:20
@claychinasky xformers are getting installed automatically, but only if needed. which means you need to have nvidia gpu detected during startup (it says so on console) and xformers selected as desired cross-attention method in settings. otherwise, having xformers installed by default for everyone is just bad.

anyhow, back to topic of missing preview images...

- so, live preview works, only final is actually missing?
- please set live previews mode to approx nn  
  (regardless if you have live preview issues or not, this is to prevent a possible race condition)
- and nothing is stuck when that happens, you can generate again fine?
- there are no errors in console when this happens?  
  (before you try to do something else that can cause errors like send non-existing image somewhere)
- any extensions/scripts you have installed separately (what's in `/extensions` folder)?

**Comment by west1778** [comment] 2023-04-29 20:24
I have a question about upgrading I know on the site you have- Main repository: Update is not performed by default, enable with --upgrade flag but does that go into the arguments on launch.py or somewhere else sorry newb question I'm sure. :-/

**Comment by vladmandic** [comment] 2023-04-29 20:29
@west1778 if the question is how to set default user command line parameters, search discussions, this issue is very specific, lets not complicate it.

**Comment by west1778** [comment] 2023-04-29 20:29
No problem thanks

**Comment by vladmandic** [comment] 2023-04-29 20:39
i've just made some changes that maaaaybe help, please update repo and then follow questions below:
(sorry for a lot of questions, but since i cannot reproduce i need something to go on with)

- so, live preview works, only final is actually missing?
- please set live previews mode to approx nn  
  (regardless if you have live preview issues or not, this is to prevent a possible race condition)
- and nothing is stuck when that happens, you can generate again fine?
- is behavior same with batch size 1 and batch size 2?
- does issue happen on simple generate without any advanced options?  
  for example, no hires fix or scripts
- there are no errors in console when this happens?  
  (before you try to do something else that can cause errors like send non-existing image somewhere)
- any extensions/scripts you have installed separately (what's in `/extensions` folder)?

**Comment by claychinasky** [comment] 2023-04-29 20:53
>     * so, live preview works, only final is actually missing?
yes, preview works, file is generated, but UI doesn't show the end image.
>     * and nothing is stuck when that happens, you can generate again fine?
everything works as expected except this issue
>     * is behavior same with batch size 1 and batch size 2?
its the same, preview shows 4 images being generated and goes to blank image.
>     * does issue happen on simple generate without any advanced options?
>       for example, no hires fix or scripts
very simple.
>     * there are no errors in console when this happens?
>       (before you try to do something else that can cause errors like send non-existing image somewhere)
nothing I can see, not even in javascript console
>     * any extensions/scripts you have installed separately (what's in `/extensions` folder)? 
its empty
```
./webui.sh
Create and activate python venv
Launching launch.py...
23:44:13-562182 INFO     Python 3.10.10 on Linux
23:44:13-755491 INFO     Version: 3c410561 Sat Apr 29 16:04:10 2023 -0400
23:44:14-035400 INFO     Setting environment tuning
23:44:14-036593 INFO     nVidia toolkit detected
23:44:14-941135 INFO     Torch 2.0.0+cu118
23:44:14-951788 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:44:14-961187 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 VRAM 7952 Arch (7, 5) Cores 46
23:44:14-962360 INFO     Verifying requirements
23:44:14-985793 INFO     Running setup
23:44:14-986208 INFO     Installing packages
23:44:14-986693 INFO     Installing repositories
23:44:14-999712 INFO     Installing submodules
23:44:15-359038 INFO     Updating submodules
23:44:16-842846 ERROR    Error running git: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / checkout main
23:44:24-497590 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg',
                         'SwinIR']
23:44:30-338632 ERROR    Error running git: /media/clay/MAIN/repos/automatic/extensions-builtin/multidiffusion-upscaler-for-automatic1111 /
                         checkout main
23:44:37-697399 INFO     Extensions enabled: []
23:44:37-698067 INFO     Updating Wiki
23:44:38-929679 WARNING  Setup complete with errors (2)
23:44:38-930774 WARNING  See log file for more details: setup.log
23:44:38-931970 INFO     Running extension preloading
23:44:38-932956 INFO     Server arguments: []
Available models: /media/clay/MAIN/models/ckpt 293
ControlNet v1.1.116
ControlNet v1.1.116
Loading theme: gradio/glass
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: /media/clay/MAIN/models/ckpt/_general/avalonTruvision_v10.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.1 GB -:--:--
Creating model from config: /media/clay/MAIN/repos/automatic/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization
Model loaded in 1.8s (load=0.5s create=0.2s apply=0.2s vae=0.3s move=0.2s embeddings=0.3s)
Startup time: 17.8s (torch=3.6s gradio=1.3s libraries=0.6s models=0.3s codeformer=0.1s scripts=6.9s ui=3.0s start=0.1s checkpoint=1.9s)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  4.46it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  8.04it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  7.98it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  8.04it/s]
```

**Comment by claychinasky** [comment] 2023-04-29 21:27
found the issue after looking at the settings.
user interface > `Do not show any images in results for web` was checked, so after unchecking it, the issue is gone.
Don't know why it is checked or not (is not set default to true I assume?) and don't quite understand the wording of it but it is solved I think.

**Comment by vladmandic** [comment] 2023-04-29 21:43
that is one of the items i was just looking at and i don't see any reason why to leave it as configurable at all - it only causes problems. that option is completely removed in the latest update from few min ago.

**Comment by claychinasky** [comment] 2023-04-29 21:48
> that is one of the items i was just looking at and i don't see any reason why to leave it as configurable at all - it only causes problems. that option is completely removed in the latest update from few min ago. i've also made few other changes that may help and i hope this issue is now resolved. but if its not, report here (with full details as noted above) and i'll reopen the issue

I can see that as an option to let it in, maybe using it from web-ui but not want to make UI updates, for distraction or something else. But wording must be very clear like description + (web-ui image viewing will be disabled andyou will not see any images) or if its set to true, it may warn in console log just once when it boots up.

**Comment by vladmandic** [comment] 2023-04-29 21:54
any option can be possibly useful in 0.01% of cases, but i'm going after set-best-defaults-as-much-as-possible.
you've already noticed that i've removed 80% of command line flags and moved whats needed to ui settings. and removed a lot of unecessary items from ui settings - the fact you didn't even notice what's missing in settings shows how often it was used :)

**Comment by Gustavitj** [comment] 2023-04-29 21:58
> that is one of the items i was just looking at and i don't see any reason why to leave it as configurable at all - it only causes problems. that option is completely removed in the latest update from few min ago. i've also made few other changes that may help and i hope this issue is now resolved. but if its not, report here (with full details as noted above) and i'll reopen the issue

Well that was a stupid problem, nevertheless thanks for the quick response, and the great work you do!

**Comment by aetherwu** [comment] 2023-05-01 11:55
Here's my process:

- I removed '--medvram' in flag then it works fine.
- I added all extension back: it disappeared after generation - again!

Now I am keep looking into my extentions ...


My other debug process:

> * so, live preview works, only final is actually missing?
YES  

> * please set live previews mode to approx nn
YES

> * and nothing is stuck when that happens, you can generate again fine?
 YES  

> * is behavior same with batch size 1 and batch size 2?
YES  

> * does issue happen on simple generate without any advanced options?
>   for example, no hires fix or scripts
No hiresfix or script

> * there are no errors in console when this happens?
No. Generated image disappears at the same time that 'Generate' button resumes to orange/nomal state.

However since I've modified my xhttp file to print more log, I've got some console logs as:
self:  http://127.0.0.1:7860/api/predict███████████████████████████████████████████████| 22/22 [00:04<00:00,  4.62it/s]
self:  http://127.0.0.1:7860/reset
Seems like a reset was sent to GUI.

> Do not show any images in results for web
Not checked.

I've also reset extentions

**Comment by vladmandic** [comment] 2023-05-01 12:21
can you check your browser inspector -> network tab.
normal sequence for generate looks like this:
![image](https://user-images.githubusercontent.com/57876960/235450746-8446fe22-f5f4-4be0-8e14-4b359d59dc2d.png)

- starts with predict
- progress calls are live preview polling
- if there is progress, you see data:image transfer
- final ends with file request to actual image

**Comment by aetherwu** [comment] 2023-05-01 12:28
> Euler/Euler A,DPM fast, LMS, fails on steps > 40.
> DPM++, DPM2, fails on steps > 20

I've got an mysious observation above.

and yes, those steps more than a certain amount, final image did not show in network panel:
![https://i.imgur.com/ccNSsbM.png]

**Comment by vladmandic** [comment] 2023-05-01 12:37
ok, that's a start - now at least i know what to look for! i'll update here when i have something.

**Comment by aetherwu** [comment] 2023-05-01 13:16
I've got another observation that might help:
For those images disappear, parameters returns obvious early comparing to those return normally:
![](https://i.imgur.com/wMbIVLD.png)

**Comment by vladmandic** [comment] 2023-05-01 17:06
i've just made some updates, can you check if it helps? still running in dark since i cannot reproduce, but i'm trying...

**Comment by pastuh** [comment] 2023-05-02 09:14
I would say I have similar issue..
The preview image is not updated but if I click on the image I see the new image.
If more than one picture is generated, only the first one is not updated.

I see this error in the browser:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at Blocks.svelte:229:30
    at Array.forEach (<anonymous>)
    at ct (Blocks.svelte:214:8)
    at Blocks.svelte:293:7
```

**Comment by vladmandic** [comment] 2023-05-04 20:03
yes, i need to add check for duplicates. i'll add it to my backlog.

**Comment by SOELexicon** [comment] 2023-05-04 20:06
> yes, i need to add check for duplicates. i'll add it to my backlog.

going to have to say it buddy, but really appreciate the work you have put into this. astounds me the amount of updates you do to this repo. 

absolutely outstanding is all I can say.

**Comment by vladmandic** [comment] 2023-05-04 21:26
anyone else on this thread has an updated status using new version of the repo?

**Comment by vladmandic** [comment] 2023-05-09 13:16
closing as last report is that its working and there are no updates from original author.
if issue persists, update here and i'll reopen.

**Closed by vladmandic** 2023-05-09 13:16 UTC
Labels: question

**Comment by PotatoePig** [comment] 2023-06-06 16:57
I have been getting this same bug and it seems to be related to controlnet. It started happening after installing controlnet 1.1.218.
reading through the thread I had some success in fixing it, but then after enabling controlnet it happened again.
to fix it originally I looked at the user interface > Do not show any images in results for web setting. It was not checked, however I checked it, applied and reloaded UI and then unchecked it, applied and restarted and the bug was gone.
that was when I enabled controlnet and the bug reappeared immediately after clicking generate.

**Comment by Gopikanta501** [comment] 2023-09-18 17:32
Please please has anyone figured out how to fix this bug?I have had it for weeks now, and it's annoying to say the least as it affects other programmes like roop... I can't drop a photo into the preview window as it just disappears. Has there been a solution anyone please?? I'm just a newbie when it comes to codes and bugs sadly...

**Comment by vladmandic** [comment] 2023-09-18 18:51
> Please please has anyone figured out how to fix this bug?I have had it for weeks now

which bug? this bug has been resolved a loooooong time ago. if you have an issue, create an issue.
if you had it for weeks and its not reported, how is it going to be fixed?

> you cant drop a photo to preview window?

what does that mean? photos are not dropped to preview window.

**Comment by Gopikanta501** [comment] 2023-09-18 21:45
Thank you for your swift reply.

I refer to the same bug/issue that was mentioned at the top of this thread.

"Issue Description
I'm a bit of a newb when it comes to why something isn't happening but when I generate an image it will show the preview in the preview window for a second but then goes to blank if I click on the show button it shows the image in the folder that opens but nothing on the image preview window."

I have the same or at least a very similar problem. When I attempt to generate, the 'generation' appears in the preview window, but when finished generating the preview disappears. It is available in the 'Output' folder, but it doesn't remain in the preview window.

If I try to 'drag and drop' a photo into that same preview window it just disappears. 

Perhaps I missed the solution given somewhere on the page, perhaps you could point the solution out. Thanks again for your help.

**Comment by vladmandic** [comment] 2023-09-19 00:27
@Gopikanta501 your issue has nothing to do with one discussed here - you have working previews, but final step goes blank.
this is very common issue in different setups and environments, search for "black images".

> If I try to 'drag and drop' a photo into that same preview window it just disappears.

this doesn't exist. where did you get the idea that you can drag and drop a photo into preview window.

**Comment by Gopikanta501** [comment] 2023-09-19 06:23
@vladmandic sorry to take up your time. The Output folder is not full of black images. The images as they appear in the preview window during generation are completed. They're just not staying in the preview window after completion (as I presume they should, and in fact they did when I first installed the programme).  Thanks again for your help.

**Comment by Gopikanta501** [comment] 2023-09-23 12:07
@vladmandic Thank you for your help. Your advice was perfect. Everything back to normal. Thanks again.
