### ISSUE TITLE
[Issue]: Extra Networks tab gets confused after clicking blue refresh icon 

### ISSUE THREAD

**Issue by Lalimec** [vladmandic/automatic#1589] opened 2023-07-06 13:46 UTC
### Issue Description

As can be seen in the image Lora tab shows checkpoints now, and checkpoints tab is just empty. TI is alright. I've tested both dev and master branch, seems like this didnt got fixed.

![image](https://github.com/vladmandic/automatic/assets/65521426/0dc0af23-15d9-4fa5-b9a6-a467b85a209c)
.
.
.
.
![image](https://github.com/vladmandic/automatic/assets/65521426/0f0dd70d-73c4-40a0-84b4-09e7c3d9082d)
.
.
.
.
![image](https://github.com/vladmandic/automatic/assets/65521426/17e03df8-c0bc-49bc-ac25-e3bb89cc1103)

Also, not related but when you click on a generated image you cant close the lightbox by clicking outside of the image. Feels a little weird but not that important.

### Version Platform Description

13:32:06-823796 INFO     Starting SD.Next                                            
13:32:06-827318 INFO     Python 3.10.11 on Linux                                     
13:32:06-834781 INFO     Version: 849877ec5 Thu Jul 6 08:50:38 2023 -0400            
13:32:07-051904 INFO     Latest published version:                                   
                         3bcca6f92b4d457eff8616e157ba13421f59527f                    
                         2023-07-05T23:51:27Z                                        
13:32:07-053624 INFO     nVidia CUDA toolkit detected                                
13:32:08-116442 INFO     Torch 2.0.1+cu118                                           
13:32:08-189427 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700                  
13:32:08-204090 INFO     Torch detected GPU: NVIDIA A10G VRAM 22581 Arch (8, 6) Cores
                         80

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by drax-xard** [comment] 2023-07-06 14:43
I'm having this issue too. And sometimes when you're scrolling through loras/whatever they dissapear altogether.

**Comment by brianjz** [comment] 2023-07-07 00:17
I spent some time trying to debug this. Surprisingly, the thing that solved it for me was to delete the `config.json` and `ui-config.json` files and restart. Wondering if there was some sort of change in there that confused it. 

I don't know if this is it or not, but I remember when I originally enabled the `Use LyCoris handler for all Lora types` setting I had to move my Loras into the directory for them to work. When I reset my json files, I noticed that my Lora system path was still pointing to my original Lora directory, but everything had been working. I changed it to the new LyCoris directory also, but I'm not sure if that was the solution or not.

This didn't solve the issue of when you scroll the page further down, all of the thumbnails get pushed to the left weirdly.

**Comment by vladmandic** [comment] 2023-07-07 14:03
there are multiple reports that resetting config (or deleting config.json) solves the problem. and i cannot reproduce it locally, so unless someone finds exact root cause of the apparently corrupt config, this will be closed as-is.

**Comment by slimeqslimedog** [comment] 2023-07-08 13:36
I haven't experienced the original issue described here, but I *have* run into the problem @brianjz mentioned, of the model thumbnails div being squashed into a tiny column when you scroll the page downward. It also doesn't fill the available vertical space when you have a lot of directories in the left-hand sidebar, which may be related. I assume there's some problem with the CSS used to draw the Extra Networks divs.
As noted above, deleting `config.json` and `ui-config.json` does *not* solve that issue. I also disabled the CivitAI helper extension just to make sure it wasn't the culprit, and it is not; the problem still persists.

**Comment by wktra** [comment] 2023-07-08 19:54
I have the same problem. 
![Screenshot 2023-07-08 145409](https://github.com/vladmandic/automatic/assets/117292904/7a8638eb-7694-411a-afd7-b4a1510c3a03)

**Comment by wktra** [comment] 2023-07-08 20:05
An update:

After a restart, I suddenly saw a fresh config.json appear. 
So I deleted config.json and ui-config.json
then restarted.

The checkpoints are all there and in their respective tab. 
The LORAs are all there in their respective tab.
My TIs are all there in their respective tab.

But as soon as I hit refresh, all of my TIs are gone. 
And I have to restart the server to get them back.

**Comment by wktra** [comment] 2023-07-08 20:43
Okay, so I think I found a fix so that the tabs remain stable, even after a refresh:

1) Change your theme to Gradio default.
2) Apply changes and Restart the server.
3) Shut down the server
4) Delete config and ui-config
5) restart server
6) Go into Settings > Extra Networks and _change from inline_ to cover or sidebar.
7) Save settings, restart the server.
8) Shut down the server and restart.

This worked for me. Everything works as normal now.
@brianjz @drax-xard @Lalimec 

Hope this helps.

**Comment by vladmandic** [comment] 2023-07-09 12:28
major update to extra networks has been published.
one outstanding issue is still https://github.com/vladmandic/automatic/issues/1612, otherwise if there are any other issues, please open a new one.

**Closed by vladmandic** 2023-07-09 12:28 UTC
Labels: cannot reproduce
