### ISSUE TITLE
[Issue]: Inpaint mask disappears but continues to be applied

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#583] opened 2023-04-28 07:30 UTC
### Issue Description

Inside inpaint, do a first render with by painting a mask. On the result to the right, click send to inpaint, sending the new image to the left slot. The mask will vanish from the left slot when the new image is shown, **however**, it continues to exist in an invisible form, and continues to affect generation. By clicking undo the proper amount, the mask vanishes, but this is annoying because it's easy to forget.

### Version Platform Description

Version 2023-04-27; Win 11; Firefox latest

**Comment by Chilluminati91** [comment] 2023-04-28 11:57
This has been happening since the very first days of automatic1111. Dont know how easy it is to fix, but if the mask carries over it should be visible indeed. Maybe also add a setting toggle to "carry over" or "remove mask" on new image.

**Comment by ShyRed** [comment] 2023-04-28 11:57
Duplicate of #156 ?

**Comment by vladmandic** [comment] 2023-04-28 13:34
@ShyRed exactly. closing this as duplicate as original issue is still open.

**Closed by vladmandic** 2023-04-28 13:34 UTC
