### ISSUE TITLE
[Issue]: ctrl + a stopped working 

### ISSUE THREAD

**Issue by AndreyRGW** [vladmandic/automatic#1644] opened 2023-07-11 13:51 UTC
### Issue Description

An issue with the full text selection function when using the Ctrl + A keyboard shortcut, which occurred after a16eee1504173aae2052b850702b6297e41e0500, causes unpredictable behavior. On one run, the key combination may work fine, on another run it may not respond at all, and in a third case it may work for a while and then stop functioning.

### Version Platform Description

```
Starting SD.Next
Python 3.10.10 on Windows
Version: a844a83d Tue Jul 11 11:00:45 2023 +0300
Latest published version: 6b26c551386ed3551d98b8df21aae56214ba8259 2023-07-11T12:35:15Z
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 2060 VRAM 12288 Arch (7, 5) Cores 34
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
Enabled extensions: ['a1111-sd-webui-tagcomplete', 'model_preset_manager', 'OneButtonPrompt',
                         'sd-webui-ar', 'sd-webui-cutoff', 'sd-webui-llul', 'sd-webui-roop-unlock',
                         'sd_webui_SAG', 'stable-diffusion-webui-promptgen', 'stable-diffusion-webui-sonar',
                         'ultimate-upscale-for-automatic1111']
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment] 2023-07-11 17:04
and i cannot reproduce. i need something tangible to go on with...

**Comment by Sunsphire** [comment] 2023-07-11 19:13
Sadly it happens to me too, I can't use the ctrl+a in the positive or negative prompt (or anywhere else). I used to do that to delete the whole prompts at once. It started to do this yesterday after the update. Today it worked but after a few hours of using SD it's not working again. I'm not sure if it's related but there are three other small things:

- I can't select the text/info under the generated image / I can't select any text by click and drag (except the text from the positive/negative prompts). I'm not sure why but I can't highlight any text by click-drag or ctrl+a. I'm pretty sure it worked a few hours ago.
- Clicking on extra networks subdirectories does nothing. Probably not related to this.
- Yesterday I had problems selecting any lora by clicking it. Clicking on a lora/lycoris/anything from the extra networks wasn't sending the lora to the prompt, but writing it directly in the prompt area worked. This only happened intermittently yesterday, today I had no problem with that so far. Most probably not related.

Since it's my first time writing on github I really hope I didn't said something really stupid....I'm really sorry if I did.
Thank you @vladmandic for your hard work, SD.Next is awesome! 

I have no errors in the console/logs.

**Comment by AndreyRGW** [comment] 2023-07-11 19:37
> * I can't select the text/info under the generated image / I can't select any text by click and drag (except the text from the positive/negative prompts). I'm not sure why but I can't highlight any text by click-drag or ctrl+a. I'm pretty sure it worked a few hours ago.

same

**Comment by fbellgr** [comment] 2023-07-11 19:47
Wouldn't including which browser your all are using be useful? For example, a recent issue with the image viewer affected only Firefox.

**Comment by vladmandic** [comment] 2023-07-11 19:54
that is VERY relevant. so is theme. and any possible extensions that deal with prompt (and there are quite a few).

**Comment by Sunsphire** [comment] 2023-07-11 20:06
Chrome 
black-orange theme, theme mode: auto
The only extension that come to my mind and deals with prompt is 'OneButtonPrompt' (I will try without it but since the bug happens randomly it might take a while). Thanks and sorry for not including those details from the start.

**Comment by AndreyRGW** [comment] 2023-07-11 20:10
I'm using MS Edge

**Comment by brknsoul** [comment] 2023-07-12 03:01
Win10, Chrome

Ctrl+A ceases to function when you zoom into an image in the viewer.

**Comment by AndreyRGW** [comment] 2023-07-12 10:45
> Ctrl+A ceases to function when you zoom into an image in the viewer.

Yes, I agree

**Comment by anothertal3** [comment] 2023-07-12 10:50
Same as @brknsoul , same setup.

In my case it was also necessary to interact with the zoomed picture, i.e., moving it using the mouse. I also tried alternating between clicking next to the zoomed image to close and using X. There might be something necessary here, too, but it breaks very quickly.

Afterwards: no more select all **AND** no more select labels in the UI (e.g. to copy a prompt or seed)
(Not sure if there's already an issue about the second behavior)

**Comment by vladmandic** [comment] 2023-07-12 15:18
just pushed a major update with pretty large javascript refactoring, i hope this issue is resolved.
if not, post here and i'll reopen.

**Closed by vladmandic** 2023-07-12 15:18 UTC
Labels: cannot reproduce

**Comment by AndreyRGW** [comment] 2023-07-12 16:56
> just pushed a major update with pretty large javascript refactoring, i hope this issue is resolved. if not, post here and i'll reopen.

Didn't help, at least not for me

**Comment by anothertal3** [comment] 2023-07-13 09:32
Can confirm, seems to have been resolved
