### ISSUE TITLE
[Issue]: First image result in img2img batch is of bad quality

### ISSUE THREAD

**Issue by byteconcepts** [vladmandic/automatic#785] opened 2023-05-06 08:37 UTC
### Issue Description

Seems like the rendering of the first image of a batch in img2img stopped before the last sampling step.

If I remember correctly, this once also was an issue in the original automatic1111 which then was solved.
But unfortunately don't know how.

### Version Platform Description

updated: 2023-05-05
hash: ceaf7571
url: https://github.com/vladmandic/automatic/tree/master

arch: AMD64
cpu: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
system: Windows
release: Windows-10-10.0.19044-SP0
python: 3.10.8

medvram, xformers + xFormers enable flash Attention

**Comment by vladmandic** [comment] 2023-05-06 12:46
that is weird.
can you provide example?

**Comment by byteconcepts** [comment] 2023-05-06 19:43
Yes, it definitely is weird. - And it was not easy to reproduce some example images where it shows.

Normally I have a collection of downloaded photographs.
I put one image as source into the img2img tab and then render it with my positive and negative prompts using the revAnimated model with a CFG Scale of 10 and Denoising strength of 0.5. With a batch of 4.
Then I again load the best result as source again into the img2img tab and repeat the process, but with the realisticVision V2.0 model and a Denoising strength of 0.5. Again with a batch of 4.

To do everything loyalty free for this example, I now created the base image of a superhero on a rooftop with txt2img tab and used the result of this one as the first source in the img2img tab. - Surprise: All four resulting images looked allright!

As next test I downloaded a high-res photograph of Superman (from a movie) and used that one as first image src in the img2img tab: Surprise again: All four resulting images looked allright after the whole process with the two models!

What the... ????

As final test I again downloaded a high-res photograph of a girl with a lot of naked skin and repeated the whole process and finally.... the first image in the batch had worse quality then the other three.

To not offend anybody I cropped the four example images. If you have the whole images, the differences show much more obvious, but if you take a look at the skin and a close look at the face, you should notice the difference.

![00118-862883191_400x400](https://user-images.githubusercontent.com/33394779/236642943-26219152-7f22-4bc5-8459-a713c94ee18b.jpg)
![00119-862883192_400x400](https://user-images.githubusercontent.com/33394779/236642958-5066a7b7-805d-45e2-8497-a3f9aad06657.jpg)
![00120-862883193_400x400](https://user-images.githubusercontent.com/33394779/236642966-6f2611b8-c45c-4aa7-9844-e8f2a6494782.jpg)
![00121-862883194_400x400](https://user-images.githubusercontent.com/33394779/236642974-0e6ed300-9c5c-48e0-9693-3e292a6fa318.jpg)

**Comment by byteconcepts** [comment] 2023-05-06 20:18
Here's another example batch...

![00127-3088953737_496x371](https://user-images.githubusercontent.com/33394779/236644964-481a69cc-f06d-49c1-aadf-8fe8df363344.jpg)
![00127-3088953738_496x371](https://user-images.githubusercontent.com/33394779/236644973-263ab8ed-3c71-4bc6-9dbb-52c377afb7a7.jpg)
![00127-3088953739_496x371](https://user-images.githubusercontent.com/33394779/236644981-64b3a36b-83ca-439a-826e-537027ed5c16.jpg)
![00127-3088953740_496x371](https://user-images.githubusercontent.com/33394779/236644987-6f4d563b-7c7d-43ad-b64b-6e720d2ccd1e.jpg)

**Comment by EfourC** [comment] 2023-05-06 20:44
Does the problem with the first image of the batch also happen if you disable `Restore Faces`?

**Comment by byteconcepts** [comment] 2023-05-06 21:02
Good question. I'll try to create another example batch.

**Comment by byteconcepts** [comment] 2023-05-06 21:24
Here the first two images of the same batch with the same source image, seed and parameters as before but without restore faces. - No difference, first image is bad, without restore faces even worse:

![00143-3088953737_496x371_no_restore_faces](https://user-images.githubusercontent.com/33394779/236647083-66bc0366-453b-40ed-825f-1445b53c4a8d.jpg)
![00143-3088953738_496x371_no_restore_faces](https://user-images.githubusercontent.com/33394779/236647088-87d92676-2b40-48f1-8031-8cefff0ee017.jpg)

**Comment by vladmandic** [comment] 2023-05-06 21:49
Just a though, sampler you use is a two pass sampler. Just as a test (I know, takes a while), can you reproduce with Euler A?

**Comment by byteconcepts** [comment] 2023-05-06 22:09
Sure and many thanks that you put so much effort into providing us a better and better experience!

**Comment by byteconcepts** [comment] 2023-05-06 22:37
Congratulations! You directly guessed it right:

The same batch with euler a creates only good images.

I directly also tested with DPM++ 2M, I guess it also uses a two pass sampler? and again the first image was bad.

Here the first and third images of the same procedure but the Euler a model, first image also good:
![00001-3088953737_496x371_euler_a](https://user-images.githubusercontent.com/33394779/236649054-bf172fdb-6883-481e-a4df-1c1089a2b07f.jpg)
![00001-3088953739_496x371_euler_a](https://user-images.githubusercontent.com/33394779/236649057-4d8fec7b-6662-412f-99b0-c61725f31ca7.jpg)

**Comment by byteconcepts** [comment] 2023-05-06 22:44
To be honest, I think that Euler a also produces great results, at least good enough for my purposes.

So the problem exists but can be avoided to choose eg Euler a until the problem will be solved, very good!

**Comment by vladmandic** [comment] 2023-05-06 23:52
Btw, if you feel like experimenting, we've just added UniPC support for img2img, but nobody really knows how it performs - I'd love to hear some feedback from people that use img2img a lot...

**Comment by byteconcepts** [comment] 2023-05-07 00:17
:-) sure, why not...

**Comment by byteconcepts** [comment] 2023-05-07 01:12
Here's the same batch using realisticVision V2 and UniPC sampler.

Unfortunately the first image seems to be bad again.
Despite of that I like the results. Is there a big difference to my Euler a batch? ... Maybe a little bit in details?

![00010-3088953737_496x371_realisticVision_UniPC](https://user-images.githubusercontent.com/33394779/236652628-cfc4feba-a4cd-4340-85b4-2536873012f1.jpg)
![00010-3088953738_496x371_realisticVision_UniPC](https://user-images.githubusercontent.com/33394779/236652632-82cb1506-d5ae-4fdb-80fc-452fc16f10e6.jpg)
![00010-3088953739_496x371_realisticVision_UniPC](https://user-images.githubusercontent.com/33394779/236652634-ceac059f-06e6-4ffa-ac16-57ff779151ca.jpg)
![00010-30889537340_496x371_realisticVision_UniPC](https://user-images.githubusercontent.com/33394779/236652638-2e38af5f-1ea2-4820-9f18-ba5338a202b9.jpg)

**Comment by byteconcepts** [comment] 2023-05-07 03:55
Unfortunately inpainting with "Inpaint not masked" doesn't work for me with the UniPC sampler.

It stops while creating the first image without any message.

I just copied the source image from the img2img tab to inpainting. All parameters stayed the same like in the img2img tab project which came out great.

**Comment by rkiga** [comment] 2023-05-18 20:32
I can't recreate this bug.

But go back and look at all the pictures again. Ignore the faces and only look at the backgrounds. All the first pictures have extra high contrast with some showing overcooked (fried) colors. That looks like what happens with too high CFG, too high prompt weights, and / or too low step count. (Or a problem with the bugged / bad samplers: DPM Fast and all LMS versions, but you're not using those.)

When you generate your batch of 4, does the first image stop changing in the live preview halfway through, while the others keep improving?

You can get rid of the angled brackets around the TI embeddings in your negative prompt, like <bad-hands-5>. Only Lora / lycoris need those. So just write: bad-hands-5, bad_prompt_version2

Regardless of the bug, your prompt weights are WAY too high. You have the combined equivalent of (50 years old:7.2) and it's still not making her look old. IMO get rid of all of your prompt weights completely, then increase the denoising strength. Or just inpaint the face and neck with "masked content: fill." You should see a much stronger change.

**Comment by vladmandic** [comment] 2023-05-29 18:43
this issue has been stalled for a while now and i don't know how to proceed with it? any suggestions?

**Comment by vladmandic** [comment] 2023-06-04 17:25
closing as no recent feedback and i don't know how to proceed on my own.

**Closed by vladmandic** 2023-06-04 17:25 UTC
Labels: bug, help wanted
