### ISSUE TITLE
[Feature]: Implement "Add to queue" feature

### ISSUE THREAD

**Issue by onegex1214** [vladmandic/automatic#559] opened 2023-04-27 09:55 UTC
### Feature description

I've been dying to have a proper built-in "Add to queue" button that basically collects all the settings of the txt2img page, and adds them to a queue, so I can keep tweaking the settings, changing the prompt, and "add to queue" and once I'm ready, I'll press "Generate all" and it'll pick up all the settings/prompt in queue and run them one after the other.

PLEASE <3

**Comment by vladmandic** [comment] 2023-04-27 12:27
very valid request. non-trivial and will place in my back-log.

**Comment by onegex1214** [comment] 2023-05-02 16:16
@AimVaguely That looks way too complicated.. when it could just be an added button next to the generate button instead of that mess.. I dunno.

**Comment by vladmandic** [comment] 2023-05-02 16:21
yes, it should be as simple as that. its in my backlog.

**Comment by onegex1214** [comment] 2023-05-02 21:58
@vladmandic Do you think it's ok for me to ask for an ETA about the feature development ?

**Comment by vladmandic** [comment] 2023-05-03 00:47
depends on the number of new issues, i'd hope by end of next week. but i need to design it properly, not just hack it.

**Comment by trewcogg** [comment] 2023-05-30 01:04
Hey there @onegex1214, we initially developed this tool to use in our company internally but recently released it as an open-source extension. 

It pretty much does what you asked + reprioritizing, canceling, etc. & works with txt2img and img2img. You can check it out here: [https://github.com/ArtVentureX/sd-webui-agent-scheduler](https://github.com/ArtVentureX/sd-webui-agent-scheduler)

Any feedback is appreciated

**Comment by vladmandic** [comment] 2023-05-30 01:24
> Hey there @onegex1214, we initially developed this tool to use in our company internally but recently released it as an open-source extension.

I took a quick look and I like what I see so far - very clean implementation.
I'll take a closer look tomorrow, but this might just deserve a bigger spotlight!

**Comment by onegex1214** [comment] 2023-05-30 03:58
> 

Oh hell yeah !!! That's awesome. I'll check that out :o you rock !

**Comment by onegex1214** [comment] 2023-05-30 04:02
@trewcogg Thanks a lot btw!

**Comment by onegex1214** [comment] 2023-05-30 05:46
@trewcogg Ok seriously. Been messing with it for a few hours. Thank you from the bottom of my heart. This is something I've been dying to have on SD ever since november. You're a godsend. Thanks 100000 times.

**Comment by onegex1214** [comment] 2023-05-30 05:47
It's great, intuitive, easy to use.. just what I needed <3

**Comment by trewcogg** [comment] 2023-05-30 14:25
@onegex1214 makes us really happy that it is of use to you! Let us know if you have ideas on how we can make it even better 🤝

**Comment by vladmandic** [comment] 2023-05-30 15:24
@trewcogg as i've mentioned yesterday, i took a closer look at the extension and still love it, but few feedbacks are in order: <https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/2>

**Comment by trewcogg** [comment] 2023-05-30 15:37
@vladmandic thanks for taking a look & leaving such good detailed feedback. We'll look into it and move forward from there

**Comment by onegex1214** [comment] 2023-06-02 18:23
I keep having this error pop everytime I open it, no matter the version..

```20:09:14-492141 ERROR    executing callback: I:\vlad-diffusion-webui\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py app_started_callback: AttributeError
┌───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────┐
│ I:\vlad-diffusion-webui\automatic\modules\script_callbacks.py:125 in app_started_callback                                                                                                            │
│                                                                                                                                                                                                      │
│   124 │   │   try:                                                                                                                                                                                   │
│ > 125 │   │   │   c.callback(demo, app)                                                                                                                                                              │
│   126 │   │   except Exception as e:                                                                                                                                                                 │
│                                                                                                                                                                                                      │
│ I:\vlad-diffusion-webui\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:24 in <lambda>                                                                               │
│                                                                                                                                                                                                      │
│    23 │   │   super().__init__()                                                                                                                                                                     │
│ >  24 │   │   script_callbacks.on_app_started(lambda block, _: self.on_app_started(block))                                                                                                           │
│    25 │   │   self.checkpoint_override = checkpoint_current                                                                                                                                          │
│                                                                                                                                                                                                      │
│ I:\vlad-diffusion-webui\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:43 in on_app_started                                                                         │
│                                                                                                                                                                                                      │
│    42 │   def on_app_started(self, block):                                                                                                                                                           │
│ >  43 │   │   self.add_enqueue_button(block, self.generate_button)                                                                                                                                   │
│    44                                                                                                                                                                                                │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Script' object has no attribute 'generate_button'```

**Comment by vladmandic** [comment] 2023-06-02 22:22
@onegex1214 i cannot reproduce. also, it doesn't help to post so deep on an general thread - if problem persists, create a new issue.

**Comment by vladmandic** [comment] 2023-06-02 22:23
i'm closing the feature request as https://github.com/ArtVentureX/sd-webui-agent-scheduler has been added to built-in list and addresses this request.

**Closed by vladmandic** 2023-06-02 22:23 UTC
Labels: enhancement, backlog
