### ISSUE TITLE
[Issue]: UniPC always here

### ISSUE THREAD

**Issue by froger-me** [vladmandic/automatic#822] opened 2023-05-09 00:27 UTC
### Issue Description

Option in config.json:
```
"show_samplers": [
        "Euler a",
        "DPM++ 2M Karras",
        "DPM++ 2S a Karras",
        "DPM++ SDE Karras",
        "Euler",
        "DPM++ 2M",
        "DPM++ 2S a",
        "DPM++ SDE"
    ],
```
And yet:

<img width="332" alt="Screenshot 2023-05-09 at 8 27 00 AM" src="https://user-images.githubusercontent.com/3622456/236964383-46c0fc61-6363-4f13-a93b-3baeb7181747.png">

### Version Platform Description

 Version: 4d9fab49 Mon May 8 11:56:59 2023 -0400

**Comment by vladmandic** [comment] 2023-05-09 11:44
duplicate of #784 - read through that (and search before creating an issue)
also, not an issue - this is better suited as a question.

**Closed by vladmandic** 2023-05-09 11:44 UTC

**Comment by froger-me** [comment] 2023-05-09 13:20
Happy to contribute!
Getting to it 👍 ✅
