### ISSUE TITLE
[Issue]: VAE not found on startup

### ISSUE THREAD

**Issue by DyingWorld** [vladmandic/automatic#1039] opened 2023-05-17 19:24 UTC
### Issue Description

After updating to b979d448, I am seeing the following messages on the command line during startup:
```
13:12:03-936723 INFO     Model created from config: E:\automatic\configs\v1-inference.yaml
13:12:06-120724 WARNING  VAE not found: vae-ft-mse-840000-ema-pruned.safetensors
```
That VAE does exist and I can load a different VAE in the UI and then load that one back.

### Version Platform Description

Python 3.10.6 on Windows
Version: b979d448 Wed May 17 14:41:13 2023 -0400
Setting environment tuning
nVidia CUDA toolkit detected
Torch 2.0.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12287 Arch (8, 6) Cores 28

**Comment by Trojaner** [comment] 2023-05-17 19:25
Duplicate of #1038

**Comment by vladmandic** [comment] 2023-05-17 19:26
closing as duplicate

**Closed by vladmandic** 2023-05-17 19:26 UTC
