### ISSUE TITLE
[Issue]: 403 forbidden for scripts/*.js in all browsers

### ISSUE THREAD

**Issue by ke1ne** [vladmandic/automatic#2106] opened 2023-08-30 07:54 UTC
### Issue Description

Hi, after some of latest commits, UI became unusable, with broken layout and blocked JS loading.
![image](https://github.com/vladmandic/automatic/assets/8934421/d18f2f59-42c6-4755-8d90-b5056d387ed9)

The browser dev console shows this:
![image](https://github.com/vladmandic/automatic/assets/8934421/5bfa9e3d-6d95-4264-9322-c5eba76a126c)

Full reinstalling didn't help too. In other words, this kind of link `http://127.0.0.1:7860/file=extensions-builtin/sd-extension-system-info/javascript/system-info.js?1693380892.4142544` doesn't work for JS for me.
Using of `--safe` gave the same result.

### Version Platform Description

```
10:42:29-801306 INFO     Python 3.10.11 on Windows
10:42:29-833157 INFO     Version: 5e14178b Wed Aug 30 02:38:25 2023 -0400
10:42:30-523455 INFO     nVidia CUDA toolkit detected
10:42:30-600705 INFO     Verifying requirements
10:42:30-618686 INFO     Verifying packages
10:42:30-620686 INFO     Verifying repositories
10:42:34-600148 INFO     Verifying submodules
10:43:04-625228 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-extension-system-info', 'sd-webui-agent-scheduler',
'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
...
10:43:05-385164 INFO     Extension preload: 0.0s E:\.ai\automatic\extensions-builtin
10:43:05-387164 INFO     Extension preload: 0.0s extensions
10:43:05-399472 INFO     Server arguments: ['--upgrade']
No module 'xformers'. Proceeding without it.
10:43:13-731289 INFO     Engine: backend=Backend.ORIGINAL
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment] 2023-08-30 12:19
i cannot reproduce this. and its not a common issue, i've asked several people to test. 
i suggest to delete config.json and ui-config.json to reset configuration and we can start troubleshooting from there.

**Comment by vladmandic** [comment] 2023-08-30 13:13
where is sdnext installed? (drive, path)?
can you start server with `--debug` and post startup log?

**Comment by ke1ne** [comment] 2023-08-30 13:37
It installed in `e:\.ai\automatic`.
Also, I see that default Gradio stuff is loaded from `venv\Lib\site-packages\gradio\templates\cdn\assets`.
Here is the log:
[sdnext.log](https://github.com/vladmandic/automatic/files/12476229/sdnext.log)

**Comment by vladmandic** [comment] 2023-08-30 14:13
log doesn't really show much.
it shouldn't matter, but any chance you can install sdnext on a) different drive, b) in a folder without a `.` in a name?
i'm really only trying to rule out few things because i cannot reproduce issue at all, so it has to be system specific.

**Comment by vladmandic** [comment] 2023-08-30 14:33
i believe you. most likely something broke in the new gradio, i'll follow-up on that, but glad you have a working system now.

**Comment by virionexe** [comment] 2023-09-03 19:03
I solved this issue locally. The problem was that a dir in my path had a begining dot too.

**Comment by ke1ne** [comment] 2023-09-03 19:17
> I solved this issue locally. The problem was that a dir in my path had a begining dot: "D://.data/SD/etc...".
> After reinstalling to a path with no dots in it, it works fine.

Yes, this helped to me too. Strange anyway.

**Comment by Meowdoleon** [comment] 2023-09-09 19:51
Oh wow. Yup, I am using a period in one of my folder, which caused me this issue.
This is irritating as I have a lot of workflow with that period as this is a root folder.

**Comment by akvyalkov** [comment] 2023-10-04 15:05
Maybe this is culprit

Gradio DOES NOT ALLOW access to:

Dotfiles (any files whose name begins with '.') or any files that are contained in any directory whose name begins with '.'

https://www.gradio.app/guides/sharing-your-app#security-and-file-access

**Comment by vladmandic** [comment] 2023-10-04 16:44
@akvyalkov thanks - and yes, that exactly is the culprit.
as it is, this is by design (although its gradio's choice), so closing the issue.

**Closed by vladmandic** 2023-10-04 16:44 UTC
Labels: upstream
