### ISSUE TITLE
[Issue]:  Fatal - detected dubious ownership

### ISSUE THREAD

**Issue by Torcelllo** [vladmandic/automatic#726] opened 2023-05-03 08:52 UTC
### Issue Description

Error getting local repository version: invalid literal for int() with base 10: "fatal: detected dubious ownership in repository at 'C:/automatic'\n'C:/automatic' is owned by:\n\t'S-1-5-32-544

and then it closes after Press Any Key

### Version Platform Description

Win 10, Chrome, latest iteration  6f976c358f6f2db4d23af0c210f4dbb01f8a24d4 2023-05-03T01:30:31Z

''''C:/automatic' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-1194271653-2810682028-2473446000-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/automatic
2023-05-03 09:42:10,517 | ERROR | C:\automatic\installer.py | Error getting local repository version: invalid literal for int() with base 10: "fatal: detected dubious ownership in repository at 'C:/automatic'\n'C:/automatic' is owned by:\n\t'S-1-5-32-544'\nbut the current user is:\n\t'S-1-5-21-1194271653-2810682028-2473446000-1001'\nTo add 
2023-05-03 09:46:13,777 | INFO | C:\automatic\installer.py | Python 3.10.6 on Windows
2023-05-03 09:46:13,901 | DEBUG | C:\automatic\installer.py | Git 2.37.3.windows.1
2023-05-03 09:46:14,200 | ERROR | C:\automatic\installer.py | Error running git: None / status
2023-05-03 09:46:14,202 | DEBUG | C:\automatic\installer.py | Git output: fatal: detected dubious ownership in repository at 'C:/automatic'
'C:/automatic' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-1194271653-2810682028-2473446000-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/automatic
2023-05-03 09:46:14,503 | ERROR | C:\automatic\installer.py | Error running git: None / log -1 --pretty=format:"%h %ad"
2023-05-03 09:46:14,505 | DEBUG | C:\automatic\installer.py | Git output: fatal: detected dubious ownership in repository at 'C:/automatic'
'C:/automatic' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-1194271653-2810682028-2473446000-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/automatic
2023-05-03 09:46:14,506 | INFO | C:\automatic\installer.py | Version: fatal: detected dubious ownership in repository at 'C:/automatic'
'C:/automatic' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-1194271653-2810682028-2473446000-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/automatic
2023-05-03 09:46:14,606 | ERROR | C:\automatic\installer.py | Error running git: None / rev-parse HEAD
2023-05-03 09:46:14,608 | DEBUG | C:\automatic\installer.py | Git output: fatal: detected dubious ownership in repository at 'C:/automatic'
'C:/automatic' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-1194271653-2810682028-2473446000-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/automatic
2023-05-03 09:46:14,860 | INFO | C:\automatic\installer.py | Latest published version: 6f976c358f6f2db4d23af0c210f4dbb01f8a24d4 2023-05-03T01:30:31Z
2023-05-03 09:46:14,863 | INFO | C:\automatic\installer.py | Setting environment tuning
2023-05-03 09:46:14,868 | INFO | C:\automatic\installer.py | nVidia CUDA toolkit detected
2023-05-03 09:46:15,414 | DEBUG | C:\automatic\installer.py | Package version found: torch 2.0.0+cu118
2023-05-03 09:46:15,415 | DEBUG | C:\automatic\installer.py | Package version found: torchvision 0.15.1+cu118
2023-05-03 09:46:15,415 | DEBUG | C:\automatic\installer.py | Package version found: torchaudio 2.0.1+cu118
2023-05-03 09:46:18,419 | INFO | C:\automatic\installer.py | Torch 2.0.0+cu118
2023-05-03 09:46:18,452 | INFO | C:\automatic\installer.py | Torch backend: nVidia CUDA 11.8 cuDNN 8700
2023-05-03 09:46:18,455 | INFO | C:\automatic\installer.py | Torch detected GPU: NVIDIA GeForce RTX 2070 VRAM 8192 Arch (7, 5) Cores 36
2023-05-03 09:46:18,457 | DEBUG | C:\automatic\installer.py | Package version not found: tensorflow
2023-05-03 09:46:18,457 | INFO | C:\automatic\installer.py | Installing package: tensorflow==2.12.0
2023-05-03 09:46:18,459 | DEBUG | C:\automatic\installer.py | Running pip: install --upgrade tensorflow==2.12.0
2023-05-03 09:47:04,334 | INFO | C:\automatic\installer.py | Verifying requirements
2023-05-03 09:47:04,337 | DEBUG | C:\automatic\installer.py | Package version found: addict 2.4.0
2023-05-03 09:47:04,337 | DEBUG | C:\automatic\installer.py | Package version found: aenum 3.1.12
2023-05-03 09:47:04,337 | DEBUG | C:\automatic\installer.py | Package version found: aiohttp 3.8.4
2023-05-03 09:47:04,338 | DEBUG | C:\automatic\installer.py | Package version found: anyio 3.6.2
2023-05-03 09:47:04,338 | DEBUG | C:\automatic\installer.py | Package version found: appdirs 1.4.4
2023-05-03 09:47:04,338 | DEBUG | C:\automatic\installer.py | Package version found: astunparse 1.6.3
2023-05-03 09:47:04,339 | DEBUG | C:\automatic\installer.py | Package version found: basicsr 1.4.2
2023-05-03 09:47:04,339 | DEBUG | C:\automatic\installer.py | Package version found: bitsandbytes 0.38.1
2023-05-03 09:47:04,339 | DEBUG | C:\automatic\installer.py | Package version found: blendmodes 2022
2023-05-03 09:47:04,340 | DEBUG | C:\automatic\installer.py | Package version found: clean-fid 0.1.35
2023-05-03 09:47:04,340 | DEBUG | C:\automatic\installer.py | Package version found: easydev 0.12.1
2023-05-03 09:47:04,340 | DEBUG | C:\automatic\installer.py | Package version found: extcolors 1.0.0
2023-05-03 09:47:04,340 | DEBUG | C:\automatic\installer.py | Package version found: facexlib 0.3.0
2023-05-03 09:47:04,341 | DEBUG | C:\automatic\installer.py | Package version found: filetype 1.2.0
2023-05-03 09:47:04,341 | DEBUG | C:\automatic\installer.py | Package version found: font-roboto 0.0.1
2023-05-03 09:47:04,341 | DEBUG | C:\automatic\installer.py | Package version found: fonts 0.0.3
2023-05-03 09:47:04,342 | DEBUG | C:\automatic\installer.py | Package version found: future 0.18.3
2023-05-03 09:47:04,342 | DEBUG | C:\automatic\installer.py | Package version found: gdown 4.7.1
2023-05-03 09:47:04,342 | DEBUG | C:\automatic\installer.py | Package version found: gfpgan 1.3.8
2023-05-03 09:47:04,343 | DEBUG | C:\automatic\installer.py | Package version found: GitPython 3.1.31
2023-05-03 09:47:04,343 | DEBUG | C:\automatic\installer.py | Package version found: httpcore 0.17.0
2023-05-03 09:47:04,343 | DEBUG | C:\automatic\installer.py | Package version found: inflection 0.5.1
2023-05-03 09:47:04,343 | DEBUG | C:\automatic\installer.py | Package version found: jsonmerge 1.9.0
2023-05-03 09:47:04,344 | DEBUG | C:\automatic\installer.py | Package version found: kornia 0.6.12
2023-05-03 09:47:04,344 | DEBUG | C:\automatic\installer.py | Package version found: lark 1.1.5
2023-05-03 09:47:04,344 | DEBUG | C:\automatic\installer.py | Package version found: lmdb 1.4.1
2023-05-03 09:47:04,345 | DEBUG | C:\automatic\installer.py | Package version found: lpips 0.1.4
2023-05-03 09:47:04,345 | DEBUG | C:\automatic\installer.py | Package version found: numpy 1.23.5
2023-05-03 09:47:04,345 | DEBUG | C:\automatic\installer.py | Package version found: omegaconf 2.3.0
2023-05-03 09:47:04,345 | DEBUG | C:\automatic\installer.py | Package version found: open-clip-torch 2.18.0
2023-05-03 09:47:04,346 | DEBUG | C:\automatic\installer.py | Package version found: opencv-contrib-python 4.7.0.72
2023-05-03 09:47:04,346 | DEBUG | C:\automatic\installer.py | Package version found: piexif 1.1.3
2023-05-03 09:47:04,346 | DEBUG | C:\automatic\installer.py | Package version found: Pillow 9.5.0
2023-05-03 09:47:04,347 | DEBUG | C:\automatic\installer.py | Package version found: psutil 5.9.5
2023-05-03 09:47:04,347 | DEBUG | C:\automatic\installer.py | Package version found: pyyaml 6.0
2023-05-03 09:47:04,347 | DEBUG | C:\automatic\installer.py | Package version found: realesrgan 0.3.0
2023-05-03 09:47:04,348 | DEBUG | C:\automatic\installer.py | Package version found: requests 2.29.0
2023-05-03 09:47:04,348 | DEBUG | C:\automatic\installer.py | Package version found: resize-right 0.0.2
2023-05-03 09:47:04,348 | DEBUG | C:\automatic\installer.py | Package version found: rich 13.3.5
2023-05-03 09:47:04,348 | DEBUG | C:\automatic\installer.py | Package version found: safetensors 0.3.1
2023-05-03 09:47:04,349 | DEBUG | C:\automatic\installer.py | Package version found: scipy 1.10.1
2023-05-03 09:47:04,349 | DEBUG | C:\automatic\installer.py | Package version found: tb_nightly 2.13.0a20230502
2023-05-03 09:47:04,349 | DEBUG | C:\automatic\installer.py | Package version found: toml 0.10.2
2023-05-03 09:47:04,350 | DEBUG | C:\automatic\installer.py | Package version found: torch 2.0.0+cu118
2023-05-03 09:47:04,350 | DEBUG | C:\automatic\installer.py | Package version found: torchdiffeq 0.2.3
2023-05-03 09:47:04,350 | DEBUG | C:\automatic\installer.py | Package version found: torchsde 0.2.5
2023-05-03 09:47:04,350 | DEBUG | C:\automatic\installer.py | Package version found: torchvision 0.15.1+cu118
2023-05-03 09:47:04,351 | DEBUG | C:\automatic\installer.py | Package version found: voluptuous 0.13.1
2023-05-03 09:47:04,351 | DEBUG | C:\automatic\installer.py | Package version found: yapf 0.33.0
2023-05-03 09:47:04,351 | DEBUG | C:\automatic\installer.py | Package version found: scikit-image 0.20.0
2023-05-03 09:47:04,352 | DEBUG | C:\automatic\installer.py | Package version found: tqdm 4.65.0
2023-05-03 09:47:04,352 | DEBUG | C:\automatic\installer.py | Package version found: accelerate 0.18.0
2023-05-03 09:47:04,352 | DEBUG | C:\automatic\installer.py | Package version found: opencv-python 4.7.0.72
2023-05-03 09:47:04,352 | DEBUG | C:\automatic\installer.py | Package version found: diffusers 0.16.1
2023-05-03 09:47:04,353 | DEBUG | C:\automatic\installer.py | Package version found: einops 0.4.1
2023-05-03 09:47:04,353 | DEBUG | C:\automatic\installer.py | Package version found: gradio 3.28.1
2023-05-03 09:47:04,353 | DEBUG | C:\automatic\installer.py | Package version found: numexpr 2.8.4
2023-05-03 09:47:04,354 | DEBUG | C:\automatic\installer.py | Package version found: pandas 1.5.3
2023-05-03 09:47:04,354 | DEBUG | C:\automatic\installer.py | Package version found: protobuf 3.20.3
2023-05-03 09:47:04,354 | DEBUG | C:\automatic\installer.py | Package version found: pytorch_lightning 1.9.4
2023-05-03 09:47:04,355 | DEBUG | C:\automatic\installer.py | Package version found: transformers 4.26.1
2023-05-03 09:47:04,355 | DEBUG | C:\automatic\installer.py | Package version found: timm 0.6.13
2023-05-03 09:47:04,355 | DEBUG | C:\automatic\installer.py | Package version found: tomesd 0.1.2
2023-05-03 09:47:04,672 | ERROR | C:\automatic\installer.py | Error running git: None / log -1 --pretty=format:"%at"
2023-05-03 09:47:04,675 | DEBUG | C:\automatic\installer.py | Git output: fatal: detected dubious ownership in repository at 'C:/automatic'
'C:/automatic' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-1194271653-2810682028-2473446000-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/automatic
2023-05-03 09:47:04,675 | ERROR | C:\automatic\installer.py | Error getting local repository version: invalid literal for int() with base 10: "fatal: detected dubious ownership in repository at 'C:/automatic'\n'C:/automatic' is owned by:\n\t'S-1-5-32-544'\nbut the current user is:\n\t'S-1-5-21-1194271653-2810682028-2473446000-1001'\nTo add '''

**Comment by vladmandic** [comment] 2023-05-03 12:01
duplicate of #483, lets continue there, closing this one.

**Closed by vladmandic** 2023-05-03 12:01 UTC
