### ISSUE TITLE
[Issue]: Vram stay allocated

### ISSUE THREAD

**Issue by gr44l** [vladmandic/automatic#886] opened 2023-05-11 22:43 UTC
### Issue Description

hello, i notice a bug that i dont have in automatic1111, my vram stay at maximum usage sometimes after an image get generated , and i have to close vladmandic and re launch it. otherwise i get a cuda error even for a simple 512*512 image

config: 
i7 12700k
32gb ram
RTX3080 12Gb VRAM
windows 10
latest version of vladmantic/automatic
Python 3.10.9
CUDA 11.8

**Comment by vladmandic** [comment] 2023-05-11 23:34
no platform or version information is not helpful.

**Comment by gr44l** [comment] 2023-05-12 08:27
i have updated my post =)

**Comment by ronbere** [comment] 2023-05-12 09:31
Same here....Vram stays allocated...
windows 10
latest commit
Python 3.10.9
CUDA 11.8

**Comment by vladmandic** [comment] 2023-05-12 11:35
i've tried with different batch sizes and counts, cannot reproduce - in both cases, memory goes up and then goes back down after generate has completed.

are you using any extensions, scripts or lora's?

can you update the app and run it with `--debug` flag, it will print step-by-step operations and all memory allocation stats.
best to delete `setup.log` before you run and when you're done, upload it here, don't copy console log as it may get big.

**Comment by onegex1214** [comment] 2023-05-12 12:26
This is very similar to the issue I posted a few days ago, I suspect models aren't properly de-loaded when changing models.

**Comment by vladmandic** [comment] 2023-05-12 12:29
there is some memory leak when changing models (not entire model, but small part of it) and i'm tracing that.
but this is explicitly about image generation and i don't see issues with that - i've run 5k images continous run and did not see any serious leaks.

**Comment by fabiobtex** [comment] 2023-05-12 18:10
What "compute settings" on setting are enabled?

**Comment by adjarar** [comment] 2023-05-13 00:03
This option in config.json ["send_size": false] is normally set to true. So if you just uprezed an image to 2k then sent to img2img it will send 2k as size to img2img. This can very easily lead to out of memory errors. I had this happen yesterday and thought there was a leak too because it kept happening. Check if this is the case for you.

The best thing is to set this to false anyway, it's not the desired behavior 99% of the time and in my opinion should be off by default.

**Comment by vladmandic** [comment] 2023-05-16 13:49
@klausman valid thing to look at, but not really related to this isssue as your problem seens related to real-esrgan a) using more memory, b) not deallocating it once it runs into oom so all subsequent operations fail as well.

can you open a separate issue and capture memory usage after each step.
- using line printed on screen:
  for example `Time taken: 3.02s | GPU active 3173 MB reserved 3834 MB | System peak 5023 MB total 12288 MB`  
  that is collected immediately upon completion
- using system info tab a few seconds after  
  (so garbage collection had a chance to catch up)

**Comment by klausman** [comment] 2023-05-16 14:48
> @klausman valid thing to look at, but not really related to this isssue as your problem seens related to real-esrgan a) using more memory, b) not deallocating it once it runs into oom so all subsequent operations fail as well.
> 
> can you open a separate issue and capture memory usage after each step.
> 
> * using line printed on screen:
>   for example `Time taken: 3.02s | GPU active 3173 MB reserved 3834 MB | System peak 5023 MB total 12288 MB`
>   that is collected immediately upon completion
> * using system info tab a few seconds after
>   (so garbage collection had a chance to catch up)

I _think_ several different things were going on:

- me not noticing some sending-around of image sizes (the `send_size` thing mentioned earlier)
- my installation got corrupted somehow:
  - when restarting the server, I would get weird piles of `IndexErrors` in the console, and messages about `[some text from my prompt]: FIle not found`
  - even deleting the venv and starting over didn't help
  - ditching both json config files (UI and base) seems to have fixed things
- I also git pull'd to the most recent commit on master/HEAD

... and now I can't reproduce the problem using the steps I mentioned. *IF* it shows up again, I will file a separate bug. Thanks for your help so far!

**Comment by vladmandic** [comment] 2023-05-18 11:53
closing as no information provided from original author @gr44l, will reopen if information becomes available.

**Closed by vladmandic** 2023-05-18 11:53 UTC
Labels: question, cannot reproduce
