### ISSUE TITLE
[Issue]: During Inpaint, SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#718] opened 2023-05-03 00:24 UTC
### Issue Description

When using Inpaint, some images have started to return a SSL error. How can the local server be experiencing such an error?

```
ERROR    gradio call: URLError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\urllib\request.py:1348 in do_open                          │
│                                                                                                                      │
│   1347 │   │   │   try:                                                                                              │
│ ❱ 1348 │   │   │   │   h.request(req.get_method(), req.selector, req.data, headers,                                  │
│   1349 │   │   │   │   │   │     encode_chunked=req.has_header('Transfer-encoding'))                                 │
│                                                                                                                      │
│ C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\http\client.py:1282 in request                             │
│                                                                                                                      │
│   1281 │   │   """Send a complete request to the server."""                                                          │
│ ❱ 1282 │   │   self._send_request(method, url, body, headers, encode_chunked)                                        │
│   1283                                                                                                               │
│                                                                                                                      │
│                                               ... 6 frames hidden ...                                                │
│                                                                                                                      │
│ C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\ssl.py:1071 in _create                                     │
│                                                                                                                      │
│   1070 │   │   │   │   │   │   raise ValueError("do_handshake_on_connect should not be specifie                      │
│ ❱ 1071 │   │   │   │   │   self.do_handshake()                                                                       │
│   1072 │   │   │   except (OSError, ValueError):                                                                     │
│                                                                                                                      │
│ C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\ssl.py:1342 in do_handshake                                │
│                                                                                                                      │
│   1341 │   │   │   │   self.settimeout(None)                                                                         │
│ ❱ 1342 │   │   │   self._sslobj.do_handshake()                                                                       │
│   1343 │   │   finally:                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in
certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ G:\stable-diffusion-vladmandic\modules\call_queue.py:59 in f                                                         │
│                                                                                                                      │
│    58 │   │   │   │   pr.enable()                                                                                    │
│ ❱  59 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ G:\stable-diffusion-vladmandic\modules\call_queue.py:38 in f                                                         │
│                                                                                                                      │
│    37 │   │   │   try:                                                                                               │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    39 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│                                               ... 16 frames hidden ...                                               │
│                                                                                                                      │
│ C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\urllib\request.py:1391 in https_open                       │
│                                                                                                                      │
│   1390 │   │   def https_open(self, req):                                                                            │
│ ❱ 1391 │   │   │   return self.do_open(http.client.HTTPSConnection, req,                                             │
│   1392 │   │   │   │   context=self._context, check_hostname=self._check_hostname)                                   │
│                                                                                                                      │
│ C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\urllib\request.py:1351 in do_open                          │
│                                                                                                                      │
│   1350 │   │   │   except OSError as err: # timeout error                                                            │
│ ❱ 1351 │   │   │   │   raise URLError(err)                                                                           │
│   1352 │   │   │   r = h.getresponse()                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in
certificate chain (_ssl.c:997)>
Downloading: "https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1" to G:\stable-diffusion-vladmandic\models\LDSR\model.ckpt
```

### Version Platform Description

2023-05-02
hash: https://github.com/vladmandic/automatic/commit/eb03fce3e4733ef98f8233e5170c12938502674d

**Comment by srcrist** [comment] 2023-05-03 00:57
I believe this is an issue with the remote server that it's trying to download the LDSR model from. You should be able to download it with a web browser and put it in the LDSR model folder. You'll need both the model.ckpt file and project.yaml file.

**Comment by mark-wd** [comment] 2023-05-03 01:06
> 

I believe you are absolutely right on this one. Shouldn't the webui be able to do it by itself, though?

**Comment by vladmandic** [comment] 2023-05-03 01:47
app does the same thing as browser - if app complains about ssl, so will browser most likely - but its also a timing issue as most of those download servers are behind some cdn with a pool of servers. if there are 10 servers with valid ssl certificate and 1 with invalid one, its pure luck which you end up with. 

i'll check if LDSR changed list of valid servers in the meantime, but otherwise, i cannot do much about it - as i cannot influence if some internet server has a temporary invalid ssl certificate. 

let me know how you'd like me to proceed?

> When using Inpaint, some images have started to return a SSL error. How can the local server be experiencing such an error?

btw, title is not really correct - its not about "some images" at all as model needs to be downloaded only once on first usage and then its stored on your disk until you delete it.

**Comment by srcrist** [comment] 2023-05-03 02:01
Vlad, for what it's worth, when I had this issue yesterday putting the same link in the browser did actually download the file without issue. It looks like using the [](https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1) link from the above log also works now. 

Not sure what this indicates, but just an fyi that the browser isn't having the same issue, if that warrants further investigation.

**Comment by vladmandic** [comment] 2023-05-03 02:05
if you can move file somewhere and let app try to download it itself once more - to prove if it was a temporary thing or there really is an issue with a python `requests` library.

**Comment by srcrist** [comment] 2023-05-03 04:01
Hey Vlad,

Tested this again. Same result. The download triggered the following error in the client, but using the link in the browser immediately worked fine. 

```
Downloading: "https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1" to D:\StableDiffusion\automatic\models\LDSR\model.ckpt

23:59:52-837035 ERROR    gradio call: URLError                                 
+--------------------- Traceback (most recent call last) ---------------------+
| C:\Program Files\Python310\lib\urllib\request.py:1348 in do_open            |
|                                                                             |
|   1347             try:                                                     |
| > 1348                 h.request(req.get_method(), req.selector, req.data,  |
|   1349                           encode_chunked=req.has_header('Transfer-en |
|                                                                             |
| C:\Program Files\Python310\lib\http\client.py:1282 in request               |
|                                                                             |
|   1281         """Send a complete request to the server."""                 |
| > 1282         self._send_request(method, url, body, headers, encode_chunke |
|   1283                                                                      |
|                                                                             |
|                           ... 6 frames hidden ...                           |
|                                                                             |
| C:\Program Files\Python310\lib\ssl.py:1071 in _create                       |
|                                                                             |
|   1070                         raise ValueError("do_handshake_on_connect sh |
| > 1071                     self.do_handshake()                              |
|   1072             except (OSError, ValueError):                            |
|                                                                             |
| C:\Program Files\Python310\lib\ssl.py:1342 in do_handshake                  |
|                                                                             |
|   1341                 self.settimeout(None)                                |
| > 1342             self._sslobj.do_handshake()                              |
|   1343         finally:                                                     |
+-----------------------------------------------------------------------------+
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify 
failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

+--------------------- Traceback (most recent call last) ---------------------+
| D:\StableDiffusion\automatic\modules\call_queue.py:59 in f                  |
|                                                                             |
|    58                 pr.enable()                                           |
| >  59             res = list(func(*args, **kwargs))                         |
|    60             if shared.cmd_opts.profile:                               |
|                                                                             |
| D:\StableDiffusion\automatic\modules\call_queue.py:38 in f                  |
|                                                                             |
|    37             try:                                                      |
| >  38                 res = func(*args, **kwargs)                           |
|    39                 progress.record_results(id_task, res)                 |
|                                                                             |
|                          ... 16 frames hidden ...                           |
|                                                                             |
| C:\Program Files\Python310\lib\urllib\request.py:1391 in https_open         |
|                                                                             |
|   1390         def https_open(self, req):                                   |
| > 1391             return self.do_open(http.client.HTTPSConnection, req,    |
|   1392                 context=self._context, check_hostname=self._check_ho |
|                                                                             |
| C:\Program Files\Python310\lib\urllib\request.py:1351 in do_open            |
|                                                                             |
|   1350             except OSError as err: # timeout error                   |
| > 1351                 raise URLError(err)                                  |
|   1352             r = h.getresponse()                                      |
+-----------------------------------------------------------------------------+
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify 
failed: self signed certificate in certificate chain (_ssl.c:997)>
```

**Comment by vladmandic** [comment] 2023-05-03 04:05
Thanks for checking, I'll follow-up tomorrow.

**Comment by vladmandic** [comment] 2023-05-03 12:23
since root cause is the same closing this as duplicate in favor of #693

**Closed by vladmandic** 2023-05-03 12:23 UTC

**Comment by SMKMultazam** [comment] 2023-09-02 09:32
https://help.autodesk.com/view/SGDEV/ENU/?guid=SGD_qa_troubleshooting_qa_unable_to_get_local_issuer_certificate_error_html
