### ISSUE TITLE
[Issue]: LLVM ERROR: Failed to infer result type(s).

### ISSUE THREAD

**Issue by vincyb** [vladmandic/automatic#413] opened 2023-04-23 12:50 UTC
### Issue Description

After loading the webUI, I gave simple text prompt to generate image. It failed

In terminal:
Initializing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:00loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<2x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort      /Users/username/automatic/webui.sh

### Version Platform Description

Apple Mac silicon
arch: arm64
cpu: arm
system: Darwin
release: 22.4.0
python: 3.10.9

**Comment by vladmandic** [comment] 2023-04-23 12:52
duplicate of #347

**Closed** 2023-04-23 12:53 UTC
