### ISSUE TITLE
[Issue]: Always getting a black image as an output from generation

### ISSUE THREAD

**Issue by arthemis235** [vladmandic/automatic#781] opened 2023-05-05 23:27 UTC
### Issue Description

**Steps to reproduce:**
1. Download the version from the git with git clone (commit is "f6898c9")
2. Copy-paste two models in a "Stable-diffusion" folder in the models (realisticVisionV20_v20.safetytensors and v1-5-pruned-emaonly.ckpt)
3. Run webui-user.bat
4. Write "crowd of people" in the prompt
5. Click "Generate"
6. Wait until generation is complete

**The output is always the following:**
No image is generated (black square of 512 * 512 pixels appearing every time)
Same thing with both models

**Console log appearing in the browser:**
```
Steps: 20, Sampler: UniPC, CFG scale: 6, Seed: 3535671298, Size: 512x512, Model hash: c0d1994c73, Model: realisticVisionV20_v20, Clip skip: 1

Time taken: 54.70s | GPU active 2624 MB reserved 3300 MB | System peak 4368 MB total 6144 MB
```

Issue is consistent (rebooting, reinstalling don't change anything)

### Version Platform Description

Windows 10, with Brave

```
Using VENV: E:\Utilitaires\Stable Diffusion\automatic\venv
12:01:46-608029 INFO     Starting SD.Next
12:01:46-611794 INFO     Python 3.10.6 on Windows
12:01:46-983312 INFO     Version: f6898c9a Fri May 5 13:40:53 2023 -0400
12:01:47-333490 INFO     Setting environment tuning
12:01:47-335492 INFO     nVidia CUDA toolkit detected
12:01:52-834234 INFO     Torch 2.0.1+cu118
12:01:52-852706 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
12:01:52-853707 INFO     Torch detected GPU: NVIDIA GeForce GTX 1660 VRAM 6144 Arch (7, 5) Cores 22
12:01:52-855709 INFO     Installing package: tensorflow==2.12.0
12:02:05-189970 INFO     Verifying requirements
12:02:05-208987 WARNING  Package wrong version: transformers 4.27.4 required 4.26.1
12:02:05-209988 INFO     Installing package: transformers==4.26.1
12:02:17-703826 INFO     Running setup
12:02:17-704828 INFO     Installing packages
12:02:17-705829 INFO     Installing repositories
12:02:17-837771 INFO     Installing submodules
12:02:19-815742 INFO     Updating submodules
```

**Comment by vladmandic** [comment] 2023-05-06 00:58
you've provided no hw info, cuda config in settings or cmdflags used.
purely based on time taken to generate, its a pretty old gpu? so most likely it has a broken `fp16` implementation, see #374 for long explanation.

**Comment by arthemis235** [comment] 2023-05-06 10:15
Sorry, I have updated the information.

I had to check the Full Precison Model and VAE option.
Now it generates images.

Generation seems a lot faster than the standard Automatic1111.

```
Steps: 20, Sampler: UniPC, CFG scale: 6, Seed: 1342739826, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, Clip skip: 1

Time taken: 13.06s | GPU active 4863 MB reserved 5274 MB | System peak 6144 MB total 6144 MB
```

Excuse-me to ask, but is that what should have happened? Do I make sense?

**Comment by vladmandic** [comment] 2023-05-06 12:42
i'm affraid there is no easy solution. using `--medvram` does exist and does something, but not that much. and using `--lowvram` slows things down a lot. the problem is that torch 2.0 is a bit more memory hungry than torch 1.13 previously used and your system is really low on both ram and vram.

there is a separate issue where app indeed has a memory leak, so even if first generation is ok, eventually it will run out of memory. normally that is not that visible since i've fixed all large leaks and what's left is quite small. but since you're so close to the limit, you run into oom quite soon.

**Comment by vladmandic** [comment] 2023-05-06 14:53
we can continue the conversation, but i'm closing the issue as original issue posted is addressed.

**Closed by vladmandic** 2023-05-06 14:53 UTC
Labels: question
